### ISSUE TITLE
QC Checklist for Clinical Biospecimen Data

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#10]
Below is a list of QC checks needed for regularly on the clinical biospecimen data. These items will be an overall review/check and an output listing of any of these occurrences.
 
1. A comparison of the blood accession ID sent from KP (BioClin_SntBloodAccID_v1r0) and the blood accession ID entered in the biospecimen dashboard (BioClin_DBBloodID_v1r0). The output for this comparison is a list of any blood accession IDs that do not match and should only include samples with a blood accession ID from both sources. The list should include the Site, Connect ID, and blood accession ID from both sources.

2. A comparison of the urine accession ID sent from KP (BioClin_SntUrineAccID_v1r0) and the urine accession ID entered in the biospecimen dashboard (BioClin_DBUrineID_v1r0). The output for this comparison is a list of any urine accession IDs that do not match and should only include samples with a urine accession ID from both sources. The list should include the Site, Connect ID, and urine accession ID from both sources.

3. A comparison of the blood date received at the RRL from KP data (BioClin_SiteBloodRRLDt_v1r0) with the blood date received at the RRL from the biospecimen dashboard (BioClin_DBBloodRRLDt_v1r0). The output for this comparison is a list of any dates received that do not match and should only include samples with a blood date received from both sources. The list should include the Site, Connect ID, blood accession ID, and blood date received from both sources.

4. A comparison of the urine date received at the RRL from KP data (BioClin_SiteUrineRRLDt_v1r0) with the urine date received at the RRL from the biospecimen dashboard (BioClin_DBUrineRRLDt_v1r0). The output for this comparison is a list of any dates received that do not match and should only include samples with a urine date received from both sources. The list should include the Site, Connect ID, urine accession ID, and urine date received from both sources.

5. Output list of any instances where data sent by KP says a baseline blood sample was collected (BioClin_SiteBloodColl_v1r0 = Yes), but the biospecimen dashboard does not have a record of receiving a baseline blood sample at the RRL (BioClin_DBBloodRRL_v1r0 = No). This output list should include the Site, the Connect ID, the accession ID from KP, the date blood collected sent by KP, and the blood collection location sent by KP.

6. Output list of any instances where data sent by KP says a baseline blood sample was not collected (BioClin_SiteBloodColl_v1r0 = No), but the biospecimen dashboard has a record of receiving a baseline blood sample at the RRL (BioClin_DBBloodRRL_v1r0 = Yes). This output list should include the Site, the Connect ID, the accession ID from the biospecimen dashboard, and the date blood collected from the biospecimen dashboard.  Exclude the most recent 48 hours of data.

7. Output list of any instances where data sent by KP says a baseline urine sample was collected (BioClin_SiteUrineColl_v1r0=Yes), but the biospecimen dashboard does not have a record of receiving a baseline urine sample at the RRL (BioClin_DBUrineRRL_v1r0=No). This output list should include the Site, the Connect ID, the accession ID from KP, the date urine collected sent by KP, and the urine collection location sent by KP.

8. Output list of any instances where the data sent by KP says a baseline urine sample was not collected (BioClin_SiteUrineColl_v1r0=No), but the biospecimen dashboard has a record of receiving a baseline urine sample at the RRL (BioClin_DBUrineRRL_v1r0=Yes). This output list should include the Site, the Connect ID, the accession ID from the biospecimen dashboard, and the date urine collected from the biospecimen dashboard. Exclude the most recent 48 hours of data.

**Comment by HopkinsDC** [comment]
The annotated clinical QC document (12/12) below includes comments, corrections, and edits to be made.
[PROD_clinical_biospecimen_QCChecklist_GitHub10_12122022.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10272191/PROD_clinical_biospecimen_QCChecklist_GitHub10_12122022.pdf)

**Comment by HopkinsDC** [comment]
@jeannewu No, you don't have to run this QC check report this week.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey. I'm unsure if you will take this over from Jing too, but this QC check output was completed. The latest report can be viewed here: https://nih.app.box.com/file/1121254901765. I do not think we are generating this report weekly like the biospecimen metrics; it is generated upon request. Michelle can confirm this when she returns next week from PTO. Let me know if you have any questions.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Yes, Madhuri and I met to go over how the rules were created, and I reached out to Jake about it being in the process. He would code it into BQ once we have the rules written and structured. Is that sufficient, or would you need a separate report also coded?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The process you describe should be fine. Thank you!
