### ISSUE TITLE
QC Rules for Home Collection (Mouthwash)

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#100]
The home collection QC rules have been drafted and are ready to be coded: https://nih.app.box.com/file/1343071051190

**Requestor(s):** Domonique

**Table or Figure title:** N/A

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Should these be added into the current biospecimen QC reports or do you want these separated?


I also want to make sure I understand Rule 3 correctly: IF BioKit_KitType_v1r0 (379252329) = 0
THEN BioKit_ReturnKitTrack_v1r0 (972453354), BioKit_SupplyKitID_v1r0 (690210658), BioKit_ReturnKitID_v1r0 (194252513), BioKit_MWCupID_v1r0 (259846815), and BioKit_MWCardID_v1r0 (786397882) = populate


Would this mean we would need all of these rules:
IF BioKit_KitType_v1r0 (379252329) = 0 THEN BioKit_ReturnKitTrack_v1r0 (972453354)=populate
IF BioKit_KitType_v1r0 (379252329) = 0 THEN BioKit_SupplyKitID_v1r0 (690210658)=populate
IF BioKit_KitType_v1r0 (379252329) = 0 THEN BioKit_ReturnKitID_v1r0 (194252513)=populate
IF BioKit_KitType_v1r0 (379252329) = 0 THEN BioKit_MWCupID_v1r0 (259846815=populate
IF BioKit_KitType_v1r0 (379252329) = 0THEN BioKit_MWCardID_v1r0 (786397882)=populate

IF BioKit_ReturnKitTrack_v1r0 (972453354)=populate THEN BioKit_KitType_v1r0 (379252329) = 0 
IF   BioKit_SupplyKitID_v1r0 (690210658)=populate THEN BioKit_KitType_v1r0 (379252329) = 0
IF  BioKit_ReturnKitID_v1r0 (194252513)=populate THEN BioKit_KitType_v1r0 (379252329) = 0
IF  BioKit_MWCupID_v1r0 (259846815=populate THEN BioKit_KitType_v1r0 (379252329) = 0 
IF  BioKit_MWCardID_v1r0 (786397882)=populate THEN BioKit_KitType_v1r0 (379252329) = 0

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 We can just add them to the current QC report to keep it simple.

Your interpretation is correct for rule 3; however, it's better to apply the rules one way since it's possible that BioKit_ReturnKitTrack_v1r0, BioKit_SupplyKitID_v1r0, BioKit_ReturnKitID_v1r0 may be used for different kit types when/if added down the road, so we don't need the second set of rules.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok so we no longer need rule Type 3 to be inversely applied?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, that's correct, no inverse rules for rule type 3. Thanks!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Thanks for clarifying! Sorry for all the questions, I just want to make sure this is coded correctly. Can you confirm that these would be the rules needed for Rule Type 8 and Rule Type 11 to account for both the inverse rule type and duplicate table check?

Rule 8:
(One way)
- IF BioKit_KitStatus_v1r0 (d_173836415_d_266600170_d_8583443674_d_221592017) = 4, THEN BioKit_SupplyKitTrack_v1r0 (531858099)= populate. This checks the kit status of the participants table
- IF BioKit_KitStatus_v1r0 (d_173836415_d_266600170_d_8583443674_d_221592017) = 4, THEN BioKit_KitShipTm_v1r0 (661940160) = populate. This checks the kit status of the participants table
- IF BioKit_KitStatus_v1r0 (d_173836415_d_266600170_d_8583443674_d_221592017) = 4, THEN BioKit_KitRecdTm_v1r0 (826941471), = populate. This checks the kit status of the participants table
- IF BioKit_KitStatus_v1r0 (d_173836415_d_266600170_d_8583443674_d_221592017) = 4, THEN  BioKit_CollCardRet_v1r0 (137401245) = populate. This checks the kit status of the participants table
- IF BioKit_KitStatus_v1r0 (d_221592017) = 4, THEN BioKit_SupplyKitTrack_v1r0 (531858099)= populate. This checks the kit status of the kit assembly table
- IF BioKit_KitStatus_v1r0 (d_221592017) = 4, THEN BioKit_KitShipTm_v1r0 (661940160) = populate. This checks the kit status of the kit assembly table
- IF BioKit_KitStatus_v1r0 (d_221592017) = 4, THEN BioKit_KitRecdTm_v1r0 (826941471), = populate. . This checks the kit status of the kit assembly table
- IF BioKit_KitStatus_v1r0 (d_221592017) = 4, THEN  BioKit_CollCardRet_v1r0 (137401245) = populate. This checks the kit status of the kit assembly table

(Inverse)
- IF THEN BioKit_SupplyKitTrack_v1r0 (531858099)= populate THEN BioKit_KitStatus_v1r0 (d_173836415_d_266600170_d_8583443674_d_221592017) = 4. This checks the kit status of the participants table
- IF BioKit_KitShipTm_v1r0 (661940160) = populate THEN BioKit_KitStatus_v1r0 (d_173836415_d_266600170_d_8583443674_d_221592017) = 4 This checks the kit status of the participants table
- IF BioKit_KitRecdTm_v1r0 (826941471), = populate THEN BioKit_KitStatus_v1r0 (d_173836415_d_266600170_d_8583443674_d_221592017) = 4. This checks the kit status of the participants table
- IF BioKit_CollCardRet_v1r0 (137401245) = populate THEN BioKit_KitStatus_v1r0 (d_173836415_d_266600170_d_8583443674_d_221592017) = 4. This checks the kit status of the participants table
- IF THEN BioKit_SupplyKitTrack_v1r0 (531858099)= populate THEN BioKit_KitStatus_v1r0 (d_221592017) = 4. This checks the kit status of the kit assembly table
- IF BioKit_KitShipTm_v1r0 (661940160) = populate THEN BioKit_KitStatus_v1r0 (d_221592017) = 4. This checks the kit status of the kit assembly table
- IF BioKit_KitRecdTm_v1r0 (826941471),= populate THEN BioKit_KitStatus_v1r0 (d_221592017) = 4. This checks the kit status of the kit assembly table
- IF  BioKit_CollCardRet_v1r0 (137401245) = populate THEN BioKit_KitStatus_v1r0 (d_221592017) = 4. This checks the kit status of the kit assembly table


Rule 11:
(one Way)
-IF BioKit_KitStatus_v1r0 (221592017) = 4 AND BioKit_KitType_v1r0 (379252329) = 0THEN MWTube1_BioCol_TubeID_v1r0 (d_143615646_d_825582494) = BioKit_MWCupID_v1r0 (d_173836415_d_266600170_d_8583443674_d_221592017) This checks the kit status of the  participants table
-IF BioKit_KitStatus_v1r0 (221592017) = 4 AND BioKit_KitType_v1r0 (379252329) = 0THEN MWTube1_BioCol_TubeID_v1r0 (d_143615646_d_825582494) = BioKit_MWCupID_v1r0 (d_259846815) This checks the kit status of the kit assembly table 


(Inverse)
-If the populated mouthwash sample tube ID (full specimen ID) should equal the populated collection cup ID, then kit status (from the kit assembly table) is Received
-If the populated mouthwash sample tube ID (full specimen ID) should equal the populated collection cup ID, then kit status (from the particiapnts table) is Received
-If the populated mouthwash sample tube ID (full specimen ID) should equal the populated collection cup ID, then kit type is Mouthwash.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The one-way rules for rules 8 and 11 in both tables look good. 

You can delete the inverse rules for both rules 8 and 11; seeing them written out like this helps clarify that they may throw errors that aren't true errors. The one-way rules should cover the receipt checks.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok thanks for confirming! I'll delete the inverse and me and Jake will start testing these in stage shortly. I'm assuming we won't see any errors based on the purposes of stage testing but at least we'll know if doesn't break our existing code

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Sorry! I was confusing these with the Death Data QC testing we were doing yesterday. But Jake is going to try to test these today/this week once the three-way table merge is figured out

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz Just noticed this open issue, the rules I showed you last week were a part of this list but the rest must have somehow been forgotten or pending data in the last few months. 

These are the additional rules that I'd be adding based on this original request. Please let me know if these no longer apply or need to be tweaked:
1. If kit status (BioKit_KitStatus_v1r0) is Pending, then date/time kit pending (BioKit_KitDatePend_v1r0) should populate
2. If kit type is Mouthwash , then return kit tracking number, supply kit ID, return kit ID, collection cup ID, and collection card ID should populate.
3. If kit status is Assigned, then supply kit tracking number should populate
4. If kit status is Shipped, then supply kit tracking number and date/time kit shipped should populate
5. If kit status is Received, then supply kit tracking number, date/time kit shipped, date/time kit received should populate
6. If kit status is Received, then the mouthwash sample is collected.
7. If kit status is Received, then the mouthwash sample tube ID should populate.
8. If kit status is Received, and the kit type is Mouthwash, then the mouthwash collection setting is Home.
9. If the mouthwash collection setting is Home, and the mouthwash sample is collected, then baseline mouthwash is collected.
10. If the mouthwash collection setting is Home, and the mouthwash sample is collected, then the mouthwash date/time collected should populate.

**Comment by KELSEYDOWLING7** [comment]
These two have many errors, I'm thinking some additional conditionality is needed:
a. If kit type is Mouthwash , then return kit tracking number, supply kit ID, return kit ID, collection cup ID, and collection card ID should populate.
b. If kit status is Shipped, then supply kit tracking number and date/time kit shipped should populate


It looks like there's the same 61 people with a kit type of mouthwash, kit status of shipped and date/time of shipped kit populated, but these are all null: supply kit tracking number, return kit tracking number, supply kit ID, return kit ID, collection cup ID, and collection card ID

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  It looks like all of the QC issues I was finding is just an issue of delayed flattening of the kit_assembly table in BQ. Jake quickly resolved that for me so these are all done! Please let me know if any of the rules mentioned above are no longer valid. If not, I'll update these all to the Biospecimen QC check

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 I will review these with Bio team on Tuesday---I am hung up on numbers 6 and 9, wondering if additional conditionality needs to be added to handle those cases where cup is returned empty, kit received with unexpected contents, etc.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Is there any updates to this issue as far as updating those two rules mentioned above or not?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 The two rules mentioned above are good as-is. No changes needed. Please update these all to the Biospecimen QC check.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Great! These will be on the Custom QC rules report (Biospe_Custom_QC_Accession_Duplicates) for now and when Jake returns from PTO we'll be adding them to the automated QC rules report (qc_report_biospecimen_prod_export2box). These will be reflected in Box as of today
