### ISSUE TITLE
Bio Weekly - Correct Table 16a, 16b, & 17 Titles

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#103]
Tables 16a, 16b, and 17 are missing the "Table" in their titles; please add this to the titles.
![Screenshot 2023-12-26 at 2 58 00 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/836510cb-d5f0-4a13-b9fe-5b8ea261b9b4)
![Screenshot 2023-12-26 at 2 58 40 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/7f669cfb-8ce6-4fbb-966d-9630a0a838ea)

**Requestor(s):** Domonique

**Table or Figure title:** 
- Table 16a. Baseline Research Biospecimen Survey Completion Time from Visit Check-In Time (Pre-COVID-19 Questions Removal)
- Table 16b. Baseline Research Biospecimen Survey Completion Time from Visit Check-In Time (Post-COVID-19 Questions Removal)
- Table 17. Baseline Clinical Biospecimen Survey Complete Time from Collection Time

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  So bizarre! Not sure how that happened but that is now fixed

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/8f960539-5d71-4064-8e8c-cad819e639d2)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/74ce91ea-d523-4b53-bc52-3bb0d92c95c7)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Definitely bizarre! Thanks for the fix.

**Comment by HopkinsDC** [comment]
Update successfully implemented in 1/8 weekly biospecimen metrics report.
