### ISSUE TITLE
Bio Weekly - Adjust X-Axis of Figures 12-15

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#104]
Adjust the x-axis of Figures 12, 13, 14, and 15 to start at **1/16/2023**.

**Requestor(s):** Domonique

**Table or Figure title:** 
- Figure 12. Weekly Biospecimen Collections at Kaiser Permanente Colorado
- Figure 13. Weekly Biospecimen Collections at Kaiser Permanente Georgia
- Figure 14. Weekly Biospecimen Collections at Kaiser Permanente Hawaii
- Figure 15. Weekly Biospecimen Collections at Kaiser Permanente Northwest

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  All set!

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c1c05ecb-e403-406d-a5a9-540fda26a5f7)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/40ede397-3d4d-4bf0-8472-30ebeb790dd9)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/11b6ef96-cb5f-4541-9356-4bf28046db4b)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4ce0539b-f3e5-4ff9-b6e2-b2a14bff0994)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Looks good, thanks!

**Comment by HopkinsDC** [comment]
Update successfully implemented in 1/8 weekly biospecimen metrics report.
