### ISSUE TITLE
Bio Weekly - Add Collections by Setting Table for HealthPartners

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#105]
Add a new table, Table 3.2, for HealthPartners collections only. 
- This new table format should be the same as Table 3.1 (Baseline Biospecimen Collection by Collection Setting at Henry Ford Health System). 
- Add the following footnote: Note: Blood and urine specimens are not collected in the Home setting, and mouthwash specimens are not collected in the Clinical setting.

**Requestor(s):** Domonique

**Table or Figure title:** Table 3.2 Baseline Biospecimen Collection by Collection Setting at HealthPartners

**Metrics to be updated or created:** Add new table

**Variables needed (include variable name and Concept ID):** 
- Verification status (821247024 = 1)
- Finalized Collection (410912345 = 1)
- Research Setting (650516960 = 0)
- Clinical Setting (650516960 = 1) 

**Specify numerator and denominator by variable name where applicable:**
- Denominator = verified participants with a finalized collection at HealthPartners. 
- Numerator = collection setting (research or clinical)

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  All set! Please note I still have all the 3.0-3.2 tables with Home collections set to 0 manually as a needed placeholder. Once we start to have home collection data I will update that to keep proper track of those collections.
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6d806519-e193-4687-8cf8-b867a50b4b48)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Noted, thanks! This table is good to go.

(Note for myself - Check Table 3.2 also for #99 when home collections go live in January)

**Comment by HopkinsDC** [comment]
New table successfully implemented in 1/8 weekly biospecimen metrics report.
