### ISSUE TITLE
Bio Weekly - Remove "Biospecimen Deviations Reported" Tables

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#106]
Remove the "Biospecimen Deviations Reported" tables (9 total) from the weekly biospecimen metrics report automation.

**Requestor(s):** Domonique

**Table or Figure title:** Tables on pgs. 37-45 in the 12/26 weekly biospecimen report

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  These are now removed

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Great, thanks!

**Comment by HopkinsDC** [comment]
Update successfully implemented in 1/8 weekly biospecimen metrics report.
