### ISSUE TITLE
Ad Hoc - Time Since Verification with No Baseline Collection

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#107]
Please generate a frequency distribution table (with row percentages) for the time (in days) that has passed since verification for participants with no baseline biospecimen collection for each site. The "time (days) since verification" can be calculated by subtracting the verification date populated from the "Today" date (i.e., whenever the table is generated).

Stratify the time (days) since verification by:
1. <30 Days
2. 30 to <90 Days
3. 90 to <180 Days
4. 180 to <270 Days
5. 270 to <365 Days
6. ≥365 Days

**Requestor(s):** Mia

**Table or Figure title:** Time (In Days) Since Verification Among Participants with No Baseline Biospecimen Collection by Site

**Variables needed (include variable name and Concept ID):**
- RcrtES_Site_v1r0 (827220437)
- RcrtV_Verification_v1r0 (821247024)
- RcrtV_VerificationTm_v1r0 (914594314)
- BioRec_CollectFinal_v1r0 (410912345)

**Specify numerator and denominator by variable name where applicable:**
- Denominator = Verified participants with no baseline biospecimen collection (821247024 = 1 AND 410912345 = 0 (or _Null_?); I'm not sure what this variable defaults to)
- Numerator = Days elapsed since verification date (914594314 = date populated)

**Mock-up table if applicable:**
![Screenshot 2023-12-27 at 8 35 37 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/593702b0-afc1-493c-be8e-88aa3c7ceee1)

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/806bb358-94ae-4546-ad30-0c61cb174d77)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Based on Table 1 of the 12/26 weekly report (included below), the table above seems to be counting verified participants _with_ a collection instead of without a collection. Can you double-check that?

![Screenshot 2023-12-27 at 11 49 45 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/97f1c255-9487-401e-8f53-48a6c7ffbf4c)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Oh! Thank you for catching that. You're right. But it doesn't look like table one is using 410912345 is null for 'No Baseline Collections'. That code is essentially if (blood or urine or mouthwash is collected) and the collection is finalized, then its counted as Baseline Collection, otherwise No Baseline Collection. I'll use that same logic for this new table so that it matches.

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4ea1a8ba-2d86-4830-b7ac-971a4cd9b4ed)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ah, ok, that makes sense. Sorry about the confusion; it's difficult to remember what parameters are used for some of these metrics.

Just one edit: can you add a "<" before "180 Days" in the third column's title?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  No problem! Oops, of course.

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4964506e-936a-4d36-8db2-e8eaef121ad1)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you!

This was an ad-hoc request from Mia, so there may be more adjustments later after her review, but it is good for now.

**Comment by StephanieWeinstein** [comment]
Hi @KELSEYDOWLING7 ,
Mia reviewed this and would like just a few changes.

combine the last two columns (i.e., 270+ days) 
break up the 2nd column to two (30-<60, 60-<90).

She would then like this added to the weekly biospecimen metrics reports 

Thanks!
Stephanie

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  All set! Please see below and let me know if this should be at the very end of the report

[Ad-Hoc---Time-Verif-with-No-BSL-Coll.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13794736/Ad-Hoc---Time-Verif-with-No-BSL-Coll.pdf)

**Comment by StephanieWeinstein** [comment]
it looks great, thank you!
Actually can you put it between Tables 25 and 26?  
Thanks,
Stephanie

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein All set! Added to this week's Biospecimen report

**Comment by HopkinsDC** [comment]
New table successfully implemented in 1/8 weekly biospecimen metrics report.
