### ISSUE TITLE
Bio Weekly- Add Orland Park collection location throughout

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#108]
Add 'Orland Park' collection location to all tables where the Collection Location is specified. eg. Table 7.1 but there are others.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Table 7.1 has been updated.
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1467c12c-2b74-4483-983c-4dfac561e710)


This location is already included in all other tables/figures that specify UC Site location (Figure 8.1 and pending table 1.1)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/09cad547-a0d1-4d5a-83d6-50302ca6ccd8)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/20289129-e16e-4e51-a4da-b3ae8a4e1531)

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 thanks for doing this so quickly. It looks like Table 7.1 is also missing the UCM Pop-Up location. Can you add that too?

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Of course

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c33c3bfc-dd07-4899-8cf2-747b7eeb626e)

**Comment by brotzmanmj** [comment]
Looks great. Out of curiosity, this table has 1807 total and Table 8.1 above has 1808. Were they just run on different data sets?

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Yes, so I have the code for the site specific tables set so that the table only counts rows for site locations I'm listing.  This way, the existing site locations are counted, and once we're aware of new ones they're adding in as a new row and increase the overall count to include all known locations. I did this because HF activated new sites numerous times before we were aware which caused the report to crash several weeks in a row.

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 that makes sense, and also means we need to keep you closer in the loop when the sites are adding new collection locations. We will tag you and Jake in all GitHub issues to that effect going forward. For the one count that is off between tables 7.1 and 8.1, it is in the DCAM location. DCAM has 1298 in Table 7.1 and 1299 in Table 8.1. Any idea why that would be?

**Comment by KELSEYDOWLING7** [comment]
Hi @brotzmanmj 
Table 1.1 Looks at any research collection, blood or urine or mouthwash. Table 7.1 only looks at blood samples

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 There's an extra row of data in Table 7.1 in the 1/8 metrics report, and I'm not sure where it came from. Is it supposed to be _UCM Pop-up_? Can you please look into this and correct it?


![Image](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/cfb883b1-bf84-4335-9949-41ea9671dacd)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Yes, somehow that typo fixed didn't get pushed to the automation. I've updated that and the order of tables 1, 1.1, 1.2, 2, ect. for issue #87 

Let me know if you need me to re-push the report with the corrections

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thanks, Kelsey. Yes, once these corrections are made, please re-push the report.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok will do. I haven't been able to run anything on my local computer today do to R errors, so I may have to push the updated version tomorrow if that's alright

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 That's totally fine. Thanks for letting me know. Hopefully, the R errors will be resolved soon.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thanks for understanding! Just uploaded the new version. It does have 29a and 28a on it though I just realized. Is that a problem?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 That's okay. They look correct based off issue 90. Thank you for re-running the report; all the fixes look good.

**Comment by HopkinsDC** [comment]
Update implemented in 1/8 weekly biospecimen metrics report; corrections made and report was re-ran on 1/9.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, [the "N/A" issue](https://github.com/Analyticsphere/metricsReportsRequests/issues/108#issuecomment-1881658116) is still showing in the 1/15 report. Can you correct that in the report's automation code today/tomorrow? Thanks!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Yes, sorry this fix didn't get into the automation somehow, and I believe I had to run 1/8 manually which is why it appeared fixed. But I'll make sure it's implemented in the automation update tomorrow when we test it

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 No worries! I remembered you had to manually run last week's report and figured the update just hadn't been added to automation. Thanks again!

**Comment by HopkinsDC** [comment]
Table successfully updated in 1/22 biospecimen metrics report.
