### ISSUE TITLE
Bio Weekly- Add metric for research collection visit time for Chicago collection locations

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#109]
Create Table 20a, same format as Table 20 but just for Chicago Research Collection Locations. You can title it 'Research Biospecimen Collection Visit Length (in minutes) for Chicago Collection Locations'

Create a figure right after that, for a time trend of the same data (for Chicago collection locations only) 'Weekly Research Biospecimen Collection Visit Length (in minutes) for Chicago Collection Locations'.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/313dc8d1-7a06-4e0e-ae72-5da6aacbdba2)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f81a3c3d-a477-4c19-af09-552a19747878)

**Comment by KELSEYDOWLING7** [comment]
Or by Site location


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d7445bb3-17e2-4c91-a1a4-f7b4ae46b29b)

**Comment by brotzmanmj** [comment]
HI @KELSEYDOWLING7  The outliers are throwing off the figures. I think I recall that we excluded outliers from the visit length tables for all the sites, setting a uniform cutpoint. Do you have that information in your code?

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  I believe we had picked a cutoff value for those outliers after looking at the data as opposed to implementing a cutoff the outliers rule per say. It looks like in Jing's older code she had previously defined the outliers as anything over 1 day, but I had removed that a while back based on the new data. 

Is there a time point you think makes sense to cut off at? Maybe at the 3rd quantile?  Please also note these are the sums of all minutes for all participants for that week. 

And do you prefer the first plot as a Site whole, or the second plot that specifies per Site location?

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 Let's keep table 20a as you have it, no changes. Can you add a footnote that states 'Note: Times at the 95th percentile and above are likely the result of participants not having been checked out at the end of their visit and do not reflect actual visit lengths.'

For the figures, I prefer the second plot. Thanks for the mention that the minutes are summed. Can we have the figure represent the do an Average Weekly Visit Length, instead of the sum of the visit minutes for that week?

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Sure thing
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/fd82d2da-de3c-40ef-af2e-a601d367e3f3)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/def46843-859f-4c24-8a41-08a149c0a94c)




Here I think it makes sense to cut off at 20,000 minutes, which would make the plot look like this:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/305bbe6b-21a3-4287-8131-e978ffc5a9c9)

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7  For the figure, I think we need to switch to Weekly Average Visit Length, instead of total minutes and then let's take a look at that and define a cutoff

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Yes, that's what this is displaying. I just hadn't changed the title yet

**Comment by brotzmanmj** [comment]
Ah, ok then I think the outliers are still really affecting the plot. Let's cut this off at 300. That would be 5 hours. That's the very outer limit if what a real visit could be.

**Comment by KELSEYDOWLING7** [comment]
Ok. That would look like this

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/774bf43c-d8bf-4af0-aa74-230ff83798cc)

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7 I think that's good, let's go with that and just update the title to indicate it is Weekly Average, and then add a footnote saying 'Note: Times greater than 300 minutes (5 hours) excluded as are likely the result of participants not having been checked out at the end of their visit and do not reflect actual visit lengths.'

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj 


![Image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d16dfc7b-806b-40a8-9608-fcbd460693a2)

**Comment by brotzmanmj** [comment]
looks good, thanks!

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj   Updated on the 1/8 Biospecimen report

**Comment by brotzmanmj** [comment]
Looks good, thanks!

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Great! For these types of requests should I be the one to close them? Or leave that for Operations like the Biospecimen reports?
