### ISSUE TITLE
Rct Wkly - Overall Recruitment Rates Table (Mia's metrics)

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#11]
Hi Madhuri,

We'd like to prioritize getting the verification/overall recruitment rate tables that Mia has been creating by hand in excel into the weekly report. For this item we'd like 3 things.
1. Non-cumulative tables of the overall recruitment rates by month and by site. I drafted what these look like in example table 1 and 2. The first is the total of all sites, the 2nd is site-specific for Sanford. We'd want separate tables for each site. Since these will be non-cumulative, each row will only represent the numbers in that month. We'll want to see the #verified, #recruits, and their response rates broken down by active/passive/overall and then the #opt-outs and their rate. 
3. A cumulative table of the the same metrics (example table 3)
4. A time-trend graph of these metrics by month

Example of the tables here on Box: [Overall Recruitment Rate Tables Examples](https://nih.app.box.com/file/1057938363271)

Let me know if you have any questions!

**Comment by jeannewu** [comment]
Hi, Amelia, the recruitment table had not recorded opt_out time as Michelle in April, you discussed it before. So how to get to opt-out rate by month?

**Comment by jeannewu** [comment]
Hi, Amelia, thank you very much for sharing the table template in the box. So the response rate is updated as the response rate for each recruitment type and overseer one as shown in the table template:****active response rate %= (N active verified/N active recruits)*100; passive response rate %=(N passive verified/N passive recruits)*100, and overall response rate  %=(N Total Verified/N Total recruits)*100****. It is _not the old version as numbers of verified participants from both active + passive recruits/ N Total active recruits_, right?

**Comment by robertsamm** [comment]
@jeannewu Hello Jing, the response rate/ratio has always been verified participants out of recruits as it is looking at how many people 'responded' to the invitation by joining the study. Please note, this metric above is for the Weekly Recruitment report so this is Madhuri's metric to work on. But I believe you took the first pass at this a while ago so feel free to share any code with Madhuri if that is helpful.

I forgot about the opt-out time being missing, let me check with Michelle and I'll get back to you.

**Comment by jeannewu** [comment]
Got it. Thanks a lot.

**Comment by jeannewu** [comment]
Hi, Amelia, Have you received my overall Recruitment Rate tables yet which were sent last week via email? And for the Optout rate, I have checked in prod, which started with collection on date from Jun. 2022. I haven't included this opt-out rate in this table yet. Please let me know if anything is needed for this set of tables. Thanks a lot.

**Comment by FrogGirl1123** [comment]
@robertsamm is this something you want consolidated into the weekly/daily report.

**Comment by jeannewu** [comment]
@robertsamm yes, I am working on this new consolidated weekly report, adapting my previous R code for the conversion of Madhuri's SAS codes for her daily, weekly, incentive and refusal metrics for this new metrics report. Thanks for asking, Amelia and Nicole.
