### ISSUE TITLE
Ad Hoc - HFH Data File for Needle-to-Receipt Times

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#110]
Please generate a flattened CSV data file that includes the following columns (in the order listed) for participants at HFH _only_:

1. Connect ID
2. RcrtES_Site_v1r0 (827220437) - **This should all be Henry Ford Health System (827220437 = 1)**
3. BioSpm_ColIDScan_v1r0 (820476880)
4. Needle-to-Receipt Time (in Hours) - **Refer to #90 for how to calculate. "Needle" and "Collection" are used interchangeably, but use "Needle" for this issue. The values in this column should have one decimal place**
5. BioSpm_Setting_v1r0 (650516960)
6. BioSpm_Location_v1r0 (951355211)
7. BioClin_SiteBldLocBL_v1r0 (185243482)
8. BioClin_SiteUrLocatBL_v1r0 (452847912)
9. BioRec_CollectFinalTime_v1r0 (556788178)
10. BioClin_ClinBloodTmBL_v1r0 (982213346)
11. BioClin_ClinicalUrnTmBL_v1r0 (139245758)
12. BioCol_PhlebInitials_v1r0 (719427591)
13. BioShip_LocalID_v1r0 (560975149)
14. BioPack_BoxID_v1r0 (132929440)
15. BioShip_SignEmail_v1r0 (948887825)

Please use the _Variable Label_ for the column titles.

**Requestor(s):** Stephanie

**Table or Figure title:** N/A

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** See list above

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Can you remind me what the tubeID variable in the biospecimen table would be? I'm trying to figure out how I can link the three Box table variables into this since that table doesn't have a Connect ID. I believe in the past we've used the tubeID from the boxes table and the tubeID from the biospecimen to find participants

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Sure! It is true that we used TubeID in the past, but I know the data structure for that changed, and "TubeID" isn't even in the data dictionary anymore. I still don't fully understand the new structure for this, but basically, you want to make the link through the biohazard bag ID (d_787237543_d_593843561 OR d_787237543_d_825582494); the format is _CXA###### 0008_.

Let me know if this helps. If not, I can take a closer look at the data dictionary.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Yes! Thank you.

I ran the data the first time but got many repeating rows that didn't seem like unique collections, so I removed duplicated. Please let me know if any data seems to be missing
[HFH_Needle_to_Receipt_No_Duplicates_2024-01-10_boxfolder_222593912729.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13890039/HFH_Needle_to_Receipt_No_Duplicates_2024-01-10_boxfolder_222593912729.csv)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The number of rows matches HFH's current number of collections, so thank you for removing the duplicates!

Column F (BioSpm_Location_v1r0) doesn't seem to be displaying properly. The values should be HFH K-13 Research Clinic (736183094), HFH Cancer Pavilion Research Clinic (886364332), or HFH Livonia Research Clinic (706927479).

For columns G and H, can you replace the clinic location IDs with the clinic names? 
HFH Clinic Locations:
- Macomb = 1060170018 OR 1060010063
- West Bloomfield = 1011220006 OR 1040010046 OR 1040010047
- Wyandotte = 1050010095
- Fairlane (Dearborn) = 1010180040
- Plymouth = 1011660013
- Royal Oak = 1011410008
- Troy = 1010360011
- K1 HFH Main = 1010010114 OR 1010010193
- Sterling Heights = 1010320019
- Columbus = 1010120026
- Livonia = 1010240013
- Taylor = 1010350019

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC ok great, and thanks for pointing those out. Here's the update
[HFH_Needle_to_Receipt_No_Duplicates_2024-01-11_boxfolder_222593912729.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13904367/HFH_Needle_to_Receipt_No_Duplicates_2024-01-11_boxfolder_222593912729.csv)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks great; thank you! The rest of the biospecimen team will review it, and I'll let you know if anything else is needed for this file.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Updated with #90  request 

[HFH_Needle_to_Receipt_No_Duplicates_2024-01-11_boxfolder_222593912729.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13907536/HFH_Needle_to_Receipt_No_Duplicates_2024-01-11_boxfolder_222593912729.csv)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, can you please add a column for the BPTL date received BioBPTL_DateRec_v1r0 (926457119)?

Also, can you look into why Connect IDs 5351970664, 7872097651, and 1189368357 are missing data for BioShip_LocalID_v1r0, BioPack_BoxID_v1r0, and BioShip_SignEmail_v1r0 in the file?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Can do. Is there a specific spot BPTL date received BioBPTL_DateRec_v1r0 should go in? And the merge seems to have no issues. Is it possible the box never shipped for those three due to a specimen deviation issue?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 It can go at the end. I was able to find the missing data in the Biospecimen Table data file and the shipping report in the dashboard but not in the Box Table file. It's very strange. 

Let me know if you can figure out why, and I'll just add the missing values; we'll still need to determine the cause eventually, though.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Oh I found the issue, I was only merging the biospecimen table and boxes table on d_787237543_d_825582494 instead of both d_787237543_d_825582494 and d_787237543_d_593843561. But d_787237543_d_825582494 has the correct  CXA###### 0008 structure, while d_787237543_d_593843561 is just yes or no. Is there another variable I should use instead of d_787237543_d_593843561?

Connect ID 1189368357 has a null biohazard bag (d_787237543_d_825582494) value. 
Connect ID 7872097651 has a biohazard bag value of CXA014716 0008, and there's no such bagID CXA014716 0008 
Connect ID 5351970664 has a biohazard bag value of CXA014715 0008, and there's no such bagID CXA014716 0008

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you for looking into this. There may be some bigger issue at play here, and I'll need some time to look into the operations end of it more. 

We want to get these data to HFH soon, so for now, you can leave the file as is with the missing data fields mentioned (I'll pull that data from the shipping reports I have and insert them) and just add the column for BPTL received date/time at the end. Thanks again!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  No problem! 
[HFH_Needle_to_Receipt_No_Duplicates_2024-01-16_boxfolder_222593912729.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13954922/HFH_Needle_to_Receipt_No_Duplicates_2024-01-16_boxfolder_222593912729.csv)
