### ISSUE TITLE
Ad Hoc - HP Data File for HP Streck Pilot Study

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#112]
**It would be great if this could be done by COB Friday (1/19). Thanks!**

Please generate a flattened CSV data file that includes the following columns (in the order listed) for participants at HP _only_:

1. BioSpm_ColIDScan_v1r0 (820476880)
2. RcrtES_Site_v1r0 (827220437) - **This should all be HealthPartners (827220437 = 0)**
3. BioCol_ColTime_v1r0 (678166505)
4. BioClin_ClinBloodTmBL_v1r0 (982213346)
5. BioClin_ClinicalUrnTmBL_v1r0 (139245758)
6. BioPack_BoxID_v1r0 (132929440) - ([Tip: Linking the Biospecimen and Boxes Table](https://github.com/Analyticsphere/metricsReportsRequests/issues/110#issuecomment-1883801018))

**Requestor(s):** Stephanie

**Table or Figure title:** N/A

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** See list above

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Sure, let me know how this looks

[HP Data File for HP Streck Pilot Study_2024-01-18_boxfolder_222593912729.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13979660/HP.Data.File.for.HP.Streck.Pilot.Study_2024-01-18_boxfolder_222593912729.csv)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks good. Can you also add a column for Collection Setting (650516960) between the _Connect_ID_ column and the _BioSpm_ColIDScan_v1r0_ column?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC All set

[HP Data File for HP Streck Pilot Study_2024-01-18_boxfolder_222593912729.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13979970/HP.Data.File.for.HP.Streck.Pilot.Study_2024-01-18_boxfolder_222593912729.csv)
