### ISSUE TITLE
Bio Weekly - Update Table/Figure Titles and Numbering

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#113]
Update each table and figure title and number in the weekly report. The original titles and their corresponding updated titles are listed in this document --> [UPDATED_Issue #113 - Table:Figure Titles and Numbering.docx](https://github.com/Analyticsphere/metricsReportsRequests/files/14012760/UPDATED_Issue.113.-.Table.Figure.Titles.and.Numbering.docx)

**Please note that each page of the document above lists the tables/figures that are supposed to be in each "Contents" section listed in #114. The bolded titles are the _updated_ titles. The two titles highlighted in yellow indicate that the table/figure's order has been changed (Figure 4.3 [3.3] and Table 26 [4.11])** 

Refer to #88 for updated titles/numbering for section 7, _Home Mouthwash Collections_.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  It looks like only Table 28 and Table are included. But right now we have Table 28a, Table 28b, Table 29a, and Table 29b. Do some of these need to get deleted?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Sorry about that, not sure what happen to those. Here's the updated file: [UPDATED_Issue #113 - Table:Figure Titles and Numbering.docx](https://github.com/Analyticsphere/metricsReportsRequests/files/14012751/UPDATED_Issue.113.-.Table.Figure.Titles.and.Numbering.docx) (I also replaced the linked file in the main issue comment above).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  No problem! This and #114 are basically done. Do you have a list of what the new row/column Totals should be named for each table?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Great! The additional edits for all the tables can be found in Box: https://nih.app.box.com/folder/244754020093. Let me know if you'd rather have an actual list of them, and I can make one.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  All set! 

[Testing-Restructure-of-Weekly-Biosec-Report.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14054224/Testing-Restructure-of-Weekly-Biosec-Report.pdf)



I also noticed some tables didn't have SD requested to be removed something like 'SS Tube 1" to "SS T1" (ex: Table 2.7)like others did. Please let me know if these also need to be fixed

**Comment by StephanieWeinstein** [comment]
@KELSEYDOWLING7 , Michelle and I will look through this.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Hi Erin, do you know if these changes will be put into affect soon? 

Also I was notified by Mia of an updated requirement for color use in plots based on color blindness. We are now limited to 7 colors, each with 5 saturation levels. 
[CGOV-20456_Color-Palette-Charts.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14561036/CGOV-20456_Color-Palette-Charts.pdf) 
I've tried to use the variations as best as possible to still be able to distinguish the difference for Site, Collection location, and Setting. before I apply this to the restyled version of the report, please let me know if there are any concerns. 
[Weekly_Biospecimen_Metrics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14562223/Weekly_Biospecimen_Metrics.pdf)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Here is the updated version with the color changes, additional/updated Tables 2.7 and 2.8 from issue #118 , additional/updated Tables 4.9 and 4.10 from issue #124 , and the additional/updated Figures 5.9 and 5.10 to split the HF Collections into two plots by setting. I also found a missing footnote requested in section 2 that's been added, and corrected Figure 3.1's title. 

[Testing-Restructure-of-Weekly-Biosec-Report.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14705155/Testing-Restructure-of-Weekly-Biosec-Report.pdf)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Here is the PDF with the comments embedded for the updates. Thanks! 

[Testing-Restructure-of-Weekly-Biosec-Report_ES comments_03.21.2024.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14723246/Testing-Restructure-of-Weekly-Biosec-Report_ES.comments_03.21.2024.pdf)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Thanks, let me know if I missed anything! Or typos, unfortunately R doesn't catch those 
[Testing-Restructure-of-Weekly-Biosec-Report.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14724004/Testing-Restructure-of-Weekly-Biosec-Report.pdf)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7, here is the list of those minor changes we just reviewed: 


Table 3.2-3.4 remove the - after Baseline 
Table 3.5 Baseline Biospecimen Survey Completion Time from Dashboard Entry of Clinical Collection Dashboard Entry
Table 4.11 Remove HFH and update Note: Table includes information for Kaiser sites only, other clinical collection sites are excluded 
Figure 5.8- update title "Baseline- Collection-To-Receipt Time (in Hours), HealthPartners Research Setting"
Figure 5.9- update title "Baseline- Collection-To-Receipt Time (in Hours), HealthPartners Clinical Setting"
Figures 5.10 and 5.11, swap these to keep consistent with showing research information first, clinical second and update titles "Baseline- Collection-To-Receipt Time (in Hours), Henry Ford [Research/Clinical] Setting" 
Figure 6.2 and 6.7 update title, take out "at" 
Figure 6.8- update title "Baseline- Weekly Research Biospecimen Collections by Collection Location, Marshfield Clinic Health System"
Figure 6.10- update title "Baseline- Weekly Research Biospecimen Collections by Collection Location, Sanford Health"
Figure 6.13- 6.16 update titles, take out "at"

**Comment by KELSEYDOWLING7** [comment]
Please let me know if I missed anything! @erincschwartz 

[Testing-Restructure-of-Weekly-Biosec-Report.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14857533/Testing-Restructure-of-Weekly-Biosec-Report.pdf)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7, just a few minor fixes left: 
- I realize now that the title I proposed for Table 3.5 is redundant, please update to: Baseline Biospecimen Survey Completion Time from Clinical Collection Dashboard Entry
- The titles for Figures 6.8, 6.10 and 6.15 all seem to get cutoff 
- Figure 6.15 remove "at"

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Thanks for catching that. Here's the updates.
[Testing-Restructure-of-Weekly-Biosec-Report.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14858684/Testing-Restructure-of-Weekly-Biosec-Report.pdf)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 I just reviewed these final edits. Look good, thank you! Changing status to Ready for Automation.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Based on this week's report is this good to close?
