### ISSUE TITLE
Bio Weekly - Add "Contents" and Section Headers

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#114]
Please add a "Contents" section to the first page of the weekly report. The contents are:

1. Collection Counts
2. Collection Completeness
3. Biospecimen Survey
4. Collection Activity Durations
5. Needle-To-Freezer Times
6. Collection Time Trends
7. Home Mouthwash Collections

Each content section should have a section header of the same name at the beginning of each section throughout the report (see #113 for a list of tables/figures to go in each section).

**Comment by HopkinsDC** [comment]
Issue is done per [comment](https://github.com/Analyticsphere/metricsReportsRequests/issues/113#issuecomment-1906420676) in #113.

**Comment by StephanieWeinstein** [comment]
@KELSEYDOWLING7 , Michelle and I need to review before you put this into automation.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Based on this week's report is this good to close?
