### ISSUE TITLE
Bio Weekly - Home Mouthwash Biospecimen Survey Metrics

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#115]
**These new tables are a continuation of #88 metrics for home mouthwash collections**

Please generate three new tables for the home mouthwash collection metrics. These new metrics will be added to the weekly biospecimen metrics report following Figure 7.1; the mock-up tables are numbered to reflect this.

**Requestor(s):** Domonique

**Table or Figure title:** 
- Table 7.7: Mouthwash Biospecimen Survey Status Among Shipped Baseline Home Mouthwash Kits
- Table 7.8: Mouthwash Biospecimen Survey Status Among Received Baseline Home Mouthwash Kits
- Table 7.9: Mouthwash Biospecimen Survey Completion Time Among Received Baseline Home Mouthwash Kits with a Collection Card

**Metrics to be updated or created:** Create new tables

**Variables needed (include variable name and Concept ID):** 
- RcrtES_Site_v1r0 (827220437) – Sites 
- BioKit_KitStatus_v1r0 (221592017) – Kit status
- BioKit_CollCardRet_v1r0 (137401245) – Collection card returned flag 
- SrvMtW_BaseComplete_v1r0 (547363263) – Mouthwash survey status flag
- SrvMtW_TmComplete_v1r0 (195145666) – Date/time mouthwash survey submitted
- BioFin_BMTimeBL_v1r0 (448660695) – Date/time mouthwash collected entered from the collection card

**Specify numerator and denominator by variable name where applicable:** 

Table 7.7
- Denominator = Shipped mouthwash kits (221592017 = 3)
- Numerator = Mouthwash survey status (547363263)

Table 7.8
- Denominator = Received mouthwash kits (221592017 = 4)
- Numerator = Mouthwash survey status (547363263)

Table 7.9
- Denominator = Received mouthwash kits with a collection card (221592017 = 4; 137401245 = 1)
- Numerator = Mouthwash survey completion time relative to card's collection time ([BioFin_BMTimeBL_v1r0 (448660695)]-[SrvMtW_TmComplete_v1r0 (195145666)]); **use the populated dates only for the calculation (disregard the populated times), as the table columns are in days**.
- **Please note that the "Not Submitted" column should be the sum of mouthwash surveys with a "Started" and "Not Started" status.**

**Mock-up table if applicable:** 
![Screenshot 2024-01-21 at 6 25 06 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/0db73573-2654-4211-8090-ede22d1bd338)

![Screenshot 2024-01-21 at 6 25 13 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/fdbfe137-67e5-4eda-a4b5-7c311e1ac073)

![Screenshot 2024-01-21 at 6 25 23 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/afe2932c-859d-41ce-98bd-7c97dc2ab5a9)

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  This is all set! I was able to run most of this in stage to test it, except Table 7.9 because 137401245 has no values in stage yet 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/2f51329c-3c9f-4d0b-b1cd-5f76994c9508)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Awesome! Can you update the total column labels to the labels I have in the [mock-ups](https://github.com/Analyticsphere/metricsReportsRequests/issues/115#issue-2093837082)?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Sorry I meant to add that too. So I can't find a way to do that without changing both the column total and row total to be the same name, which doesn't make sense for what they're actually calculating. I'll keep playing with it and doing research but I'm not 100% sure its possible

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, thanks for letting me know this. There are some tables in the report already that have just the column label updated and the row total as just "Total" (Table 8 [2.7] and Table 13 [2.13]); maybe looking at the code for those could help. If not, then it'll be better just to have "Total" for both.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thanks! I was able to update this but with the new denominators showing 0 people I'll have to wait for the data to rerun them

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Okay, no problem. Thanks!

**Comment by StephanieWeinstein** [comment]
@KELSEYDOWLING7 , Michelle and I need to review this. so hold for now.  thx!

**Comment by KELSEYDOWLING7** [comment]
Closing this to keep all communication of Home Mouthwash metrics to issue #88
