### ISSUE TITLE
Bio Weekly - Update Table 2.6 with New HFH Clinic Location IDs

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#116]
Please the new HFH clinic location names and corresponding Location IDs (BioClin_SiteBlLocation_v1r0) and incorporate the names into Table 2.6 [formally Table 7.3] (clinical blood draw completeness at HFH) for when the IDs are pushed to NCI.

**NCO = 1010270015
Ford Road = 1010200009**

**Requestor(s):** Domonique

**Table or Figure title:** Table 2.6: Blood Collection Completeness Among Baseline Clinical Collections by Clinic Location, Henry Ford Health

**Metrics to be updated or created:** Update existing table

**Variables needed (include variable name and Concept ID):**
- BioClin_SiteBlLocation_v1r0 (185243482)

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  All set! Doesn't look like there's any at Ford Road yet 



![Image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/168ec5d6-2713-4fb6-acc4-a31a937e1570)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Looks good, thanks! 

Ford One hasn't launched yet, but I got the ID from HFH ahead of time, so it'd be included when it does.

**Comment by KELSEYDOWLING7** [comment]
Ford One now has its first participant. This has been updated in Table 7.3 current Weekly Biospecimen Report version while the Restructured/Restyled Weekly Biospecimen Report is still under review
