### ISSUE TITLE
Updates to Wkly Module Metrics

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#117]
Hello @KELSEYDOWLING7 , we are finally bringing the module metrics report back up in priority for revisions. Eventually, we would like to fold this report into the Operations Report instead of being run separately. For now, please work on this outside of the Operations Report and outside of the automation until we finalize all of the metrics needed. Once finalized, we will then work on where each metric should go in the Operations report. 

We made several comments in the file attached below. We would like to consolidate and get rid of several of the metrics and also requested changes to current metrics as well as new. Some of the metrics we will also need to discuss before finalizing (e.g. there's a metric that we need the distribution reran so we can decide what categories would make sense to convert it to a categorical table). Can you please take a look and let us know if you have any questions? Once we get closer to a final version, we will re-evaluate which metrics should also be updated to be stratified by site FYI.

We know you have several higher priorities right now, so we understand you may not be able to get started on this right away which is fine.

Comments below:
[CCC_Weekly_Module_Metrics_12_11_2023_AMRComments_Updated01242024.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14041409/CCC_Weekly_Module_Metrics_12_11_2023_AMRComments_Updated01242024.pdf)

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Hi, thanks I'll get started on these. One general question though. Is it possible to keep this as a separate report? The Operations report already can take up to an hour to run depending on the machine/issues/testing/ect. We were really hoping to reduce its size, which is where we got into the specifics of what csv outputs were or were not being used. I'd very much like these tables to not be added to that report, as it would only increase how long it already takes to run/test the Operations report. 


Also do you have another version of the pdf? Several of the notes are cut off on my end

**Comment by KELSEYDOWLING7** [comment]
@robertsamm Here's the updated report from the notes I could see. please let me know if anything is missing or misinterpreted.
[CCC-Weekly-Module-Metrics_RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14067304/CCC-Weekly-Module-Metrics_RMD.pdf)



For table 2, if stratification of recruitment status is removed there are therefore only 2 columns, so I'm not sure if row percentages would make sense. Each row would be 100%. For now I kept them as the percentage of participants within each Module as it was before (so each section will have the 3 not started, started, and submitted rows add up to 100).


For table 7 in the currently existing report, we do have a Github issue for that (https://github.com/episphere/questionnaire/issues/220) but no current ETA on making a fix.

**Comment by brotzmanmj** [comment]
Hi Kelsey,
This is getting much closer. I've attached with feedback. 
[CCC-Weekly-Module-Metrics_MJB.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14315591/CCC-Weekly-Module-Metrics_MJB.pdf)

After you address this, we'll take a look and see what else we need.
Thanks

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Thank you for your feedback. Here is the updated report with the requested changes. I also changed 'Completion' and 'Completion Time' to 'Submission' and 'Submission Time' in the report for consistency.

[CCC-Weekly-Module-Metrics_RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14349129/CCC-Weekly-Module-Metrics_RMD.pdf)

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7 We think looks really good. A couple of small changes and then this should be good to move to prod. 
- Delete Figure 1 and Figures 2.1-2.4. They aren't revealing much that is useful and we're finding them pretty hard to consume.
- Table 6 change units to minutes to better align with the other information in the report
- Table 2- is it possible to put Not Started, Started, Submitted in columns and have BOH, MRE, SAS, LAW in rows to make it easier to follow?
- One table to add to the beginning of the report, please make it Table 1. Completion of Baseline Survey by Site. Please make the format the same as Table 13 from the Weekly Operations report but it should just reflect Baseline Survey, not blood collection.

Then we'll give it one last glance before you post it to Connect_ALL.

**Comment by brotzmanmj** [comment]
Actually one more thing, sorry! @KELSEYDOWLING7 please add to Table 4 a row at the bottom for 'All Modules' meaning time from verification to the time they completed the last of the four modules they submitted, regardless of which one was last. And please change Table 4 to days instead of hours.

**Comment by KELSEYDOWLING7** [comment]
Good morning, @brotzmanmj  Just about done. The only question I have is should that Table 4 only look at Active participants, or at all participants? I realized I had it set to active only

**Comment by brotzmanmj** [comment]
Good question @KELSEYDOWLING7  Let's include all participants

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Thank you! Please let me know if anything else should be changed. I assumed the new table one should just be essentially all completed or not all completed, and that row percentages would make the most sense.
[CCC-Weekly-Module-Metrics_RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14462977/CCC-Weekly-Module-Metrics_RMD.pdf)

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 just one thing, the new table looks great, can you change in the title from '...Baseline Surveys...' to '...Initial Survey...' for consistency? The format looks perfect.

**Comment by brotzmanmj** [comment]
And I think this change still needs to be made: @KELSEYDOWLING7 please add to Table 4 a row at the bottom for 'All Modules' meaning time from verification to the time they completed the last of the four modules they submitted, regardless of which one was last. And please change Table 4 to days instead of hours.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Sorry! The old table 4/new table5 was being incorrectly masked so it's here now. And yes, that consistency update has also been made. 
[CCC-Weekly-Module-Metrics_RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14465852/CCC-Weekly-Module-Metrics_RMD.pdf)

If this is good to go I'll post it to the Connect_ALL folder manually for the next two Mondays, since it's a bit late for us to get that into next week's automation, and during the next automation meeting on 3/15 Jake can add this in

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7 new Table 5 and Table 7 don't have the 'N' column. Can you please add that? 
 Fine to do it manually for the next two Mondays.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Thank you for pointing that out. Please see the updated report. If this looks good, I can upload it to Connect_ALL. Do you have an existing folder it should go in or should one be created?

[CCC-Weekly-Module-Metrics_RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14482529/CCC-Weekly-Module-Metrics_RMD.pdf)

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7 Thanks for adding that. 

In the footnote of Table 9 there are a couple of typos, can you fix those?

And on Table 10 can you put row percents instead of column percents? I think they will be much more informative.

And then it can go on Box in this new folder I just created here for Connect Weekly Survey Status Metrics: https://nih.app.box.com/folder/251929835507

**Comment by KELSEYDOWLING7** [comment]
[CCC-Weekly-Module-Metrics_RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14482920/CCC-Weekly-Module-Metrics_RMD.pdf)

If this looks good I'll upload there now

**Comment by brotzmanmj** [comment]
Look good, thanks! Ready to upload
