### ISSUE TITLE
Bio Weekly - New Tables for Research Blood Tubes Collected

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#118]
Please **replace** the current Table 2.7 (formally Table 8): _Blood Tubes Not Collected Among Partial Blood Collections at Research Collection Visits_ with two new tables:

1. Table 2.7: Total Blood Tubes Collected Among Baseline Research Baseline Collections (within each finalized baseline research
>- Within finalized baseline research collections, how many total blood tubes were collected
>- **Only 0 through 5 blood tubes collected is possible for research**
>- This new table is similar to the format/structure of Table 2.8 (formally Table 9): _Total Blood Tubes Collected Among Baseline Clinical Biospecimen Collections_
**Add the following note to the new Table 2.7** --> Note: Research collections are expected to have a total of 5 blood tubes collected.

2. Table 2.8: Blood Tubes Collected Among Baseline Research Collections by Tube Type 
>- Within finalized baseline research collections, home many of each tube type have been collected
>- This new table is similar to the format/structure of Table 2.9 (formally Table 10): _Blood Tubes Collected Among Baseline Clinical Biospecimen Collections by Tube Type_
**Add the following note to the new Table 2.8** --> Note: Research collections are expected to include 2 SSTs, 1 Heparin, 1 EDTA, and either 1 ACD or 1 STRECK.

**Be sure to update the table numbers in section 2 after added these new tables**

**Requestor(s):** Domonique

**Table or Figure title:** 
Table 2.7: Total Blood Tubes Collected Among Baseline Research Baseline Collections
Table 2.8: Blood Tubes Collected Among Baseline Research Collections by Tube Type

**Metrics to be updated or created:** Replace existing table with two new tables

**Variables needed (include variable name and Concept ID):**
- RcrtES_Site_v1r0 (827220437) – Sites
- BioSpm_Visit_v1r0 (331584571) - Select Visit
- BioSpm_Setting_v1r0 (650516960) – Collection setting
- BioRec_CollectFinal_v1r0 (410912345) - Complete Collection
- BioCol_ObjColl_v1r0 (593843561) - Object collected

**Specify numerator and denominator by variable name where applicable:**

Table 2.7
- Denominator = Finalized Baseline research biospecimen collections (331584571=0; 410912345=1; 650516960=0)
- Numerator = Total count of blood tubes collected [0-5] (d_652357376_d_593843561;  d_454453939_d_593843561;  d_838567176_d_593843561;  d_299553921_d_593843561;  d_703954371_d_593843561; &  d_505347689_d_593843561)

Table 2.8
- Denominator = Finalized Baseline research biospecimen collections (331584571=0; 410912345=1; 650516960=0)
- Numerator = blood tubes collected (d_652357376_d_593843561;  d_454453939_d_593843561;  d_838567176_d_593843561;  d_299553921_d_593843561;  d_703954371_d_593843561; &  d_505347689_d_593843561)

**Mock-up table if applicable:** 
![Screenshot 2024-01-24 at 2 52 14 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/3aa0b760-fdf5-497b-9e49-3985ed499b81)

![Screenshot 2024-01-24 at 2 52 21 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/88392204-f054-4a19-94f6-2847966df3e0)

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein @brotzmanmj  Here you go!
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/00ff46a7-e027-4e5f-80f6-5b4d4d53ecf7)


Please note Connect ID 1958238595 somehow had 6 research blood tubes

**Comment by erincschwartz** [comment]
Kelsey, this looks good. Accepted

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz While the Style Updates are still under review, do you want the Table 8 in the currently running Weekly Biospecimen Report to be updated with these changes?

**Comment by erincschwartz** [comment]
I have it on my list to look over the style updates, I will get to this by COB Monday and I will be in touch if I have any questions. If you want to hold off and update this table when you make the style updates, that is fine.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Based on this week's report is this good to close?
