### ISSUE TITLE
 New Variables Needed in the Flattened M1V1 table(s)

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/metricsReportsRequests#119]
The Mod1 January push has some new variables. Can you update the m1v1 flattened table in Stage (for now) and eventually Prod to include these new variables? Thanks! 

Mod1 is the only survey I know for sure is being updated Wednesday. We may have to keep an eye out for other surveys being updated that will also have new variables

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 

I updated m1v1 and m1v2 in STAGE.

I can update them in PROD after the January push.
