### ISSUE TITLE
Rct Wkly - Duplicate frequency count and time trend

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#12]
We would like to monitor the duplicates more closely. Since we currently filter the active dups out of the metrics, I think this will need to be a separate report. Since we are hoping the number of duplicates will go down - this won't need to be run forever.

1. We would like a frequency table of the duplicate types stratified by site (do not need to stratify by active vs passive) and then a total column for the total number of duplicates
2. We would like a time trend graph for duplicates where duplicate type=Participant Already Enrolled ONLY. (Basically, we want to see if the duplicate scenarios where people sign in with more than one account decreases over time with the preventative measures we have put into place). The time trend should be per month.

Let me know if you have any questions for this one!

**Comment by mnataraj92** [comment]
Here's the report: https://nih.app.box.com/file/1068870404266

Note- the columns add to 436 and not 430- this was the issue we discussed earlier where there were 6 participants with a verification status of something other than 'duplicate' but had a duplicate type. I updated this in the SOP draft.

**Comment by robertsamm** [comment]
Thanks @mnataraj92. Michelle and I have reviewed and both the table and the time trend look great! Exactly what we needed. Only comments are edits to the metric titles. For the table please change to 'Duplicate Frequency By Duplicate Type and By Site' and the time trend change to 'Time Trend for Duplicate Type = Participant Already Enrolled'.

Thanks for the reminder about the 6 participants that need their duplicate type changed. I'll send a separate email to loop Michelle and Nicole in but we will need to generate a list of the people in this category and which sites they belong to and ask the sites to push an update.

**Comment by mnataraj92** [comment]
Here it is with the updated title changes: https://nih.app.box.com/file/1068870404266

**Comment by robertsamm** [comment]
Looks perfect, closing isue.
