### ISSUE TITLE
Text permission table

### ISSUE THREAD

**Issue by kmazzilli** [Analyticsphere/metricsReportsRequests#120]
Requestor(s): Kaitlyn Mazzilli

Table or Figure title: Table 65. Permission to text mobile phone number among verified participants

Metrics to be updated or created: Weekly operations report

Variables needed (include variable name and Concept ID): 
Text permission, yes or no: concept id: 646873644, variable name: RcrtUP_MobileTxt_V1R0

Mock-up table if [applicable:] 
[Table 65 mock up.docx](https://github.com/Analyticsphere/metricsReportsRequests/files/14129762/Table.65.mock.up.docx)

Notes:
We are looking to see how many verified participants have given us permission to text their mobile phone number. We would like to show this in a table (see mock up) with the counts and percents. We would also like to have a row for people who did not give us a mobile phone number. This should add up to the number of total verified participants that we have.

@mnataraj92 Would concept id:388711124, variable name: RcrtUP_Mobile_v1r0 be blank if a mobile number was not given? If so, that would work for the row that would show who did not give us a mobile phone number.

Approved by: Michelle Brotzman

**Comment by mnataraj92** [comment]
yep, 388711124 would be blank if a mobile number was not given

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/19c7c19c-5b53-437d-ab14-05d52ae31854)

**Comment by kmazzilli** [comment]
This looks good to me! Thanks @KELSEYDOWLING7

**Comment by brotzmanmj** [comment]
This looks good and it's great to see such overwhelmingly positive numbers!
