### ISSUE TITLE
Check metric reports for updated age ranges

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#122]
Please review all reports metrics that refer to age and the coding to be sure that the additional age categories (30-34, 35-39, 66-70) to the de-identified age variable (934298480) are included and will populate in the reports. For categories where we have zero participants in it they should still show in the report as ‘0’ instead of not appearing at all.

Reports possibly impacted: 
-Operations Report
-Biospecimens Report
-Weekly Surveys
-Weekly Logs
-anything else?

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  This is all set! It will be reflected starting on the 19th as the next automation update is the 16th. In the Operations report, tables 59 and 62 have been updated as well as the weekly logs. The Weekly CCC Module Metrics report and Weekly Biospecimen Report don't reference this age variable.
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c69fe08f-81bd-43ba-91db-5092d1371a11)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1782224d-6b63-4cb0-b17f-77dcc20cc99b)


I've also reviewed the module metrics and confirmed that nothing there needs to be changed. The age variables are not limited to 40-69 (ex: age at diagnosis, age starting to use certain products, age at first/last period, LIFE questions, ect.). I will, however, update the Module 3 QC to make sure people aren't answering the LIFE questions past their current age or providing say an age of using a product past their current age

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 thanks this looks good! I see that Marshfield already has someone in the '66-70' age range verified for 'site reported age at time of recruitment'. @mnataraj92 @brotzmanmj @kmazzilli is this expected? Do you recall discussing this with MF already?

**Comment by mnataraj92** [comment]
I don't remember the situation exactly because it was some time ago but there was someone we agreed to let stay in the study that was outside of the age range at the time because they were already verified and they would be eligible with the new age ranges.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Hi Amelia, does anything else need to be looked into for this or am I good to close the issue?

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 I confirmed with Michelle she was aware of the MF participant in the 65-70 age group so nothing more needed. Closing issue.
