### ISSUE TITLE
QOL/PROMIS Survey Metrics - Operations Report

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#123]
Please add to the Operations Report the follow 3 new metrics for Quality of Life/PROMIS survey

1. QOL Survey completion

- This should look similar to Table 10 in the Operations Report but replace the columns of status with ‘Not Eligible’, ‘Not Started’ ‘Started’, ‘Submitted’
- Title: Completion of Quality of Life 3-Month Survey of Verified Participants by Site
- Footnote: The QOL 3-Mo Survey becomes available to participants 3-months post-verification. The survey is currently available only to prospectively verified participants starting on 03/01/2024 and will be made available to retrospective participants at a later date. 

2. QOL survey completion time (from start to submission) in minutes

- This should look similar to '4. Duration in minutes from start to submission for each section' on the Weekly Survey Metrics with categorical table + quartile ranges. 
- The estimated duration is 10-15 minutes, so for the categories perhaps do: Under 5 minutes, 5 to 10 minutes,10 to 15 minutes, 15 to 20 minutes, 20 to 30 minutes, 30+?
- Title: Quality of Life Survey Completion Time from Start to Submit for Verified Participants

3. Time from QOL trigger to submission of QOL survey

- see github issue for details on trigger: https://github.com/episphere/connect/issues/877. Survey will trigger based on the sending of the notification, specifically the first contact attempt for the QOL 3-month notification.
- Think this can just be a quartile range for now until we have more data to suggest categorical ranges. Suggest adding addtl percentile range (perhaps 90th?) and we'll monitor to see if addtl quartiles are needed.
- Title: Quality of Life Survey Completion from Trigger to Submit for Verified Participants
- Footnote: The QOL 3-Mo Survey is triggered to participants at 3-months post-verification

**Comment by robertsamm** [comment]
FYI I think the 'Not Eligible' status CID is still being created in item 1. @mnataraj92 can you update here once it's created?

**Comment by mnataraj92** [comment]
320303124 = 789467219

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Ok all set. Once we have data for these variables and a QOL notification type I can test this code

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  I'm going to start testing this code now that we have stage data. This may be more of a Madhuri question but do you know if we'll be creating a derived QOL trigger flag variable? The reason I ask is otherwise I'll have to merge the notifications table into this report for table 3 (on the notification category of "3mo QOL Survey Reminders", attempt of "1st contact" and the notification_time for each of those occurrences). Just trying to figure out the best way to go about that table

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 the survey is triggered upon the QOL PROMIS email/SMS notification being sent to the participant. This is when the survey shows up on the PWA for the pt to complete and the survey status flips from 'not yet eligible' to 'not started'. 

If we don't want to merge the notification table data in, could we consider the trigger of the survey anywhere where the survey completion flag does not equal 'not yet eligible'? @brotzmanmj thoughts?

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 the flag for the3-month QOL/PROMIS survey will be the CID for 'not yet eligible' for people who for whom the survey is not triggered. You can use that.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj @robertsamm  Sorry a better question would be is there a timestamp variable being created that's associated with this trigger? Table 3 requires the difference of two time stamps. So we'd have to use the time stamp from the notifications table if there is not a timestamp for those who become eligible

**Comment by brotzmanmj** [comment]
Yes, it will be the timestamp of the first notification.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  @brotzmanmj  Here are these table with the data we have thus far. 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ae383358-fc57-4db0-96d4-c0f0689fff2a)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/dff7c2d1-08c7-4bb8-8c98-4d462433e019)

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 Thanks Kelsey. These look good. A few comments below.

1. Table 67: could we have the columns in this order - not eligible, not started, started, submitted? (unless Michelle had indicated a different order already)
2. Table 68: Is it possible to order the rows from least amount of time to most: Under 5, 5-10, 10-15 min
3. Table 69: Can you add the time unit? I'm assuming it's minutes above? Should we change it to hours to match some of the time trends we have for the initial survey (e.g. the time from verification to initial survey section submission is in hours)? This length of time will continue to get longer as time goes on.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm Oh, of course. 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/59138983-9530-4a5b-b701-95cafed97ed6)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c31b0c4a-9a84-46e0-ae73-33945db28230)



 It looks like the other tables with summary statistics (Tables 39, 54, 55, 56, 57,58) are in days.  This is what Table 69 would look (numeric preview) like in days and in hours, respectively
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f577c17c-d092-4a48-8e63-d6d1f1f7119d)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/84b5fdc4-7e39-43e2-b7be-806f9377490f)

**Comment by robertsamm** [comment]
Thanks @KELSEYDOWLING7, let's go with days for table 69

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Ok all set! 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d111b710-3efc-48bc-b997-6dd48f2f51fe)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c8f2b82c-6fea-4ee1-9247-154778de6da3)

**Comment by robertsamm** [comment]
Perfect! Just one minor thing @KELSEYDOWLING7, for table 68 and 69 please add the '3-Month' back into the survey title like it is in the first one (QOL is a repeated measure, so we'll have future quality of life surveys) These can go ahead and be posted to ALL once fixed.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Done!
