### ISSUE TITLE
Bio Weekly- Incorporate ad hoc changes to expand Table 25 and add table for order placed to present day

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#124]

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Updated Table 25, added the new Table 26, and updated the remaining table numbering accordingly
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/56042179-56bd-4a3e-b25f-f641e607846f)


I also updated the restructured style version of the report (Table 25 is the equivalent of Table 4.9 in that report)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6ac725b2-c0b4-4e28-8e5f-51a9002436c8)
