### ISSUE TITLE
KPGA phone pilot selection

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#126]
Hi @KELSEYDOWLING7 Here are the instruction for the KPGA phone pilot selection. Please review and then we can discuss.
https://nih.app.box.com/file/1459676582273

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Here's the preliminary tables
[KPGA-Phone-Pilot.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14513728/KPGA-Phone-Pilot.pdf)

**Comment by brotzmanmj** [comment]
Closing this request at KPGA will do selection on their side
