### ISSUE TITLE
Module Metrics- PROMIS related metrics

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#127]
Hi Kelsey, For the PROMIS metrics, can you add the following:

Only among those who are eligible for PROMIS (so drop off the 'not yet eligible' people and keep those who are PROMIS flag = not started, started, submitted), we'd like to know the PROMIS response rate stratified by these four groups:

- Completed baseline survey Modules 1-4
- Collected any baseline biospecimen (blood, urine, or mouthwash)
- Completed both of the above
- Completed neither of the above

Since the PROMIS metrics are in the operations report, please add this new metric there

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Please let me know how the updated Table 67 and new Table 68 look.

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e3bef776-a745-496d-89a8-cc635e229c3a)

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7 Thanks for doing these so quickly. 

For Table 67,  please change the last column header to 'Total QOL Eligible Participants' as opposed to total verified participants.
And change title to' Completion of 3-Month Quality of Life Survey among Eligible Participants'

For Table 68, let's make the rows labels a little clearer
Completed all baseline survey modules 1-4, no baseline samples
Completed any baseline sample, did not complete baseline survey
Completed both survey and sample(s)
Completed neither survey or sample(s)
And change title to 'Completion of 3-Month Quality of Life Survey by Baseline Data Completeness'

And would it be possible to get a run of this today (even if not yet automated)? Mia will be very interested in these data. Thanks.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  No problem! Sorry, I was OOO yesterday. Please see the updated tables below

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/19d493b1-9ba7-4d78-9b92-f669dd247298)

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7 all looks good except still need the change to the title for Table 67

**Comment by KELSEYDOWLING7** [comment]
My mistake! that has now been updated

**Comment by brotzmanmj** [comment]
Great, thanks!
