### ISSUE TITLE
Error in Table 62 of operations report

### ISSUE THREAD

**Issue by kmazzilli** [Analyticsphere/metricsReportsRequests#128]
Requestor(s): Kaitlyn Mazzilli

Table or Figure title: Table 62 "Age of All Active and Passive Recruits"

Metrics to be updated or created:
Weekly Operations Report

Current table with errors highlighted:
<img width="1247" alt="Screenshot 2024-03-19 at 6 20 00 PM" src="https://github.com/Analyticsphere/metricsReportsRequests/assets/40246056/72095d70-9656-452e-be96-66f02e6232af">

Notes: It looks like there is a typo in both the total row and column of this table. This table is actually showing the Total Recruits instead of Total Verified. Could you fix the titles of the total row and total column to read "Total Recruits" instead of "Total Verified Participants"?

Approved by: Mia Gaudet

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  Yes, all set! This will be reflected on Mondays report
