### ISSUE TITLE
KPGA deviations

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#129]
@KELSEYDOWLING7 can you run a current biospecimen deviations report for KPGA, like the one below that has been removed from the Weekly Biospecimen Metrics Report? They have 2,000+ deviations reported, much more than other sites and I would like to see if there is a pattern/something more we need to look into. 

![Image](https://github.com/Analyticsphere/metricsReportsRequests/assets/157617486/77910f02-3dc0-46b8-a7c6-23163fcfc07d)

Please let me know if you need additional information.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Sure thing. Let me know if you're able to see the full picture of if it gets cut off. its very long. 
![Rplot](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/80bb78f8-6505-47e7-bcda-3a11a2b20602)

**Comment by KELSEYDOWLING7** [comment]
It did not attach the way I thought it would
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/a074d138-cbec-42ea-9ccd-60e6bfce685c)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/514a683c-4580-422d-a92f-29206bd327a2)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 that was sure fast! Between the 2 images you sent, I believe this is just what I needed. Thanks!

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 I will bring this to the Bio team tomorrow and likely move it to "Done" unless they would like this added in to the Weekly Report.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Should this issue be good to close?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 please keep this open. We did not cover in our meeting, as time ran short. Will review these on Friday and get back to you.

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7  I closed this issue, reviewed with Bio team and this report provided the information we needed. Thank you!

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Great thanks!
