### ISSUE TITLE
Rct Report - Consolidate Daily and Weekly Report

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#13]
Hi @jeannewu, we would like to consolidate the daily and weekly recruitment report into one report that will be run weekly and make some minor formatting changes. I have created an outline of how we want this report to look like here: https://nih.app.box.com/file/1080304024953.

As you can see in the outline, we want to reorder some of the tables and add table and figure titles to each metric. It would also be nice to group some of the metrics into sections, so I have included those headers in yellow highlight. We also want to clean up the table names to make them more understandable to people who don't view these reports often since we are going to start sharing this report out to all sites so I made some title changes in blue highlight. Finally, some of the tables need either a column label change, change to the denominator, or a footnote - please see the comments I made to the side. At the bottom of the report I included the tables/charts we don't need need anymore and can be dropped from the report.

Let me know if you have any questions, I am happy jump on a call as well.

**Comment by robertsamm** [comment]
Hi @jeannewu Michelle and I have an updated consolidated metrics report outline. Please ignore the link above that one is outdated. Here is the new outline to work off of: [Consolidated Metrics Report Outline ](https://nih-my.sharepoint.com/:wb:/g/personal/robertsamm_nih_gov/EZUqSyBcSClBjifx4T6-n48BmLmFE7e5bVJiKt_lE611ew?e=XCsbwG)

Please reference this document to consolidate the Daily and Weekly CCC Metrics Report into one report. The metrics in the green box are the ones to use in the report and they are put in order that we want to see them. You'll see a red 'D' for metrics pulled from the Daily Report and a blue 'W' for those from the Weekly. The metrics in the grey box are metrics that are no longer needed. Let me know if you have any questions.

**Comment by jeannewu** [comment]
@robertsamm thank you very much for sending me this consolidated metric report outline. In my view via MacBook, all tables are lined up in a single page with four columns without the Table order numbers. May you please give me the order of these tables and plots from both Daily and Weekly metrics in this consolidated report if possible? Thanks a lot.
