### ISSUE TITLE
Operations Weekly Metrics- BL survey completion by research vs clinical collection setting

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#130]
Requesting two new metrics:
1)
Title: Completion of Baseline Survey (modules 1-4) by Collection Setting, among Participants who Donated Baseline Samples
Limit this metric to participants with any baseline collection (blood, urine or mouthwash for research, blood or urine for clinical).
Where to put it: After Table 23 
Format: Format the same as Table 23 but the rows will be:

> Baseline Research Collection
> Baseline Clinical Collection  
> Total 

Make these site specific and only needed for hybrid sites: HFH and HP for now (Sanford and Chicago will be added when they launch hybrid in May and June respectively).

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Please let me know how this looks. I fixed 'modules' in the titles to 'Modules' after it ran.
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/3cfbfa9e-fbea-4d00-9069-eed15a6526de)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/958cf26f-b90e-4bed-92f0-11701bd7df7f)



I'm assuming we also now need to add two to all table numbers after these?

Also for variables I used:
684635302 (BioFin_BaseMouthCol_v1r0, any mouthwash collected) 
167958071 (BioFin_BaseUrineCol_v1r0, any urine collected) 
878865966 (BioFin_BaseBloodCol_v1r0, any blood collected) 
650516960 (BioSpm_Setting_v1r0, Collection Setting) 
I also filtered these participants to be verified, as is the case in table 23.

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7  can we get row percents? We're comparing the relative survey completion rates between those who did clinical collections vs those who research collections, so the row percents will give us the best view of that.

And yeah, we would need to update the rest of the table numbers after this. 
It would be good to move to a format with a table of contents and subsections similar to how we have the Biospecimen Weekly Report so it will be less onerous to update table and figure numbers. Do you agree and would you like to propose sections that we can respond to or have us initiate that?

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj 
Updated to row percentages.
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/55d958da-5c1d-41d0-8d3c-8d6f67f672ef)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/012fa06c-3198-4cb3-846c-a559d1221407)


I agree, it would be very helpful to split this similar to the Biospecimen report for renumber and reordering. I think up until Figure 6.9 (current report page 67 divides nicely, but from there I would think the remainder of the tables would need to be put elsewhere to fit this particular pattern. Happy to discuss or create a mock up.

Section 1 Recruitment Status and Verification: Table 1/Figure 1 through Table 9
Section 2 Baseline Activity Completion: Table 10-Table 33
Section 3 Data Destruction, Refusals, Withdrawal, and Deceased Participants: Figure 5 through Table 36
Section 4 Baseline Incentive Eligibility: Table 37- Figure 6.9

Then this is where it gets a bit messy, and is just one idea for how to arrange the rest:

Section (maybe after section 1 above to go with verification data) Demographics of Verified participants : Tables 59-64
(Possibly adding pre-consent opt outs to section 3): Tables 48-50 
(Possibly added to section 1): Tables 42-47, and Table 66
(possibly added to section 2): Table 51-58b
Section 5 QOL: Tables 65, 67-70

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7  These two tables look good. Consider this done.

I'll open a new issue for sectioning the Weekly Operations Report so we can close this request and track that one separately.
