### ISSUE TITLE
Weekly Operations Report - Update Table 34 Ref and Wds

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#132]
On Table 34 in the weekly operations report (Refusal and Withdrawals among Consented Participants), @KELSEYDOWLING7 are you using the Participation Status variable to generate this table or is it generated from the individuals yes/no flags for the various refusal and withdrawal variables? The answer will determine what if any changes we want to make.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  This is generated from the individual yes/no flags of the refusal and withdrawal variables

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 great. In that case, could you just change the column header for 'Data Destruction' to 'Data Destruction Requested' (just so we can different that from data destruction carried out which will be in production soon). And please add a footnote as follows:
Note: All withdrawal requests inherently include HIPAA revocation but are counted in table only once as 'Withdraw Consent'. All data destruction requests inherently include withdrawn consent and HIPAA revocation but are counted in table only once as 'Data Destruction Requested'.

**Comment by KELSEYDOWLING7** [comment]
Ok @brotzmanmj  Here's a preview of the updated table
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/47404747-7c9e-44bf-9b71-ae751d0462f0)

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7  looks good, thanks, just one spelling error on the column header for Data Destruction Requested.

**Comment by KELSEYDOWLING7** [comment]
Oops! Thank you for catching that
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ced9be05-b158-457b-9987-b2ab011840f6)

**Comment by brotzmanmj** [comment]
Looks good! OK to close.
