### ISSUE TITLE
Make Data Destruction ad hoc report an automated 

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#133]
We would like to make it so the ad hoc Data Destruction Report is automated and run on a monthly basis to assist with monitoring the data destruction tasks. This can be placed in the DCEG_ONLY Reports folder. A couple of edits to the report are listed below.

1. Add a column for ‘Data Destroyed’ where participation status (912301837)=data destroyed (884452262)
4. Change ‘Data Destruction Flag’ column label to ‘Data Destruction Requested Flag’ 
3. Change 'Data Destruction Form Flag' label to 'Data Destruction Form Signed' 
6. Change label for 'Date of Singed Data Destruction Flag' to 'Date Signed Data Destruction Form'
7. Delete 'All Baseline Surveys Completed' column and change to separate columns for each survey module status
8. Change 'Biospeimen (BU or BUM) Survey Flag' label to 'Baseline Biospecimen Survey Flag'
9. Add 'Baseline' to blood, urine, and mouthwash collected labels

**Comment by KELSEYDOWLING7** [comment]
I've made a new subfolder for these monthly reports here https://nih.app.box.com/folder/255783409227 within the DCEG_only Metrics reports folder. Do you want that run on the first of the month like all the other current monthly reports?

I've also uploaded today's report with these corrections there

**Comment by robertsamm** [comment]
Thanks @KELSEYDOWLING7 most of the changes look good, thanks for making them so quickly! The only one I'm not seeing is the first item, to add a column for 'data destroyed'. 

Yes, first of the month is perfect!

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  My mistake! I added the column but forgot to update the output. The completed update is now on Box

**Comment by robertsamm** [comment]
Thanks @KELSEYDOWLING7 reviewed and looks great! Thanks so much for finalizing this report on short notice. Closing out the issue.
