### ISSUE TITLE
Add ignore file for Module 1 QC issues

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/metricsReportsRequests#134]
Can we ignore any QC errors where the qc rule is NA or crossValid1 equal to or less than char() and Module 1 was started before May 26, 2023?

This is linked to closed issue #227 in Episphere (wouldn't let me tag you in Episphere)

**Comment by jacobmpeters** [comment]
Hi Kelsey. Apologies that this one fell through the cracks. I'll add this to my ToDo.

**Comment by KELSEYDOWLING7** [comment]
No problem! Definitely a lower priority

**Comment by jacobmpeters** [comment]
I put this on my calendar as a ToDo for tomorrow afternoon.

**Comment by jacobmpeters** [comment]
Getting started on this now..

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Forgot we have a qaqc repo. I'm going to close this issue here and put it there, seems more of an appropriate location
