### ISSUE TITLE
Ad Hoc- UChicago Orland Park Visit Count Per Week

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#136]
@KELSEYDOWLING7 Can you please create a table with the week in one column and the number of completed visits in the second column? Please run when you are able and run again to reflect the next 3 weeks of collections, through 4/26/2024.

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/7c820a3c-7588-488e-857b-aab9c44e50e0)


Compare to Figure 1.2 in the new structure
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9b3cbe04-69a3-4f68-bdd8-4dc56fc232a7)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Thank you Kelsey, this looks great. I will share with Bio team on Friday and look forward to seeing the numbers in the Ad Hoc table the next few weeks.

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Adding one additional week to this request; we would also like to see collection count the week of 4/29

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Ok, in 3 weeks I'll rerun this

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7, please run this report each week, last run on 5/6. I will be sharing the numbers weekly with Mia.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz Shown below is the final count for the week of 4/1-4/7 and the beginning of the count for the week of 4/8-4/14
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/32c16e87-235e-40af-a1b3-9015f1c76974)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f574c550-d77f-4009-9f6a-ec0dc56c32be)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/fc4d1b9f-a422-4f56-bcc4-fb45b868017f)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e9c96c10-0a6b-4e28-9ccd-70969a846893)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0e4133f7-ae3e-4c58-b273-467421fd7e0b)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 We would like to continue monitoring Orland Park. Please continue to run this ad hoc report weekly until further notice. After May Prod release, UChicago will be adding Clincial Collection at Orland Park (in addition to Research). Beginning week of 5/27, please rename Collection Count to "Research Collection Count" and add column for "Clincial Collection Count." Please add Note: Clinical collections launched 5/23/2024.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/56d102c5-f724-4ac5-8a1c-69994601583d)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/10bcc3a6-be83-4bfa-92a5-e29db6a1d28f)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/31c9f48d-737d-4ebd-8069-580043b5d147)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![Uploading image.png…]()

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/52edb9e7-693e-48c3-b26f-22b158cbf305)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5511640c-312f-4d54-a83a-13a4877edce0)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1bfc3e39-b0c8-49c5-bafa-e5470c218966)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/087027dc-3e18-4e8f-9299-a0d9abb85dc4)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1c230b4c-8fd8-45d0-a905-8abb89cbf1f0)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/dd58aaef-2e0d-4930-b91f-244e4dd5c7a0)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d2acc8f6-7a35-4ccc-a31f-9ac6fa4a99cd)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/ae646b0a-3a26-44a8-b2b2-e8fe1d3a9e74)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/f9e0a8e9-e3d8-44a3-b269-6090589cedaf)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/fdfd962e-b5ae-4acc-964d-66456c53cdb4)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/941b1dd5-5999-4b91-b030-2d5799db1664)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/e5896253-c289-4720-9134-ae9966688703)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/67620be4-179f-4453-8784-245304577349)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/00e2f0c1-1946-4713-89f2-c8d0254f8ce5)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  does this need to be run again today or is this good to close?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Please continue to run this ad hoc report. UChicago has participants on the schedule until the beginning of October, they are attempting to convert those research visits to clinical collections but will accommodate participant wishes if they prefer the research visit. We would like to know how many research visits are occurring weekly in as they wind down. I will let you know when we can stop running this report and close this issue.

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/f96c538e-e6e6-4b48-a06b-e3d59833c744)

**Comment by KELSEYDOWLING7** [comment]
Just adding the next line due to the size of the table

![image](https://github.com/user-attachments/assets/4a93f80e-a99e-4cb4-9239-669de3e5ac20)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/bf5a3b1d-89d4-4d6a-b6b8-326058718d5b)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/8c177b0a-7aca-4545-8fe1-d5bf6a7a44f9)

**Comment by KELSEYDOWLING7** [comment]
No new collections this past week!

**Comment by KELSEYDOWLING7** [comment]
No new collections

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7  Research collections at Orland Park are now finished. No need to run this ad hoc report anymore. This issue can be closed.
