### ISSUE TITLE
Bio Weekly- SFH Clinical Collection Metrics

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#138]
**Metrics that we expect to SFH added to:** 
•	TBD, Table 1.3: Baseline Clinical Biospecimen Collections by Clinic Location (only added if SFH clinical broken down by site/region, will circle back on 4/16)
•	Table 2.2: Baseline Clinical Biospecimen Collection Completeness by Specimen Type
•	Table 2.9: Baseline- Total Blood Tubes Collected Among Clinical Biospecimen Collections
•	SFH added to Table 2.10: Baseline Blood Tubes Collected Among Clinical Biospecimen Collections by Tube Type 
o	Add to footer for SFH: (9) SFH: 4 SST, 2 Heparin, 3 EDTA
•	Table 3.2: Baseline Biospecimen Survey Status Among Clinical Collections
•	Table 3.5: Baseline Biospecimen Survey Completion Time from Clinical Collection Dashboard Entry
•	Table 3.9: Baseline Biospecimen Survey Completion Length (in Minutes) Among Submitted Clinical Surveys (Post-COVID-19 Questions Removal)
•	Table 4.6: Baseline- Time (in Days) from Verification to Clinical Collection Among Participants Verified on or After 2/01/2023
•	Table 5.3: Baseline Collection-To-Receipt Time (in Days) Among Clinical Collections
•	Table 5.4: Baseline Collection-To-Receipt Time (in Days) Among Clinical Collections by Clinic Location
•	Table 5.6: Baseline- Time (in Hours) from Clinical Collection to Receipt by Clinic Location
**New Tables/Figures needed:**
•	New table needed, will be Table 1.8: Baseline Collection Setting Among Biospecimen Collections by Specimen Type, Sanford Health 
•	Update needed to: Figure 5.2: Baseline Collection-To-Receipt Time (in Hours), Sanford Health--make this: Figure 5.2: Baseline Collection-To-Receipt Time (in Hours), Sanford Health **Research Setting**
•	New Figure needed, will be 5.3: Baseline Collection-To-Receipt Time (in Hours), Sanford Health Clinical Setting
•	New Figure needed, will be Figure 6.10: Baseline− Weekly Biospecimen Collections by Collection Setting,
Sanford Health (update numbering of current Figure 6.10 to 6.11)
•	TBD, New Figure needed, will be Figure 6.12: Baseline- Weekly Clinical Biospecimen Collections by Clinic Location, Sanford Health (depends if we are going to separate SFH clinical collections by location, will circle back 4/16)

Responses to your email on 4/11:
1.	For QC:
a.	Custom QC Report (pdf report)
•	Rule #18 and #19: IF BioClin_BldOrderPlaced_v1r0/BioClin_UrnOrdPlaced = 1, THEN BioClin_BldOrderPlacdDt_v1r0/BioClin_BldOrderPlacdDt_v1r0 must be populated. HP Excluded. 
1.	Should HF and SF also be excluded? **SF should be excluded, they are not sending information on Order Placed to NCI** 

2.	For the report:
•	Table 4.8 and 4.9- we have HP excluded. Will we need SF excluded? **Yes, SF excluded**
•	Table 4.10- we have HP and HF excluded. Will we need SF excluded? **Yes, SF excluded**
•	Table 4.11- Right now we have that manually set to KP only. Should hybrid sites (HP, HF, SF) also be included? **Yes, hybrid sites are excluded (UCM will also be excluded when they launch clinical). We already updated the note for this table with the last edits to indicate this is just for KPs**
•	Table 5.3 **(this table is overall clinical data from each site, so include Sanford clinical overall)** , 5.4, and 5.6 - will there be Site locations or only the overall Sanford site? **TBD, I will circle back on Tuesday, 4/16**

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz - If you could follow up with me today I can get some of these updates in for Monday's report if preferred.


Will automatically update once we have clinical data in PROD:
• Table 2.2
• Table 2.9
• Table 2.10--- Do you want the footnote added now even before we start getting clinical collections?
• Table 3.2
• Table 3.5
• Table 3.9
• Table 4.6
• Table 4.11


Manual updates:
• Table 1.3- need to wait on location IDs to be given
• Table 5.3, 5.4, 5.6- need to wait on location IDs to be given
• Table 4.8- will see if Jake can put update into automation for Monday
• Table 4.9- will see if Jake can put update into automation for Monday
• Table 4.10- will see if Jake can put update into automation for Monday


New tables/figures/titles:
• Table 1.8- code done, will be implemented once there's clinical data
• Figure 5.2- Do you want the title update to go into automation now?
• Figure 5.3- code about done, will be implemented once there's clinical data
• Figure 6.10- code about done, will be implemented once there's clinical data
• Figure 6.12- need to wait on location IDs to be given

**Comment by erincschwartz** [comment]
Add new table: 

Table 1.4: Baseline Clinical Biospecimen Collections at Sanford Health by Clinic Location (other tables in section 1 will need new numbering) 

Please include the following columns: 
Collection Location    Total Clinical Collections     Clinical Collections in Past 7 days      Clincal Collections in past 30 Days

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Table 4.8-4.10 are updated. Table 1.8 is the only new table/figure I can properly implement without the location IDs. Do you want me to add that or wait until all SF tables/figures can be added?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Please add Table 1.8 now. 

I do not believe any of the following need location identifiers but do not see them updated in the Metrics Report, can they be added now?
- Adding SFH to existing Table 5.3: Baseline Collection-To-Receipt Time (in Days) Among Clinical Collections 
- New Figure 5.3: Baseline Collection-To-Receipt Time (in Hours), Sanford Health Clinical Setting 
- New Figure 6.10: Baseline− Weekly Biospecimen Collections by Collection Setting, Sanford Health 

Also, please update footnote on Table 2.9: Baseline- Total Blood Tubes Collected Among Clinical Biospecimen Collections to include **SFH-9**

**Comment by KELSEYDOWLING7** [comment]
Ok I'll add 1.8 then as well as that footnote. The way the code is written now multiple tables have linked dependencies so I would need the locations to get the proper counts. Sorry for the confusion, I just checked on those this morning and noticed that' why the counts weren't coming in

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Unless you were ok with this line being added to Table 5.4 for now:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c3bc3a50-143c-4d20-a8ec-864a5052c029)

Because that's linked to Table 5.3
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4fe385c1-173d-46ee-aff9-d15d8f28d0f1)


And also linked to Figure 5.3 and Figure 6.10
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/87e0777d-5227-4870-b20f-ce9e5f05d695)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/803b46cb-177a-4aa7-8120-14bcea1daef8)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  I was able to use the csv Sanford sent us to make Tables 1.4 and Figure 6.12. Table 1.4 will only use the sites that had collections in the last 7 or last 30 days, Figure 6.12 will count all collections.

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/64464b39-de4b-4f81-9d77-73a39ee54cf3)


This may get messy with 35 colors only (and the lightest 7 were asked not to be used would likely need to be used)  when we have many site locations but for now it works. 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/7f97862c-640d-4cf9-bb8e-ccc8b695c823)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 For table 1.4, Sanford wants all locations listed there, so there should be a column after location for Total Clinical Collections, then the columns for past 7 days + past 30 days. This table will not be limited to just the visits in the past 7 days. Will that work?

For 6.12, is it possible to limit this figure to only sites that had collections in the past 7 days? Each week it would be different but that might be alright.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Oh sure, my mistake. Please note that collections in the last 7 days will appear in both of the last two columns. How would you like the percentages, by row or by column? They're currently by column.
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1c690a9a-f4ad-4d17-81ab-ab5040fd93c9)


If we're only going to show the collections in the last week, we should probably only have the x axis be about a two to four week time span so it doesn't have continually growing blank space. I would also recommend we add a footnote to explain why this Figure is so short, continually changing, and includes the current week. Please let me know your thoughts
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d15dbf01-4ec9-4975-b76b-33f79ea7b236)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 I am meeting with Maddi at noon today to discuss what she would like to see for Table 1.4 and to discuss Figure 6.12. Can you quickly run these again, now that they have 4+ collections done....might help to see the updated figure

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Sure! (I'll update the column names so they fit on the pdf)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/cc3c21ac-be46-497b-b945-0518fb7ad43e)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f9db54fc-7788-4fcb-b342-b506e5533408)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7  Figure 6.12 is only showing the first collection, not all 4. Can this be updated?

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Originally you asked only to see the collections in the last seven days for Figure 6.12. Do we need that reversed?

**Comment by KELSEYDOWLING7** [comment]
It's hard to tell because of the colors but both locations had one collection on 5/20 so they're overlapping one another

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Sanford was hoping to see only the sites represented that had collections in the last 7 days so that the graph was not too hectic, given the number of potential clincial collection locations. The intention was not to only show the past 7 days on the X axis. Sorry this was not more clear! 

X axis will be time since clincal colleciton launch 5/13 but then each week, the Figure will only include the sites that had collections within the previous 7 days.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz Ok, so currently the graph does only show collections in the last 7 days as needed. I can change the x axis to be 5/13 onwards, but because we will only ever show collections in the last 7 days, the left portion of the graph (before 7 days ago) will be blank and as the weeks go on the blank portion will take up more and more of the graph... Does that make sense?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Did thorough review of Sanford metrics with Maddi. She does not see the need for Figure 6.12. Eventually, when they understand the top 10 most used clincal colleciton locations, they may want this figure. For now, we can leave it out. 

Table 1.4 is perfect as-is. 

For **Table 5.4**: Baseline Collection-To-Receipt Time (in Days) Among Clinical Collections by Clinic Location and **Table 5.6**: Baseline- Time (in Hours) from Clinical Collection to Receipt by Clinic Location, Maddi feels it will be of high interest to their site to have this data broken down by clincal collection location (like it is for HFH). Can we add by location into the current tables for now and move to a stand-alone table if needed down the road if the lists get too long?

**Comment by erincschwartz** [comment]
Please remove Sanford from Table 1.3 since data will appear in new Table 1.4

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  As discussed, to avoid code complications and in anticipation of eventual split tables, we'll just give SF their own tables now. Please let me know if you need the title or anything adjusted
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/68e8c973-002d-43ca-a6bb-2bca31f7983c)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/897c763a-c640-482c-a92c-40c9dcb3a400)

**Comment by erincschwartz** [comment]
This looks good, ready for automation. Thanks Kelsey!

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Ok great, all set for Monday! For tracking purposes can we reset the status to "Ready for Automation" or "Done" and close the issue once it's in the report next week?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Yes, let's update to 'Done' and close the issue once the report is updated on Monday.
