### ISSUE TITLE
Adding fitted average to  Figure 6.4: Baseline- Weekly Clinical Biospecimen Collections by Clinic Location, Henry Ford Health

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#139]
@KELSEYDOWLING7 As we just discussed, can you please add a fitted average to 
Figure 6.4: Baseline- Weekly Clinical Biospecimen Collections by Clinic Location, Henry Ford Health?

![Image](https://github.com/Analyticsphere/metricsReportsRequests/assets/157617486/82e8fbe5-1321-40e7-82e9-c7730622589a)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ff05ac4d-64dd-4ea5-9f2c-2d7f3ea19171)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  In case it's needed, here is the corrected plot with the black dotted line as the weekly average of all site locations


![Image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/65d323e7-6aad-40ec-b5e2-9b6e16974ae1)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Thank you for working to add the fitted average line above. Bio team has reviewed and we do not need to incorporate the fitted avg into the metrics report. Closing this issue.
