### ISSUE TITLE
HFH Collection Counts at Livonia- Clinical vs, Research

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#140]
@KELSEYDOWLING7 When you have a chance, can you run a table, similar to the table you have been running for Orland Park, to show weekly number of Clinical vs Research collections at Henry Ford's Livonia site, going back to the first week of February 2024 through now?

**Columns would be**:  Week   >     Research Collection Count    >  Clinical Collection Count

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  I'm seeing the HF has only ever had 1 collection (which matches our current report tables) and that was on 2023-09-04. As for research:

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/23925e26-3c36-4203-9bbf-367959d61440)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ac91a4e9-417b-4dd1-8ff0-20f34dd537d7)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4f6fd67b-788c-41c7-8d3e-eda432a1889e)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c01e0975-01d1-43a3-b4b8-59633208fd75)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/08a44ff5-4e2f-4791-bcec-f07e84b202df)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4872bcb3-b0b4-493b-b56a-1db975c926a2)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/359665dd-a5e2-4970-8a48-e89f0afa39a9)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d14e8eb5-32f1-47ce-acec-c840430bc509)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 You can discontinue running this ad hoc report.
