### ISSUE TITLE
Biospec Weekly Report- error in table 5.1?

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#142]
From HFH: I am looking through the most recent Connect weekly reports and I would like to ask that your team double check the Biospecimen report; particularly table 5.1 Baseline Collection to Receipt time. This table appears to drastically different from the 4/29 report to the 5/6 report; I am thinking that numbers got mixed up for example HFH has >4 days as 1.2% on 4/26 and then its 49.6% on 5/06.

**Comment by KELSEYDOWLING7** [comment]
HI @brotzmanmj  While I'm not sure how this would have fixed this particular problem, I noticed that there were now collections at the new site location "HFH Pop-Up" . Updated that table and all HFH tables that would reference research site locations for HF. When I ran the report today HFH has only 1.2% >4 days again.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj Here's the table as of yesterday:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/bf761e2e-bff0-433d-b5f9-a3bf68609de4)

Do you think the issue is ok to close?

**Comment by brotzmanmj** [comment]
Yes, good to close. Have you also added the HFH pop-up in Tables 5.2 and Table 5.5 and anywhere else that research collection locations are listed?

**Comment by KELSEYDOWLING7** [comment]
Yes they are updated in tables 5.2, 5.5, 1.2, and 2.5
