### ISSUE TITLE
Updates to home mouthwash metrics

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#143]
@KELSEYDOWLING7 Please make the following updates Baseline Home Mouthwash Collections section of the Weekly Biospecimen Metrics Report:

1. Rearrange the figures as such: 
Figure 7.3 change title to Figure 7.1 (insert immediately below Table 7.2) 
Figure 7.1 change title to Figure 7.2
Figure 7.2 change title to Figure 7.3

2. Change the orientation of Table 7.9 to landscape 

3. Split Table 7.9 into two versions: one to reflect data before update to PWA language and one for after, tables should will appear like this, with footnotes: 

Table 7.9: Baseline- Mouthwash Biospecimen Survey Completion Time Relative to Collection Time Reported on Collection Card (Pre-update to survey description on PWA) 
Note: The description of the home mouthwash survey was updated in the PWA on 5/22/2024

Table 7.10 Baseline- Mouthwash Biospecimen Survey Completion Time Relative to Collection Time Reported
on Collection Card (Post-update to survey description on PWA) 
Note: The description of the home mouthwash survey was updated in the PWA on 5/22/2024

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Do you want Figure 7.3 to remain after Table 7.3 or move to before?

**Comment by erincschwartz** [comment]
The new Figure 7.3, shown below, should remain where it is, before Table 7.3. Thanks!
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/157617486/4c9b180e-f096-4633-8c13-cfffd6dd8263)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Updated! Please see the new order and note the updates to the counts in what was previously Figures 7.1 and 7.2. I have quadruple checked the counts and this is correct. I apologize for the misinformation displayed in the previous graphs 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/8d5840eb-197b-4f3c-8def-6da1b533987b)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/079afd29-7ff0-4e66-abc9-52f542dfcf5c)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/b19e97ed-bae5-4d07-b2b4-c8d25a8fdf87)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/28fea2d3-4f5f-4419-b388-28269018f48a)

**Comment by KELSEYDOWLING7** [comment]
[Weekly_Biospecimen_Metrics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/15327040/Weekly_Biospecimen_Metrics.pdf)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Here are the notes from our discussion:

- Please update the date of eligibility to 3/29/2024 in the footnotes (you already added this back into the programming)
- Add a column in Table 7.2 between Total Shipped and Received called "Total Shipped up to 1 week ago" and update title to: Table 7.2 Baseline- Home Mouthwash Kit Return Rate for Packages Shipped up to 1 Week Ago (% will be Received/ Total Shipped up to 1 week ago)
- Figure 7.1- update title to:  Baseline- Total Kits Received of Total Kits Shipped Up To 1 Week Ago, by Site
- Figure 7.2- Remove footnote
- Figure 7.3- Update title to: Baseline− Home Mouthwash Kit Return Rate for Kits Shipped Up To 1 Week Ago; make % match that in table 7.2; Add to footnote: Received data are current through [report cutoff]

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/978197a5-5d8e-41cd-b97b-931b4d4371ac)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/dbea7a5a-baa9-4615-b086-ded947ffac0d)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f644c3a5-6a44-4456-bf33-dc4dff9d2e5b)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 These look good! Not much to see in Table 7.2 since no kits were shipped in the past week, new column is same total shipped. 

Would it make sense to put the original footnote back in Figure 7.3, so it would read "Shipped data are current through [1 week prior]. Received data are current through [date of data pull]?

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  My thoughts exactly on Table 7.2. As for the footnote on Figure 7.3 I think its important to note what the graph is showing vs what the percent is showing. As we discussed, we can't cut off the shipping line early but not the received. What that graph is showing is all shipped counts through 5/12 (week of 5/6), all received counts through 5/12 (week of 5/6), and a percent of  all received counts through 5/12 (week of 5/6)/ shipped counts through 5/5 (week of 4/29)

**Comment by KELSEYDOWLING7** [comment]
If it's too confusing to follow, we could in theory leave the percent out of that Figure all together. The percent you want is already labeled in Table 7.2

**Comment by erincschwartz** [comment]
It works how you have it. No need to change the footnote then.

**Comment by KELSEYDOWLING7** [comment]
Ok. I realized I put Received data through (one week prior) when it should be shipped data (through one week prior) I can change just that

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Are we good to close this issue? The code to Figure 7.10 is done, but because of the pause in shipments I can't run it. We agreed that Table 7.9 would be kits shipped before 5/22/24 and Table 7.10 to be kits shipped on or after 5/22/24. Other than that the code is identical

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/40d4c52e-bff4-475f-aa8f-bbf61f46d81d)

**Comment by erincschwartz** [comment]
Ok to close, thanks Kelsey!
