### ISSUE TITLE
Bio Weekly- Fix table 4.7

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#144]
@KELSEYDOWLING7 Please remove "Clincial" and "Research" throughout Table 4.7

![Image](https://github.com/Analyticsphere/metricsReportsRequests/assets/157617486/25331dd7-f2c2-4b6d-90a5-042335e09768)

Mouthwash metrics remain top priority right now, this can wait until you have the bandwidth

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1319582b-7639-4087-a389-7c116615a6ef)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 That was fast, thank you! Looks great.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Np! That one was very straightforward

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  This was applied to yesterdays report. Is this good to close?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Looks good, thank you! I updated status to 'Done'
