### ISSUE TITLE
Add BSWH to QC

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#146]
In preparation for BSWH launch in June, we will need to add BSWH to the QC mimicking what has been done for the other sites + making sure the BSWH data shows up in the QC in general.

Planned timeline for June release to plan for when these should all be added by and to test QC using stage data below.
Stage Testing: 6/17 - 6/21
Prod Release: 6/24 (10am ET)

Please let me know if you have any questions!

**Comment by KELSEYDOWLING7** [comment]
Thanks for giving me the testing dates! The code should be about done for all QC outside of the Recruitment QC, I'll test it once we have stage data.

**Comment by KELSEYDOWLING7** [comment]
@mnataraj92  @jacobmpeters  Can you add BSW to the Recruitment QC?

**Comment by jacobmpeters** [comment]
Hey @KELSEYDOWLING7. 

@mnataraj92 and I added BSWH to the appropriate existing rules. Madhuri also added 3 new rules for race/ethnicity that are specific to BSWH. We'll test them on Monday.

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  @mnataraj92  Are we good to close this?

**Comment by jacobmpeters** [comment]
Yep!
