### ISSUE TITLE
QC - add additional QC for Spanish implementation

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#148]
_Placeholder. Specific requests will be added once defined._ _Amelia to schedule a meeting to discuss._

In preparation for the Spanish implementation release in June, we will need to add some additional QC.

**Comment by robertsamm** [comment]
@jacobmpeters @KELSEYDOWLING7 2 QC checks for Spanish below

1.	Preferred language is required and set at time of consent. Check that there are responses for all participants that have submitted consent and no missings for this group of people.
2.	Preferred language responses are only English and Spanish (after consent), null (pre-consent). No other responses.

**Comment by KELSEYDOWLING7** [comment]
Rule 1:
@jacobmpeters  @mnataraj92  I added this to the "Rules to Add" tab. 

Rule 2:
@jacobmpeters  Is that something that can be added to the automated rules or would we need that to be a custom rule? I'm thinking "Preferred language responses are only English and Spanish (after consent)" is already covered through rule 1 but I'm not sure if: "if d_919254129==104430631 then the valid value of d_255077064=NA" would work.

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 I'll try to implement Rule 2 today and update the issue if anything else is needed.

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 

I added a rule for rule 2. I think these are sufficient to cover all of Amelia's specifications. Do you agree?

| rule_id | Label | ConceptID | Qctype | ValidValues | CrossVariableConceptID1 | CrossVariableConceptID1Value |
|---|---|---|---|---|---|---|
| 279 | If consented, then preferred language is required (Spanish or English) | d_255077064 | CrossValid1  | 163149180, 773342525 | d_919254129 | 353358909 |
| 280 | If not consented, preferred language responses are null | d_255077064 | crossValid1 is not populated |  | d_919254129 | 104430631 |

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Yes! That would be perfect, thank you. Do you need me to add that to the Recruitment QC "Rules to Add" tab or is that already in there?

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 Great! Nope, nothing more for you to do on this. Madhuri and I will test out these rules when data are available and then close this.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm for the first rule, there are many consented participants in DEV will a null preferred language. Does the backfilling of all previously consented participants still need to take place? 

> @jacobmpeters @KELSEYDOWLING7 2 QC checks for Spanish below
> 
> 1. Preferred language is required and set at time of consent. Check that there are responses for all participants that have submitted consent and no missings for this group of people.
> 2. Preferred language responses are only English and Spanish (after consent), null (pre-consent). No other responses.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Following up on the question above

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 sorry I missed your question! I think the backfilling of the preferred language response will only occur in prod.

**Comment by KELSEYDOWLING7** [comment]
That's ok! In that case we can't really test that rule. But the second rule works

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 That makes sense! I think that's fine. Once the prod participants are backfilled when we go live at the end of the month we can check to see if the QC works for that then.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm with Preferred Language not backfilled, rule number 2 might be trickier to interpret. I can confirm anyone not consented has a null preferred language value, but a null preferred language flag now technically means English. Please let me know if that is alright and I can add that two part rule to the custom Recruit QC rules report

**Comment by KELSEYDOWLING7** [comment]
Apologizes, rule 1 has the same difficulty of interpretation, as we will have many null values for those not backfilled. Please let me and Jake know how to proceed. Likely the best way to update this would be to also filter for the consent date after the prod launch

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 good question! Now that we aren't backfilling preferred language for anyone who consented prior to the release (on or after 8/1), I think we are going to need to split up the QC for retrospective vs. prospective groups.

Anyone who consented prospectively on or after 8/1 should have:
1. Preferred language is required and set at time of consent. Check that there are responses for all participants that have submitted consent on or after 8/1 and that there are no null values for this group of people.

All participants, regardless of consent date/status:
2. Preferred language responses are only English, Spanish, or null. No other responses.

**Comment by KELSEYDOWLING7** [comment]
Thanks Amelia!

@jacobmpeters @mnataraj92  I've removed rule_id 279 and 280 from the automated Recruitment report. Since this is a date specified rule, I'll add this new rule number 1 to the Custom recruitment QC report. The new rule number 2 I've added to the 'Rules to Add' tab ad just an 'NA or valid' rule. If it looks good to you can it be added to the live rules for the next automation?

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 Thanks for handling 279 and 280.

I have added the "new rule number 2" to the main rules tab. It will be included in our next run, which will be Tuesday this week.

**Comment by KELSEYDOWLING7** [comment]
Thanks! I'll add the Custom Recruitment Qc rule to our automation update list for Thursday

**Comment by KELSEYDOWLING7** [comment]
@mnataraj92  There are about 15 errors popping up for rule number 1. I'll add the output of this refreshed report to the usual folder

**Comment by KELSEYDOWLING7** [comment]
> Hi @KELSEYDOWLING7 good question! Now that we aren't backfilling preferred language for anyone who consented prior to the release (on or after 8/1), I think we are going to need to split up the QC for retrospective vs. prospective groups.
> 
> Anyone who consented prospectively on or after 8/1 should have:
> 
> 1. Preferred language is required and set at time of consent. Check that there are responses for all participants that have submitted consent on or after 8/1 and that there are no null values for this group of people.
> 
> All participants, regardless of consent date/status: 
> 2. Preferred language responses are only English, Spanish, or null. No other responses.



@robertsamm  This is done. Rule number 2 here is in the automated rule file with no error. Rule number 1 is in the custom QC rules ('Recruitment_Derived_Variable_QC.pdf')  and does have some errors. They are both posted in this box folder each week as of today: https://nih.app.box.com/folder/194196493018

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Are we good to close this issue?

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 Yes! Thanks for checking.
