### ISSUE TITLE
Bio Weekly- UChicago Clincal Collection Metrics

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#149]
**Metrics that we expect to UChicago added to:**
Table 1.3: Baseline Clinical Biospecimen Collections by Clinic Location (list out each location) 
•	Table 2.2: Baseline Clinical Biospecimen Collection Completeness by Specimen Type
•	Table 2.9: Baseline- Total Blood Tubes Collected Among Clinical Biospecimen Collections
•	Table 2.10: Baseline Blood Tubes Collected Among Clinical Biospecimen Collections by Tube Type
            o	Add to footer for UCM: (4) SFH: 2 SST, 1 Heparin, 1 EDTA
•	Table 3.2: Baseline Biospecimen Survey Status Among Clinical Collections
•	Table 3.5: Baseline Biospecimen Survey Completion Time from Clinical Collection Dashboard Entry
•	Table 3.9: Baseline Biospecimen Survey Completion Length (in Minutes) Among Submitted Clinical Surveys (Post-COVID-19 Questions Removal)
•	Table 4.5: Baseline- Time (in Days) from Verification to Clinical Collection Among Participants Verified Before 2/01/2023 (please also add HP and Sanford to this table----thinking this through again, they may have had particiapnts verified before 2/1/2023 that opt for Clincial Collection once they know it is an option)
•	Table 4.6: Baseline- Time (in Days) from Verification to Clinical Collection Among Participants Verified on or After 2/01/2023
•	Table 5.3: Baseline Collection-To-Receipt Time (in Days) Among Clinical Collections
•	 Table 5.4: Baseline Collection-To-Receipt Time (in Days) Among Clinical Collections by Clinic Location (list out each location)
•	Table 5.6: Baseline- Time (in Hours) from Clinical Collection to Receipt by Clinic Location (list out each location)

**New Tables/Figures needed:**
•New table needed, will be Table 1.9: Baseline Collection Setting Among Biospecimen Collections by Specimen Type, University of Chicago Medicine
• Update needed to: Figure 5.4: Baseline Collection-To-Receipt Time (in Hours), University of Chicago Medicine--make this: Figure 5.4: Baseline Collection-To-Receipt Time (in Hours),  University of Chicago Medicine Research Setting
• New Figure needed, will be 5.5: Baseline Collection-To-Receipt Time (in Hours), University of Chicago Medicine, Clinical Setting
• New Figure needed, will be Figure 6.6: Baseline− Weekly Biospecimen Collections by Collection Setting, University of Chicago Medicine 
• New Figure needed, will be Figure 6.8: Baseline- Weekly Clinical Biospecimen Collections by Clinic Location, University of Chicago Medicine 

**Footnote Updates:** 
Tables 4.8 and 4.9 add UChicago (and Sanford) to exclusion list with HP

**NOTE: UChicago should also be excluded in the QC rule:** 
a. Custom QC Report (pdf report)
• Rule Bio Metric - Distribution Curves for Research Collection Visit Length #18 and Bio Metric - Weekly Biospecimen Data Tables  #19: IF BioClin_BldOrderPlaced_v1r0/BioClin_UrnOrdPlaced = 1, THEN BioClin_BldOrderPlacdDt_v1r0/BioClin_BldOrderPlacdDt_v1r0 must be populated. HP Excluded.

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Crosswalk for UChicago clinical collection locations is below:
 
South Loop (location id = 1)
Orland Park (location id = 2)
Kenwood (location id = 3)
River East (location id = 4)
Dearborn Station (location id = 5)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  I don't think that's right...We already have Blood Location ID (d_173836415_d_266600170_d_185243482) ==1,2,3 and Urine Location ID (d_173836415_d_266600170_d_452847912) ==1,2,3 for HP locations

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 The crosswalk info above is what Nina sent to Madhuri and looking at their first clinical collection, they sent BioClin_SiteBldLocBL_v1r0 = 1 (that collection was at South Loop). **Do we need to tell Chicago that they need new designations for their clincal collection locations since HP already took 1,2,3?**

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  That's correct, those values are already taken. It looks like the DD was incorrectly updated so I just emailed Rebecca to change that as well

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/2f627d54-f846-470f-aad8-b3d024e7033b)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d240ac27-cab4-42fc-86e1-cc4091e3fb38)

Should 2.9 have an updated footnote matching 2.10?
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/7fe9d781-e386-4353-8499-bbddcd4f22e3)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/86161cc1-9cc5-416f-bd54-13c0ac35f516)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9dfcf7dd-921d-475b-9175-f308640852b8)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/30a07caf-6f80-4cf3-80c0-663b852739ba)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1752c9cc-982c-4c94-b97e-dacf2baad279)

Table 4.5 includes all clinical sites, but there are no matching collections for HP, SF, or UC

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0782265e-5eb0-4cd6-9bcf-c4a5ce142c77)

(Table 5.3)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0030fde0-a020-468f-b1dc-c383fda4c8e3)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5098d8dd-a939-49b0-910d-6944084ddb61)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/50d4f033-d209-4e10-8ef2-678f5781261c)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/986eadca-e241-45d1-8e5b-46a70d7a4581)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/b885f2ea-8e91-4c98-b667-6b208ac92c90)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/b4ddb4f5-317f-4fa1-b7f5-5c48824982b8)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1c9ddd46-45c0-4541-bd56-e9b49d97f4d6)



Excluded from the QC rules:  
"IF BioClin_BldOrderPlaced_v1r0/BioClin_UrnOrdPlaced = 1, THEN BioClin_BldOrderPlacdDt_v1r0/BioClin_BldOrderPlacdDt_v1r0 must be populated. HP Exclude.". Reflected in today's Biospecimen QC

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7; just reviewed and have a few notes: 

- Table 2.9 should have updated footnote, please add "UChicago- 4"
- Table 2.10 should have updated footnote, please add "(4)UChicago- 2 SST, 1 Heparin, 1 EDTA"

- UChicago should not be included in Tables 4.8 or 4.9, can you remove?
-
- The data in 6.6 shown above does not seem right, compared to Figure 6.5 in the prod report (I looked at last week's report). Can you double check this?

- Can figure 6.8 be edited to remove all the blank space before 5/20?

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Thanks for reviewing so quickly
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/40d2e084-1942-4c6b-a818-7083eb6da227)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/bfa093fb-b58d-4a1f-8036-304fd4471109)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/7fd8ae97-eb3a-4102-9afa-50a625ae064f)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/244a9804-4e5c-4fa2-96cd-4fcbd76e7716)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/71a17240-e874-4a2e-90d4-62e585471da8)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Everything looks good. 

Just checking, in Figure 6.8, I assume Dearborn Stations collection is overed up by the South Loop dot, correct?

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Great! Yes, Dearborn had 1 on 6/3 but not on 6/10. I can also update the graph to include 0 on the y axis if you want to see that line always continue

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 add as-is for now and please work to add the 0 for next automation

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Right now the only way to set Figure 6.8 to 0 is including all Site locations and having all of them set to 0 until the first collection. Do we want that, or is it ok as is? Once the collections are consistent the lines will be as well (see current Figure 6.13 for example)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Please advise on the comment above or if this is good to close as is

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 I think we do want the lines to dip down to 0 when there are no collections. We have more data now that weeks have passed and I think that the figure will be more descriptive if we can see the weeks when there weren't any clincal collections at a given location

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz Ok that would look like this 
![image](https://github.com/user-attachments/assets/8c589079-faf0-4878-90b2-6990007e1ed7)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7, let's go with this so we can see when clincial locations dip down to 0 collections. I imagine as clinical collections ramp up, the figure will look different/better

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Please let me know if this looked good on Monday's report and this issue is good to close

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 UChicago clincal collection metrics look good. Issue is ready to close.
