### ISSUE TITLE
Weekly Survey Metrics - add metrics for Spanish

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#150]
@KELSEYDOWLING7 metrics to be added to the survey report for Spanish. Please work with Madhuri to get the correct survey Spanish variables and with Marie-Josephe on the Spanish survey metrics.

1.	Survey completion metrics by preferred language for each module
2.	Time to completion by preferred language
3.	Compare preferred language to survey language for each module (are they completing surveys in languages other than preferred language)
4.	Consistency of language choice in survey completion (Counts of people completing all surveys in one language vs. flip flopping between languages among surveys)

Tagging @m-j-horner here as I was unable to assign

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  @m-j-horner This is based on current DEV data but please let me know your thoughts

1.Survey completion metrics by preferred language for each module
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/247a1eae-99f1-4c18-ad26-c00ba5c21905)

2. Time to completion by preferred language
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/88c02788-a19e-4bd4-8fa3-7f08e4b9d387)
3. Compare preferred language to survey language for each module (are they completing surveys in languages other than preferred language)
- Language flags haven't been tested yet. But thinking the language of survey as rows, and preferred language as columns. Something like this below
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/272d5e6a-91c1-4f28-9f01-5583b1e2032f)


4. Consistency of language choice in survey completion (Counts of people completing all surveys in one language vs. flip flopping between languages among surveys)
- Do we just want three rows, one with "All Survey Languages Match Preferred Language" and one "Some Survey Languages Match Preferred Language" and "No Survey Languages Match Preferred Language" with the counts for each? Something like this below
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5d5f2099-badb-45b2-873b-67e2092015ea)

**Comment by m-j-horner** [comment]
@KELSEYDOWLING7  
thank you, great start! Please see my proposed analysis for Language metrics. 
[spanish language metrics -07242024.docx](https://github.com/user-attachments/files/16367832/spanish.language.metrics.-07242024.docx)

**Comment by KELSEYDOWLING7** [comment]
@m-j-horner Following up on our Teams chat. I believe we may need to adjust the request of number 4 (Table 13), as there are repeat rows. Please let me know how you'd like that table, or any other table, adjusted

![image](https://github.com/user-attachments/assets/9e004df1-53e0-4d1c-ad2c-b19185f1fbe0)
![image](https://github.com/user-attachments/assets/1b814fe5-23c5-4a62-b0fc-3998d3e4c42d)
![image](https://github.com/user-attachments/assets/d26367b7-db5b-49d9-900c-089cf77a25f4)

**Comment by m-j-horner** [comment]
tables and analysis plan resolved on call with Kelsey 8/19/24

**Comment by KELSEYDOWLING7** [comment]
Going to change table 13 to 2 rows:
1. All survey flags (regardless of how many surveys are done) are consistent with the Preferred Language Flag
2. Any survey flags inconsistent with the Preferred Language

This will be on a Connect ID level count, and this will be moved above the table 12 set shown above
