### ISSUE TITLE
Ad hoc- KPGA weekly collection count table

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#151]
@KELSEYDOWLING7 The PI at KPGA is requesting tabular format for number of collections per week reflected in Figure 6.15.

**Comment by KELSEYDOWLING7** [comment]
[KPGA_Collection_Counts.csv](https://github.com/user-attachments/files/15685991/KPGA_Collection_Counts.csv)
@erincschwartz

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Did this need to be run weekly like Orland Park counts, or just the one time?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 We do not need to run this weekly. Closing this issue now. Thanks!
