### ISSUE TITLE
Adding 3 new clincal collection locations for HFH

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#152]
@KELSEYDOWLING7 Please add the following 3 clincal collection locations to the Weekly Biospecimen Metrics Report for HFH

**Variables:**
185243482       Blood Location ID
452847912       Urine Location ID

 **Location Name for Metrics Report and Clinic identifier**
  Brownstown- 1050020026 
  Columbus- 1010120026  
  Sterling Heights- 1010320019    

Once collections occur at these locations, they should appear in the following figures/tables that specifically list out HFH clincal collection locations: 

Table 1.3: Baseline Clinical Biospecimen Collections by Clinic Location
Table 2.6: Baseline Blood Collection Completeness Among Clinical Collections by Clinic Location, Henry
Ford Health
Table 5.4: Baseline Collection-To-Receipt Time (in Days) Among Clinical Collections by Clinic Location
Table 5.6: Baseline- Time (in Hours) from Clinical Collection to Receipt by Clinic Location
Figure 6.4: Baseline− Weekly Clinical Biospecimen Collections
by Clinic Location, Henry Ford Health

**Comment by KELSEYDOWLING7** [comment]
Reiterating comment from email:

It looks like there’s some mismatch here. Your original email/original HF request had this below, and we already have Ford Road in the code and DD. 

Clinic Name-Clinical 	Orgcode
Brownstown	BRN
Ford Road	FRDRD
New Center One	NCO





Your new email/updated HF request has this below, but we already have Columbus and Sterling Heights in the code and DD.

Location name              Identifier
 Brownstown                  1050020026 
 Columbus                      1010120026
 Sterling Heights             1010320019

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 As we discussed earlier this week, the only new location is: Brownstown 1050020026

**Comment by KELSEYDOWLING7** [comment]
Thanks. The code is done, just need to wait until there's data for that location for me to push to automation

**Comment by erincschwartz** [comment]
Thanks Kelsey. I asked Kirsti at HFH to inform me when the first collection occurs at Brownstown.

**Comment by erincschwartz** [comment]
Update: Brownstown launch delayed until mid-July, I will update here when the first collection at that location occurs.

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 I checked the Prod data and just received confirmation from HFH, the first collection at Brownstown, location ID occurred on 7/19. Please activate this location in the programming so it appears in the metrics report.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Thanks for letting me know! Table 1.2 and 5.4 are set up to include Brownstown once a collection is completed, finalized, has a collection timestamp, and RRL receipt time stamp. It didn't show up on yesterday report because the finalized collection flag(BioRec_CollectFinal_v1r0)  is null. It has to be a finalized collection to be included

**Comment by KELSEYDOWLING7** [comment]
Brownstown collections are now showing up in the report

![image](https://github.com/user-attachments/assets/e66957e1-5277-43d3-861d-8818858978ec)
![image](https://github.com/user-attachments/assets/077fc689-55ea-435b-9731-2ff900528482)
![image](https://github.com/user-attachments/assets/cace6191-adb8-44cd-b8fe-26008119ba27)
![image](https://github.com/user-attachments/assets/98c0034e-a38b-4bb8-b685-13b8e7fc92c9)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Excellent! Do you want me to double check this on Monday's report before closing this issue?

**Comment by KELSEYDOWLING7** [comment]
Sure, that sounds good!

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Please let me know if this looks as expected today and if we can close this issue

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Brownstown data look good, this issue can be closed.
