### ISSUE TITLE
Additional tables for Home Mouthwash Metrics

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#153]
As mentioned yesterday, we would like some of the home mouthwash metrics separated to see home mouthwash kit return rates/how long it takes using FedEx vs. USPS. Please make the following changes: 

- Update title of Table 7.2 Baseline- Total Home Mouthwash Kit Return Rate for Packages Shipped up to 1 Week Ago
- Add new table 7.3 Baseline- Home Mouthwash Kit Return Rate for Packages Shipped up to 1 Week Ago (kits shipped before 6/17/2024)
(add footnote: Note: Kits were returned using USPS prior to 6/17/2024)
- Add new table 7.4 Baseline- Home Mouthwash Kit Return Rate for Packages Shipped up to 1 Week Ago (kits shipped after 6/17/2024)
(add footnote: Note: Kits were returned using FedEx after 6/17/2024)

- Update current Table 7.4: Baseline- Time (in Days) from Home Mouthwash Kit Shipment to BPTL Receipt (kits shipped before 6/17/2024)
(add footnote: Note: Kits were returned using USPS prior to 6/17/2024)
- Add new table 7.5 Baseline- Time (in Days) from Home Mouthwash Kit Shipment to BPTL Receipt (kits shipped after 6/17/2024)
 (add footnote: Note: Kits were returned using FedEx after 6/17/2024)

Everything else will remain the same

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  The code is ready. I'll keep an eye out for new shipments, test it, and then I'll push the change. Right now the most recent date of shipment is still 5/29. 

Also with this being a separate issue can we close #143 ?

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/08921945-401a-46fe-b133-7072435e15c1)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/dba39825-d507-479d-b201-90ec4f7cbfe3)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/befe091c-1ddb-499a-9a6c-1e6a21d2af1e)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/7a1b4f83-d078-43f0-8c7b-730f12218ebf)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/88b2dd68-82b2-4f36-a30f-671f23ad37b6)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/eb0078ae-b657-4582-a1e5-ad792965403d)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/78d5b78f-a886-4506-aca5-7f148f1a6a19)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Are you able to run and post the updated tables here based on our discussion on Friday?

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Just finished


![image](https://github.com/user-attachments/assets/6bf18825-a851-4f13-81e0-01ef1697b942)
![image](https://github.com/user-attachments/assets/c0404631-7874-441c-ad3a-87fa6cab98b6)
![image](https://github.com/user-attachments/assets/8c27917b-2419-472e-b1bd-fe27cfe2dfd3)
![image](https://github.com/user-attachments/assets/fcccd84b-2d71-4d0d-858a-750e5ece1645)
![image](https://github.com/user-attachments/assets/92a83e31-f3e4-408a-a4dc-98394cad8b71)
![image](https://github.com/user-attachments/assets/11f3e5ff-b8f3-4eb4-80f3-65968a80bb8f)
![image](https://github.com/user-attachments/assets/be06d177-983f-45a2-adfb-e468195de853)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Noticed a mistake in the column order of the ones I posted last night. Apologies, these are the updated tables
![image](https://github.com/user-attachments/assets/fb95ee04-d6ae-435f-aa1d-9c1fd7507936)
![image](https://github.com/user-attachments/assets/ef4b00a4-5a6c-4886-80fa-36dc4da31516)
![image](https://github.com/user-attachments/assets/eef7cca7-2ddc-45bd-bfbb-e1c1edb10c64)

![image](https://github.com/user-attachments/assets/8a6357b8-9714-4f52-97d7-c34c4a46e538)
![image](https://github.com/user-attachments/assets/560bea35-5020-43ff-813f-3d44331d651e)
![image](https://github.com/user-attachments/assets/82be8016-b00b-459b-8c94-ea2f32dc4d2d)
![image](https://github.com/user-attachments/assets/6ba8be58-1cdd-4fa2-b2c0-d3cbff02b5ed)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Can you update the title of the new Table 7.5 shown above, this should be:
![image](https://github.com/user-attachments/assets/098c43d0-dbaa-412e-b773-24f0b0d5f050)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz 
![image](https://github.com/user-attachments/assets/a30dc7f9-cd51-4be6-899f-2d0a74cee758)
![image](https://github.com/user-attachments/assets/5edcadfe-24ea-4511-87d0-b2dd4fcac05f)
![image](https://github.com/user-attachments/assets/4e2f9e19-b79f-4a4f-a760-9e26afe14438)
![image](https://github.com/user-attachments/assets/763965d1-da2e-4653-b7c6-dee31f6f3ef3)
![image](https://github.com/user-attachments/assets/72d8b700-7501-49bc-a0e1-3c267d612e31)
![image](https://github.com/user-attachments/assets/b660f79d-6cba-4484-a935-87bf75883146)
![image](https://github.com/user-attachments/assets/21ae3a84-6082-4c53-a388-3a85808d385c)
![image](https://github.com/user-attachments/assets/73b02a0a-400d-4fb2-a784-a079b6a3545b)
![image](https://github.com/user-attachments/assets/64782847-34ef-4b2d-ac56-d1b1eed40bc4)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 These tables/figures look good. Ready for automation.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Great! Any concern with the order of the tables/figures before I push this to automation?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 The order makes sense to me, go ahead and push to automation. Thank you!

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Please let me know if this looked good on Monday's report and this issue is good to close

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 All looks good, issue is ready to be closed.
