### ISSUE TITLE
Weekly Biospecimen Metrics- Table 2.2 (limit to blood + urine)

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#154]
Please limit Table 2.2 to include data on just blood and urine; remove home mouthwash data (which is currently showing up as unknown).

![Image](https://github.com/Analyticsphere/metricsReportsRequests/assets/157617486/d21dd97e-2171-4d86-a32f-279ace3d4b24)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  All set!
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4f207f59-2d0e-4f36-a4ad-324f1e474340)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Do we need the same done for Table 2.1?
