### ISSUE TITLE
Add QC rule re: home mouthwash

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#155]
Given that we have little insight into whether particiapnts have shipped their home mouthwash kit back, we will use survey completion date as a proxy to assume they have shipped the kit back. Please add the following QC rule: 

**If BioSpm_MWSettingBL_v1r0 is Home and SrvMtW_TmComplete_v1r0 is more than 5 days ago, BioKit_KitStatusBL_v1r0 should be Received.** 

We will track the return kit of any participants who appear on this list to understand whether there may be an issue in the delivery to FNL.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  All set. It's showing no errors. Did you expect there to be any?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Based on Prod data, yes, I would expect there to have been 7 participants flagged by this rule as of last week. They all summited their mouthwash surveys in April/May but their kits are still in Shipped status, have not yet been Received.

**Comment by KELSEYDOWLING7** [comment]
Ok we may be missing some logic in that case. Today's run still showed no one. Can you provide those Connect IDs so I can try to see what else we need?

**Comment by erincschwartz** [comment]
Connect IDs that should have been flagged: 

2355880037
9767599256
6103220325
9055416970
3469967349
2105822113
9811592533

**Comment by KELSEYDOWLING7** [comment]
Got it! All 7 have null values for BioSpm_MWSettingBL_v1r0 instead of Home

**Comment by erincschwartz** [comment]
Glad that was an easy discovery, sorry about that, I didn't realize they would have null value. So, is the rule now just going to state: **If SrvMtW_TmComplete_v1r0 is more than 5 days ago, BioKit_KitStatusBL_v1r0 should be Received.**?

**Comment by KELSEYDOWLING7** [comment]
Now they come up! I'll update that for next week

**Comment by erincschwartz** [comment]
Thanks!

**Comment by KELSEYDOWLING7** [comment]
Np! Requesting this to be updated on Monday's report since it was such a small change

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Please let me know if this issue is good to close after yesterdays report

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Good to close, data in the report looks as expected. Thank you!

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 We realized that using a 5 day window was too short, the rule as originally set was flagging participants whose specimens were still in transit back to FNL. Please update the 5 day window to 10 days. 

Updated rule will read: If BioSpm_MWSettingBL_v1r0 is Home and SrvMtW_TmComplete_v1r0 is more than 10 days ago, BioKit_KitStatusBL_v1r0 should be Received.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  All set! I've uploaded the updated error list on Box here as well: https://nih.app.box.com/file/1620512505484

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Thank you, this looks much better compared to the list that was present in Monday's QC report since some of the kits listed there have already been received. 10 days seems like a more logical timeframe. I will check the report that comes on Monday and if all looks good, I will update here that we can close this issue again.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Please let me know if this looks as expected today and if we can close this issue

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Can you please update the title to indicate 10 days (instead of 5)? And, the last column is not needed. If it easy to remove, please do. If this is not simple, it can stay. 



![Image](https://github.com/user-attachments/assets/97baa794-0805-4730-a5c2-375f9e5bf439)

**Comment by KELSEYDOWLING7** [comment]
Good catch! Sorry about that; that's now been updated

**Comment by erincschwartz** [comment]
Thank you, I will cross check on the report  on Monday, then we should be good to close this issue.

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Can we actually replace the last column with Return Kit Tracking Number (BioKit_ReturnKitTrack_v1r0)? This will save me many steps in order to do FedEx tracking for each of the kits on this QC list. This can wait until after your trip.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  This has been updated in this week's report. Ill push this to automation later this week

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Thank you, it was much easier for me to do my FedEx check with the Return Shipping Tracking IDs in the QC report.  I will ensure everything looks good next week after it is put into automation and then this issue can be closed.

**Comment by brotzmanmj** [comment]
Checking to see if we can close this @erincschwartz if this looks all fine on today's report?

**Comment by erincschwartz** [comment]
Looks good in todays report, issue can be closed.
