### ISSUE TITLE
Add QC rule: list of all Connect IDs and Collection IDs for participants with multiple collections

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#157]
Please add this item to the QC report: 

Identify all participants with more than one collection at baseline (ignoring any non-finalized collections), list connect ID and collection IDs under the following categories: 
            Multiple Research collections
            Research and Clinical collections
            Multiple Clincal collections

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Would these be different then the current duplicates report? https://nih.app.box.com/file/1590922024431

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 I did not remember/may have not been aware of that duplicates report. Let me discuss with Bio team tomorrow, we may just request slight change to how the current report is formatted (i.e. limiting each participant to one row, which includes all data; limiting to Finalized collections only, adding collection setting etc.). I will be in touch.

**Comment by KELSEYDOWLING7** [comment]
Sounds like a plan! It's posted each week here https://nih.app.box.com/folder/221297686961 with the other QC outputs

**Comment by erincschwartz** [comment]
The Duplicates report will work for this purpose if we can add a few thing: 

1) can you add another column to flag somehow for "True Duplicate" which would be yes only if both/all collections for a given participant had been finalized?
2) can you add another column to indicate Collection Setting (Research or clinical) 

Once this is updated, I will begin checking this report weekly when I do my QC report review.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Great, please let me know how this looks: https://nih.app.box.com/file/1599523196858

I can also upload this as an xlsx if you need to be able to play with/search through the document easier

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 This looks good. Are you able to add columns with tube level collection data (yes/no)? No rush on this, it would just be an easy way for anyone reviewing these duplicate collections to understand what was actually collected at each visit, to determine if there is a site issue that needs to be addressed.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz Yes! Actually in doing so I'm noticing that many of these new duplicates are the separate MW collections. Should I update this to only look for Collection IDs like CXA instead of both CXA and CHA?

**Comment by KELSEYDOWLING7** [comment]
This looks much more accurate after having removed the HMW collections: https://nih.app.box.com/file/1601852227065

I also added a second file in that folder which is just that same file but in xlsx format. Please let me know your preference.

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 This is much more accurate without the home mouthwash collections included, good catch. It will likely be easiest for me to work with this file in xlsx format. Thank you for making these changes.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz This will be run manually today and should be updated in the automation update on Thursday

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Did the duplicates report from Monday look as expected?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 The report is looking pretty good. However, I am wondering about the definition used for True Duplicate, when I filter for "yes" there are still un-finalized cases showing up. I am hoping to have an easy way to filter for participants who have more than one finalized collection. Can you look at this and let me know what you find?

**Comment by KELSEYDOWLING7** [comment]
I'm only seeing 4 cases from last week that have a true duplicate flag of yes without all finalized collections, and those are all HMW. Not sure how those 4 got in but I'll fix that. Connect IDS: 1745183594, 6959982098, 7610857929, 9441852986

The others all look correct to me unless you see others.

**Comment by KELSEYDOWLING7** [comment]
Hopefully now this looks as expected: https://nih.app.box.com/file/1619626767908

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7, this looks as expected now. Thank you! We can close this issue
