### ISSUE TITLE
QC report- Ignore blood accession ID discrepancy for Connect ID 4782195164

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#158]
After discussion with Michelle, we will not have UChicago fix the blood accession ID discrepancy identified in the QC report for Connect ID 4782195164. 

Please update the QC report to ignore this case.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  For confirmation, this is just the urine accession ID that needs to be excluded, yes? It looks like it the urine accession ID by the request title and QC report, not the blood accession ID mentioned in the description.

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Sorry, it is BLOOD accession ID, I just updated the title. Sorry for the confusion.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  That's ok. That's done and will be applied to Monday's report

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Please let me know if this looked good on Monday's report and this issue is good to close

**Comment by erincschwartz** [comment]
Looked good, please close this issue.
