### ISSUE TITLE
Bio Weekly - Verified Clinical Participants with Blood Draw Order Placed

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#16]
Add a stacked bar chart to the weekly biospecimen metrics that shows the number of verified participants that have had a blood draw order placed (**BioClin_BldOrderPlaced_v1r0 = Yes**) vs. the number number of verified participants that have not had an order placed (**BioClin_BldOrderPlaced_v1r0 = No or Null**) for each KP site (**RcrtES_Site_v1r0**). The sum of the stacked bars should be the total number of verified participants for each site. (See mock-up below) 

![Screenshot 2023-02-21 at 5 08 33 PM](https://user-images.githubusercontent.com/85250133/220469960-e1a4d158-1c75-4a54-b6a8-5e4a87daa4ec.png)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Is there a specific place in the report you would like this? Or is at the end with the other plots?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 You can add it to the end with the other plots and make it Figure 4.

**Comment by KELSEYDOWLING7** [comment]
Ok! The counts in the bar section is giving me extreme difficulty for some reason, but the rest of this figure is done. I'll add it to Monday's report.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Great, thanks! And if putting the numbers in the bars is giving you too much trouble, please feel free to change the layout if you need to. My mock-ups are more of a guide rather than a rigid template. I normally use PowerPoint and Word to make them, so I know you can always replicate them in R.

**Comment by KELSEYDOWLING7** [comment]
Perfect, thank you! What I could easily do is just add a table that specifies the counts underneath the plot if that would work for you.

**Comment by HopkinsDC** [comment]
Yes, that works! Can you add the percentages in parentheses as well? (Each bar for each KP site totals 100%)

**Comment by KELSEYDOWLING7** [comment]
Of course! Let me know how these look: 


![Table 23](https://user-images.githubusercontent.com/101136647/221013639-d6e675ea-f9a0-4742-844e-f33afc2ac67b.PNG)
![Figure 4](https://user-images.githubusercontent.com/101136647/221013649-874ad130-db43-461e-ac6c-8e6696745fc9.PNG)

**Comment by HopkinsDC** [comment]
This looks good!

Just some minor edits:
- Retitle the table to "Number (and Percent) of Clinical Blood Draw Order Status of Verified Participants by Site"
- Remove the top row of the table "Blood Order Placed" 
- Shift the column titles "Blood Draw Order Placed", "No Draw Order Placed", and "Total" down to the same row as "KP_Site"
- Remove "KP_" from the first column name 
- Rename the plot's y-axis to "Number of Verified Participants"

**Comment by KELSEYDOWLING7** [comment]
All done! Just the the column titles "Blood Draw Order Placed", "No Draw Order Placed", and "Total" are fighting me getting pushed down to the same row as "KP_Site". So I bolded them instead. Let me know what you think!
![Table 23](https://user-images.githubusercontent.com/101136647/221029225-e16c0e9e-3bbb-46a3-a4b9-d0b9d4d2ee62.PNG)
![Figure 4](https://user-images.githubusercontent.com/101136647/221030195-08f62378-017c-41f8-bcea-6ec2fba36b48.PNG)

**Comment by HopkinsDC** [comment]
Hmm, that's strange. Can it possibly be fixed by removing some of the vertical and some horizontal borderlines like most of the other tables in the metrics report? (See screenshot of Table 8 below as an example)

![Screenshot 2023-02-23 at 4 16 05 PM](https://user-images.githubusercontent.com/85250133/221032517-032642da-b8aa-4bca-9960-bd9ae10cd884.jpg)

If not, don't worry about it. Everything else is great!

**Comment by KELSEYDOWLING7** [comment]
That's what I'll be working towards, but those tables have several layers of renamed variables to construct the final tables, so backtracking and replicating it will just take some time.  But if this looks good for now, great! I'll start working on #17

**Comment by HopkinsDC** [comment]
Oh ok, thanks for that explanation. It looks good for now and is ready to be added to the report. Thank you for your work on this!

**Comment by KELSEYDOWLING7** [comment]
Of course!

**Comment by HopkinsDC** [comment]
@brotzmanmj FYI, issue 16 is done and will be added to the metrics. Let Kelsey know if any other changes are needed.
