### ISSUE TITLE
Metrics report- add table for mouthwash return rate after sort order update

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#160]
The sort order for mouthwash mailing labels will be changed with the August release, to put those who completed their biospeicmen collection most recently at the top. We are interested in knowing if receiving the home mouthwash kit in closer proximity to the clincial collection visit this has an impact on the mouthwash kit return rate. 

In conjunction with the August release, please add a new table, titled: **Table 7.5 Baseline- Home Mouthwash Kit Return Rate for Packages Shipped up to 1 Week Ago (kits shipped after 8/28/2024)** (The existing table 7.5 and all subsequent tables will need new numbers)

Table will mimic Table 7.4 (shown below), with the following footnote: **Note: Sort order was updated on 8/28/2024**

![Image](https://github.com/user-attachments/assets/ca7eccc9-5af0-4d0a-8fcd-95bef293468c)

**Comment by KELSEYDOWLING7** [comment]
Will update after the prod push when there is data

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Do these number make sense? I'm not sure if the additional amount received to shipped a week ago makes sense
![image](https://github.com/user-attachments/assets/60fcd429-4e42-40b4-a616-1bd1fc6ed7a3)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 I reviewed with Michelle, this looks good to move to automation. I will review again once it is in the report next week and let you know if the issue can be closed.

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7, can we update the titles and/or footnotes for the following tables as indicated below: 

![Image](https://github.com/user-attachments/assets/7dca584f-1998-4bb0-8440-f6acbd3db956)
**Update footnote to:** During this time the kit return method was USPS


![Image](https://github.com/user-attachments/assets/b4d400d9-a33c-4ab4-bdc4-6a2788680b99)
**Update title to:** Table 7.4 Baseline- Home Mouthwash Kit Return Rate for Packages Shipped up to 1 Week Ago (kits shipped
between 6/17/2024 and 8/28/2024)
**Update footnote to:** During this time the kit return method was FedEx; Query for addresses to print pulled oldest clinical collection date/time stamp first.

![Image](https://github.com/user-attachments/assets/c721f9cc-6efc-4524-8195-daa2ec20c4f1)
**Update footnote to:** Query for addresses to print was updated on 8/28/2024 to pull most recent clinical collection date/time stamp first. Kit return method remained as FedEx.

**Comment by KELSEYDOWLING7** [comment]
All set! This will be updated in next week's report

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz Good to close after Monday's report?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 In Monday's report, it does not look like any of the titles or footnotes were updated to reflect the requests above. 

In reviewing, I realize that I have one additional change to the footnote for Table 7.5, can this be updated to say: Query for addresses to print was updated on 8/28/2024 to pull most recent clinical collection date/time stamp first, with a 5 day lag from date of clinical blood/urine collection date. Kit return method remained as FedEx.

**Comment by KELSEYDOWLING7** [comment]
Oh it looks like the changes haven't been merged yet. But yes, all set

**Comment by erincschwartz** [comment]
Thanks. I will take a look next Monday. 

Also, should the sums of the totals shipped in Tables 7.3-7.5 equal the total shipped in Table 7.2? Likewise for the number received? 

It seems that Table 7.2 is not including the totals from Table 7.5.

**Comment by KELSEYDOWLING7** [comment]
Not quite. Table 7.3 and 7.4 total 7.2, but there's overlap between tables 7.4 & 7.5. 

Should 7.4 be those after 6/17/24 but before and including 8/28/24? Right now it's just after 6/17/24

**Comment by KELSEYDOWLING7** [comment]
NOW updated with the new titles and footnotes, and Tables 7.3-7.5 total up to Table 7.2

**Comment by erincschwartz** [comment]
Reviewed the report from Monday, this looks good! We can close this issue.
