### ISSUE TITLE
Follow-up 1 eligibility count by week

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#161]
Assuming an 8/1/2025 start date for FU 1, with eligibility trigger of 3 years post-verification (and not withdrawn, deceased or refused all future biospecimen collections), can you provide the number of participants that will be come eligible for FU1 per week. per site between 8/1/2025-8/1/2027? 

We want to see what initial roll out numbers look like and also see where numbers of participants eligible for FU 1 will spike. 

Could this be completed in the next 2 weeks, after your work on operations and PROMIS metrics? It would be nice to know what kind of numbers we are looking for participant who could potentially be invited in for FU1 going into the Annual Meeting,

**Comment by KELSEYDOWLING7** [comment]
Hi Erin, please see file below
[Follow Up Eligibility Count by Site.csv](https://github.com/user-attachments/files/16714036/Follow.Up.Eligibility.Count.by.Site.csv)

**Comment by erincschwartz** [comment]
@brotzmanmj, Kelsey believes it is better to just manipulate the data in Excel vs. making updates to the code show how many participants are newly eligible by week. I added columns into the spreadsheet to show count of newly eligible and grand totals. We will review/discuss on Tuesday during Small Group meeting. 


[Follow Up Eligibility Counts by Week by Site.xlsx](https://github.com/user-attachments/files/16729156/Follow.Up.Eligibility.Counts.by.Week.by.Site.xlsx)

**Comment by brotzmanmj** [comment]
Great, thank you! One question... Does the first row (8/1/25 - 8/7/25) include all those eligible up to and including that week?

**Comment by erincschwartz** [comment]
I will have to verify with Kelsey when she is back whether row to is all those eligible up to 8/1 or if that count also includes that whole week.
