### ISSUE TITLE
PROMIS metrics additions and changes

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#162]
To document what Kelsey and I discussed in August 2024 to prepare for PROMIS backlog launch:

Higher Priority:
-Move PROMIS metrics from Weekly Operations Report to Weekly Survey Module Metrics report

- Keep existing Table 7.2 as is. 
- Add Table 7.2a, same format as Table 7.2 but 'among participants verified on or after December 1, 2023.'
- Add Table 7.2b, same format as Table 7.2 but 'among participants verified prior to December 1, 2023.' Include a footnote that the PROMIS/QOL survey was released to all those verified prior to December 1, 2023 on August 30, 2024.

-Keep existing Table 7.3 as is.
-Add an interation of Table 7.3a and Table 7.3b with same parameters as described above (verif before and after Dec 1, 2023)

-Keep Tables 7.4 and 7.5 as is (no need to have these stratified by Dec 1, 2023 date)

Lower Priority:
For separate existing report on PROMIS Survey Response Analysis by Email and Text Attempts:
-Keep existing Tables 1 and 2 as is but limit them to 'among participants verified on or after December 1, 2023'
-Add an iteration of Table 2 that is limited to participants verified prior to December 1, 2023.' The dates that are relevant are the exact dates that the messages will be sent to the entire backlog. First message will be sent Thursday August 30, 2024. Second message will be sent Tuesday Sept 2, 2024. Third message will be sent Saturday Sept 6, 2024. Fourth message - ask Hana for exact date (should be 45 days after Aug 30)
-You can wait to create this report in mid-September and by then the first three messages will have been sent with just contact #4 remaining.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm @brotzmanmj  Please let me know how the Weekly Survey Module Metrics tables look. If they look as expected, I'll post this version of the report with them included today in the Connect_ALL folder

![image](https://github.com/user-attachments/assets/4ec7d792-db50-4a40-927f-2738c2dbd214)
![image](https://github.com/user-attachments/assets/031494d9-00eb-4d66-bdeb-635d83eaa2e0)
![image](https://github.com/user-attachments/assets/95b19ee0-1cad-40d8-a589-5de0b5a0be8c)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/fd6afc22-c47e-4500-a021-b8efc51be1a2)

**Comment by brotzmanmj** [comment]
HI @KELSEYDOWLING7, we seem to be including too many people. In the survey metrics, the metrics need to exclude those who are not QOL eligible people (those that were verified less than 90 days ago). I feel like the numbers aren't reflecting that. Can you check?

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  You're right, I had to update the logic of Not started and Not Eligible based on the recent updates Tony made. I had that portion of the code commented out. that's been updated
![image](https://github.com/user-attachments/assets/f4b9accd-52a4-4a07-b3c8-be0b4189c277)
![image](https://github.com/user-attachments/assets/c6479e89-ae08-4e28-a2ec-3c09c01c2ebf)
![image](https://github.com/user-attachments/assets/bf7ca8a2-4abf-4ff3-a0bd-bf8d4aa90dab)

**Comment by brotzmanmj** [comment]
HI @KELSEYDOWLING7 , the same changes are needed to table 12, 12a, and 12b to only include QOL eligible participants. The column and row total headers are misleading in this context... both should say Total QOL Eligible Participants rather than Total Verified Participants. And the titles for 12a and 12b need to include the December cutoffs, similar to the titles in 11a and 11b. Thanks

**Comment by KELSEYDOWLING7** [comment]
Ok. The 'Not eligible' column has been removed and all titles updated. Should we change the row names in Tables 12-12b to match the ops report? (Completed survey and sample(s); Completed sample(s), no survey; Completed survey, no sample(s); Completed neither)
![image](https://github.com/user-attachments/assets/cb598acb-3fd8-4c1d-81ca-de4f16f14ed5)

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7 , this looks great. No need to change the row headings. If you can just fix the capitalization I the titles for 12a and 12b then I think we're good to go!

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Easy enough! Do you just want among in lowercase?

**Comment by brotzmanmj** [comment]
Lowercase 'among'. Uppercase 'Eligible Participants Verified'
Thanks

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  All set. This will be adding to the list of Automation updates for Thursday

**Comment by KELSEYDOWLING7** [comment]
> ![image](https://private-user-images.githubusercontent.com/101136647/365735009-fd6afc22-c47e-4500-a021-b8efc51be1a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMDA3MTMsIm5iZiI6MTcyNjAwMDQxMywicGF0aCI6Ii8xMDExMzY2NDcvMzY1NzM1MDA5LWZkNmFmYzIyLWM0N2UtNDUwMC1hMDIxLWI4ZWZjNTFiZTFhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQyMDMzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTMwNzE5MmI0ODc4NWM2YmVlYTcwMzhlZDZhOWRjYjcxMTA0ZTcwNWVkMmFiZDY1ODE0MmY4N2IwNDNiZDJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ujpqJisRjh4ajdEpy_Eq7v4Iy2iiTt0hjB9Aintzo04)

Any concern or questions with this table? Or are we good to close this issue?

**Comment by brotzmanmj** [comment]
Hi Kelsey, the table didn't come through in that last comment. Which one were you referencing?

**Comment by KELSEYDOWLING7** [comment]
Oh, this one 
![image](https://github.com/user-attachments/assets/0b867875-96b8-48a0-85a2-657fb3fc1ea3)

**Comment by brotzmanmj** [comment]
That one looks good, thanks
