### ISSUE TITLE
Monitor withdrawals after PROMIS backlog release

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#166]
We would like to monitor for a spike in withdrawals after PROMIS backlog release.

Please add a footnote to Figure 6.1 in the Operations Weekly Report to state: PROMIS/QOL Survey released to over 20,000 participants verified prior to December 1, 2023 on August 28, 2024.

Also, please fix spelling error on Y axis in word 'Requests'.

**Comment by KELSEYDOWLING7** [comment]
HI @brotzmanmj  as of yesterdays report this was Figure 6.1. Are you referring to a different plot?

![image](https://github.com/user-attachments/assets/ec07f90f-9f9e-4069-b4f2-8f7a0d979c3a)

**Comment by brotzmanmj** [comment]
Hi, Yes this is the one

**Comment by KELSEYDOWLING7** [comment]
This has been updated and will be added to the next automation update

![image](https://github.com/user-attachments/assets/2cb05885-6b2d-4d12-96c6-6b0f7f04d2a6)

**Comment by brotzmanmj** [comment]
Thanks Kelsey!
