### ISSUE TITLE
Connect Experience Survey Metrics - to be added to Weekly Survey Metrics Report

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#167]
Hi @KELSEYDOWLING7 For metrics to be added to the weekly survey metrics report for the new 2024 Connect Experience survey please see below. This survey is being implemented in this September release, but I know you had other higher priority items to tackle first. These metrics should largely mimic the QOL survey metrics that were recently finalized, but limited to participants eligible for the Connect Exp Survey. 

Eligibility for Survey: Verified between March 1, 2024 and July 31, 2024. Not withdrawn and not deceased. Not refused all
future activities and not refused all future surveys. Not eligible participants will have a 'null' survey flag status. Eligible pts survey status flag will be set to 'not started' as default.

Metrics needed:
- Completion of Survey stratified by Site for eligible pts (not started/started/submitted)
- Completion of survey by baseline data completeness (completed all surveys+samples, completed surveys but no samples, completed sample(s) but no survey, completed none). Please use same category labels as the other metrics similar to this.
- Time from Start to Submit - categorical (use same time categories at QOL as we don't have an estimate of how long this survey typically takes yet)
- Time from Trigger to Submit - summary statistic (please include 90th percentile as well)

See requirements github issue for list of new CIDs for survey: https://github.com/episphere/connect/issues/1073

Please tag @kmazzilli and @brotzmanmj in any questions as I am OOO starting today

**Comment by KELSEYDOWLING7** [comment]
Thanks @robertsamm , this sound pretty straight forward. Can you just clarify what the trigger would be for this survey?

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7  We also want to add the survey completion by demographics, same tables as those you created for Deanna for PROMIS for the annual meeting. 

Jake is running the selection of the people who will be eligible for this survey. The criteria are in the survey requirements document. For those selected, the survey status flag will be set to 'not started' upon the prod release. Everyone who is not eligible will remain null for the survey status flag.

**Comment by brotzmanmj** [comment]
Survey requirement document is here: https://nih.app.box.com/file/1253587581669

**Comment by KELSEYDOWLING7** [comment]
Hi Michelle, thank you. I saw Jake and Leila's comments from this morning and those all make sense. But for the trigger to submit time calculation I would need a time variable for the trigger. By that document I'm assuming that would be the time of the first notification?
![image](https://github.com/user-attachments/assets/1887f62d-4baf-4c57-8355-5cf9726484c8)
![image](https://github.com/user-attachments/assets/4a74a9a6-6106-44f3-8243-c992dc09f5aa)

**Comment by brotzmanmj** [comment]
Hi Kelsey, Good question, so technically the survey will be available at the date/time of the prod push. However participants won't be aware of it until they get the first notification, unless they happen to log into MyConnect between the prod push overnight and 3pm the next day when the notification goes out. I think for metrics purposes it is still to use the date/time of the first notification.

**Comment by KELSEYDOWLING7** [comment]
@HanaShiho or @robertsamm Do we know what the category name is for these notifications? I'm not seeing anything in stage or DEV

**Comment by HanaShiho** [comment]
@KELSEYDOWLING7 here's the category name: 2024 Connect Experience Survey. They aren't in stage yet but you should be able to see them in dev!

**Comment by KELSEYDOWLING7** [comment]
Thanks! I don't see it yet but I'll keep an eye out. The code is done and ready for testing once there's data

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/17859552-7035-41c4-b604-0ed28a1f385d)

**Comment by brotzmanmj** [comment]
Hi Kelsey, looks good. The only thing I see is the last column on Table 15, update column header to Total Eligible (remove reference to QOL).

**Comment by KELSEYDOWLING7** [comment]
Oh, yes my mistake.
![image](https://github.com/user-attachments/assets/bdaf38ac-fe48-4f2a-9020-ec3fb64faeb3)


I'll keep an eye out as prod data comes in and then add these to the weekly metrics report

**Comment by KELSEYDOWLING7** [comment]
Here are the tables with prod data. I can add these tables to today's Module Metrics report and just run it manually.

![image](https://github.com/user-attachments/assets/9ef06ee3-80c3-49c2-bfdd-afdc18e34ba5)

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 this looks good, I just have minor feedback on table 21:
-Could the 'completed both survey and samples' category be moved to the top so that it goes in order of most completed to least completed?
-Is it possible to make the total column a column percent? 

![image](https://github.com/user-attachments/assets/8b322ffc-3567-40c3-b127-a09ab70d6200)

**Comment by KELSEYDOWLING7** [comment]
Hi, yes the ordering is an easy fix. And then do you want all percentages to be column percentages? Or cell percentages for this table and then just the total column to be column percents?

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 just the total column should be a column percent, and then the other cells should remain as row percents so that we can see what the relative completion rate is for the four different groups. Thanks for checking!

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/991c77dc-8d5a-4ed8-81f4-fb58120e6064)

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 looks perfect!
