### ISSUE TITLE
Connect Experience Survey QC to be added

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#168]
Hi @jacobmpeters For metrics to be added to the weekly survey metrics report for the new 2024 Connect Experience survey please see below. This survey is being implemented in this September release and stage testing should be starting 9/30.

QC to be added:

- Only survey flag values in DD allowed (no weird values)
- No survey data if survey flag=null
- Date started populated only if survey flag is started or submitted
- Date submitted populated only if survey status flag is submitted

See requirements github issue for list of new CIDs for survey: https://github.com/episphere/connect/issues/1073

Please tag @kmazzilli and @brotzmanmj in any questions as I am OOO starting today

**Comment by KELSEYDOWLING7** [comment]
Assigning me and Madhuri, as we write the QC rules and then work with Jake to get them into automation

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Here are the rules below that we can test once there's data. For rules 3 and 4 I added the rules both ways: if the survey is started or submitted, the start/stop time must be populated. If the survey status is not started, the stop/start time must be null.

For rule 2 I'm thinking the this rule will have to be custom: if d_956490759=NULL, then nrow(Connect_Experience_Survey) must = 0

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DOWLIN~1/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DOWLIN~1/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

<div ccp_infra_version=3 ccp_infra_timestamp=1727439363902 ccp_infra_user_hash=1490346582
ccp_infra_copy_id=53a14d27-f8d5-4c9d-88c3-c6ae5eb5e163 data-ccp-timestamp=1727439363902>


ConceptID | Qctype | ValidValues | CrossVariableConceptID1 | CrossVariableConceptID1Value
-- | -- | -- | -- | --
d_956490759 | NA or valid | 972455046, 615768760, 231311385 |   |  
d_263355177 | crossValid1NotNA |   | d_956490759 | 615768760, 231311385
d_199471989 | crossValid1NotNA |   | d_956490759 | 231311385
d_263355177 | crossValid1 is not populated |   | d_956490759 | 972455046
d_199471989 | crossValid1 is not populated |   | d_956490759 | 972455046



</body>

</html>

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters @mnataraj92 These rules have been added to the 'Rules to Add' tab of the Recruitment QC Rules file. No errors so far when I tested the rules manually

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  These issues are now included in the live report as of this week and no errors were found. Are we good to close this issue?
