### ISSUE TITLE
PROMIS metrics by demographics

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#169]
Add to the Weekly Survey Module Metrics the PROMIS completion rates by age, sex, race, and combo that were run for the annual meeting for Deanna.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Do you want all of these tables added (except the first table)?
[Retension-Metrics.pdf](https://github.com/user-attachments/files/17138281/Retension-Metrics.pdf)

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7  yes that would be great, thanks

**Comment by KELSEYDOWLING7** [comment]
Please let me know how these look: Tables 13-17

https://nih.app.box.com/file/1657242878328
