### ISSUE TITLE
Bio Weekly - Drill-down on Table 7 for UChicago

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#17]
Add a table to the weekly biospecimen metrics report that shows the number and percent of blood completeness among University of Chicago baseline research collections by collection location (**BioSpm_Location_v1r0**). UChicago's collection locations are **UC-DCAM, Ingalls Harvey, River East, & South Loop**.

The layout and column titles of this table should be the same as Table 7 (Blood Completeness among Baseline Research Collections), but the first column should be titled "Collection Location" rather than "Site".

Add this table after Table 7 (Blood Completeness among Baseline Research Collections); **It'll be Table 7.1**

Title this table "**Blood Completeness among University of Chicago Baseline Research Collections by Collection Location**"

**Comment by KELSEYDOWLING7** [comment]
Hi @HopkinsDC  Please let me know how this looks
![table 7_1](https://user-images.githubusercontent.com/101136647/221203698-8f1e167a-594e-455b-86cd-93eecbbba3ee.PNG)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This is perfect! Thank you!

**Comment by HopkinsDC** [comment]
@brotzmanmj FYI, issue 17 is done and will be added to the metrics. Let Kelsey know if any other changes are needed
