### ISSUE TITLE
Update to Sanford Health clinical collection metrics

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#170]
As discussed, Table 1.4 could us some updates. Please make the following updates: 

1) Update the title to: Table 1.4: Baseline Clinical Biospecimen Collections in the Past 30 Days at Sanford Health by Clinic Location 
2) Add footnote: This table reflects Clincal Collections in the past 30 days; the total number of Clinical Collections at Sanford Health is #
3) Remove Total Clinical Collections column

Is it also possible to add regional headers to this table (Bismarack, Bemidji, Fargo, Sioux Falls) and list clinics under appropriate header? Maddi will update the crosswalk document to indicate which region each clinic falls under. She is also planning to re-name some of the clinic locations as the current location labels not informative to their Connect team. 

Maddi would also like another table, would be Table 1.5 Top Baseline Clinical Collection Locations at Sanford Health by Region 

This table would list the current top 10 clincial collection locations in each region (Bismarack, Bemidji, Fargo, Sioux Falls); columns would be Collection Location and  Total Clinical Collections. 

Happy to discuss if needed.

**Comment by KELSEYDOWLING7** [comment]
If we are already going to do a total count by region for the new Table 1.5, I would strongly prefer not putting the region labels in Table 1.4. It's doable but the code is already quite complex, and would be more so with the constantly rotating site locations listed and having to map their appropriate region. I think the information would already be captured well in Table 1.5, but if they really want it I can look into it after the crosswalk is redelivered.

Here is Table 1.4 without the region labels. Any update to the Site location names will automatically be applied once the new crosswalk is sent over:
![image](https://github.com/user-attachments/assets/a1ba1d66-5c56-4715-9b6f-997156f55266)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7, just want to point out that the top 10 locations per region in the proposed Table 1.5 will also rotate based on volume of collections. Do you think this will be too complex to list by region? Also, Table 1.5 won't have a total count by region, it will just have the totals for the 10 clinical collections locations with the highest volume within each region. But, you bring up a good point, could we add a footnote to Table 1.5 with the total for each region, like the footnote for total collections in Table 1.4?

**Comment by KELSEYDOWLING7** [comment]
Ah, ok that's a good point too. The footnote I can definitely do. The rest will be easier to decide on or further discuss once I have the update crosswalk to play around with

**Comment by erincschwartz** [comment]
I will pass the crosswalk along as soon as Maddi sends it over.

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Can you look at the footnote for Table 1.4? It seems low compared to the number of collections listed in Table 1.9. They have not had any clincial collection re-draws that I am aware of. 

![Image](https://github.com/user-attachments/assets/15b9a093-e2bd-4cdd-977f-53284f22f646)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  You're right. I've updated the code for the footnote. Do you need me to rerun the report to fix that table?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 thank you for looking into this. I already let Sanford know that the code was being looked at. No need to re-run the report. I will check it next Monday.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz Just checking in on this issue. Is Maddi still working on the crosswalk?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7, Yes, we are still waiting on Maddi to send an updated crosswalk. She is out of office this week but I sent her an email to get an updated timeline.

**Comment by KELSEYDOWLING7** [comment]
Adding updates here from our email chain with the new crosswalk:


**Table 1.4**
![image](https://github.com/user-attachments/assets/3b920211-1b72-4127-9c60-283d68f80b29)
![image](https://github.com/user-attachments/assets/7b87f395-efaa-46b9-9596-2d4dd4d032f4)



**Table 1.5**
![image](https://github.com/user-attachments/assets/29e05d87-ce6a-4c18-b463-3c8283e4b93f)

**Comment by KELSEYDOWLING7** [comment]
Table 1.4 tweaked with Maddi's request to have the monthly counts descending 

![image](https://github.com/user-attachments/assets/3a22086d-44ad-45fb-b6ca-62134ec0b77f)
![image](https://github.com/user-attachments/assets/3ed491c8-e50c-4eda-b80d-9f3a997b0428)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 This looks good. Thanks!

**Comment by erincschwartz** [comment]
Quick question about table 1.5, I see more than the top 10 listed for Fargo and Sioux Falls. I assume this is just because there are no collections in Bemidji and few in Bismarack. Please confirm. 

Also, if SFH team would find it helpful, can you incorporate the total per region either 1) in the table or 2) in a footnote? If in footnote, it could say: This table reflects Clincal Collections at the top collection locations in each region. The total number of Clinical Collections in each region are as follows: Bemidji: X; Bismarack: X; Fargo: X; Sioux Falls: X.

**Comment by KELSEYDOWLING7** [comment]
Correct, I notified Maddi of those two thing as well. Bemidji has no collections as of yet and for Fargo those last few collections locations are all tied for 10th place. Those will adjust as new collections come in. 

Yes, the footnote can easily be added. Do you want to check with Maddi first if they need it, or just have me add it now?

**Comment by erincschwartz** [comment]
I think we should just add it now. Thanks.

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/84492272-62a5-4fe4-a0e2-0cc9445920db)

**Comment by KELSEYDOWLING7** [comment]
Updated in yesterdays report. Please let me know if we are good to close this issue

**Comment by erincschwartz** [comment]
Just reviewed, can you double check the total counts in the footnotes for Tables  1.4 and 1.5? The total in 1.4 is 267, which is only 7 more than the week before but Figure 6.12 seems to show a lot more than that. Also, the totals in all 4 regions in Table 1.5 only add up to 237, so even if the note in 1.4 is correct, something seems off. Thanks!

**Comment by KELSEYDOWLING7** [comment]
Thanks for pointing that out. The footnote in Table 1.4 was correct, 1.5 had an error. 
![image](https://github.com/user-attachments/assets/1dadcdcc-7ff7-4a47-876d-33b76cb157a3)

![image](https://github.com/user-attachments/assets/adc6c80f-aa19-4d57-8ee9-4f7522455a8e)


And the jump does look to be about 7 is Figure 6.12. Please let me know if I'm missing anything
![image](https://github.com/user-attachments/assets/45707573-e9c5-4287-97f0-3d04caea4149)

**Comment by KELSEYDOWLING7** [comment]
Table 5.4 also matches the count 
![image](https://github.com/user-attachments/assets/dbee31e9-a108-4c0c-a63f-5cc30a9f13fd)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Thanks for looking into this. I am still a little but confused, isn't Figure 6.12 showing the count of collections per week,  not the difference since the previous week? The way I understand it, the figure is showing 40+ collections last week (not just 7). 

Also, can you fix the spelling errors in the footnote for Table 5.4--so sorry, in this ticket I had misspelled Bismarck but you already corrected that in the tables...just the footnote error remains. 
![Image](https://github.com/user-attachments/assets/c03a8647-52dd-490c-ad54-e8676c282f41)

**Comment by KELSEYDOWLING7** [comment]
Hi Erin, you're right. It appears SF is missing some locations on their crosswalk. There are 8 IDs and a total of 38 collections from those unidentified locations that were being excluded from the code since they were not labeled. I emailed Maddi requesting an updated crosswalk to fix the code

**Comment by erincschwartz** [comment]
We are doing metrics review during Bio Team meeting later this morning. Please clarify, were the 38 collections mentioned above missing from Tables 1.4 and 1.5 in Monday's metrics report---meaning the total clincial collections at SFH is actually higher than what is showing?

**Comment by KELSEYDOWLING7** [comment]
Hi Erin, those counts were before the most recent crosswalk from SF. Now we just have those 18 we discussed with missing location IDs. The rest are accounted for

**Comment by KELSEYDOWLING7** [comment]
Are we good to close this issue? Outside of the missing location IDs in issue #184 everything else lines up
