### ISSUE TITLE
QC report- Cases that have been investigated and can be ignored

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#171]
**Item 20** Urine Tube 1 
        Ignore Connect ID **4002548016**
        (The site team determined that this was accidentally entered and attempted to remove from the collection prior to finalization but 
         the Dashboard would not allow this. They did remove it from the shipping list, thus it did not appear on the manifest.)

**Item 29** Mismatched Blood Accession IDs
       Ignore Connect IDs **4900116130 and 5461650381**
       (Mis-linked samples, participants were invited in for re-draw and samples were marked as QC only)
       Ignore Connect IDs **4462616750,  9111871102, 8476952861**
       (Have been investigated and marked WILL NOT FIX)

**Item 30**  Mismatched Urine Accession IDs  
       Ignore Connect IDs **4900116130 and 5461650381**
       (Mis-linked samples, participants were invited in for re-draw and samples were marked as QC only)

**Item 33** Supply/Return Kit ID mismatch
       Ignore Connect ID **4765411890**
       (no difference in actual Supply Kit and Return Kit IDs, just lower case c was entered for Return Kit ID , dashboard will not allow 
        lowercase following Sep release)
      

@kelsey, there are several more that I mentioned have been on the QC report since before my time in this role. I need to further investigate the reasons we are ignoring them and will add to this issue at a later date.

**Comment by KELSEYDOWLING7** [comment]
Sounds good! The ones listed here have been added

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Thank you, these are all now ignored from the report as requested. 

Can you please also ignore the following under ****Item 29** Mismatched Blood Accession IDs**:

Connect ID **6229346420** 
(manual accession ID entry error) 

 Connect ID **7515171846** 
(lab drew only 1 blood tube one day, then participant came back in another day, site confirmed this Accession ID belongs to this participant) 

 Connect ID **8336144924**
(listed in poly accession ID list, flagged because there must have been a spacing issue in the list or Dashboard)

**Comment by erincschwartz** [comment]
One more to ignore under  **Item 29 Mismatched Blood Accession IDs:**

Connect **2974054638**
(Confirmed from site, clinical lab team scanned one blood tube 2x, resulting in duplicate accession ID listed in Poly Accession ID list)

**Comment by KELSEYDOWLING7** [comment]
Added. Those exclusions and my new version of duplicate filtering have been applied to the report. Some new issues did come up, though this may be from running the report midweek. Regardless, please let me know if any of these don't seem right: https://nih.app.box.com/file/1587551786119

**Comment by erincschwartz** [comment]
Two more to ignore under Item 29 Mismatched Blood Accession IDs:
**Connect ID: 9963945282** 
(Site explained issue, only partial collection but clincial lab team did not pay attention to which Accession IDs were on the filled tubes so Connect team received tubes that had the cancelled Accession IDs but confirmed this Accession ID did belong to the participant)

**Connect ID: 9554775290**
(Site explained there had been a data transcription error and the full list of poly accession IDs was not sent over, confirmed that the ID scanned matched an ID in the Poly Accession ID list)

**Comment by KELSEYDOWLING7** [comment]
Added! Jake's out today so we may not be able to get this into automation for Monday

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 These two Connect IDs from the comment above are still appearing in the QC  report (12/2) under number 29 Mismatched Blood Accession IDs. Can you look into this? 


Connect ID: 9963945282
(Site explained issue, only partial collection but clincial lab team did not pay attention to which Accession IDs were on the filled tubes so Connect team received tubes that had the cancelled Accession IDs but confirmed this Accession ID did belong to the participant)

Connect ID: 9554775290
(Site explained there had been a data transcription error and the full list of poly accession IDs was not sent over, confirmed that the ID scanned matched an ID in the Poly Accession ID list)

**Comment by KELSEYDOWLING7** [comment]
Yes. The code is in place for ALL Biospecimen QC Github issues, but because some are under review I haven't pushed them to automation. I'd have to go in and remove the code for the ones pending approval and add them back in for later. If these are time sensitive changes, please let me know and I can try to remove all the other changes outside of this one

**Comment by erincschwartz** [comment]
Thanks for explaining. Not time sensitive, we can wait until all new QC items are ready. I will be discussing the others during my 1:1 with Michelle tomorrow.
