### ISSUE TITLE
Ad Hoc Metrics for Internal Biospecimen Meeting on 10/28

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#173]
During discussion on planning for Follow-up 1 collections, we discovered that we would like insight into various study activity to date. Please see the request below for ad hoc metrics we are requesting, to be reviewed during the Internal Biospecimen Meeting on Monday, 10/28.  We are still finalizing the rest of the request, I will add the other items here when available. 

Purpose: to inform prioritization of reminders for baseline biospecimen collections prior to the Follow Up 1. Christian indicated that we want to prioritize people who recently completed the baseline survey modules. 

1.	Run a frequency of the order in which the following activities were completed
      a.	BOH completion first, blood/urine collection second
      b.	Blood/urine collection first, BOH completion second
      c.	BOH completion first, mouthwash collection second
      d.	Mouthwash collection first, BOH completion second

2.	Among participants who have donated blood and/or urine in Research setting and completed any baseline module(s), provide counts for the following time intervals (<=30 days, 31 to <=90 days, 91 to <=180 days, 181 to <=365 days, 366 or more days) between completion of blood and/or urine donation and the following surveys, regardless (i.e., absolute value of difference) of which activity occurred first:
      a.	BOH 
      b.	MRE 
      c.	SAS 
      d.	LAW 

3.	Among participants who have donated blood and/or urine in Clinical setting and completed any baseline module(s), provide counts for the following time intervals (<=30 days, 31 to <=90 days, 91 to <=180 days, 181 to <=365 days, 366 or more days) between completion of blood and/or urine donation and the following surveys, regardless (i.e., absolute value of difference) of which activity occurred first:
      a.	BOH 
      b.	MRE 
      c.	SAS 
      d.	LAW 
 
4.	Among participants who have donated mouthwash in Home setting and completed any baseline module(s), provide counts for the following time intervals (<=30 days, 31 to <=90 days, 91 to <=180 days, 181 to <=365 days, 366 or more days) between completion of mouthwash donation and the following surveys, regardless (i.e., absolute value of difference) of which activity occurred first:
      a.	BOH 
      b.	MRE 
      c.	SAS 
      d.	LAW 

Please let me know if you have any questions about this request or concern over the timeline. Thanks!

**Comment by KELSEYDOWLING7** [comment]
Good morning Erin, just a few quick questions. 

First, for the blood/urine collection timestamp should I use (556788178m BioRec_CollectFinalTime_v1r0, Time Collection Finalized)? 

Second, should these only look at finalized collections (for blood and urine collections)?

Third, should duplicate collections be excluded?

**Comment by erincschwartz** [comment]
Yes, please use (556788178m BioRec_CollectFinalTime_v1r0, Time Collection Finalized)

And, yes, only finalized collections
 
And, yes, duplicate collections should be excluded, lets look at the first collection only

**Comment by KELSEYDOWLING7** [comment]
Great! Those are all done then. Let me know when the additional request are finalized

**Comment by KELSEYDOWLING7** [comment]
For our meeting with Michelle today: [Internal_Bio_Meeting_10_28_2024.pdf](https://github.com/user-attachments/files/17412777/Internal_Bio_Meeting_10_28_2024.pdf)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Here's the metrics with the updated Total lines ad additional info on the first section
[Internal_Bio_Meeting_10_28_2024.pdf](https://github.com/user-attachments/files/17461281/Internal_Bio_Meeting_10_28_2024.pdf)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Thank you for updating this ad hoc metrics report. In review, we realized it will be informative to break down number 4 above into two groups, those with the original mouthwash eligibility sort order and those after we switched the order with the August Prod Release. Can you please adjust number 4 and run an additional metric, as shown below: 

4. Among participants who have donated mouthwash in Home setting **that were shipped their home mouthwash kit before 08/29/2024** and completed any baseline module(s), provide counts for the following time intervals (<=30 days, 31 to <=90 days, 91 to <=180 days, 181 to <=365 days, 366 or more days) between completion of mouthwash donation and the following surveys, regardless (i.e., absolute value of difference) of which activity occurred first:
a. BOH
b. MRE
c. SAS
d. LAW

5. Among participants who have donated mouthwash in Home setting **that were shipped their home mouthwash kit on/after 08/29/2024** and completed any baseline module(s), provide counts for the following time intervals (<=30 days, 31 to <=90 days, 91 to <=180 days, 181 to <=365 days, 366 or more days) between completion of mouthwash donation and the following surveys, regardless (i.e., absolute value of difference) of which activity occurred first:
a. BOH
b. MRE
c. SAS
d. LAW

Please let me know if you have any questions.

**Comment by KELSEYDOWLING7** [comment]
All set!
[Internal_Bio_Meeting_10_28_2024.pdf](https://github.com/user-attachments/files/17479827/Internal_Bio_Meeting_10_28_2024.pdf)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Is this good to close now that the meeting's concluded?

**Comment by erincschwartz** [comment]
Yes, we can close. We have not yet discussed these metrics because other topics took priority on 10/28 but I have the document saved. Thank you!
