### ISSUE TITLE
Adjust time lag for Table 7.5 in Weekly Biospecimen Metrics Report

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#176]
Please adjust the time lag to 2 weeks (14 days) for Table 7.5 when you have a chance. 

New title: Table 7.5 Baseline- Home Mouthwash Kit Return Rate for Packages Shipped up to 2 Weeks Ago (kits shipped
after 8/28/2024)

![Image](https://github.com/user-attachments/assets/ce65d7f7-8624-43c2-8701-cbe4a6758b57)

**Comment by KELSEYDOWLING7** [comment]
Good morning @erincschwartz  let me know how this looks
![image](https://github.com/user-attachments/assets/d2f23c23-08cf-41aa-bb09-044ab9fa2f9e)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 This looks good, ready for automation.

**Comment by KELSEYDOWLING7** [comment]
Updated on this Mondays report

**Comment by erincschwartz** [comment]
This looks good in production, can close this issue now. Thank you!
