### ISSUE TITLE
Ad Hoc Metrics for Serology Pilot Study

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#177]
We are preparing samples to be sent off for a multiplex serology pilot study. Please run a report to include the following:  

1. Among participants who have donated blood samples since January 1, 2024 to now, run distribution for age, sex, race/ethnicity using site-provided variables  

2. Among participants who have donated blood samples since January 1, 2024 to now, run distribution for baseline surveys (1-4) that have been completed  

This is not needed for 10/28 meeting, please just generate when you have a chance.

**Comment by KELSEYDOWLING7** [comment]
All set! Let me know if you need anything else
[Serology-Pilot-Study-Stats.pdf](https://github.com/user-attachments/files/17480265/Serology-Pilot-Study-Stats.pdf)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Anything else needed for this?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7, nothing more needed at this time. This issue can be closed. Thank you!
