### ISSUE TITLE
Updates to Weekly Biospecimen Metrics Report

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#178]
As discussed during the call on 10/24, please make the following changes to the Weekly Biospeicmen Metrics Report: 
**Update intro paragraph on pg 1:** 
This Weekly Metrics report contains tables and plots for the Connect Biospecimen samples, many stratified
by health provider site. This information pertains to verified participants as of the date above and collections
that are final**ized. This report is limited to information from participants' first finalized specimen collection. In the even that a participant donated specimen(s) in a repeat collection, that information is not reflected in this report** 

Add a new Table 1.2 Baseline Biospeicmen Collection Setting (mimics format of Table 1.1)
Columns will be: Site, Baseline Collection, Research, Clinical, Home 

Add footnote to Table 2.11 Note: This table includes deviations on all baseline specimens except home mouthwash.

**Comment by KELSEYDOWLING7** [comment]
Hi @erincschwartz one thought on this. For table 1 we define 'Baseline Collections' as blood, urine, or mouthwash collection and that the collection is finalized. Because the home mouthwash is not finalized, this is not captured in table 1.1. If we include it 1.2, the numbers will be off. 

This would only be the case for those that had ONLY home mouthwash done. I believe we mentioned this, as we didn't want to double count anyone. Do we want a footnote for table 1.2 as well mentioning that Home is for those with ONLY home mw?

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Good point that we don't want to double count. I think adding a footnote will help explain. Note: Any collections indicated under 'Home' setting reflect collections in which home mouthwash was the only sample collected. 

For now, all sites should have 0 under Home, since the home mouthwash eligibility criteria is completion of clinical blood and/or urine collection. That may change in the future though.

**Comment by KELSEYDOWLING7** [comment]
One other question. Some people have only blood or only blood urine, ect so I'm curious how you'd like to have the denominator reflected. For example, here the total collections from table 1.1 would be 34,835. 
![image](https://github.com/user-attachments/assets/1183aa26-74f5-415d-8dfd-90c168c542cb)

But each collection type (blood, urine, mouthwash) will not perfectly add up to 34,835 by collection setting unless we include those with no collections. So for Table 1.2 do you want the blood, urine, and mouthwash to each add up to 34,835 by including non-collection counts? Or no?

**Comment by KELSEYDOWLING7** [comment]
You were right, no home collections only for the time being. 
![image](https://github.com/user-attachments/assets/8663b044-cda2-4b31-af1b-251087cba3d5)

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/06f1465d-f074-4a56-b57a-3d7d34b8fb91)

**Comment by erincschwartz** [comment]
New Table 1.2 and footnote for Table 2.11 look great, ready for automation.
