### ISSUE TITLE
Bio Metric - Distribution Curves for Research Collection Visit Length

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#18]
Please generate a univariate distribution graph for each research site, with the curve displayed, to show their distribution of research biospecimen collection visit length (**in minutes**). 

The research sites are HealthPartners, Sanford, University of Chicago, Marshfield, and Henry Ford.

Collection visit length is the difference between Date/Time Check-In Complete (**BioChk_Time_v1r0**) and Time check out complete (**BioFin_CheckOutTime_v1r0**)

We will use these distributions to define outliers for each site; these distributions are one-time metrics, and **should not** be included in the biospecimen weekly metrics.

For your reference, Table 22 (Research biospecimen collection visit length by site (in minutes)) displays the summary statistics for each sites' visit length in minutes.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This issue is not urgent and can wait until after the edits to the weekly metrics are complete.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  I created these graphs in both boxplot and histogram. Please let me know your preference. It looks like roughly anything over roughly 1,500 minutes would be an outlier. 
[Biospecimen-Issue-18.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10902376/Biospecimen-Issue-18.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This is great. Thanks you!
