### ISSUE TITLE
QC report- Add check for both Research and Clinical collections at same timepoint

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#182]
Please add the following QC check: If BioSpm_Visit_v1r0 is Baseline, then BioSpm_Setting_v1r0 for all collections for the participant should either all be Research or Clinical. This only applies to participants with duplicate baseline collections. 

Same rule will be needed when we launch follow up collections.

**Comment by KELSEYDOWLING7** [comment]
Question on this one, there actually is no real variable 'BioSpm_Visit_v1r0', at least not on its own. It's just a part of these three nested variables: BioChk_CompleteBL_v1r0, BioFin_CheckOutTmBL_v1r0, BioChk_TimeBL_v1r0

I'm trying to think of how to write the logic for this rule. Do all participants, research or clinical, have that check out time?

**Comment by erincschwartz** [comment]
Looks great, cross-checked with the QC errors in last Monday's report. Ready for automation.

**Comment by KELSEYDOWLING7** [comment]
> Looks great, cross-checked with the QC errors in last Monday's report. Ready for automation.

I think that comment went to the wrong issue!

**Comment by KELSEYDOWLING7** [comment]
This issue has three participants with errors, 4545815202 5054849844 1981842976. What variables would you like outputted for this rule?

**Comment by erincschwartz** [comment]
The code for this rule appears to be working. We were aware of 4545815202 and 1981842976 (should be fixed now that Tony made the Prod manual changes). I was not aware of 5054849844 and will look into this further with Michelle next week. Please add this new rule to the QC report.

**Comment by KELSEYDOWLING7** [comment]
Sounds good! What variables would you like outputted for this rule?

**Comment by erincschwartz** [comment]
Just Connect ID is fine. I filtered the Biospe_formats to just look at that ID and can see a nice comparison

**Comment by KELSEYDOWLING7** [comment]
Ok, then in that case all the current Github Biospecimen QC change requests are reflected on the most recent Bio QC report on this Box folder:   https://nih.app.box.com/folder/249010743726 ,  including the list of Connect IDs requested for issue #185
