### ISSUE TITLE
QC- Update/Consolidate QC items 7-11

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#186]
**Update QC rule 7 to the following:** 
If BioFin_BaseUrineCol_v1r0 = yes, collection setting is Clincial and BioClin_DBUrineRRLDtBL_v1r0 occurred more than 7 days ago, BioClin_SiteUrineColl_v1r0 must be yes

**Remove current QC rules 8-11 and consolidate into this one rule:** 
If BioFin_BaseBloodCol_v1r0 = yes, collection setting is Clincial and BioClin_DBBloodRRLDtBL_v1r0 occurred more than 7 days ago, BioClin_SiteBloodColl_v1r0 must be yes

**Comment by KELSEYDOWLING7** [comment]
Updated

**Comment by KELSEYDOWLING7** [comment]
https://nih.app.box.com/file/1587551786119

**Comment by KELSEYDOWLING7** [comment]
If approved by Wednesday 12/4, this can be updated in the automation for Monday's report
