### ISSUE TITLE
QC- Items to ignore

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#188]
Please ignore the following from #29- Blood accession ID discrepancies

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Connect ID
--
3544623873
3293040395
7571439842
3165368475
6954174713
6361337944
1629086681
9768745029
3770024701   
8836251245

</div>

<p><cite style='margin:0in;font-family:Calibri;font-size:9.0pt;color:#595959'>(HFH
did not send clinical data in a timely manner and cannot access the Accession
IDs for these collections.)</cite></p>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>&nbsp;</p>

</body>

</html>

Also, Connect IDs 
4727512872 
5506703775
8123989364
9963945282
9554775290
All have been investigated by SFH and deemed WILL NOT FIX

**Comment by erincschwartz** [comment]
Moved this back to 'In Progress'

Please also ignore the following from QC item 29, Blood accession ID discrepancies

**Connect ID 3312148528**
(HFH team member scanned the Connect specimen label instead of the clincal tube label into the Dashboard

**Connect ID: 6729595173**
(SFH team confirmed one number was cut off in Poly accession ID string sent, which matches the Accession ID scanned into the Dash)

**Connect ID: 9843228847**
(SFH team confirmed manual entry error of Poly Accession ID list)

**Comment by KELSEYDOWLING7** [comment]
Added
