### ISSUE TITLE
Error in BSWH weekly logs

### ISSUE THREAD

**Issue by kmazzilli** [Analyticsphere/metricsReportsRequests#189]
It seems like there may be an error in the weekly logs for BSWH. In the last 3 posted files (11/11, 11/18, and 11/24) the week of 11/4-11/10 is entered twice. The numbers (invitations, specimens collected, etc.) also do not match up between the two weeks. For example, under "invitations per week" the first 11/4-11/10 entry says 108 but the second entry says 0.

Kelsey could you please look into:
1. The double entry
2. Which numbers are correct between the two entries
3. The other weekly logs for all sites and overall to make sure they look ok? I don't see the repeated week on my end, but just to be sure.

Thanks!
Kaitlyn

**Comment by KELSEYDOWLING7** [comment]
Hi @kmazzilli that's odd... I can confirm that's the only Site where this occurred. What's odd is that the code is the same for all sites; it loops through each site's data and the code hasn't been changed since July. This is all Jing's old code so it will take me a bit to sort through it all. Please let me know if it happens again or if this just seems like a one time occurrence.

**Comment by KELSEYDOWLING7** [comment]
No errors showing up this week

**Comment by kmazzilli** [comment]
Hi @KELSEYDOWLING7, thanks for the update - I'm looking at the BSWH weekly log that was posted yesterday and am still seeing the same issue of the 11/4-11/10 issue posted twice with mismatching numbers.

**Comment by KELSEYDOWLING7** [comment]
Yes. I'm unsure how to fix the code without breaking the other sites and/or week counts. Since this was a one time occurrence my preference would be to keep the code as is but continue to monitor it to ensure it was just a one time occurrence

**Comment by brotzmanmj** [comment]
@erincschwartz is the extra row messing up the counts? Is it just a repeated row for the week with all 0 values? Are the cumulative counts accurate?

**Comment by erincschwartz** [comment]
@brotzmanmj, did you mean to pose the question above to Kaitlyn? I am not very familiar with the Weekly Logs and cannot speak to this issue.

**Comment by brotzmanmj** [comment]
Yes, sorry, multitasking! @kmazzilli is the extra row for that week impacting the cumulative counts?

**Comment by kmazzilli** [comment]
@brotzmanmj It’s not a repeated row with zeroes, though some of the numbers in each row are zeroes. I see what Kelsey is saying, this could be messy to fix and the overall cumulative counts seem okay! 

The data for this week in particular is confusing and could cause problems for someone trying to use data from this week alone I think (like me, when I was trying to calculate Nov averages, I wasn’t sure which row to use because they both contain different numbers).  One of the discrepancies I am seeing is for specimens. The first entry of 11/4-10 says 0 specimens were collected that week, the second entry has 2 specimens were collected that week. So under cumulative specimens, the first entry for 11/4-10 says 24, the second says 26. 

However, I am not sure if this is related, but it looks like on the weekly operations report, the BSWH Figure 1.4 "Weekly Number of Invitations and Study Activity Completion" is cut off at this week, and does not show data past 11/11, even though there are data to show according to the weekly logs.

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7 we discussed with Nicole yesterday and her suggestion was for you to look at the issue with the Weekly Operations Report Figure 1.4 that Kaitlyn mentioned, since that is running on new code and not Jing's old code. And Nicole will ask Autumn to start looking into the weekly log code.

**Comment by KELSEYDOWLING7** [comment]
Agreed! I'll focus on that today. 

My presumption is that something went awry when BSW sent us their data for that week. The code considers that week of the fourth to be data from 11/4-11/10 and if any of the data was somehow sent on say the 11th, it may have been misinterpreted by the code. 

If something like that were to happen, could you Teams Message me the contact information for someone at BSW? Either way I can try to merge the data from that likely split week to correct this for just BSW

**Comment by brotzmanmj** [comment]
Thanks Kelsey. I'm trying to figure out what you mean by 'sent us their data for that week'. Mostly it is our system setting the dates when events occur. Happy to hop on a call to discuss if that would help.

**Comment by KELSEYDOWLING7** [comment]
I was wondering if any of the variables necessary for the blood count may have been sent after the fact. But if that is not possible please disregard.

What is most odd is that the code in the live automation and the code on my local machine are the same, but I just ran it and I DO get a completed Figure 1.4 without changing anything. If that figure still shows up incomplete on Monday I will run the report manually again and look into any potential discrepancies on Github. 
![image](https://github.com/user-attachments/assets/15267ad6-5ac9-40d4-a88e-4856fa7ea429)


The only way this should/could have happened was if everything was 0 for the weeks of 11/8 and 11/25 but had a value for 12/2. Then in that case the only issue is that the lines should have been on 0 for those first two weeks. Instead they did not populate, and only populated once there was a value again on 12/2. Which is why there are not dots on the lines for weeks 11/18 and 11/25. Please let me know if that makes sense, and if the logs match that theory.

**Comment by KELSEYDOWLING7** [comment]
I can adjust the plots to look more like this, where 0 is always represented. It can just be hard to see all lines because lines with the same counts get overlapped. 
![image](https://github.com/user-attachments/assets/2461608c-c5d1-4ff2-9a1e-26d6718f16e3)

**Comment by brotzmanmj** [comment]
I like the new figure where the 0's are always represented. That is a better depiction of the actual data

**Comment by KELSEYDOWLING7** [comment]
Perfect. It's too late to have this in automation for Monday so I'll just run this report manually until we're able to update. And this will be applied to this whole set of figures. (Figures 1.4-1.13)

**Comment by brotzmanmj** [comment]
Hang on, Kaitlyn just pointed out that something is not right about the graph. The weekly log shows numbers of invitations and verifications for weeks where you have 0 on this group. Can you compare?

**Comment by KELSEYDOWLING7** [comment]
Yes, got it. There was a request before to exclude outliers. There was a high jump in week 11/25 that was being excluded. Does this look more accurate?
![image](https://github.com/user-attachments/assets/8f140b5a-14d4-44b9-89c3-34457712a4f9)

**Comment by KELSEYDOWLING7** [comment]
I think only UChicago needs to have the one major outlier excluded. Here's what the plots look without outliers excluded. Please let me know your thoughts
![image](https://github.com/user-attachments/assets/4e287113-0329-4d6a-bebb-a977e30eb872)
![image](https://github.com/user-attachments/assets/5a0899de-1976-4616-8c5e-7eb8ca8a930e)
![image](https://github.com/user-attachments/assets/32ca2586-7447-450c-bcab-4e4bc7aac86f)
![image](https://github.com/user-attachments/assets/06c6dfb7-2dba-41f5-b274-42bebae84a67)
![image](https://github.com/user-attachments/assets/7c084475-30b5-46d4-81c8-c2f67142e1c9)
![image](https://github.com/user-attachments/assets/632d46e3-c727-40ee-bf8b-2d1fd8b0ead9)
![image](https://github.com/user-attachments/assets/1b5f526f-9ea8-446a-8179-26df50db833d)
![image](https://github.com/user-attachments/assets/3f6c3178-8ee8-408f-8610-b222327f574e)
![image](https://github.com/user-attachments/assets/aa5696bf-28b8-4497-8b60-d109ea57dee6)

**Comment by KELSEYDOWLING7** [comment]
I noticed in the BSW weekly logs that the first row for the week of 11/4 shows 108 invitations, 0 specimen collections and 0 baseline survey responses. The second line shows no invitations, 2 research specimen collections, and 0 baseline survey responses. The major issue is these specimen collections coming in on a separate line. Just to circle back, there's no way that that research specimen data could have been sent to us later than it was meant to be? That was what I was trying to get at earlier

**Comment by brotzmanmj** [comment]
The research specimen data doesn't get sent to us, it's just part of our data system from the start

**Comment by KELSEYDOWLING7** [comment]
Ok good to know, I'll keep investigating. Please let me know your thoughts on the outlier exclusions. At least the issue with the Figure "missing data" has been solved

**Comment by brotzmanmj** [comment]
For the BSWH figure without excluding outliers, verifications and survey+blood don't match the weekly logs for the 11/4 and 11/18. The invitation numbers now match the weekly logs. If the weekly log is incorrect, then we're not sure what 'reality' is.

**Comment by KELSEYDOWLING7** [comment]
I think that plot is off by a week. Meaning the lines should be shifted to the left one week. If we combine those two weeks for 11/4 we'd had 108 invitations, 2 survey+blood and 0 verified. That looks identical to this highlight portion. Just like the logs start at 6/24/24 but the graph lines start at 7/1/24. 

![image](https://github.com/user-attachments/assets/2f5de0fc-4bd1-4160-b5c5-12672f6c7efd)

**Comment by KELSEYDOWLING7** [comment]
The plots have been updated/corrected, though not yet pushed to production. I updated the span of the left y axis to shrink it to the actual values of the Verified and Survey+Blood counts. This way it's easier to see where those are at, and I don't have to manually exclude or redefine outliers for each site in invitations for any week. All points are shown, and in my opinion this is easier to follow/estimate. Please let me know if you have any questions of concerns. 
![image](https://github.com/user-attachments/assets/d93b17bc-e5ce-48b0-b1bc-6fb856e00b85)
![image](https://github.com/user-attachments/assets/300d824a-da3d-4664-8d78-377d3f71100e)
![image](https://github.com/user-attachments/assets/a3109f93-fcda-4bf0-8ac7-905876350000)
![image](https://github.com/user-attachments/assets/3cbb8015-f744-48dc-887c-6d0e096528d0)
![image](https://github.com/user-attachments/assets/4907e891-8583-4c92-a439-a985519a2391)
![image](https://github.com/user-attachments/assets/172ecfb8-36e8-479f-9633-fe4b0b9cac00)
![image](https://github.com/user-attachments/assets/cf49825a-a1e6-40dd-afef-93e7650725b1)
![image](https://github.com/user-attachments/assets/8b8451ef-dce2-4f8d-b085-763b4118aac6)
![image](https://github.com/user-attachments/assets/d26cd616-201e-4a59-a0e8-d8017e9bd2e6)
![image](https://github.com/user-attachments/assets/f7d7fec3-bd72-417d-b0c0-36984824bebb)

**Comment by KELSEYDOWLING7** [comment]
I'll just reupdate BSW so that the counts of 0 are as distinct as the other sites

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/user-attachments/assets/28e7b7f5-f0db-4e73-a0bd-fc98c26fe8a5)

**Comment by kmazzilli** [comment]
These look good to me and BSWH seems fixed. @robertsamm @brotzmanmj any feedback?
