### ISSUE TITLE
Bio Metric - Weekly Biospecimen Data Tables 

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#19]
To track the progress of the sites on my end in more detail, I need a Biospecimen Coordinating data table. 

This data table should be cumulative and should be generated weekly, and the data will be daily.

These data tables will be generated in addition to the recruitment, biospecimen, and boxes data excel files (no changes to these files!)and should not be added to the biospecimen weekly metrics report. 

Columns to be included in the file:

1. Date 
2. Site (If all sites can't be in the same table, one table for each site will work as well)
3. Number of Biospecimen Collections 
4. Number of Incomplete Blood Collections (Research Only) 
5. Percent Incomplete Blood Collections (Research Only)
6. Number of Blood Draw Orders Placed (Clinical Only)

- For the Site column: If all sites can't be in the same table, one table for each site will work as well, but that's a lot of tables
- "Date" Format: M/D/YY; Order from most recent to least recent and expand across row
- Incomplete Blood Collection = No Blood + Partial Blood

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Hi, if we could set up a call I think that would help clarify. Thank you!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, no problem. You'll get an invite shortly.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thank you. Mostly my question is surrounding the date. I'm thinking that each time I run the table will be for one day, and if you wanted the data over the course of the last 7 days I can run one table per weekday. I'm not sure how I would filter each row by the date, pull the data from BQ for multiple dates and split them by date

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Here are the variables for the data file columns. Also, I looked at the variables a little more, and the date/time for collection is **BioRec_CollectFinalTime_v1r0**. 

[CCC Biospecimen Data File.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10925668/CCC.Biospecimen.Data.File.pdf)

Let me know if you have any additional questions.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thanks! This helps. It looks like columns 5-11 have the filtrations but not the actual variable you want recorded. Could you add the variables that should be in those columns before the filtering needed for them?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Sure. Here you go. 

[CCC Biospecimen Table.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10933395/CCC.Biospecimen.Table.pdf)

**Comment by KELSEYDOWLING7** [comment]
[Biospecimen_Coordinating_Table 1__2023-03-17_.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/11001166/Biospecimen_Coordinating_Table.1__2023-03-17_.csv)
[Biospecimen_Coordinating_Table 2__2023-03-17_.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/11001167/Biospecimen_Coordinating_Table.2__2023-03-17_.csv)


Please let me know how these look! @HopkinsDC

**Comment by KELSEYDOWLING7** [comment]
Of course! Updated:
[Biospecimen_Coordinating_Table_Two_2023-03-27_.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/11082957/Biospecimen_Coordinating_Table_Two_2023-03-27_.csv)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7  Good Morning, Kelsey. 

In table 1, the collection date (BioRec_CollectFinalTime_v1r0) for the KP sites seems to be incorrect. The KP sites didn't start collections until Feb of this year, but the dates in the table are showing as 2022. Can you look into this? I checked the prod csv files (Connect_prod_Biospe_Formats_2023-03-27_), and the collection date seems to be correct there.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Hmm so the dates in Biq Query start 9/23/22.... I see three dates for KPGA in September of last year, and three dates for KPHI in September of last year. Is it possible they did test collections?

**Comment by KELSEYDOWLING7** [comment]
The collection date is d_556788178 right? I'm seeing 25 collections for KP sites before February of this year for that variable

**Comment by HopkinsDC** [comment]
Yes, that's the correct concept ID. Is it possible to limit the file to data in production (in case it is test data)?

**Comment by KELSEYDOWLING7** [comment]
It's definitely possible to filter out data before February, I'm just concerned because all of the data in production for KP for that variable is before February. There's 110 entries for that variable in production and only 7 are after February

**Comment by KELSEYDOWLING7** [comment]
So I'm looking at the data directly in production for d_556788178. The data in production has all but 7 entries after February 1st, and the other 103 before. So I'm not sure if maybe there's another derived variable I should be using instead?

**Comment by HopkinsDC** [comment]
Can you determine how Jing has the dates for d_556788178 in the file below (they are correct here)?

[Connect_prod_Biospe_Formats_2023-03-27_.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/11092754/Connect_prod_Biospe_Formats_2023-03-27_.csv)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  That's what I'm looking into now, comparing both tables/csv files

**Comment by brotzmanmj** [comment]
The dates in the file that Jing sent yesterday are correct

**Comment by HopkinsDC** [comment]
I'll take a closer look later today, but from a quick glance, it looks correct now.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, please add the following columns to the Biospecimen Coordinating table:

- All_Blood_Coll_Research; =1  **IF** all research blood collection tubes = 1  (d_299553921_d_593843561, d_703954371_d_593843561, d_376960806_d_593843561, d_838567176_d_593843561, d_454453939_d_593843561, d_652357376_d_593843561)
*Clinical collections can be left blank
*Add this column after _No_Blood_Coll_Research_ column

- BioFin_BaseBloodCol_v1r0; 878865966 (No=0, Yes=1)

- BioFin_BaseUrineCol_v1r0; 167958071 (No=0, Yes=1)

- BioFin_BaseMouthCol_v1r0; 684635302 (No=0, Yes=1)

Let me know if you have any questions.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC All set! Let me know how this looks
[Biospecimen_Coordinating_Table_One_2023-04-07_.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/11180861/Biospecimen_Coordinating_Table_One_2023-04-07_.csv)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 These tables have been so helpful for me! I am in the process of listing changes I'd like after working with them for a while, and I'll post them here when I'm done. 

These changes will not be urgent, and any work you have for the biospecimen metric or QC (or the many other tasks I'm sure you have) should be prioritized over this issue. Thanks!

**Comment by HopkinsDC** [comment]
I will actually keep the tables as is and close this issue. Thanks!
