### ISSUE TITLE
SFH- Accession ID discrepancies

### ISSUE THREAD

**Issue by erincschwartz** [Analyticsphere/metricsReportsRequests#191]
This week's QC report flagged the following Accession ID discrepancies, please investigate:
![Image](https://github.com/user-attachments/assets/48010f01-4484-4dcd-b6ac-ec32ede4a7c4)

There were also others that we can ignore that were flagged due to "." between IDs vs. "," and extra spaces. Please note that there is a considerable amount of work involved in cleaning up these issues, it is imperative that SFH work to ensure back end clinical collection data processes are improved to cut down on manual entry. And, if/when manual entry is needed, please emphasize to team members the importance of ensuring it is correct. Thanks!

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  I tagged myself in this, but rereading the issue it seems that maybe SF needs to be tagged in this instead?

**Comment by erincschwartz** [comment]
Added to this board in error. Deleting.
