### ISSUE TITLE
CCC Weekly Report- Opt Outs metric fix

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#20]
Jing,
On the CCC Weekly Report, if both opt out flag = Yes and Consent = Yes for a participant, consider the opt-out to be 'no' when you generate the metrics.

**Comment by jeannewu** [comment]
@brotzmanmj Thank you very much, Michelle. I have updated the table 6 and table 7 based on your comments (excluding the recruits whose opt-out=Yes, and Consent=Yes.
