### ISSUE TITLE
Bio Metric - Last Meal Time vs Mouthwash Collection Time

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#22]
Please run a _one-time_ metric comparing the time of the reported last meal and the mouthwash collection time. This metric will be for research collections only (BioSpm_Setting_v1r0; 650516960=0).

The denominator is all submitted biospecimen surveys (SrvBLM_ResSrvCompl_v1r0; 265193023 = 2).

Calculate difference between SRVBIO_EATDRINKTIME_V1R0 (191057574) and BioFin_BMTime_v1r0 (448660695) in hours, and categorize into the following:
1. 0 hrs to 3 hrs 
2. (>) 3 hrs to 12 hrs 
3. (>) 12 hrs to 24 hrs 
4. (>) 24 hrs to 48 hrs 
5. (>) 48 hrs to 72 hrs 
6. (>) 72 hrs

*Exclude records with no value for SRVBIO_EATDRINKTIME_V1R0 (191057574) or BioFin_BMTime_v1r0 (448660695).

See the mock-up of table below:
![Screenshot 2023-04-06 at 5 49 42 PM](https://user-images.githubusercontent.com/85250133/230500394-88e12ffd-0d2d-4004-97a8-63b66e7e27c2.png)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  There's only 8 participants that have data for BioFin_BMTime_v1r0 (448660695), none of which have data for SRVBIO_EATDRINKTIME_V1R0 (191057574) so I wouldn't be able to run this report just yet

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, something is wrong. There should be at least 2,397 verified participants with data for BioFin_BMTime_v1r0 (448660695), which is about how many mouthwash samples have been collected so far. Can you look into this?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  This may be an issue with the data coming in, unless maybe that's the wrong concept ID? There's only 47 instances total with any data for BioFin_BMTime_v1r0 (448660695) in Big Query and only 8 instances total with any data for SRVBIO_EATDRINKTIME_V1R0 (191057574). That is the case for all the raw data

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Yes. Just so I can explain, where is the data coming from on your end where you're seeing a total of 2,397 verified participants with data for BioFin_BMTime_v1r0 (448660695) and mouthwash samples collected?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok that's concerning.... that doesn't match the raw data we actually have. I'll have to wait until Jing returns to go over her code and see if possibly some variables are being combined

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC I apologize! I was somehow looking in DEV instead of prod; the data is matching the Data Files. However, all participants that have both SRVBIO_EATDRINKTIME_V1R0 (191057574) and BioFin_BMTime_v1r0 (448660695) answered are only from the KP sites, not the Research Sites. Do you know why that might be? 


For reference, here is this table for the Clinical Sites 
![Draw Order to Collection MW](https://user-images.githubusercontent.com/101136647/232505337-6ba5b975-b7cd-45c9-bd25-185f9e714a39.PNG)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  I apologize! I had been accidently looking at DEV instead of PROD. The data does look correct and the data files match PROD. 

However, D_191057574 is just a time variable, and does not have any date associated with it. Is there some other date I can combine with this variable to make it match the YYYY-MM-DD structure of 448660695?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, that's a relief! Thanks.

d_867307558 (SRVBIO_EATDRINKBEFORE_V1R0) indicates when they last ate or drank before the collection (0 = The same day, 1 = The day before, 2 = More than a day before). Are you able to use this to generate a date?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Here you go! I just had to remove about 23 participants that hadn't answered d_867307558 to get this to work. 

[Time-of-Last-Meal-to-MW-Collection-Time.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11254886/Time-of-Last-Meal-to-MW-Collection-Time.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, sorry for the delay. I was out unexpectedly yesterday and Tuesday. 

This looks good. Can you please change the title to "Time from Last Meal to Time of Mouthwash Collection"

@brotzmanmj Michelle, is this something you want by sites and/or added to the biospecimen metrics?

**Comment by brotzmanmj** [comment]
@HopkinsDC good question, I'm trying to remember the origin of this request... can you remind me?

**Comment by HopkinsDC** [comment]
@brotzmanmj We wanted some metrics on certain biospecimen survey topics (i.e., last meal to mouthwash collection, menstrual survey completion status, the proportion of skipped questions, etc.)

**Comment by brotzmanmj** [comment]
Thanks. Let's talk again in the biospecimen small group about the purpose and scope of the metrics and then we can decide where they should reside, and if they need to be site specific.

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 are you already running univariate frequencies on the biospecimen survey data? Checking the expected skip patterns? And missingness analysis? If so, we can review that and then think about what other metrics we would need to add, like the one above.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC here is the report updated with the new title.
[Time-of-Last-Meal-to-MW-Collection-Time.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11324334/Time-of-Last-Meal-to-MW-Collection-Time.pdf)


@brotzmanmj  For the biospecimen survey data, yes I have the code for the univariate statistics (which check the expected skip patterns) and the missingness analysis (that also follow the expected skip patterns). Here are those two reports, respectively. If you need any clarification let me know! The missingness analysis report has the number of participants that SHOULD have responded based on the skip logic on the y axis and the percentage of those that skipped ("Missing") or answered ("Present") on the bottom of each table

[Biospecimen-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11324503/Biospecimen-Survey-Summary-Statistics.pdf)

[Biospecimen-Survey-Missingness-Analysis.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11324504/Biospecimen-Survey-Missingness-Analysis.pdf)

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  It looks like some variables were missing from the flattened tables yesterday, so here are the updated Clinical and Research Biospecimen Univariate Statics and Missingness Analysis. The only major difference I saw was the significant difference in skipping month and year at time of COVID between the two; all clinical patients answered whereas about 1/3 of research participants skipped


Research:
[BUM-Bio-Research-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11347515/BUM-Bio-Research-Survey-Summary-Statistics.pdf)
[BUM-Bio-Research-Survey-Missingness-Analysis.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11347516/BUM-Bio-Research-Survey-Missingness-Analysis.pdf)


Clinical:
[BU-Biospecimen-Clinical-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11347518/BU-Biospecimen-Clinical-Survey-Summary-Statistics.pdf)
[BU-Biospecimen-Clinical-Survey-Missingness-Analysis.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11347519/BU-Biospecimen-Clinical-Survey-Missingness-Analysis.pdf)

**Comment by HopkinsDC** [comment]
@brotzmanmj For this metric (https://github.com/Analyticsphere/metricsReportsRequests/files/11324334/Time-of-Last-Meal-to-MW-Collection-Time.pdf):

1. Do we want this by site?
2. Do we want this in a metrics report? If yes, which one?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  @brotzmanmj  In case you would like to see this one by Site 
[Time-of-Last-Meal-to-MW-Collection-Time.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11615712/Time-of-Last-Meal-to-MW-Collection-Time.pdf)

**Comment by HopkinsDC** [comment]
This may be good to add this to the biospecimen survey statistics report once it's updated. Stand-by.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Add this table to the Biospecimen Suvery Summary Statistics report (as part of the edits in issue #36) below the "EATDRINKBEFORE" tables. 

This issue can be closed once complete.

**Comment by KELSEYDOWLING7** [comment]
Added
