### ISSUE TITLE
Bio Metric - Average Time Between Draw Order and Collection

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#23]
Please run descriptive statistics on the time between draw order placement time and clinical collection time in days for each KP site. Include records with a clinical collection date on or after 02/01/2023. I've included a mock-up table below.

Variables/CIDs:
- Date/Time Blood Order Placed - BioClin_BldOrderPlacdDt_v1r0 (769615780)
- Date/time Clinical Blood Collected - BioClin_ClinBloodTime_v1r0 (982213346)

![Screenshot 2023-04-13 at 11 22 26 AM](https://user-images.githubusercontent.com/85250133/231807851-a1e7b8b4-0273-418d-9556-0da7f31a3a28.png)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Please see below and let me know if you need this as just a one time metric or added to a report

[Average-Time-Between-Draw-Order-and-Collection.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11225373/Average-Time-Between-Draw-Order-and-Collection.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks great, Kelsey.

Please remove the number column on the far left, align the KP site names to the left, and add this to the biospecimen metrics report; make it Table 22 and make the "Clinical Blood Draw Order Status Among Verified Participants" Table 23.
