### ISSUE TITLE
Operations - data issue in counts for Tables 37-39 'Current Status in Workflow'

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#25]
Requestor(s): Amelia + CCC Metrics Review Group

Tables: Tables 37-39. 'Current Status in Workflow' for All Recruits, Active Recruits, and Passive Recruits

Metrics to be updated: Weekly Operations Report

Variables needed: Vars needed to show 'Never Signed-In', 'Signed-in, No Consent' and 'Profile, Verification Incomplete' statuses in recruitment workflow

- RcrtSI_SignedIn_v1r0 (230663853)
- RcrtCS_Consented_v1r0 (919254129)
- RcrtUP_Submitted_v1r0 (699625233)
- RcrtV_Verification_v1r0 (821247024) = 0 = Not yet verified (875007964)

Vars to be updated: counts in 'Never Signed-In', 'Signed-in, No Consent' and 'Profile, Verification Incomplete' statuses

Notes: Jing, there seems to be an error in the data for the 3 statuses noted above in all 3 tables for 'current status in workflow'. Each of those columns are showing all 0s when we should have at least some active recruits counted in those categories. Can you please take a look?

Approved by: Nicole

Addtl Note: Jing, please only post metrics you are currently working on to the CCC/DCEG Box folder, once update is approved then can go into ALL.

**Comment by jeannewu** [comment]
Amelia @robertsamm , thanks for your careful checking. Yes, it is the bug on the labels, just fixed with all these three tables. I will rerun the Consolidated weekly report of this week soon. Thanks a lot.

**Comment by robertsamm** [comment]
This looks good now to me as well but let's wait to close out the issue until I can review again using next Monday's report and cross-reference the SMDB from next Monday as well.

**Comment by jeannewu** [comment]
Sure. Thanks a lot.

**Comment by robertsamm** [comment]
Looks good in 5/8 report, closing issue.
