### ISSUE TITLE
Operations - update table 13 to delineate 'completes' for research vs clinical biospecimen collections

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#26]
Requestor(s): Amelia on behalf of Heather at KP

Table: Table 13. Completion of Baseline Survey and All Three Baseline Samples Among Verified Participants

Metrics to be updated or created: Weekly Operations Report

Variables needed: Vars needed to update number of completes for the KP sites only (any blood, urine, and mouthwash collected vs blood and urine collected only)

Notes: Jing, we would like to update table 13 to redefine how  'completes' are calculated for research sites vs clinical sites since the KP sites are not collecting mouthwash. This is similar to how you are defining 'completes' on the weekly log tables. 
- So for the research sites (HP, HFH, MF, SF, and UC), the definition for 'yes' would stay the same but for the four KP sites the definition for yes would be all 4 surveys + urine and blood only (no mouthwash).
- Please also update the table title to state 'Table 13. Completion of Baseline Survey and Baseline Samples Among Verified Participants'. 
- Also add a footnote that says 'Completion=yes if all 4 sections of the initial survey are completed and samples donated (for research collections: urine, mouthwash, and any blood is collected; for clinical collections: urine and any blood collected).

Approved by: Michelle + Mia

Addtl Note: Jing, please only post metrics you are currently working on to the CCC/DCEG Box folder, once update is approved then can go into ALL.

**Comment by jeannewu** [comment]
Hi, Amelia, @robertsamm, thank you very much for your clearing request. Therefore, the table 13 is updated (shown in the email just sent to you). If correct, I will update the table 13 in this week's report. Thanks

**Comment by robertsamm** [comment]
This also look awesome, no issues in the data! Is it possible to fix the spacing in the footnote after "note" and "donations"?

![image](https://user-images.githubusercontent.com/67074735/236466181-5657ea82-9bb1-47d2-88bf-4d0cfc4783f3.png)

**Comment by robertsamm** [comment]
Looks good in 5/8 report. Closing issue.
