### ISSUE TITLE
Operations - Figure 1 remove dates from x-axis

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#29]
Requestor(s): Amelia on behalf of Mia

Figure: Figure 1. Number Overall Verified & Response Rate Over Time

Metric to be updated: Weekly Operations Report

Variables needed: vars already being used in this plot to show number verified and response rate over time

Notes: In Figure 1, could you modify the x-axis so it does not contain dates in the future? For example, the latest report dated 5/1/2023 contains 5/8/2023 and 5/22/2023 on the x-axis. This looks odd to the reader.

Approved by: Mia and Michelle

Addtl Note: Jing, please only post metrics you are currently working on to the CCC/DCEG Box folder, once update is approved then can go into ALL.

**Comment by jeannewu** [comment]
Hi, Mia and Amelia, @robertsamm, 

For the updated Figure 1:(below), will you think it ok now? Thx, Jing![image](https://user-images.githubusercontent.com/99832343/236513903-d6dbe2f6-5116-466b-86cb-0cc217caf2e9.png)

**Comment by robertsamm** [comment]
Thanks Jing, this looks perfect. I think it can be updated in the report.

**Comment by jeannewu** [comment]
Hi, Amelia, I have completed the Consolidated weekly metric of this week. with all the updated tables and plots. Please check it [ ](https://nih.app.box.com/file/1208900552119) and let me know if anything is needed. thanks.

**Comment by jeannewu** [comment]
Hi, Amelia, @robertsamm, this weekly report is here:  https://nih.app.box.com/file/1208900552119

**Comment by robertsamm** [comment]
Looks good in 5/8 report. Closing issue.
