### ISSUE TITLE
Transfer running of Weekly Module Metrics from Kelsey to Madhuri

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#3]
Hi Madhuri, at Nicole’s request please look at Kelsey’s code for the [Weekly Module Metrics](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnih.app.box.com%2Ffile%2F1024420198558&data=05%7C01%7Camelia.roberts%40nih.gov%7Cef0471eb82a44ca951dc08daa2f92328%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001488163214348%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TGUUDACM%2BRgrVNhW6cSIs1UJdYqdGihWz8Ox0V433q0%3D&reserved=0) and try running it yourself but with your data. This will resolve issues with differences in denominators and redundancy in reporting. For now, we understand this means that the tables you generate would be in a separate document from your SAS report. After the R conversion, the plan is for you to incorporate these metrics into your CCC Weekly Report. Please include the counts and not just the percentages in all tables.

**Comment by mnataraj92** [comment]
Kelsey will continue to run her code with modifications from operations and I will continue running mine. Kelsey and I will compare our module #'s on a weekly basis.
