### ISSUE TITLE
Bio Metric - Time from Date Verified to Date Draw Order Placed (in Days)

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#30]
Please generate a table that shows descriptive statistics of the time (in days) from the verification date to the date of draw order placement. All records with a collection setting of "**Clinical**" should be included in this table (**d_664882224_d_650516960**). 

**Variables** (A value must be present for both variables to be included in this table):
1. RcrtV_VerificationTm_V1R0 (914594314)
2. BioClin_BldOrderPlacdDt_v1r0 (769615780)

**Include the following columns**:
1. Site
2. Number of Draw Orders Placed (This should be the total number of blood draw orders placed for the site)
3. Min
4. Q1
5. Median
6. Mean
7. SD
8. Max

- Title this new table "Time (in Days) from Verification to Draw Order Placement"
-The table format can match that of the table entitled "Time (in Days) from Draw Order Placement to Clinical Collection by Site" in the latest biospecimen metrics report (5/8/23).
- Make this new table Table 22 in the biospecimen metrics report, and make the table entitled "Time (in Days) from Draw Order Placement to Clinical Collection by Site" Table 23; Renumber all tables following this change.

**Comment by KELSEYDOWLING7** [comment]
Good morning @HopkinsDC Please let me know how this looks
![New Table 22](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c5c9accc-13ec-401b-91c3-844d54123c8a)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Good Morning, Kelsey. This looks good!

Can you further limit the denominator to participants verified on or after January 1, 2023 (Newly verified participants), since the KP sites officially launch in February 2023?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Oh, sure!  That's been updated
![New Table 22](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/31e4b196-003e-4dd5-a2b6-d4652f671d22)

**Comment by KELSEYDOWLING7** [comment]
Oh I just realized I filtered these as verified on or after 2/1/23 (when they launched). Here is verified on or after 1/1/23
![New Table 22](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9dbb93c5-cc13-4a75-b9f6-c2170b9ab1b1)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Sorry, I confirmed with Michelle that "newly verified" is 2/1/23, so the [first table](https://github.com/Analyticsphere/metricsReportsRequests/issues/30#issuecomment-1542221286) was correct. We can use that one.

Also, add a footnote stating the following: 
"Note: Time from verification to draw order placement calculated for participants verified on or after February 1, 2023."

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  
![New Table 22](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/cc32a65c-7156-4c80-8b94-632d8110f2cc)
Ok got it, added and adjusted.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks great! You can go ahead and add it to the weekly biospecimen metrics report; post the updated report here, and starting next week, it can appear in the version posted in Box.

I'll close this issue once I review the updated report here. Thanks!

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 and @HopkinsDC this metric looks great, thanks for adding it in so quickly! Michelle asks that 'Baseline' be added to the title so it would say 'Time (in Days) from Verification to Baseline Blood Draw Order Placement'.

Domonique, I believe this request may have stemmed off one of the metrics requests Heather at KPCO made right? For the metric she wanted, it was actually time from verification to baseline blood _collection_ (not draw order placement). Kelsey can you keep the one you just made above in the report and then add a second metric for this? This one should be for all sites (not just the KPs) and stratified by people verified before Feb 1, 2023 vs February 1, 2023 onward.

**Comment by HopkinsDC** [comment]
@robertsamm Thank you for clarifying this, Amelia. Not all participants will have a blood collection date/time, so we will use the collection time and limit it to the baseline visit type.

@KELSEYDOWLING7 Please see the details below. 

Variables (A value must be present for both variables to be included in this table):
- RcrtV_VerificationTm_V1R0 (914594314)
- BioRec_CollectFinalTime_v1r0 (556788178)
- Visit Type = Baseline (d_266600170_d_331584571)

Include the following columns:
1. Site (Include all sites, both KP and non-KP)
2. Number of Baseline Collections (This should be the total number of blood draw orders placed for the site)
3. Min
4. Q1
5. Median
6. Mean
7. SD
8. Max

- Title this new table "Time (in Days) from Verification to Baseline Collection"
- Make this new table **Table 22** in the biospecimen metrics report, and make the table entitled "Time (in Days) from Verification to Draw Order Placement" **Table 23**; Make "Time (in Days) from Draw Order Placement to Clinical Collection" **Table 24**; Renumber all tables following these changes.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  It doesn't seem like we have a d_266600170_d_331584571 variable. 

We have d_331584571_d_266600170_d_135591601 BioChk_Complete_v1r0, d_331584571_d_266600170_d_343048998  BioFin_CheckOutTime_v1r0 and d_331584571_d_266600170_d_840048338 BioChk_Time_v1r0

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 331584571 should be BioSpm_Visit_v1r0, with a value of 0 equaling Baseline (266600170). It's row 330 in the data dictionary.

We can't use the ones you included because those only apply to non-KP sites (research collections).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok nvm I see it in the biospecimen table in BQ as just d_331584571 with 266600170 as an answer. Sorry for the confusion

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Please let me know how this looks

![Verif to BSL Collection](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5268cfa4-c20d-4ee0-a56a-8903489d03c3)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks good. Thank you! You can add it to the biospecimen metrics report.

@robertsamm Amelia, do you know why Chicago's numbers would look like this? I'm not too familiar with the verification process.

**Comment by robertsamm** [comment]
@HopkinsDC UC has a lot of individuals who complete the entire enrollment process from consent to verification and then study activity completion at the beginning of their extended biospecimen visit. I think this would explain why their times are so much shorter than most sites.

@KELSEYDOWLING7 is this stratified by people verified before Feb 1, 2023 vs February 1, 2023 onward?

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Sorry! I did forget to stratify them. I'll have to make this into two tables then, one before 2/1/23 and one on or after

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  @HopkinsDC  Please let me know how these looks and I'll run this week's Biospecimen Metrics Report with them added


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1be31664-9352-4fdb-9f6f-0bef3bdc2e1a)


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/95569a9b-269c-47b7-b543-25f79a0d841c)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you, Kelsey! 

Please change the word "Those" to "Participants" in both titles and add a column for "Number of Verified Participants" between the Site column and the Number of Baseline Collections column.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  It looks like the Number of Verified Participants and the Number of Baseline Collections are the same for each. Does that sound right?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Oh, that's right, because the table only includes participants with both. 

You can disregard adding that column. Sorry about that! The [tables you have before](https://github.com/Analyticsphere/metricsReportsRequests/issues/30#issuecomment-1547810330) are fine. Thanks!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  No problem! I'll rerun the report and post it to Box (in the weekly metrics and ALL folders).

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 Thanks Kelsey! I agree these look great.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  @HopkinsDC Good morning! Is it ok to close this issue?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey. Can you make the "A" and "B" in the titles of these tables lowercase? After that, yes, this issue can be closed.

**Comment by KELSEYDOWLING7** [comment]
Updated and added to the weekly Biospecimen Metrics report
[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11615498/Weekly-Biospecimen-Metrics-RMD.pdf)
