### ISSUE TITLE
Bio Weekly - Incorporate Hybrid Model Metrics into Weekly Metrics Report

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#31]
This is a list of items to check in the biospecimen metrics report once the hybrid model (research and clinical collections at a single site) is launched at Henry Ford. 

- [x] **Table 5** - Add Table 5.1 below table 5 for Henry Ford. Title table "Baseline Biospecimen Collection by Collection Setting at Henry Ford Health System". Restrict this table to collections at Henry Ford.
- [x] **Table 8** - We need a way to display tubes not collected in a clinical setting for hybrid sites; Should this be a separate table?
- [x] **Table 9** - Confirm Henry Ford clinical collections show up in table (table should include all records with a collection setting of "Clinical"). Add "(5)HFH: 2 SST, 1 Heparin, 1 EDTA, 1 ACD" to footnote.
- [x] **Table 11 & 12** - In the title, change the word "KP" to "Site". Confirm Henry Ford clinical data is included in table (table should include all records with a collection setting of "Clinical").
- [x] **Table 18, 20, 22, & 23** - Confirm Henry Ford clinical data is included in table (table should include all records with a collection setting of "Clinical")
- [x] **Figure 1** - Confirm Henry Ford clinical collections show up in table (table should include all records with a collection setting of "Clinical").
- [x] **Figure 3** - Add separate trendline for clinical collections

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Hi Domonique, now that the hybrid settings have launched I've started to adjust the weekly biospec metric code accordingly. But I had some questions. 

Table 22 looks at all sites, so HF is already included in this. Is it only meant to be clinical?
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/bb0f3b96-7dd0-4e30-90f9-3dbf2f384b34)


I also have some questions on if "Hybrid" will be added to all current biospecimen specimen setting variables, but I'll ask Nicole tomorrow when I meet with her

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, Tables 22a and 22b should include clinical records only (I will be adding an issue for a separate table for research soon); with that, Henry Ford should show up when they start receiving clinical specimens.

The collection settings will remain Clinical, Research, and Home. "Hybrid" is a term that describes a site offering both clinical and research collections; Hybrid is not a collection setting type.

**Comment by KELSEYDOWLING7** [comment]
Oh ok, thank you for the clarification. I'll update 22a and 22b. 

The code is mostly set up so I'll incorporate it once we have participants that fit these requirements (where site=HF and setting=clinical)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC The one HF hybrid collection is showing! Tables 9, 11, 12, 18, 20, 22, 23 and Figure 1 have this collection accounted for. 

I am still working on Table 5.1 and Figure 3. It looks like the participant had all tubes collected, so Table 8.1 won't run for now

**Comment by KELSEYDOWLING7** [comment]
Table 8.1 is pending the Dev-Ops fix: hybrid collections  (BL_BioSpm_BloodSetting_v1r0, BL_BioSpm_UrineSetting_v1r0, BL_BioSpm_MWSetting_v1r0) are all coming up as research  



Figure 3 Now has the HF Clinical Collection included
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9064c651-3bc8-48e5-aa2c-bf9deec48404)

**Comment by KELSEYDOWLING7** [comment]
Table 10 and 24 can also be adjusted to include HF clinical participants

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  To clarify-  do you want a repeat of Table 8 but only with hybrid collections? It looks like research collections only have at SS tube 1, SS Tube2, Heparin Tube 1, EDTA Tube 1, and ACD Tube 1; hybrid collections only have  SS Tubes 2&3, Heparin Tube 2, and EDTA Tubes 2&3.  Does that sound right?




![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5a6f398f-78cd-4880-bdc1-8675abe45d9b)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 I am meeting with Michelle and Amelia to solidify the checks/changes needed for HFH clinical collections tomorrow. I will update this issue soon after that.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The following edits are based on **6/26** metrics reports

- [ ] **Table 6.7** - stratify by research and clinical setting for HFH (see mock-up below)
![Screenshot 2023-06-27 at 12 09 38 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/7e70718e-03f0-4aa1-96f9-b530dc3551e0)

- [ ] Add **Table 7.3** that shows the blood draw completeness for Henry Ford's clinical collections by the collection location (BioClin_SiteBlLocation_v1r0 -185243482)
- I have to names of the clinics, but I don't know which name goes with which location ID yet, so just use the location ID that HFH pushes to NCI, and I'll update this issue with that info. 
- The table layout should be the same as Tables 7-7.2. 
- Title this table "Blood Completeness among Henry Ford Baseline Clinical Collections by Clinic Location"

- [x] Remove **Table 8.1** (not the best we to show these data)

- [ ] **Table 9** - Add a "1-4" column between the "0" and the "5" columns. The "1-4" column should be a _cumulative_ count of blood draws with only 1 to 4 blood tubes collected. 

- [ ] **Figure 3.1** - Remove "Hybrid" trend line (already included in figure 3 as the clinical trend line)

**Comment by HopkinsDC** [comment]
> @KELSEYDOWLING7 The following edits are based on **6/26** metrics reports
> 
> * [ ]  **Table 6.7** - stratify by research and clinical setting for HFH (see mock-up below)
>   ![Screenshot 2023-06-27 at 12 09 38 PM](https://user-images.githubusercontent.com/85250133/249218907-7e70718e-03f0-4aa1-96f9-b530dc3551e0.png)
> * [ ]  Add **Table 7.3** that shows the blood draw completeness for Henry Ford's clinical collections by the collection location (BioClin_SiteBlLocation_v1r0 -185243482)
> * I have to names of the clinics, but I don't know which name goes with which location ID yet, so just use the location ID that HFH pushes to NCI, and I'll update this issue with that info.
> * The table layout should be the same as Tables 7-7.2.
> * Title this table "Blood Completeness among Henry Ford Baseline Clinical Collections by Clinic Location"
> * [x]  Remove **Table 8.1** (not the best we to show these data)
> * [x]  **Table 9** - Add a "1-4" column between the "0" and the "5" columns. The "1-4" column should be a _cumulative_ count of blood draws with only 1 to 4 blood tubes collected.
> * [x]  **Figure 3.1** - Remove "Hybrid" trend line (already included in figure 3 as the clinical trend line)

@KELSEYDOWLING7 As a follow up, below are HFH's clinic location names and corresponding IDs:

1. 1050010095 = HF Wyandotte Hospital
2. 1060010063 = HF Macomb Medical Pavilion
3. 1040010047 = HF West Bloomfield Hospital

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

For Table 6.7 how do you want to show those that have no collections? Since they won't fall into either research or clinical

Table 7.3 is set up, but we need more blood draws to run it. Right now all blood draws are complete so it's messing up the structure of the table and throwing error messages

Right now for table 9, the number of blood draws (for clinical sites) are only showing as 0,5,6,7,8,9,10. There doesn't seem to be any with 1-4

**Comment by HopkinsDC** [comment]
Closing this issue to transitioning to metrics modification template format.
