### ISSUE TITLE
Operations - new metric for all combinations of study activity completion

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#32]
Requestor: Amelia and Michelle

Report: Weekly Operations Report

New table: 'Baseline Study Activity Completion Among Verified Participants by Sample Donation and Initial Survey Completion'

Num/Denominator: percentages should be cell percents.

Table mock-up:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ROBERT~1/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ROBERT~1/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

  | No Samples | Blood only | Urine only | Mouthwash only | Blood and Urine | Blood and   Mouthwash | Urine and   Mouthwash | All 3 Sample   Donations | Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
No Survey   Sections | N (%) |   |   |   |   |   |   |   |  
BOH only |   |   |   |   |   |   |   |   |  
BOH and LAW |   |   |   |   |   |   |   |   |  
BOH and MRE |   |   |   |   |   |   |   |   |  
BOH and SAS |   |   |   |   |   |   |   |   |  
BOH, MRE, and   LAW |   |   |   |   |   |   |   |   |  
BOH, MRE, and   SAS |   |   |   |   |   |   |   |   |  
BOH, SAS, and   LAW |   |   |   |   |   |   |   |   |  
All 4 Survey   Sections |   |   |   |   |   |   |   |   |  
Total |   |   |   |   |   |   |   |   |  

</body>

</html>

Footnote: In order of how the survey sections appear on MyConnect; BOH=Background and Overall Health (Module 1), LAW=Where You Live and Work (Module 4), MRE=Medications, Reproductive Health, Exercise, and Sleep (Module 2), and SAS=Smoking, Alcohol, and Sun Exposure (Module 3)

Notes: Hi Jing, can you please add a new table to the report that looks at all the possible combinations of baseline initial survey and biospecimen donation completion? I've mocked up a table above of what this should look like. In the row labels you can just use the survey module acronyms (e.g. BOH, MRE, etc) but can you add a footer under the table that defines the module acronyms? See the mock up above. Please let me know if you have questions! This isn't urgent so if you can't start it until next week that's definitely fine (you do not need to work on this over the weekend). 

Approved by: Michelle

**Comment by jeannewu** [comment]
Hi, Amelia @robertsamm, Thank you very much for assigning this work for me. So the observations in this table should be overall verified participants without stratified by site, right? and the percentage (N %) will be the %  of overall participants with any biospecimen collections or survey completions, right?  Thanks a lot. Jing

**Comment by robertsamm** [comment]
Hi @jeannewu Great questions. Sorry I forgot to clarify! There should be one table that is overall sites and then separate tables for each site (having them stratified by site will prob be too complicated). The % denominator should be out of all verified participants and then I think to capture the people who didn't donate samples or complete any surveys there should be a column and row added for 'none' - thanks for thinking of this! I'll try and see if I can update the table above.

**Comment by robertsamm** [comment]
@jeannewu Hi Jing, I just edited the table above. Let me know if you have any other questions! Until these tables are finalized and approved, can you keep them out of next week's operations report?

**Comment by jeannewu** [comment]
Hi, Amelia @robertsamm, Great. Yes, I will work on this set of tables till it is complete and approved for the operation report in future (not in the next week report, right?).

**Comment by robertsamm** [comment]
@jeannewu Hi Jing, yes that's right. It won't be ready in time for next week's report which is fine. Let's keep it separated out for now so that you run next week's report as normal. And since it's already so late in the day it's ok if you don't start these tables until next week.

**Comment by jeannewu** [comment]
Got it. Thanks, Amelia. @robertsamm

**Comment by jeannewu** [comment]
Hi, Amelia @robertsamm, just a quick question on this set of new tables, we have a similar set of biospecimen and survey completion tables in the Consolidated weekly metrics (Table 14-23), and now as requested, I am going to create another set of these tables with more details. So what should I do with these two sets of similar tables in the metrics?

**Comment by jeannewu** [comment]
Hi, Amelia, I have just create this set of tables shown in Table 52-61 with the recruitment data last week (sent via team). Please check them and let me know if anything is needed.

**Comment by robertsamm** [comment]
@jeannewu Hi Jing, I reviewed these new tables and they look great! Only minor feedback below:
1. Is it possible to add percents to the 'total verified participants' column on the right as well? Where it would be out of all verified participants? If you aren't able to, then let's take out the percentages in the 'total verified participants' row at the bottom. 
2. Can you update the footnotes to the order I specified? Module 4 actually comes 2nd now in the app, as they swapped the order in which it is displayed (but didn't change the module names). So it should say 'In order of how the survey sections appear on MyConnect; BOH=Background and Overall Health (Module 1), LAW=Where You Live and Work (Module 4), MRE=Medications, Reproductive Health, Exercise, and Sleep (Module 2), and SAS=Smoking, Alcohol, and Sun Exposure (Module 3).'
3. In the footer as well, can you fix the spacing in front of 'Mouthwash collection is not yet available at KP sites.'. Also please change it to 'at clinical sites' instead of just KP. That way you won't have to update this footer in the future when HFH launches their hybrid clinical collections.
4. Unfortunately, we'll need to change where these tables go in the report. Can you put them after table 23? I'm sorry, I know that means you'll have to renumber the other tables.

**Comment by jeannewu** [comment]
@robertsamm Hi, Amelia, thank you very much for your helpful comments.  This set of tables are created for overall verified participants and participants among each site.

- for your first comment, may you please let me know which table you would like to add the percents to the 'total verified participants' column on the right, the table for overall participants, all the table of each site?
- I will update the foot note as what you describe here and add this set of tables after Table 23 in the next report, right if they are approved?

**Comment by robertsamm** [comment]
Hi Jing @jeannewu, can you add the percents to the 'total verified participants' column to both the overall table and the site tables? And yes that's correct.

**Comment by jeannewu** [comment]
Hi, Amelia @robertsamm , I have updated the new set of biospecimen collection and survey completion tables with your comments. Please check them T24-T33 (sent via team). Please let me know if anything is needed. Thanks a lot. Jing

**Comment by robertsamm** [comment]
Hi @jeannewu thanks for making these updates! Can you check how the site-specific tables are being calculated for the percentages? They should be out of the number of all verified participants at that _site_, not all verified participants in the overall table.

For example: For HPs 'All 4 surveys x all 3 specimens', the count=804 which is correct. But the percent should be 53.42% (804/1505). This is just one example, please update all cells for each of the site tables.
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/223c03b7-c595-46a7-b845-ae9b1fe65b0c)

**Comment by jeannewu** [comment]
Hi, Amelia, all the percentage of each cell is n/the overall verified participants n=8819 (shown in Table 24) as requested. Will you think it correct? Or I misunderstood your comments?

**Comment by robertsamm** [comment]
Hi Jean, the overall table should be overall verified participants which is correct. Each site table should be total verified participants at that site. Does that make sense?

**Comment by jeannewu** [comment]
Hi, Amelia @robertsamm, I will update the tables by site with their own verified participants as the denominators. Thanks a lot.

**Comment by jeannewu** [comment]
Hi, Amelia, I have updated the T24-T33 with the denominators as their own overall participants. The updated pdf file is sent via team. Please check it and let me know if anything is needed. Thanks

**Comment by robertsamm** [comment]
Hi @jeannewu, thanks for making this update. These look perfect! You can add this to the finalized Weekly Operations Report and run it on Monday. When you run it on Monday please let me know when you copy it to ALL folder so I can update the study managers on the new metrics. No need to copy it to ALL this week.

**Comment by jeannewu** [comment]
Got it. I will integrate this set of new tables into the next week report and let you know when I put it in ALL folder next Monday. Thanks, Amelia @robertsamm
