### ISSUE TITLE
Bio Metric - Menstrual Cycle Survey Follow-Up (KP Sites)

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#33]
@KELSEYDOWLING7 We want to follow up on the menstrual cycle survey metric in issue #21 to reassess the code for determining the response ratios for the KP sites. Can you review this again to see if the KP sites are still returning zeros?

**Comment by KELSEYDOWLING7** [comment]
Hi @HopkinsDC yes these are now populating. I forgot that the concept ID for SrvBlU_MENST60_v1r0 is the same for both the clinical and research surveys. Please see the updated tables 
[Menstral-Cycle-Survey-Response-Rate.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11547604/Menstral-Cycle-Survey-Response-Rate.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you for taking a second look at this. Please move the "Total Eligible" column between the "Site" column and the "Not Started" column. 

This issue can be closed after this edit.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Good morning, please let me know how this updated version looks
[Menstral-Cycle-Survey-Response-Rate.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11600246/Menstral-Cycle-Survey-Response-Rate.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks good. Thanks! Please update the Weekly Module Metrics table with this version (Table 8).
