### ISSUE TITLE
Bio Weekly - Research Only: Time from Verified to Baseline Collection

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#34]
Please generate two tables (a and b) for time from verification (**a=verified before 8/1/2022, b=verified on or after 8/1/2022**) to baseline collection for all research collections. 

These tables should have the same formatting and columns as [Tables 22a and 22b](https://github.com/Analyticsphere/metricsReportsRequests/issues/31#issuecomment-1581233013).

Variables:
- BioSpm_Setting_v1r0 (650516960) = Research (534621077)
- RcrtV_VerificationTm_V1R0 (914594314)
- BioRec_CollectFinalTime_v1r0 (556788178)

**Comment by brotzmanmj** [comment]
Domonique, are you also saying the existing tables 22a and 22b will be restricted to clinical collections? So there will be four tables instead of 2? We will need to titles to be updated to include Research Collections and Clinical Collections respectively

**Comment by HopkinsDC** [comment]
> Domonique, are you also saying the existing tables 22a and 22b will be restricted to clinical collections? So there will be four tables instead of 2? We will need to titles to be updated to include Research Collections and Clinical Collections respectively

Yes, I asked Kelsey to restrict the current Tables 22a and 22b to clinical only [HERE](https://github.com/Analyticsphere/metricsReportsRequests/issues/31#issuecomment-1581331193). The table titles and numbering will be undated accordingly.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Please see the attachment for the current version of Table 22a-22d and see the following edits. Thanks!

[Weekly-Biospecimen-Metrics-RMD_06_12_23.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11761880/Weekly-Biospecimen-Metrics-RMD_06_12_23.pdf)

1) Switch table order to have research tables first and the clinical tables second.
2) Renumber the research tables to be Table 22a and 22b.
3) Switch to the words "Baseline" and "Research" in the title; should be "Research Baseline Collection"
4) Renumber clinical tables to be Table 23a and 23b.
5) Switch to words "Baseline" and "Clinical" in the title; should be "Clinical Baseline Collection".
6) Remove duplicate "Verified" in title of first research table.
7) *See [issue #35](https://github.com/Analyticsphere/metricsReportsRequests/issues/35) and number that table Table 24 when done.
8) Renumber all tables following the changes above.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Aside from #35 , please let me know how this looks with the requested edits


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6062db06-eece-4130-a42a-79e68954e949)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 For the research tables, the date should be 8/1/2022 (the clinical tables are 2/1/2023), and add the following footnote to research tables: "Note: August 2022 marks when research collection appointments were routinely offered to all new recruits at or near the time of verification." 

And remember to renumber the clinical tables 23a and 23b once #35 is added.

Everything else looks good.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC All set! Since issue 35 will create the new table 24, wouldn't these stay 22?


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/344b0f1d-ca9f-4976-b552-ed4af487fb6a)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The numbering pictured above can stay the same for now, but when #35 is finished and added, Tables 22a and 22b (research) will stay the same, Tables 22c and 22d (clinical) will become Tables 23a and 23b, and then #35 will be Table 24.

Does that make sense?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ah! I see. Yes, ok that's been updated



![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/66824b28-55fd-47e7-9b75-f14b76f35d56)

**Comment by HopkinsDC** [comment]
Tables updated in the weekly metrics report successfully.  This issue is complete.
