### ISSUE TITLE
Bio Weekly - Verification (on or after 6/1/2022) to Baseline Collection by Campaign Type

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#35]
Generate a table that shows time (in days) from verification to baseline collection for all participants (clinical and research) verified on or after 06/01/2022 by campaign type (RcrtSI_CampaignType_v1r0 (667474224)). See mock-up below.

Group "Screening Appointment" (348281054) and "Non-screening Appointment" (324692899) campaign types into one category (named "Upcoming Appointment") and group all of the other campaign types into another category (named "All Other Campaigns"). 

- Leave the "Q1" column out of this table 
- Add a "Total Number of Baseline Collections" column to the end of the table.
- Add the following footnote: "Note: _Upcoming Appointment_ includes “Screening appointment” and “Non-screening appointment” campaign types. _All Other Campaigns_ include “Random”, “Demographic Group”, “Aging out of study”, “Geographic group”, “Post-Screening Selection”, “Technology adapters”, “Low-income/health professional shortage areas”, and “Other” campaign types."
- Title this table _**Time (in Days) from Verification on or After 6/1/2022 to Baseline Collection by Campaign Type**_
- Add this table to weekly Biospecimen Metrics report as **Table 24**.

**NOTE: Mock-up only shows KP sites, but the table should list all sites (include both research and clinical collections in the table)**
![Screenshot 2023-06-12 at 11 14 53 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/a986eb4e-7017-43e8-8d53-9d1c1413b0e9)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Good morning, I'm still tweaking the code but it looks like Sanford Health and Marshfield don't have any upcoming appointment types, which is causing several errors in the code. Does that sounds right? Or might there be more filters we need to add?


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d54ba579-df66-46a1-8055-d01e3d9ed0de)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Not all sites are doing appointment-based campaigns, so Sanford and Marshfield are correct.

All active recruits (CID 486306141) are assigned a campaign type when they are invited. All passive recruits (CID 854703046) are assigned a campaign type only when they are verified; They are always defaulted to "none of the above" because they weren't invited as part of any campaign (this would put them in the "All Other Campaigns" for this table). Is there a reason why the total number of collections is so low for each site since all participants have a campaign type?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thank you for the clarification! You had asked for these to be all participants verified after 6/1/23, just two weeks ago. Should that date be changed?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 OH! Haha, that's supposed to be 6/1/22. Sorry about that!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ah! Ok that makes much more sense. and there's much more data. Unfortunately the NA's in the Upcoming appointment are causing a lot of problems in creating the Number of Baseline Collection columns.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hm, interesting. Try excluding Sanford and Marshfield from this table since they don't do appointment-based campaigns. We may have to add that they are excluded in the footnote.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  That doesn't seem to help either. It Looks like HP is in the same boat too, but even if I remove that as well I'm getting error messages. I have this for now, which I can add the report for Monday, and I'll continue to work on adding those columns back.


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c535a9bd-fc61-4eb4-9796-d91e0af94c73)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, but change the year in the title to 2022 too, and add the footnote before adding to the report.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Finally got it to work!



![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/eb95c65c-092d-4885-af22-51f837aeb1a1)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thanks, Kelsey! Please reorder rows to list non-KP sites first and then KP sites (matching the order in the other tables in the report) and I'll close this issue once you confirm that is done.

**Comment by KELSEYDOWLING7** [comment]
@KELSEYDOWLING7  All set!


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/023fabdf-4400-4455-8eb5-598e03efdf89)
