### ISSUE TITLE
Bio Surveys - Summary Statistics Report Edits

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#36]
Please see the PDF below with comments for edits from the biospecimen team. 
[2.0_EDITS_BUM-Bio-Research-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11826805/2.0_EDITS_BUM-Bio-Research-Survey-Summary-Statistics.pdf)

The changes made to the time-sensitive tables (see PDF below) should also be incorporated into the summary report as well.
[Statistical-Significance-of-BU-vs-BUM-Missingness.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11826839/Statistical-Significance-of-BU-vs-BUM-Missingness.pdf)

Edits should be made to BUM and BU survey summaries, and to the COVID questions (wherever applicable) in each.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC The note about the select all questions was cut off. I can only see SYMPTDAY, PREMITTHLOST, HEIGINE. The only other one I could find was COV8.

For now I'll add a "multiple answers selected" row like we talked about last week so for now you'll have a better report to use. I'll have all the combos in there by the end of the week 


[BU-Biospecimen-Clinical-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11872434/BU-Biospecimen-Clinical-Survey-Summary-Statistics.pdf)
[BUM-Bio-Research-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11872435/BUM-Bio-Research-Survey-Summary-Statistics.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Sorry for the delay! "HYGIENE" is the end of the note, but yes, please apply to COV8 if applicable.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  No problem! Ya that was a huge typo here but it's correct on the report. COV8 is also on both reports. Please let me know how they look and I'll work on adding the combinations

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Please see the doc below for additional edit comments. Thanks!

[3.0_EDITS_BUM-Bio-Research-Survey-Summary.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11882693/3.0_EDITS_BUM-Bio-Research-Survey-Summary.pdf)

**Comment by HopkinsDC** [comment]
> @KELSEYDOWLING7 Please see the doc below for additional edit comments. Thanks!
> 
> [3.0_EDITS_BUM-Bio-Research-Survey-Summary.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11882693/3.0_EDITS_BUM-Bio-Research-Survey-Summary.pdf)

All edits should be to both the BUM and BU survey summaries.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  I'm assuming you still want to know what variable you're looking at in the Title Right? For example, "SEX: Biological Sex assigned at birth" changed to "Table 1: SEX"?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 We don't need that variable since the rest of the title is pretty clear. This may be an issue for the "Medications" tables though, so for those, replace the word "Medication" in the title with the medication name.

Ex. TYLENOL: Medication Taken, if so, Last Time Taken => **Tylenol Taken & Last Time Taken**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  I'm not quite sure what to conclude from this, but this is the updated Statistical Significance without UC and stratified
[Statistical-Significance-of-BU-vs-BUM-Missingness.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11900145/Statistical-Significance-of-BU-vs-BUM-Missingness.pdf)
 by completion within 12 hours and after 12 hours

**Comment by KELSEYDOWLING7** [comment]
The COVID table rows still need to be finished, but other than that, these should have the remaining listed 
issues resolved. 



[BUM-Bio-Research-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11910460/BUM-Bio-Research-Survey-Summary-Statistics.pdf)


[BU-Test.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11910524/BU-Test.pdf)

**Comment by HopkinsDC** [comment]
> @HopkinsDC I'm not quite sure what to conclude from this, but this is the updated Statistical Significance without UC and stratified
> [Statistical-Significance-of-BU-vs-BUM-Missingness.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11900145/Statistical-Significance-of-BU-vs-BUM-Missingness.pdf)
> by completion within 12 hours and after 12 hours

@KELSEYDOWLING7 When you return the week of 7/11, please rerun the missingness significance, once with UChicago removed but without the 12hr stratification, and then again stratified by completion within 12 hours and after 12 hours but with Uchicago included (i.e., separate these restrictions). Thanks!

**Comment by HopkinsDC** [comment]
> The COVID table rows still need to be finished, but other than that, these should have the remaining listed issues resolved.
> 
> [BUM-Bio-Research-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11910460/BUM-Bio-Research-Survey-Summary-Statistics.pdf)
> 
> [BU-Test.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11910524/BU-Test.pdf)

@KELSEYDOWLING7 Looks great! When you return the week of 7/11, please review the calculations for SLEEPTIME and WAKETIME tables and send the raw response data for these two survey questions. Thanks!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  I think you meant rerun the significance once with UC removed but with stratification and once with UC included but without stratification. 

Here is with the stratification, but without UC



[Statistical-Significance-of-BU-vs-BUM-Missingness.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/12003347/Statistical-Significance-of-BU-vs-BUM-Missingness.pdf)

**Comment by KELSEYDOWLING7** [comment]
Here is with UC but without stratification


[Retest-Significance-without-Time-Stratification-of-BU-vs-BUM.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/12003401/Retest-Significance-without-Time-Stratification-of-BU-vs-BUM.pdf)

**Comment by KELSEYDOWLING7** [comment]
Here is the raw data for SLEEPTIME and WAKETIME for the clinical and research surveys. 

(I only extracted the version 2 of these variables to avoid confusion, as clinical only has version 2 SLEEPTIME and WAKETIME variables. Only version 2 of these variables are on the reports above as well)


[Research_SLEEPTIME_WAKETIME_2023-07-10_.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/12003516/Research_SLEEPTIME_WAKETIME_2023-07-10_.csv)
[Clinical_SLEEPTIME_WAKETIME_2023-07-10_.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/12003517/Clinical_SLEEPTIME_WAKETIME_2023-07-10_.csv)

**Comment by HopkinsDC** [comment]
Closing this issue to transitioning to metrics modification template format.
