### ISSUE TITLE
Hybrid Metric -  Stratify Collection Completeness by Collection Setting for Henry Ford

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#37]
NOTE: Issue is a continuation of #31. 

**Requestor(s):** Biospecimen Team

**Table or Figure title:** Baseline Biospecimen Collection Completeness, Henry Ford Health System

**Metrics to be updated or created:** Update table to include all verified participants stratified by collection setting (research and clinical)

**Variables needed (include variable name and Concept ID):** 
- Verification status (821247024 = 1)
- Finalized Collection (410912345 = 1)
- Research Setting (650516960 = 0)
- Clinical Setting (650516960 = 1) 

**Specify numerator and denominator by variable name where applicable:**
- Denominator = Verified status (821247024 = 1)

**Mock-up table if applicable:**

![Picture1](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/a705ddfc-0eb0-4148-b113-5942255ca969)

**Notes:** 
- Table should exclude verified participants with no complete collection.
- Add footnote: _"Mouthwash Collected" does not apply to clinical collections; mouthwash is not collected in a clinical setting._

**Approved by:** Biospecimen Team

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  (just bringing this question over from #31) how do you want to show those that have no collections? Since they won't fall into either research or clinical

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Please exclude verified participants with no complete collection. I put it under Notes, but should have made it a separate comment like I did for the other issue. Sorry about that.

**Comment by KELSEYDOWLING7** [comment]
Oh! Thank you, sorry I missed that

**Comment by KELSEYDOWLING7** [comment]
Since Clinical collections won't have any mouthwash collections, no rows with "Yes" under Mouthwash will be created. There's also as of now no participants with ONLY blood or urine collected. So essentially clinical only has one row, making the tables very hard to line up next to each other in a legible way. Would you/the biospecimen team be open to this being split into a 6.7a and 6.7b table for clinical and research? It is MUCH simpler to run that code


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/be643133-94e8-48b8-a7fd-a50b740ed802)

**Comment by KELSEYDOWLING7** [comment]
Otherwise it ends up looking like this (since participants with no collections were removed) which I don't think is as interpretable

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/64a2e0bb-9579-4419-bb45-c877ced564a3)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, I think it'll be best to restructure the collection completeness tables. 

Tables 6 through 6.9 (in biospecimen metrics report) can be condensed into two tables; the first being **Table 6a: Baseline Research Collection Completeness by Site** and the second being **Table 6b: Baseline Clinical Collection Completeness by Site**. See the mock-ups below.

The denominator is verified participants with a finalized collection. Table 6a should be restricted to the research setting, and Table 6b to the clinical setting. 

![Screenshot 2023-07-13 at 11 42 59 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/b0bdeaa1-51a0-4122-a81a-3fef74b0688c)


![Screenshot 2023-07-13 at 11 43 20 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/735daa8d-da26-480a-b1e2-dadd28c5f5d5)


Correct me if I'm wrong, but if the tables are restructured to the tables pictured above, both tables should automatically update to include additional sites as they come on (e.g., HealthPartners and Sanford will eventually be hybrid (have both research and clinical collections)).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Oh this is great! Yes the clinical will automatically update as we get more hybrid sites


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c53a1306-0fea-4ffd-bf95-757e6a9bf335)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Awesome! So KP sites will never have research collections; can they be excluded from Table 6a? And for Table 6b, can the sites with no clinical collections be hidden until that have values? (trying to same some page space).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Yes, sorry wrong one copied

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5ab0f838-0bff-44af-af0f-77d28228f183)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, good. A few more edits:
- make all the percentages 1 decimal place
- make the "B" in the Table title lowercase
- reorder the table rows to match the order in the mock-ups above
- add "Only" to the end of the "Blood & Mouthwash" and "Urine & Mouthwash" row titles in Table 6a.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/2f85d882-153d-494b-be91-524bf1e23c0e)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Perfect! Please replace the existing Tables 6-6.9 with these two tables in the next weekly biospecimen report (7/17).
