### ISSUE TITLE
Hybrid Metric - Clinical Blood Draw Completeness for Henry Ford

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#38]
NOTE: Issue is a continuation of #31. 

**Requestor(s):** Biospecimen Team

**Table or Figure title:** Baseline Clinical Blood Draw Completeness by Collection Location, Henry Ford Health System

**Metrics to be updated or created:** Create new table for this metric.

**Variables needed (include variable name and Concept ID):** 
- Verification status (821247024 = 1)
- Finalized Collection (410912345 = 1)
- Clinical Setting (650516960 = 1) 
- Clinical Location ID (185243482)
>- 1050010095 = HF Wyandotte Hospital
>- 1060010063 = HF Macomb Medical Pavilion
>- 1040010047 = HF West Bloomfield Hospital

**Specify numerator and denominator by variable name where applicable:**
- Denominator = Verified status (821247024 = 1)

**Mock-up table if applicable:**
- Table layout should match that of tables 7, 7.1, & 7.2, in the weekly biospecimen metrics report (posted on 7/10)

**Notes:** 
- Table should exclude verified participants with no complete collection.

**Approved by:** Biospecimen Team

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 In reference to [your comment](https://github.com/Analyticsphere/metricsReportsRequests/issues/31#issuecomment-1629593262) in #31, can you post what the table looks like currently?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC The final version of the tabel can't be run yet but this is what it looks like for now. All blood tubes are showing as collected


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/54518444-0cea-4222-aacd-ceae826cdd61)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 I'm a little confused about why it can't be run. Wouldn't the "Partial Blood" and "No Blood" columns be zeroed out for number and percent if all the draws are complete? So it should look like Table 7.1 (screenshot below) but with zeros for the partial blood and no blood columns and the totals for the locations (3 and 5) in the far right column.

![Screenshot 2023-07-12 at 10 16 19 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/c4d9fce6-3dc2-41c8-ab4c-2f671f8e8db4)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Sorry, I should've specified. It can run like that if I recode it, but just not the way it's coded now. I'd have to put a different code in place for now the way it is, put in placeholders for the partial and no bloods of all 0's, then keep checking on it until we have partial and no blood collections to revert back to the original code. I can start working on that

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/93497ac7-3f30-4e14-bd1b-4d34236f506c)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This table looks good. Please add to the next weekly biospecimen report (7/17).

I'll keep an eye on HF's clinical collections for incomplete blood collections and will open a new issue when this table needs to be recoded (or will you automatically know when this happens?).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Great! I think the new code will break once we have incomplete collections, but just in case if you could let me know that would be great

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Will do! Thanks.
