### ISSUE TITLE
Update calculcation for "completes" in Operations Report and Weekly Logs

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#39]
**Requestor(s):** Amelia Roberts, on behalf of Mia and Michelle

**Table or Figure title:** 
Operations Report:
(1) Figure 3: Total Expected Recruits vs Actual Verified Recruitments vs. Numbers of Blood Collections 
(2) Table 13. Completion of Baseline Survey and Baseline Samples Among Verified Participants.
Weekly Log/Connect Totals by Week Reports for All Sites and Individual Sites:
(3) Cumulative Completed All Participant Study Activities
(4) Completed All Participant Study Activity Response Ratio among Invited = Completed All Activities/ Invited
(5) Completed All Participant Study Activity Response Ratio among Verified = Completed All Activities/ Verified
(6) Completed all Participant Study Activities per week

**Variables needed (include variable name and Concept ID):**
Blood: BioFin_BaseBloodCol_v1r0 (CID 878865966)
AND
Initial Survey: SMMet_BaseSrvCompl_v1r0 (CID 100767870) 

**Notes:**
Hello Jing, we would like to change how we are calculating and defining "completes" for all sites. Before, we were defining "completes" where KP sites=initial survey + blood and urine donation only and all research sites =initial survey + blood, urine and mouthwash donation. To simplify and standardize the definition across all sites, we would like to change this definition to just be complete=initial survey + blood only. Urine and mouthwash will _not_ be taken into consideration at all anymore. This will require changes to the metrics noted above, two metrics in the Operations Report and then multiple metrics in the Weekly Logs (also called the Connect Totals by Week). I have included the two variables that should be used to define completes above. 

Addtl Changes:
(1) In Figure 3, this will affect the pink calculation. Can you also rename the label from 'Initial Srv+Samples' to 'Initial Srv+Blood'?
(2) In Table 13, can you also change the footnote to state: "Completion=yes if all 4 sections of the initial survey are completed and blood is collected."
For the Weekly Log metrics that I noted above, all 4 metrics (numbers 3-6) will also need relabeling. Can you change it to 'Completed BL Survey+Blood'. See below.
(3) Cumulative Completed BL Survey+Blood
(4) Completed BL Survey+Blood Response Ratio among Invited = Completed BL Survey+Blood/ Invited
(5) Completed BL Survey+Blood Response Ratio among Verified = Completed BL Survey+Blood/ Verified
(6) Completed BL Survey+Blood per week

Please let me know if you have any questions and when you are ready for me to review. Please do not post these updates into the ALL folder until reviewed and approved by the CCC.

**Approved by:** Michelle Brotzman

**Comment by jeannewu** [comment]
@robertsamm, So in this way, the blood collection is only counted for the completion of biospecimen in the Fig3 and table 13 and the weekly log, right? Yes, I will update them soon. Thanks a lot.

**Comment by robertsamm** [comment]
@jeannewu Hi Jing, yes blood but also the initial survey, but no other specimens.

**Comment by robertsamm** [comment]
All of these metric updates have been completed and looks good.
