### ISSUE TITLE
Bio Survey Summary - 1 Decimal Place for Percentages

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#40]
Please make all percentages in the biospecimen Suvery Summary Statistics have 1 decimal place.

**Requestor(s):** Bio Team

**Table or Figure title:** All tables in summary with percentages

**Metrics to be updated or created:** Update

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  The new reports been updated with this request and #41  with the first two tables swapped


[BUM-Bio-Research-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/12043507/BUM-Bio-Research-Survey-Summary-Statistics.pdf)
[BU-Test.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/12043508/BU-Test.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Just a few more edits:
- Add "Table 4:" to the table title "Time from Last Meal to Time of Mouthwash Collection" in BU summary
- Reverse the row order of Table 4: Time from Last Meal to Time of Mouthwash Collection in BU summary to match that in BUM summary
-  Remove the "Statistical Significance of BU vs BU Missingness" from both summaries (that was just from the bio team's review)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  All set!

[BUM-Bio-Research-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/12069374/BUM-Bio-Research-Survey-Summary-Statistics.pdf)
[BU-Test.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/12069376/BU-Test.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7  Great! The BU summary looks good. 

For the BUM summary, can you move the "Mouthwash Data Collection" section to be between the "Reproductive Health" and "COVID-19" sections?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Yup, all set

[BUM-Bio-Research-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/12069751/BUM-Bio-Research-Survey-Summary-Statistics.pdf)

**Comment by HopkinsDC** [comment]
> @HopkinsDC Yup, all set
> 
> [BUM-Bio-Research-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/12069751/BUM-Bio-Research-Survey-Summary-Statistics.pdf)

Can you also renumber the "Mouthwash Data Collection" & "COVID-19" tables (not urgent at all)? Once the table number is corrected, I will close this issue. Thank you!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Oops, almost forgot. Here you go 

[BUM-Bio-Research-Survey-Summary-Statistics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/12070787/BUM-Bio-Research-Survey-Summary-Statistics.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thanks! I'm closing this issue, but this there a reason Plot 16 (pg. 33) is blank?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Also, you can start running and uploading summaries to the [Biospecimen (BU and BUM surveys) Box folder](https://nih.app.box.com/folder/208060008158) monthly. I moved the existing files to the "_OLD" folder so we know when the updated version was implemented.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  It just means no one's answered that question yet, so the code just automatically creates a blank plot. And yes! Can do. How often do you want them updated/uploaded?

**Comment by HopkinsDC** [comment]
> @HopkinsDC It just means no one's answered that question yet, so the code just automatically creates a blank plot. And yes! Can do. How often do you want them updated/uploaded?

You can add the summaries from today and then upload them every month starting in August.
