### ISSUE TITLE
Operations - update Figure 1 y-axis

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#42]
Requestor(s): Amelia on behalf of Mia

**Table or Figure title**: Number Overall Verified & Response Rate Over Time

**Metrics to be updated or created**: Operations Report

**Notes:**
Please update the y-axis on the right. The y-axis maximum for the "Cumulative Response Rate" should be 10 (not 20). 
Please also update the title of this y-axis to "Cumulative Response Proportion".

**Approved by:** Mia Gaudet

**Comment by jeannewu** [comment]
@robertsamm, Hi, Amelia, the Fig1 is updated for the cumulative response rate as requested above. The updated Fig1 and Fig3 are both in the this week's weekly report in box. Please help me review them and let me know if anything else is needed. Thanks.
