### ISSUE TITLE
Bio Weekly - Stratify Biospecimen Survey Metrics by Pre- and Post-COVID Question Removal

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#43]
Please stratify the four biospecimen survey metric tables (Tables 17-20 in weekly bio report; 7/24) by the separation of the COVID-19 questions from the survey; the COVID questions were removed on **7/5/2023**. Stratification will result in eight tables total.

The first tables (17a, 18a, 19a, and 20a) should only include surveys submitted before 7/5, and the second tables (17b, 18b, 19b, and 20b) should include surveys submitted on of after 7/5.

**Requestor(s):** Biospecimen Team

**Table or Figure title:** 
- Table 17a. Baseline Research Biospecimen Survey Status by Site (Pre-COVID-19 Questions Removal)
- Table 17b. Baseline Research Biospecimen Survey Status by Site (Post-COVID-19 Questions Removal)
- Table 18a. Baseline Clinical Biospecimen Survey Status by Site (Pre-COVID-19 Questions Removal)
- Table 18b. Baseline Clinical Biospecimen Survey Status by Site (Post-COVID-19 Questions Removal)
- Table 19a. Baseline Research Biospecimen Survey Completion Time from Visit Check-In Time (Pre-COVID-19 Questions Removal)
- Table 19b. Baseline Research Biospecimen Survey Completion Time from Visit Check-In Time (Post-COVID-19 Questions Removal)
- Table 20a. Baseline Clinical Biospecimen Survey Completion Time from Collection Time (Pre-COVID-19 Questions Removal)
- Table 20b. Baseline Clinical Biospecimen Survey Completion Time from Collection Time (Pre-COVID-19 Questions Removal)

**Metrics to be updated or created:** Update metrics

**Variables needed (include variable name and Concept ID):** Use variables from existing tables (Tables 17-20)

**Specify numerator and denominator by variable name where applicable:** 
Stratify existing numerator by submission date before and on/after 7/5 
- Research - SrvBLM_TmStart_v1r0; 822499427 = <07/05/2023
- Clinical - SrvBlU_TmComplete_v1r0; 764863765 = ≥07/05/2023

**Mock-up table if applicable:**
![Screenshot 2023-07-26 at 6 17 16 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/362c0f80-6c15-4233-b5e1-3c37a729172c)

![Screenshot 2023-07-26 at 6 17 43 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/53c67152-8d0f-4f60-b2fa-4e6173e13031)

**Notes:**
- Add the following footnote to all eight stratified tables: _Note: The COVID-19 survey questions were separated from the Biospecimen Survey on July 5, 2023._

Approved by: Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  For Tables 17 & 18 should it be SrvBLM_TmStart_v1r0 and SrvBlU_TmStart_v1r0 before and after 7/5/23 as opposed to completed so it can include all who haven't started or have started but haven't finished?  

We also won't have anyone for the row of "Not Started" in Table 19 and Table 20 if we use the completion time stamp.

Please note those who started before 7/5 but have not finished by 7/5 will likely have had to restart the survey and seen the new version where COVID questions were not included. This was how we expected participants to have seen module 1 version 1&2 and modules 2 versions 1&2 if they had started but not finished the module before it was versioned

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Your question made me think a little more about this, and it makes more sense to stratify tables 19 and 20 only, since the removal of the COVID questions was an effort to improve submission time; tables 17 and 18 are merely snapshots of the current status proportions.

Can you move forward with stratifying tables 19 and 20 only?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Of course! Should be still be submitted times before and after 7/5? And just the "Not Submitted" will be all 0's?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, stratify submission by before and after 7/5. The "Not Submitted" row can be excluded since that can't be stratified; the denominator can be updated to included "Submitted" status only.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Good morning, I'm having some issues removing that row, so this may have to be how the tables look on Monday until I can figure out how to tweak the code


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e5d8efcd-956f-45c1-8fd0-f4107282d75f)

**Comment by KELSEYDOWLING7** [comment]
Resolved and updated!

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4580a8e2-2f5b-43eb-921e-01c1dab559d7)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Looks good; please add the footnote above to the tables.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Per Michelle: _Please revert Tables 20a and 20b to a single table (not before and after COVID questions removal) as that isn't a relevant metric for the clinical collections._

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/de711818-b024-4c08-82b6-31f056841656)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Should the footnote just be removed from Table 20 now?

**Comment by HopkinsDC** [comment]
> @HopkinsDC Should the footnote just be removed from Table 20 now?

Yes, you can remove it from Table 20. Once that's done, this issue is complete. Thanks!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ba8aec4b-89e5-41f7-941e-1351a86167f6)
