### ISSUE TITLE
Operations - Issue in Table 43/44 Campaigns Metrics

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#44]
**Requestor:** Amelia Roberts

**Tables:** Table 43. Total Number of Active Recruits in Campaign, Table 44. Success Rate by Campaign Type for Active Recruits

**Notes:**
There seems to be an issue in how random sample is being calculated in table 44. Please check the data and calculations for both 'random sample' and also doublecheck the rest of the categories.
- Table 43 shows 0 HP recruits invited in random campaign, but in T44 shows 8 HP recruits were verified through random campaign; same for UC and HFH have verified recruits in random campaign even though 0 invited. Could be that sites sent wrong campaign type for passive recruits instead of ‘none of the above’, but need to see if issue below is causing this first.
- In table 43, all 4 KPs, MF, and SF have invited 4,000-30,000 individuals under random campaign but in T44 show 0 verified for all those sites. Possible, but unlikely. I think there is something wrong with how these are being calculated in the table. 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/b9d53129-22e7-4769-83bd-cc871a32e287)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/80962cc2-6143-4d2d-aa8d-9b4c7fdb6189)

**Approved by:** Nicole Gerlanc

**Comment by jeannewu** [comment]
Hi, Amelia, thank you very much for your checking. Yes. the header of the Table 44 is not correct and I will update Table 44 soon in the report. Thanks a lot.

**Comment by brotzmanmj** [comment]
HI Jing, this is a high priority. Can you address this right away and re-run the report?

**Comment by jeannewu** [comment]
Hi, Michelle and Amelia, thank you very much. The table 44 was already updated and saved in the Connect_ALL and Connect_DCEG folders.

**Comment by robertsamm** [comment]
Table 44 Campaign Success looks correct now, closing issue.

**Comment by jeannewu** [comment]
@robertsamm Thanks for your double checking and approval, Amelia.
