### ISSUE TITLE
Bio Weekly - Cumulative Weekly Collections at Marshfield (Figure 5)

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#45]
Marshfield reported that their weekly collections graph in the weekly biospecimen metrics report (Figure 5) seems to only be showing the cumulative weekly collections for their main location (Marshfield). Figure 5 should include all finalized collections from all of its locations. 

**Requestor(s):** Marshfield

**Table or Figure title:** Fig 5. Weekly Biospecimen Collections at Marshfield Clinic Health System

**Variables needed (include variable name and Concept ID):** N/A
- RcrtES_Site_v1r0 (214456996)
- BioSpm_Location_v1r0 (951355211)
- BioRec_CollectFinal_v1r0 (410912345)

**Specify numerator and denominator by variable name where applicable:** N/A
- Denominator = All finalized collections - BioRec_CollectFinal_v1r0 (410912345 = 1)
- Numerator = All finalized collections at Marshfield site - RcrtES_Site_v1r0 (214456996 = 6)

**Notes:**
- Remove the filter for Collection Location (951355211) from Figure 5.

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Good morning, I'm a little confused on this one. Figure 5 already is all Marshfield locations final collections, and Figure 5.1 the same but with specified collections by location


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0533a9e5-e7f5-4690-a21e-9ed4cdbb236c)


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4bb0a12c-db81-4469-8a86-c45314be32ff)

**Comment by HopkinsDC** [comment]
To clarify, the main site name is Marshfield (RcrtES_Site_v1r0; 214456996=6), and it has a collection location of the same name (BioSpm_Location_v1r0; 951355211=1). Figure 5 is at the RcrtES_Site_v1r0 level.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Hi Domonique, I don't see any reason why Figure 5 wouldn't be including all the collections. That graph does not filter for Collection Location, only Site Name==Marshfield.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, ok, but the Marshfield site had a total of 31 collections the week of 6/19 and 30 collections the week of 7/17; why isn't this showing accurately in Figure 5? All the collections for each week in the graph seem to be lower than 20.

Also, there are now two Figure 5s in the weekly metrics report; please correct that and remember to keep ongoing edits/updates in a test/dev environment until they are approved by me or Michelle to be added to the metrics report.

**Comment by KELSEYDOWLING7** [comment]
Ok I'll take a look and that and try to figure out why the totals aren't properly showing. And my mistake! I was playing around with a theory and forgot to take that out

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Please let me know how this looks:

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6dad2320-ba88-4271-baec-b78312db0734)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/3293aeeb-9ddc-436d-834a-8b7ed58dbffd)





It looks like Chicago had this problem too so the code has been updated there as well

(Before)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/399c0169-330e-42b9-9711-10fed64f69fe)


(After)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/011755ae-a0e6-454b-855b-039c88486ec3)



(Compare to site location)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/12f71b8e-1d60-4bc0-90d6-25cf9df55711)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks so much better; thank you for fixing these! 

You can add these updated figures to Monday's weekly metrics report (8/14).
