### ISSUE TITLE
File names incorrect on Incentive Eligible Reports

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#46]
Report: NORC and Other Site Incentive Eligible Reports

I noticed an issue with the [NORC Incentive Eligible Reports_DCEG](https://nih.app.box.com/folder/167284102961). This one doesn’t seem related to the automatic run, just something that wasn’t caught before. The file names should be swapped. The ones titled ‘[OtherSites](https://nih.app.box.com/file/1280626708377)’ should only have UChicago participants as they are not currently doing NORC gift card incentives, just cash. The ones titled ‘[NORC](https://nih.app.box.com/file/1280635472992)’ should have all of the sites, except UChicago, because all other sites are utilizing NORC incentives. When you look at the reports, it's showing the wrong sites in each report.

Also, I believe we requested this report be run monthly instead of weekly a while back.

**Comment by jeannewu** [comment]
@robertsamm, thank you very much for your helpful check. And for the NORC sites, the data are only presented with NORC.Payment.Eligibility,  Eligible.for.Payment ,  Time.Payment.Eligible.for.Round without the payment chosen (d_130371375_d_266600170_d_945795905). Will you think it ok to add this variable in this data?

**Comment by brotzmanmj** [comment]
Please do not add any variables, thanks.

**Comment by jeannewu** [comment]
Got it. Thanks a lot.

**Comment by jeannewu** [comment]
@robertsamm @brotzmanmj All the incentive data have been corrected with the file names. And the incentive file would be delivered once per month in future as expected
