### ISSUE TITLE
Bio Weekly - Biospecimen Survey Completion Time Length in Minutes

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#47]
Please generate **four** descriptive statistics tables for the biospecimen survey completion time in minutes from start time to submission time **stratified by pre- and post-COVID-19 questions removal on July 5.** "Pre-COVID-19" are surveys submitted before 7/5/23, and "Post-COVID-19" are surveys submitted on or after 7/5/23. The layout of these tables should be

**Requestor(s):** Biospecimen Team

**Table or Figure title:** 
- Table 21a. Research Biospecimen Survey Completion Length (in Minutes) by Site (Pre-COVID-19 Questions Removal)
- Table 21b. Research Biospecimen Survey Completion Length (in Minutes) by Site (Post-COVID-19 Questions Removal)
- Table 22a. Clinical Biospecimen Survey Completion Length (in Minutes) by Site (Pre-COVID-19 Questions Removal)
- Table 22b. Clinical Biospecimen Survey Completion Length (in Minutes) by Site (Post-COVID-19 Questions Removal)

**Metrics to be updated or created:** 4 new tables

**Variables needed (include variable name and Concept ID):**

Table 21a/b:
- BioSpm_Setting_v1r0 (650516960 = 0)
- SrvBLM_TmStart_v1r0 (822499427) - research start time
- SrvBLM_TmComplete_v1r0 (222161762) - research end time

Table 22a/b:
- BioSpm_Setting_v1r0 (650516960 = 1)
- SrvBlU_TmStart_v1r0 (534669573) - clinical start time
- SrvBlU_TmComplete_v1r0 (764863765) - clinical end time

**Specify numerator and denominator by variable name where applicable:**
Table 21a:
- Denominator = submitted research surveys (SrvBLM_ResSrvCompl_v1r0; 265193023 = 2)
- Numerator = surveys submitted before 7/5/23 (SrvBLM_TmComplete_v1r0 = populated date < 7/5/23)

Table 21b:
- Denominator = submitted research surveys (SrvBLM_ResSrvCompl_v1r0; 265193023 = 2)
- Numerator = surveys submitted on or after 7/5/23 (SrvBLM_TmComplete_v1r0 = populated date ≥ 7/5/23)

Table 22a:
- Denominator = submitted clinical surveys (SrvBlU_BaseComplete_v1r0; 253883960 = 2)
- Numerator = surveys submitted before 7/5/23 (SrvBlU_TmComplete_v1r0 = populated date < 7/5/23)

Table 22b:
- Denominator = submitted clinical surveys (SrvBlU_BaseComplete_v1r0; 253883960 = 2)
- Numerator = surveys submitted on or after 7/5/23 (SrvBlU_TmComplete_v1r0 = populated date ≥ 7/5/23)

**Mock-up table if applicable:** Table 21a/b mock-up is the first table and Table 22a/b mock-up is the second table.
![Screenshot 2023-08-15 at 11 45 48 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/3450b31d-d076-4b92-b51d-b9d809b08f0e)

**Notes:**
Add the following footnote to all 4 tables: Note: The COVID-19 survey questions were separated from the Biospecimen Survey on July 5, 2023.

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  This should be a pretty quick fix. Should this push down the current Table 21 & Table 22 to Tables 23 & 24?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Good morning, I just created the first table and I'm a little confused by the preview. I made sure this is the difference from completion time-start time, that only completed surveys are reviewed, and where there are no missing start or completion time stamps. But I'm still seeing negative times and many 0's. Is it possible that the sites entered in times wrong or prod changes had typos or some other explanation for this?


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/17f2e3a5-99ce-4f24-883c-f2fe784da770)

**Comment by HopkinsDC** [comment]
> @HopkinsDC This should be a pretty quick fix. Should this push down the current Table 21 & Table 22 to Tables 23 & 24?

Yes, please push the current Tables 21 and 22 down and renumber them and all the following tables.

**Comment by HopkinsDC** [comment]
> @HopkinsDC Good morning, I just created the first table and I'm a little confused by the preview. I made sure this is the difference from completion time-start time, that only completed surveys are reviewed, and where there are no missing start or completion time stamps. But I'm still seeing negative times and many 0's. Is it possible that the sites entered in times wrong or prod changes had typos or some other explanation for this?
> 
> ![image](https://user-images.githubusercontent.com/101136647/261020120-17f2e3a5-99ce-4f24-883c-f2fe784da770.png)

Hm, very strange. The start date/time and submitted date/time are autogenerated based on when the participant starts and submits the survey; the sites don't enter these times. 

Are the dates being taken into account along with the time? And are the duration calculations using the correct start and complete variables for research (SrvBLM) and clinical (SrvBlU)?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  it looks like I was just missing a code alterations for the date.  Table 21a still has a negative min, but none of the others do.  And yes, I made sure all of those aspects were coded.



![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9396bc49-b693-4d10-8740-8a5d9edc8279)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks good! Thanks. 

For Table 21a, are you able to tell if there are multiple surveys will a negative completion time, or is it just one/a few?

**Comment by KELSEYDOWLING7** [comment]
There are four and I can give you those Connect IDs if it would help. 2 are HP and 2 are Marshfield

**Comment by HopkinsDC** [comment]
Ok, thanks. Please exclude those surveys and add the following to Table 21a's footnote: _Research biospecimen surveys with a negative completion time have been excluded._

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  No problem. Ok that first table has been updated.

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5396c4b5-5d5a-40b9-8be2-1643719fd665)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you! One last thing, can you add a "Perc. 95" column for the 95th percentile to each table

After this addition, these tables can go into the next weekly metrics report (8/21).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Sure thing


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/079ee4cb-72a9-4f5f-a355-7ba432b4ddf4)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Looks good, thank you.
