### ISSUE TITLE
Bio Weekly - Table 1 Updates

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#48]
Please make the following edits to Table 1.
1. Remove the middle column ("No Collections but had an Appointment")
2. Update table title (see mock-up below)
3. Update column title (see mock-up below)

**Requestor(s):** Biospecimen Team

**Table or Figure title:** Table 1: Baseline Biospecimen Collection Status Among Verified Participants by Site

**Metrics to be updated or created:** Update Table 1

**Variables needed (include variable name and Concept ID):**
- RcrtV_Verification_v1r0 (821247024)
- BioRec_CollectFinal_v1r0 (410912345)
- RcrtES_Site_v1r0 (214456996)

**Specify numerator and denominator by variable name where applicable:** N/A
- Denominator = All verified participants (821247024 = 1)
- Numerator = participants with finalized collection (410912345 = 1); participants with no finalized collection (410912345 = 0)

**Mock-up table if applicable:** 
![Screenshot 2023-08-17 at 11 22 59 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/e4c24a11-e56e-42c7-9b7c-42e611925e0e)

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4f022b07-1630-4bf7-ae13-002ff1c41dcc)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Can you remove the "Baseline Biospecimen Collections" top row?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Yes, I just noticed that too


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/b8036c92-0d6f-48c0-9f85-69cd720af58d)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you! Is it possible to put the other column titles in the same row as the "Site" column title?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC With this type of crosstab table I don't think it is. It seems to automatically do this

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, no problem.

This table update can go into the next weekly report (8/21).
