### ISSUE TITLE
Bio Weekly - Table 2 Updates

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#49]
Please make the following edits to Table 2.
1. Remove the middle column ("No Blood Collections but had an Appointment")
2. Update table title (see mock-up below)
3. Update column title (see mock-up below)

**Requestor(s):** Biospecimen Team

**Table or Figure title:** Table 2: Baseline Blood Collection Status Among Baseline Collections by Site

**Metrics to be updated or created:** Update Table 2

**Variables needed (include variable name and Concept ID):**
- BioRec_CollectFinal_v1r0 (410912345)
- BioFin_BaseBloodCol_v1r0 (878865966)
- RcrtES_Site_v1r0 (214456996)

**Specify numerator and denominator by variable name where applicable:**
- Denominator = participants with finalized collection (410912345 = 1)
- Numerator = any baseline blood collected (878865966 = 1); no baseline blood collected (878865966 = 0)

**Mock-up table if applicable:** 
![Screenshot 2023-08-17 at 11 40 23 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/b403da55-d956-4252-bd8e-ee31a7785b11)

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/b00eb56d-912e-46a9-9999-c8cc8575d48c)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Looks good, thank you. This table update can go into the next weekly report (8/21).
