### ISSUE TITLE
Bio Weekly - Remove Table 3 and Table 4

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#50]
Please remove Tables 3 and 4 from the weekly metrics report.

**Requestor(s):** Biospecimen Team

**Table or Figure title:** 
- Table 3. Baseline Urine Collections Among Verified Participants
- Table 4. Baseline Mouthwash Collections Among Verified Participants

**Metrics to be updated or created:** Update Tables 3 & 4

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** Renumber all tables following the removal of these tables.

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Removed

**Comment by HopkinsDC** [comment]
Update approved and ready for next weekly metrics report (8/21).
