### ISSUE TITLE
Bio Weekly - Weekly Percent Incomplete Blood Draws; Timetrend for UChicago & Henry Ford

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#51]
Please generate two graphs that show the weekly percent of incomplete blood draws (partial blood + no blood) for UChicago **and** Henry Ford. Include the total percent incomplete and percent incomplete for each location in a single graph.

**Requestor(s):** Biospecimen Team

**Table or Figure title:**
- Figure 1. Weekly Percent of Incomplete Blood Draws by Collection Location, University of Chicago Medicine
- Figure 2. Weekly Percent of Incomplete Blood Draws by Collection Location, Henry Ford Health

**Metrics to be updated or created:** Create new figures

**Variables needed (include variable name and Concept ID):** 
Refer to code for metric table _Blood Completeness among University of Chicago Baseline Research Collections by Collection
Location_ in weekly metrics report for "all blood", "partial blood", and "no blood" calculations. "Incomplete" should be "partial blood" + "no blood".

**Specify numerator and denominator by variable name where applicable:** N/A
- Denominator = finalized collections (410912345 = 1)

**Mock-up table if applicable:** 
![Screenshot 2023-08-17 at 1 47 15 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/9a345175-ffd4-4f74-914c-c2b993fadf19)

**Notes:** 
- **These graphs should come after the respective blood draw completeness tables in the weekly metrics report (_Blood Completeness among University of Chicago Baseline Research Collections by Collection Location_ & _Blood Completeness among Henry Ford Baseline Research Collections by Collection Location_).**
- Add the following footnote to the respective figure: 
>- Note: NCI notified UChicago of incomplete blood draws on January 26, 2023.
>- Note: NCI notified Henry Ford of incomplete blood draws on April 19, 2023.
- Renumber all plots following the removal of these tables.

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Do you know when these collections first started at UC? And for HF?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 They both started on 7/11/2022.

**Comment by HopkinsDC** [comment]
*Issue not urgent

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC I'm trying to work backwards in Jing's code to determine how he came up with blood completeness versus partial or no. It seems like research locations take 5 blood samples and clinical 11? Can you clarify which samples are for each?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, research only considers SST1, SST2, Heparin1, EDTA1, and ACD1 (5 total).

Also, this plot type should only be applied to research collections, so for Henry Ford, you only have to generate a plot for their research locations (HFH Cancer Pavilion Research Clinic, HFH K-13 Research Clinic, and HFH Livonia Research Clinic).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thanks!

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0c3f75e0-a78f-47ee-b980-c34bda3f5381)


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/b1b63460-9cea-4995-a7cb-71b996cc22f5)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 These graphs seem a little off to me, but I'm unsure why.

Is each weekly percent only counting collections within that week? For example, if 14 collections are completed in one week, and 4 of them have an incomplete blood draw, the percentage for that week should be 28.6%; this would start over the next week, with a new number of weekly collections as the denominator.

It also seems like some weeks are not plotted at all.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  That's correct, as far as what the percentages are and it should reset each week. I tried removing any instances where the percentage is 0, to avoid that awkward return to 0 between each week. Without it, they look like this:

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e20b522e-5395-48f8-bf67-4bf1f424d4fe)


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/cd5baffb-32b6-448b-90f7-64ee230b0036)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Can you adjust the y-axis scale to show in increments of 5 instead of 25?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/37238c1b-0302-4b8e-90d2-4fac54d91899)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f3ae4f4c-f19c-491a-8301-091d5103fd8f)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, some of the 0% are true percentages for some of the weeks. For Henry Ford, the weeks of 8/15, 8/22, 9/5, 9/12, 9/19, 9/26, 10/10, 11/21, 12/12, 1/16, 1/30, 2/20, and 6/5 are all truely 0% (there may be more after 6/5); those should be in the graph. 

For the other 0%s, are those just missing values? Or could it be because of the "reset" for each week that cause the trend line to drop to 0 before going to the next point?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  In theory it could be missing values if no blood draws were inputted when taken certain weeks. But other than that it seems to be this odd reset, and I'm trying to figure out why that parts even happing. It's the same code as this graph, which does not "reset" to 0

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/19b8edf9-c751-492c-8a6d-990ce37b20f0)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, thanks for looking into this! It'll be difficult to see the sites' progress with the "resets" in the graph, so if this can be resolved before adding these plots to the report, that would be great.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  It looks like the only true 0's for either is 6/30/22, 7/7/22, 7/14/22, 12/22/22. 12/22 isn't in the biweekly dates shown here, so I think it would be safe to remove all 0's. I also don't see missing weeks but if you do can you let me know which?


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e7e6f384-958f-42e8-83af-cc87c99a2c6a)


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/541ec0ad-0d16-478d-af4b-9f20448bf2c1)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, that makes sense. And just to confirm, the incomplete collections are being calculated as ≤4 out of 5 tubes collected, correct?

Also, please revert the y-axis to quarter increments and update the x-axis to include all Monday dates (make it weekly, not biweekly).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Yes, these are everyone that does not have all 5 tubes collected. 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9e01cde6-288b-43ec-9316-3ecd8b0e22d1)


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/867162f4-b83c-456e-ad46-0da000d4c18d)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Great, thanks for confirming. These look good, but I want to hold off on adding them to the weekly report until Michelle can also review them. She's out of the office today but should be back tomorrow.

You can put this issue on hold for now and continue to issue #57 (not urgent, but the last of this round of metrics edits).

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Good morning Kelsey, Michelle reviewed these figures, and we'd like you to generate a data table showing the weekly total number of collections in one column and the number of incomplete collections in another column for UChicago and Henry Ford. You can post the table in this issue for us to review; this table is a one-time generation and will not be added to the weekly report. Thank you!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Hi, sorry for the delay. I finally got the table how I needed it and was able to recode the graph based on that new table. Now I just need to separate the line by Site locations


[Figure1 Table.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/12431674/Figure1.Table.csv)
![new fig1](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c2fd4c53-eba1-46b5-8d1c-d117eb6737eb)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Also looking at HF, should that be research locations only? Or combine all locations? Right now the clinical only has one incomplete blood collection

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 No worries. This looks perfect, thank you!

You can combine all locations for the UChicago graph and the Henry Ford graph, so a graph like the one above is good. For Henry Ford, it should only include research collections.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Great!!

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/44b111be-fc02-4fa5-a56d-d133c203254c)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ebf84e71-c5dd-436e-8518-fbfdfad6fd6d)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Looks great. One last thing: please remove the "by Collection Location" from both of the graph titles. They are good to go after that.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c2b50b63-8c1c-4649-bfa2-993d8ce89411)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/7a622ebb-dc9a-4958-8dc9-738a1db7ce73)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Excellent, thank you!

These plots can go into the next weekly report (8/28).

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, I'm reopening this issue to add Michelle'e request to add 2 additional trendiness to Figures 1 and 2, one just for the weekly count of "No Blood" and the other just for "Partial Blood". The existing trend line in the figures should remain in the figures and should be labeled "Total".

**Comment by HopkinsDC** [comment]
Updated Figures 1 and 2 look good. The updated figures can be added to the next biospecimen metric report (9/25).

![Screenshot 2023-09-20 at 3 04 35 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/ddcdc0f4-1559-42dc-8940-1f930ecf993f)
