### ISSUE TITLE
Bio Weekly - Table 6a/b Update

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#52]
Please make the following changes to Tables 6a and 6b:
- Change the row percents to column percents 
- Remove the period between the title number and letter for both (6.a --> 6a.)
 
**Note: Table numbers may differ based on the removal of Tables 3 and 4 from the weekly metrics report**

**Requestor(s):** Biospecimen Team

**Table or Figure Title:** 
- Table 6a. Baseline Research Collection Completeness by Site
- Table 6b. Baseline Clinical Collection Completeness by Site

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5fd41b59-a8fc-4390-9564-34c050eaed44)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/2036c7cf-0371-49fe-9e2f-cdf21bc405a7)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Can you remove the "Site" top from both tables?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/74c34d3f-c4aa-462a-bb71-7cf40f31d5ab)


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/824f5f32-fd06-47c0-be13-5f37296606c8)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Great, thanks! This table update can go into the next weekly report (8/21).
