### ISSUE TITLE
Bio Weekly - Table 23a/b Update

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#53]
Please make the following changes to Tables 23a and 23b:
- add the following footnote - _Note: Baseline Clinical Collections were launched in February 2023._
- swap the order of the words "Clinical" and "Baseline" in the titles (Clinical Baseline --> Baseline Clinical)

**Table numbers may differ based on the removal of Tables 3 and 4 from the weekly metrics report**

**Requestor(s):** Biospecimen Team

**Table or Figure Title:**
- Table 23a. Time (in Days) from Verification to Clinical Baseline Collection for Participants Verified Before 02/01/2023
- Table 23b. Time (in Days) from Verification to Clinical Baseline Collection for Participants Verified on or After 02/01/2023

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable**: N/A

**Mock-up table if applicable:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/8d7dcc61-6dc2-4bd2-be71-8bf9778f9a3d)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4c3769cf-b9ee-4176-b303-0697f6ebddc3)

**Comment by KELSEYDOWLING7** [comment]
Oops, uploaded B twice. Here's A


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/8a4209e0-52ca-47b3-9e26-74a66662d5d0)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you! These updated tables can go into the next weekly report (8/21).
