### ISSUE TITLE
Bio Weekly - Percent Suverys Submitted; Timetrend for UChaicgo

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#54]
Generate a line graph that shows the percentage of surveys not submitted for UChicago. ("No submitted" = "started" + "no started"). UChicago started collections on 7/11/22, making survey data became available at the same time.

**Notes:** 
- This figure should be inserted below the _Baseline Research Biospecimen Survey Status by Site_ table in the weekly metrics report.
- Add the following footnote: _Note: Biospecimen Surveys with a completion status of “Started” and “Not Started” are considered “Not Submitted”._
- Renumber all figures following the addition of this figure.

**Requestor(s):** Biospecimen Team

**Table or Figure title:** Figure 3: Weekly Percent of Biospecimen Surveys Not Submitted, University of Chicago Medicine  

**Metrics to be updated or created:** Create new figure

**Variables needed (include variable name and Concept ID):**
Refer to code for metric table _Baseline Research Biospecimen Survey Status by Site_ in the weekly metrics report for "Started", and "not started" calculations. ("No submitted" = "started" + "no started")

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** 
![Screenshot 2023-08-18 at 9 35 09 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/e894984e-0851-44d3-947a-f786943852c0)

**Approved by:** Domonique

**Comment by HopkinsDC** [comment]
*Issue not urgent

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/05dd8b90-97c3-482b-9d5a-ddeb21d6b24c)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Corrected it to not have the continual dips to 0

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c4e57f34-0066-4fd4-9c4d-c48f8bb32ad6)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
Does anything more need to be done with this one?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 No, this one is good to go.

This plot can go into the next weekly report (8/28).

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Following up on [my comment](https://github.com/Analyticsphere/metricsReportsRequests/issues/57#issuecomment-1693458879) to update _Figure 3: Weekly Percent of Biospecimen Surveys Not Submitted, University of Chicago Medicine_ to be a cumulative weekly percent, (for each week, the denominator would be the total number of triggered surveys, and the numerator would be the total number of surveys not submitted (started + not started)). Can you make this change?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Yes, please see below:

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/8e3523a9-8bdb-46a2-beb5-bfce9488b731)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This doesn't seem quite right. UChicago has been hovering about 50% cumulative not submitted (started + not started) surveys for a while. All of the past metrics reports show a the 'not started' between ~44-49% and the 'started' between ~2-5%. This past Monday's report shows 47.9% 'not started' and 2.1% 'started' (50% not submitted cumulative).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thank you for letting me know, this code is trickier then I expected. I'll continue to work on it

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  I believe I have it!

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5c637053-25b7-4eaa-82bf-fe2e53c84e30)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks better, thank you! Can you update the title to: **Figure 3**. Weekly Cumulative Percent of Biospecimen Surveys Not Submitted, University of Chicago Medicine

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Slight edit! This looks more accurate as well

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f8a1b5c8-4873-4be8-9384-91bd2c01592c)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 It does, thanks again! 

This updated graph can be added to the next biospecimen metrics report (9/25).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Hi, is there an issue with this plot that came up?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 No, there's no actual issue, but Michelle wants some changes made. 

I'm looking into what makes the most sense for what we want to see from this figure and will add a comment here with the updates needed.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Please make the following changes to Figure 3:

1. Change the figure trend line to show the percent "submitted" surveys rather than "not submitted"; the "submitted" trend line should be a mirror image of the current trend line.
2. Update the title to - Figure 3. Weekly Cumulative Percent of Biospecimen Surveys Submitted, University of Chicago Medicine

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Changing the filter from Not Started or Started to Submitted, this is the plot that I'm getting. Please let me know if this does not look as you expect

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f94c8edc-1335-4035-9599-588c80e8e029)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yeah, that was the idea. This looks good to me. Michelle will review this tomorrow for approval. Thanks!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Michelle ok'ed this updated figure. Can you remove the word "Weekly" from the title? After that, it is good to go!

Also, can you generate a separate figure showing a non-cumulative weekly percent of surveys submitted (similar to the image in [this comment](https://github.com/Analyticsphere/metricsReportsRequests/issues/54#issuecomment-1686821110) but submitted)? The denominator would be the total number of triggered surveys _within each week_, and the numerator would be the total number of surveys submitted _within each week_. **This is an ad-hoc request; the biospecimen group will decide if it should be added to the weekly report after reviewing.**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Great, here's the renamed Figure 3
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c463a958-73b8-468e-b54f-d8ff2e066693)



And here's the comparative weekly count of Figure 3
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1eb0af2f-39ce-414b-a794-9d97c541e0bb)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The comparative weekly count of Figure 3 can be added to the weekly report. Its title should be "Figure 3.1 Weekly Percent of Biospecimen Surveys Submitted, University of Chicago Medicine" and it should come right after Figure 3 in the report.

Thank you for your work on this!

**Comment by HopkinsDC** [comment]
Update successfully implemented in 12/18 weekly biospecimen metrics report.
