### ISSUE TITLE
Bio Weekly - Percent Suverys Submitted in 0-3hrs; Timetrend for UCHI, HFH, and SFH

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#55]
Generate a line graph that shows the percentage of surveys submitted within 3 hours of visit check-in for UChicago, Henry Ford, and Sanford. Collections started on 7/11/22, making survey data became available at the same time.

**Notes:** 
- This figure should be inserted below the _Baseline Research Biospecimen Survey Completion Time from Visit Check-In Time (Post-COVID-19 Questions Removal)_ table in the weekly metrics report.
- Renumber all figures following the addition of this figure.

**Requestor(s):** Biospecimen Team

**Table or Figure title:** Figure 4: Weekly Percent of Biospecimen Surveys Submitted within 3 Hours of Visit Check-In

**Metrics to be updated or created:** Create new figure

**Variables needed (include variable name and Concept ID):**
Refer to code for metric table _Baseline Research Biospecimen Survey Completion Time from Visit Check-In Time (Post-COVID-19 Questions Removal)_ in the weekly metrics report for "0 hrs to 3 hrs" calculations.

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** 
![Screenshot 2023-08-18 at 9 54 30 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/967ce50d-33c7-412c-9e8f-c83315c6e5e2)

**Approved by:** Domonique

**Comment by HopkinsDC** [comment]
*Issue not urgent

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/b28d5a2e-9c84-4450-90b6-7635acc6d23d)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 please remove HealthPartners and Marshfield from the graph.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/657c94b3-9a9c-4c9b-bd60-08ba3fe1451e)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 I didn't anticipant this graph being a little difficult to read; can this be made into 3 separate plots (one for each site)? 

The titles can be updated to include the site name; for example:
(1) Weekly Percent of Biospecimen Surveys Submitted within 3 Hours of Visit Check-In, Henry Ford Health System 
(2) Weekly Percent of Biospecimen Surveys Submitted within 3 Hours of Visit Check-In, Sanford Health 
(3) Weekly Percent of Biospecimen Surveys Submitted within 3 Hours of Visit Check-In, University of Chicago Medicine

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e5c7fb95-763f-48af-b58a-3a004ec1b6e4)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/93d0efd8-5bb0-4953-858f-0f4a49372dd8)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/70dbb02d-5a8f-4226-a136-410dd89c35f8)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thanks, Kelsey! One last question: is there a reason why the trendlines return to 0% between each weekly percentage? Can that be adjusted to be a continuous line between each weekly percent?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Weird. Yes, I can adjust that


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ac57eff0-81c2-40a6-941a-c81a3d786541)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/000f6923-4ee1-4fa8-b5d8-e6df71164d34)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/a2789b72-6a50-426e-ab8a-d1fae5c4ffd3)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Excellent, thank you! 

These plots can go into the next weekly report (8/28).
