### ISSUE TITLE
Bi Weekly - Combine Tables 11 & 12

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#56]
Please combine tables 11 and 12 (_Baseline Blood Collection Status in Data Sent from Site vs Connect Biospecimen Dashboard_ & _Baseline Urine Collection Status in Data Sent From Site vs Connect Biospecimen Dashboard_) into one table. See the mock-up below for the new table's format.

**Notes:** 
- Add the following footnote: _Note: Data sent by sites experience an availability delay of up to 48 hours behind data from the Biospecimen Dashboard_
- Renumber all tables that follow

**Requestor(s):** Biospecimen Team

**Table or Figure title:** Table 4. Data System Status Among Baseline Clinical Collections by Specimen Type

**Metrics to be updated or created:** Create new table

**Variables needed (include variable name and Concept ID):**
- BioSpm_Setting_v1r0 (650516960)
- BioRec_CollectFinal_v1r0 (410912345)

**Specify numerator and denominator by variable name where applicable:**
- Denominator = finalized clinical collections (650516960 = 1; 410912345 = 1)

**Mock-up table if applicable:**
![Screenshot 2023-08-18 at 10 48 51 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/41d2803e-f790-4df3-a2e7-ca1884397356)

**Approved by:** Domonique

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 *Not urgent

When you begin working on this issue, can you tell me why/how there are values for the "No-No" cells in the old tables? For a collection to be finalized, the data will have to be in the dashboard at least.

**Comment by HopkinsDC** [comment]
*Issue not urgent

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  And you want this as the new table four instead of table 11? I'm thinking it would only have a mouthwash sample but I'll take a look

**Comment by KELSEYDOWLING7** [comment]
Actually disregard that comment, it looks like this previous table only pulled form the participants table, so it didn't have the finalized clinical collections filter (410912345 = 1). That variable is only in the biospecimen table, so I'll have to merge the two and add the filter for this table.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, thank you for checking that. and yes, this table will be Table 4, and it'll replace both Tables 11 and 12.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Right now the data is showing no one that is site data only. It's either both dashboard and site, or dashboard only. Does that sound correct because of the delay mentioned in the footnote? If so, I'd have to remove the row for Site Data Only

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 That's actually correct; the data should exist in the dashboard before the site data is pushed to us. If there is "site only" data, that indicates missing data in the dashboard.

Is it possible to keep the "Site Data Only" row and have it display zero count and percent?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thanks

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6a618788-ac0d-404c-bded-848c944d6cf9)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Can you please remove the "Total" column?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c17c2b4d-7fc0-47d6-9a56-4977a60ac758)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/3ae26b15-ff2b-4a51-98ed-e9314b7a12b9)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Perfect, thank you! 

This table can go into the next weekly report (8/28).
