### ISSUE TITLE
Bio Weekly - Relocate Deviations Tables

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#57]
Move the site-specific deviations tables (Tables 14.1-14.9) to the end of the weekly metrics report and add a new section for them titled "Appendix 1: Site Deviations"; add the section title under "Tables" and "Plots" and remove the table numbers from the table titles.

**Requestor(s):** Biospecimen Team

**Table or Figure title:** 

**Metrics to be updated or created:** Update Tables 14.1-14.9

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** Renumber all tables following the removal of these tables.

**Approved by:** Domonique

**Comment by HopkinsDC** [comment]
*Issue no urgent

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  With some of the plots now scattered throughout the report, does it make sense to have Table and Plot sections anymore?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Please leave the sections as they are for now; once all the changes are complete from this round of edits, I'll define new sections based on how the tables/graphs are grouped and their general topic (i.e., collections, surveys, completeness, deviations, etc.).

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 for this issue, you can just move Tables 14.1-14.9 to the end of the report and disregard adding an Appendix section.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok, do you still want the table numbers removed from the title too?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, that'd be good, thanks.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Good morning, like this?

[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/12439387/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks good, thanks!

Off topic, but I took another look at _Figure 1: Weekly Percent of Biospecimen Surveys Not Submitted,
University of Chicago Medicine_ and can it be changed to show the cumulative percentage of surveys not submitted over time? So, for each week, the denominator would be the total number of triggered surveys, and the numerator would be the total number of surveys not submitted (started + not started)?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Great. 

Ok I can work on that when I get back. I already put the Figure 1 as in into Jake's automation, and I'm afraid to change it again so close to me leaving. Can it be left as is for now? Or do you need it taken out?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 ok, no problem. You can leave it in as is until you return. Thank you!
