### ISSUE TITLE
Update Operations Report - UChicago Incentives

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#58]
**Requestor:** Amelia Roberts

**Table or Figure titles:**
(1) Table 38. Time From Incentive Eligible to Incentive Issued by NORC in Days
(2) New table to be new Table 39. Time From Incentive Eligible to Incentive Issued by UChicago in Days

**Metrics to be updated**: Operations Report

**Variables needed:** payment issued and payment eligible variables for both NORC and UChicago vars

**Notes:**
UChicago has started sending the rest of their incentive data this week. Table 36 and 37 look good as is, but table 38 will need to be updated and a new table created as well.
(1) Table 38. Time From Incentive Eligible to Incentive Issued by NORC in Days: 
-please remove UChicago from this table completely and make sure the 'total' row does not include UChicago either. 
Please keep the footnote that states 'For all sites except Chicago'

(2) New table, will be new Table 39. Please title 'Time From Incentive Eligible to Incentive Issued by UChicago in Days'. 
-This will be a similar summary statistics table as table 38 but it will only be for UChicago pts. 
-Please include 'incentive issued' count and the same quartile ranges for now. Make sure to use the correct payment vars for UC pts. 
-Please also add a footnote that states 'UChicago is currently doing cash payment only, no NORC giftcards'
-Note, Madhuri is currently checking with UChicago team on data accuracy due to the negative time between payment eligible and payment issued. We may update this table with a couple other reqs once we hear back from UC.

**Approved by:** Michelle

**Comment by jeannewu** [comment]
@robertsamm thank you very much for your request, Amelia. I will work on these two tables and let you know if I have any problems. Also for the incentive data, will you need the incentive data for UChicago? if yes, what variable (additional variables) would be included in the incentive data (as the NORC incentive one)?

**Comment by jeannewu** [comment]
@robertsamm How about "Table 37. Baseline Incentive Status for Incentive Eligible Participants". Right now, Table 37 is for the NORC pts, not the Chicago included. Will you think it necessary to add the one for Chicago on this incentive and eligible table? Also I will remove the footnote under the table 37 as "Note: University of Chicago Medicine has not sent incentive data yet to CCC", right?

**Comment by robertsamm** [comment]
Hi @jeannewu I believe Table 37 already encompasses both NORC and UChicago. See below. I don't think anything on this table needs to be changed except for the footnote. Yes, I agree please remove that footnote about UC not sending incentive data yet
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/c42ca3cb-7ee9-412a-a54b-b8eab8ad0a3c)

**Comment by jeannewu** [comment]
Great. I will remove the footnote for the Table 37.

**Comment by kmazzilli** [comment]
Hi @jeannewu we noticed that there are two Table 39s in the Operations Report. We would like to keep the one that you created for this Github issue, located on page 36 and remove the one located on page 35. Please see the attached screenshot for the one we would like removed. Thanks!
<img width="1228" alt="Screenshot 2023-09-18 at 4 11 47 PM" src="https://github.com/Analyticsphere/metricsReportsRequests/assets/40246056/42314504-3cba-40b0-acea-2a8ba342bfae">

**Comment by KELSEYDOWLING7** [comment]
Good morning @kmazzilli  Based on yesterdays report it looks like this table duplicate table 39 has been removed

**Comment by kmazzilli** [comment]
Great, thanks @KELSEYDOWLING7 !
