### ISSUE TITLE
Bio Processing Metrics - Needle to Freezer Time By Site

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#6]
Please generate **cumulative** needle to freezer time pie charts for plasma and serum for each research collection site (Marshfield, HealthPartners, Uchicago, Sanford, and Henry Ford) using the most recent [Connect Cumulative BSI Report](https://nih.app.box.com/folder/170816197126). 

Note: This metrics will be a single generation occurrence at this time.

**Comment by jeannewu** [comment]
Hi, Madhuri, I've checked the data in box, it is still the one saved on Oct. 24, 2022, which we had done the plot with already. Will you mean a new data coming next Monday?
