### ISSUE TITLE
Operations Report - add new plots for enrollment thru completion time trends by week

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#66]
**Requestor(s):** Amelia Roberts and Kaitlyn Mazzilli

**Table or Figure title:**
(1)Weekly Counts of Enrollment through Study Activity Completion through DATE - Overall
(2-10)Weekly Counts of Enrollment through Study Activity Completion through DATE - Site
**Metrics to be updated or created:** Operations Report

**Variables needed:** use same variables and calculations for invitations, verified, and survey+blood completes that are in the weekly log. 

**Notes:**
Jing, we would like to add 10 time trend plots (one overall and the rest by site) that show enrollment through study activity completion _by week_. All on the same plot we would like the following time trends
-number of invitations
-number verified
-number of survey+blood (e.g. completes)
this is similar to the plots you made for Mia, but this should be non-cumulative with timepoints by week. (see plot 7 on [biospecimen report](https://nih.app.box.com/file/1298042416585) for example of non-cumulative, weekly plot. )

Please add under figure 3 on the Operations report, so will start at figure 4 onwards.

**Approved by:** Michelle Brotzman

**Comment by jeannewu** [comment]
@robertsamm based on the figure you requested above, the new cases of invitations, verified, survey + blood completion  each week each week would be shown in the time-trend plot by overall, and each site, right?

**Comment by robertsamm** [comment]
Hi @jeannewu yes that sounds right!

And please make sure to keep these plots in DCEG only until we approve.

**Comment by robertsamm** [comment]
So one plot for overall, one plot for HP, one plot for HFH, and so on.

**Comment by jeannewu** [comment]
@robertsamm since the response rate is about 2-6% (verified / invitation) generally, the weekly trends of invitation, verified, and completion by week would not be as clear as expected in one universal scale of y-axis in one plot. Would you still need tri-time trends in one plot scaled with one y-axis?

**Comment by robertsamm** [comment]
Hi @jeannewu these should be counts, not rates for each. 
-number of invitations
-number of verified
-number survey+blood/completes
Start with all 3 on one plot with one y axis first and we will then review and adjust if needed. I know the much higher number of invitations will skew the scale a bit.

**Comment by jeannewu** [comment]
@robertsamm Thank you very much for your explanation. But what I mean is the total larger number of new invitations, vs the few new cases of verified, less new cases of completions in the plot. In contrast with the # invitation, the plots of new verified or completions would not be easy to Sea their curve changes by week.

**Comment by robertsamm** [comment]
@jeannewu can you show me an example of just the overall plot by week? It may be that we need to switch to biweekly or monthly

**Comment by jeannewu** [comment]
@robertsamm Please see the new cases of invitation, verified, completed in HP site:

recruit.week.date | total_verifieds | active_recruits | total_allacts
-- | -- | -- | --
4/16/23 | 63 | 1198 | 32
4/23/23 | 53 | 603 | 35
4/30/23 | 81 | 599 | 29
5/7/23 | 53 | 599 | 32
5/14/23 | 51 | 799 | 33
5/21/23 | 56 | 796 | 38
5/28/23 | 48 | 799 | 25
6/4/23 | 44 | 806 | 26
6/11/23 | 54 | 801 | 39
6/18/23 | 71 | 799 | 27
6/25/23 | 73 | 797 | 40
7/2/23 | 81 | 802 | 36
7/9/23 | 64 | 795 | 32
7/16/23 | 77 | 800 | 37
7/23/23 | 48 | 797 | 51
7/30/23 | 52 | 800 | 34
8/6/23 | 89 | 803 | 42
8/13/23 | 69 | 805 | 38
8/20/23 | 68 | 802 | 51
8/27/23 | 58 | 802 | 41
9/3/23 | 51 | 804 | 46
9/10/23 | 8 | 0 | 0

**Comment by jeannewu** [comment]
<img width="384" alt="image" src="https://github.com/Analyticsphere/metricsReportsRequests/assets/99832343/88cdf08c-db1a-4c64-bb4f-b13bf30d56fb">

**Comment by robertsamm** [comment]
Thanks @jeannewu! I see what you mean. Michelle mentioned Nicole had a suggestion for utilizing a break in the graph to have invitations on the same plot as the other numbers. Could you consult with @FrogGirl1123 to see if you are able to utilize that?

**Comment by jeannewu** [comment]
@robertsamm and @kmazzilli I have put all these time trend plots: activities, refusal (request 66 and 67) in the last week report sent via team. Please check them. Looking forward your helpful comments. Thanks a lot.

**Comment by robertsamm** [comment]
Hi Jing, for Figures 4-4.9 I think you're right, the break won't work. And we should go with the 2 y-axis graphs like the one below. Thanks for mocking the ones with the break up so we can see it! Additional edits to these figures before they are ready:
-Change the left y axis to state '# Individuals Verified or Completed Study Activities'
-The x-axis isn't consistent on the site ones, please have it match the overall one with the dates showing biweekly and count markers per week
-Please update the end of the x axis for all plots so that the end date is not in the future, it creates a drop off in the time trend. In the future please make sure all time trend graphs don't do this.
-Remove key titles 'Baseline Study Activities' and 'Verified Activities' , it's not needed
-Make the key consistent across all plots with it going left to right: Verified, Survey+Blood, Invitations

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/15e1085a-f791-4ec4-b32f-428f2f5c5ba7)

**Comment by jeannewu** [comment]
@kmazzilli and @robertsamm thank you very much for your comments. I will update these plots based on your suggestions.

**Comment by kmazzilli** [comment]
We reviewed these plots and it looks like the only outstanding thing is to remove the "verified.activities" key title. Thanks so much!

**Comment by jeannewu** [comment]
@kmazzilli got it. I will remove this label name in the plot. Thanks

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  Based on yesterdays report, it looks like this legend title has been removed

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 These plots are still incorrect in the automated report uploaded to ALL on Monday here: https://nih.app.box.com/file/1342288439223. The colors of the trend lines don't match the key again and the counts look incorrect. For example, KPCO should have invitations staying steady at 3,000 per week but they only go up to ~1200 and are not staying steady. Please check all these plots and the ones for withdrawal/destruction in case those also didn't have the code updated. Can you also delete the incorrect report from ALL so the sites aren't using these plots unknowingly?

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Good morning, yes. Jing has uploaded her latest version to the all as all other requests were pending. But I will upload the edited code now.  My version with the "corrected" code is the report in the DCEG folder. Can you let me know these issues are also showing there? 

Just so I know, are Figures 5.0-5.12 approved? If so, the same report in the DCEG folder from Monday can simply be put in the all folder.

**Comment by robertsamm** [comment]
Gotcha, thanks @KELSEYDOWLING7. Is it this one? https://nih.app.box.com/file/1342288439223 The KPCO plot still looks incorrect to me based on the invitation numbers but I didn't check each one.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  This one: https://nih.app.box.com/file/1342073937264


That has this plot, which seems to line up with the invite numbers you had mentioned.

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/833578b0-410f-4397-82d9-7e74e18711a6)

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 Thanks for finding the correct link! Yes, this plot still looks incorrect. The color of invitations is incorrect and their weekly invitation counts should be hovering around 3,000 (comparing to the weekly log counts). This plot is not showing that. KPNW is also incorrect, and I'm guessing the others are as well.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  No problem, and oh ok I see. It looks like the colors are correct in the Overall plot, but not the site plots, so I will fix that real quick. As for the numbers, I'm not sure why all of a sudden the plots wouldn't match the logs so I will work with Jing on that

**Comment by jeannewu** [comment]
HI, @robertsamm Here pasted is a copy of the plot(I think it is the correct one! )Please check it and let me know if anything is needed. [image](https://github.com/Analyticsphere/metricsReportsRequests/assets/99832343/7ed2fffc-9913-41c2-b7b4-f5ea62344073)

**Comment by jeannewu** [comment]
@robertsamm If you think it ok, I will put the report in the Box folder: Connect_DCEG folder.

**Comment by robertsamm** [comment]
Thanks @jeannewu yes, that looks correct for KPCO. Can you make sure all of the site plots are updated the same?

**Comment by jeannewu** [comment]
Hi, @robertsamm, I think this version is correct ( I will put it in the box folder: Connect_DCEG_ONly).  I will check the version done with the pipeline and fix it if possible. Thanks a lot.

**Comment by robertsamm** [comment]
Hi @jeannewu please make sure to have Kelsey check it

**Comment by jeannewu** [comment]
@robertsamm and Kelsey Thank you very much for your helps. Kelsey helped me check it and I have just put it back to the Box: ALL and DCEG_Only folder.

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 The site enrollment figures look correct but Figure 4.0 for overall is showing weekly invitations ranging from 110,000-180,000 in the past several months. That can't be right. Looking at the weekly log report for all sites it should be something like 10,000-18,000. Can you take a look again? does the scale just have an extra 0?

**Comment by KELSEYDOWLING7** [comment]
@robertsamm Hi Amelia, @jeannewu  updated the code. It appears the 180,000 figure it correct. What was wrong was the individual site numbers. Those have been updated in her report here, and the number add up. Please let me know if this still doesn't match what you were expecting
[Connect_WeeklyOperationsMetrics_newplots_2023-10-23.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13170165/Connect_WeeklyOperationsMetrics_newplots_2023-10-23.pdf)

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 please check the overall and site plots against the weekly logs for the count of invitations. We're still finding errors. It appears that now all of the plots right y axis is off by a magnitude of 1,000.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Having looked at the logs, we were able to update the plots. Please see below

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4e07c63c-4b78-4677-854c-bd822de96504)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4b39776c-70a9-43e1-abbc-460b587e2e64)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/16502618-3a64-4d91-99e5-71835acec4de)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c4c2c640-df77-4d68-8395-489b8aeacb75)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/a83d07d9-5997-41d8-bf8f-04fd6a629cf5)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4dbaee0e-3ffe-4704-a70b-0a85b8d24a68)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/afc785bd-70a3-48c9-a049-f346a52ac95d)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/7924298e-458a-4ba6-946e-904dd6e6fbc6)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/2c5c6dc0-d1fe-451c-aa3b-51cd77430116)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/de3d4573-1d4f-4801-9e21-d275a81fe0e5)

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 yes! These all look perfect. Thank you for doing the comparison and fixing the last few issues.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Great, I'll have this and the updated columns on the logs from #75  on Monday's report in the ALL folder.
