### ISSUE TITLE
Operations report - weekly withdrawal and/or data destruction trends

### ISSUE THREAD

**Issue by kmazzilli** [Analyticsphere/metricsReportsRequests#67]
**Requestor(s):** Amelia Roberts and Kaitlyn Mazzilli

**Table or Figure title**: Weekly Counts of Withdrawals and Rates by Invitations Through DATE Overall
Weekly Counts of Withdrawals and Rates by Invitations Through DATE SITE

**Metrics to be updated or created**: Weekly Operations Report

**Variables needed (include variable name and Concept ID):**  Date withdrew consent (659990606) and Date requested data destroyed (269050420)

Specify numerator and denominator by variable name where applicable:

Mock-up table if applicable:

**Notes:**
We would like to add time trend plots to the operations report, one overall, and the rest by site (so 10 figures total) of withdrawal  request counts and rates by invitations per week. We are interested in seeing one trend line of the counts of people who either requested withdrawal AND/OR have data destruction. This is because participants who request withdrawals with data destructions do not have a timestamp under withdraw, they have a timestamp under data destruction. We would like to have one line for the counts and a second line on the same figure for the rates where rate=N withdrawals/ N invitations.

**Approved by:** Michelle Brotzman

**Comment by jeannewu** [comment]
@kmazzilli for this plot, the data destruction and consent withdrawal should be the new or cumulative cases by week? also what is the rate by Invitation? will you mean the response rate (cumulative verified/accumulative active invited), cumulative one, right? See below (the table and plot of HP)

Starting Date by week | new case. Data destruction | new cases. Withdrawal Consent | cumulative response | data destruction.cum | consent.cum
-- | -- | -- | -- | -- | --
4/3/23 | 0 | 0 | 8.96078724 | 7 | 23
4/10/23 | 0 | 1 | 8.657268 | 7 | 24
4/17/23 | 1 | 1 | 8.66250411 | 8 | 25
4/24/23 | 1 | 2 | 8.84659163 | 9 | 27
5/1/23 | 0 | 0 | 8.84664595 | 9 | 27
5/8/23 | 0 | 2 | 8.7322798 | 9 | 29
5/15/23 | 1 | 3 | 8.65726344 | 10 | 32
5/22/23 | 0 | 0 | 8.54469081 | 10 | 32
5/29/23 | 0 | 0 | 8.4178861 | 10 | 32
6/5/23 | 0 | 0 | 8.3521113 | 10 | 32
6/12/23 | 0 | 1 | 8.37222458 | 10 | 33
6/19/23 | 0 | 2 | 8.40072694 | 10 | 35
6/26/23 | 0 | 1 | 8.46045941 | 10 | 36
7/3/23 | 0 | 1 | 8.44664718 | 10 | 37
7/10/23 | 0 | 2 | 8.48527062 | 10 | 39
7/17/23 | 1 | 5 | 8.40739565 | 11 | 44
7/24/23 | 0 | 1 | 8.34871558 | 11 | 45
7/31/23 | 0 | 2 | 8.43063379 | 11 | 47
8/7/23 | 1 | 1 | 8.43473852 | 12 | 48
8/14/23 | 0 | 2 | 8.43598226 | 12 | 50
8/21/23 | 0 | 0 | 8.4029299 | 12 | 50
8/28/23 | 0 | 0 | 8.34776815 | 12 | 50
<img width="557" alt="image" src="https://github.com/Analyticsphere/metricsReportsRequests/assets/99832343/81370a51-e2e9-48f4-9d53-6c7b37a2e958">

**Comment by kmazzilli** [comment]
Hi @jeannewu the withdrawal+data destruction counts should be new cases in that week, not cumulative. For the rate, this is a new rate, which would be (number of withdrawals/number of invitations).

**Comment by jeannewu** [comment]
@kmazzilli thank you very much for your response and clarification on this new rate. And is the number of invitation a cumulative one by week or new cases of invitations by week? And can we make the unit of the rate as "/1000" because their ratio might be much smaller than 0.01?

**Comment by kmazzilli** [comment]
Hi @jeannewu for the number of invitations, we would like to see the invitations for that week. For the unit, I think that should be fine, thanks!

**Comment by jeannewu** [comment]
@kmazzilli sorry to bother you again. The refusal and withdrawal variables are a set of hierarchical variables: 22 out of 186 participants with withdrawal consent: d_747006172 requested data destructions (d_83104102) in the participants table(09052023). So for this refusal and rate plot, will you need me to create a time trend plot (two curves) for (new cases of withdrawal consent( d_747006172) and their rate/new invitations by week, or plus the new cases of data destructions by week also?

**Comment by kmazzilli** [comment]
@jeannewu no worries, so when a participant selects data destruction, it is a hierarchical choice, meaning that it automatically also triggers withdrawal. In a situation where a participant only selects withdrawal, but not data destruction, there is a timestamp captured for their withdrawal. Participants who request data destructions do not have a timestamp under withdraw (even though they are withdrawing), instead the timestamp shows up under data destruction only. We want to gauge how many people withdrew total: which means we need to assess who only selected withdrawal AND those who selected data destruction, since both situations count as a withdrawal. So, we would like to see one combined count for people who selected withdrawal or data destruction in one curve. And then we would like a second curve on the same graph for the rate of those same counts by invitation, so ((number of weekly withdrawals+destructions)/(number of weekly invitations)). Thank you, let me know if you have more questions.

**Comment by jeannewu** [comment]
@kmazzilli got it. Thank you very much for your clear explanation. So the plot should be included with two curves(data destructions, and its rate given by the # new cases of invitations by week.

**Comment by brotzmanmj** [comment]
Will we be able to distinguish the number of data destructions from the number of withdrawals on the curve if we do it this way? I think we need withdrawal without data destruction (one curve) and with withdrawal with data destruction (second curve).

**Comment by jeannewu** [comment]
@brotzmanmj Great. Got it.

**Comment by jeannewu** [comment]
@kmazzilli May you please let me know what order of this set of plots are in the weekly report? Are they after the time trend plots of verification activities (request 66) as a set of Fig5? Thanks a lot

**Comment by jeannewu** [comment]
@kmazzilli I put these plots after the Fig4 (for the request66) in the weekly report I sent to you and Amelia this Monday to check. Because the refusal and withdrawal cases are quite few in contrast to the invitations by week, the ratio of refusal+ withdrawal over the invitation is calculated as # cases per 1K invitations by week. If possible, may you please review these set of plots? Thanks a lot.

**Comment by kmazzilli** [comment]
Hi @jeannewu thanks for doing this and for checking in! Sorry for the delay. We took a look, and we have some feedback:

- We would actually like to remove the rate of cases/invitations off of the graph completely. 
- We would like to also remove the right y-axis. 
- The label on the left y-axis could read "# of withdrawals and data destruction requests". 
- For the orange curve, can the label say "Withdrawals only"? And for the red curve "Data destruction only"?

We would like to add 3 cumulative plots as well:

- The x axis would be time, the y axis would be the # of cumulative withdrawals and data destruction requests. 
- On this plot, we would like to see two trend lines. One for (#of withdrawals/# verified participants), the second for (#of data destructions/#verified participants). 
- We would like 3 of these plots total, one plot for all sites combined and then 2 additional plots for 2 groups of sites. Group 1 would be the KPs and University of Chicago. Group 2 would be the remaining four sites, HP, HFH, SF, MF.

- All of these plots could be moved down to after Table 33 and before Table 34.

Thank you!

**Comment by jeannewu** [comment]
Thank you very much for your comments @kmazzilli . I will update the plots without the ratio and add these three new cumulative ones by overall, KP sites total, non-KP sites total between Table 33 and Table 34. Should these updates be shown in the next week's weekly report, or later when they are finally reviewed and approved ?

**Comment by kmazzilli** [comment]
To clarify in your comment above: the 3 cumulative plots are overall, KP sites plus University of Chicago, and then the four remaining sites, HP, HFH, SF, MF. These updates don't need to go in the next weekly report, and we can wait to add once we have reviewed and approved. Thanks so much!

**Comment by jeannewu** [comment]
@kmazzilli Thanks for your prompt corrections. So the UoC would be added to the KP sites. And what is the plot title of these three plots?

**Comment by kmazzilli** [comment]
@jeannewu that's correct, thank you for clarifying. For these three the titles can read:
- Overall title: Cumulative Withdrawals and Data Destructions by Number of Verified Participants Through DATE Overall
- Group 1 title: Cumulative Withdrawals and Data Destructions by Number of Verified Participants Through DATE KPs and UChicago
- Group 2 title: Cumulative Withdrawals and Data Destructions by Number of Verified Participants Through DATE HP, HFH, SF, MF

 

That reminds me that for the weekly plots, we can change the titles now that we have removed the rates to:
- Weekly Counts of Withdrawals and Data Destruction Requests Through DATE Overall
- Weekly Counts of Withdrawals and Data Destruction Requests Through DATE SITE

**Comment by jeannewu** [comment]
Great. Thanks @kmazzilli

**Comment by jeannewu** [comment]
@kmazzilli Sorry to bother you again. I have a question on the cumulative plots of refusal withdrawals and data destruction plots. As you requested above: "On this plot, we would like to see two trend lines. One for (**#of withdrawals/# verified participants**), the second for (**#of data destructions/#verified participants**)", will you want plots of the ratio of ratio of (cumulative # of withdrawals/cumulative# verified, and as well as the ratio of (cumulative # of data destructions/ # cumulative verified) weekly? If so, the range of both ratio  till this week are: cumulative ratio of withdrawal/verified: (**0, 174/16144= about 1.08%**), and the cumulative ratio of data destruction/ #cumulative verified  (**0, 23/16144=about 0.14%**). Would you like to use this set of ranges of ratios to make the longitudinal plots?  Just double check. Thanks a lot.

**Comment by kmazzilli** [comment]
Hi @jeannewu for the cumulative plots we would just like to see the counts within the calculations for the two trend lines, so only (#withdrawals/#verified) and (#data destructions/#verified). Amelia and I will be out the next few days for a site visit at University of Chicago so we may not be able to respond. @KELSEYDOWLING7 can you provide assistance in the meantime? Thank you!

**Comment by jeannewu** [comment]
@kmazzilli So #withdrawals/#verified means the participants with withdrawals among the verified ones, not the ratio of the #withdrawal or data destructions and verified participants, right?

**Comment by jeannewu** [comment]
@kmazzilli I have done with all additional plots and put the updated report temporarily in [ ](https://nih.app.box.com/file/1311105779906). Please review it and let me know if anything is needed when you are available. Thanks a lot.

**Comment by kmazzilli** [comment]
@jeannewu @KELSEYDOWLING7 Thanks for your work on this, we have some feedback. There are two separate asks - there are weekly plots that we asked for as well as cumulative, so we would like to keep figures 5.1-5.9. The weekly plots will not have a ratio (so these look okay - but there is a spelling error in the y-axis label). For the cumulative plots, there should be a ratio on a second y axis (so it looks similar to Figure 1). For the ratio, we are a bit confused about what you are asking; this should be the # of withdrawals/ # of all consented participants [regardless of withdrawal status] and then a second ratio for # of data destructions out of the same denominator. Sorry for the confusion!

**Comment by jeannewu** [comment]
Got it. Thanks a lot. Don't worry, Kaitlyn. I will ask Kelsey for her helps in these days.

**Comment by kmazzilli** [comment]
Hi @jeannewu @KELSEYDOWLING7, thanks for your work on this. Some feedback:

1. The weekly plots look good, except the y axis label has a misspelling of the word "request".
2. The cumulative plots also share the above misspelling.
3. For the cumulative plots, can you add a second y axis on the right (so it looks similar to Figure 1) for the following two ratios. 1:  (# of withdrawals)/ (# of all consented participants [regardless of withdrawal status]) and 2: # of data destructions out of the same denominator?
4. A reminder to only post these plots in the "DCEG only" file for now while we are improving them, and once they are approved, they can be posted in "ALL".

Thank you!

**Comment by jeannewu** [comment]
@kmazzilli Thank you very much for your helpful response. And I will update the misspelling in the plots. And for the cumulative plots, the ratio of (# of withdrawals)/ (# of all consented participants [regardless of withdrawal status]) is quite small (the current cumulative withdrawals = 204 among 24212 consented participants (including 16634 verified participants). The accumulative ratio of the data destruction would be much smaller in 23 participants requested data destruction among the consented participants. If such ratios are what you need, what unit of the ratio would you like to have in the plot by % or by per 1000?

**Comment by jeannewu** [comment]
@kmazzilli the cumulative plots of refusal and withdrawals are shown in https://nih.account.box.com/login?redirect_url=%2Ffile%2F1316860043147&logout=true. the ratio of the refusal and data destructions are counted. by cumulative # consent withdrawal / cumulative request data destructions per 1000 consented participants. Please check them and let me know if anything is needed.

**Comment by jeannewu** [comment]
@kmazzilli as you requested "For the cumulative plots, can you add a second y axis on the right (so it looks similar to Figure 1) for the following two ratios. 1: (# of withdrawals)/ (# of all consented participants [regardless of withdrawal status]) and 2: # of data destructions out of the same denominator", this set of ratio curves among all consented participants are different from the current curves from the verified participants. After I checked with Kelsey, we both agree that If both sets of curves among different participants are shown in one graph, it might be confusing because the verified participants are the consented participants verified after their user profiles were submitted. How about your opinion?

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  essentially should the new denominator be among consented participants who are ALSO verified? Otherwise unverified but consented participants should be a different graph, as the denominators wouldn't be the same

**Comment by jeannewu** [comment]
@KELSEYDOWLING7 Thank you very much for your clear explanation for my questions on this plot.  @kmazzilli  As Kelsey explained, right now, **202 verified participants with consent withdrawal and data destructions are among 16635 verified** participants (with consents submissions). And they are mainly from **204 consented participants** with refusal and withdrawal **among 17935 consented participants**.  The ratio curves among the consented participants are not presented the cumulative plots of refusal withdrawals/data destructions among **verified participants** as shown in the title of the current graph.

**Comment by kmazzilli** [comment]
Hi @jeannewu and @KELSEYDOWLING7 
Thanks! 
For the cumulative plots, we would like four things to be shown:
1. The cumulative withdrawals as shown by the left y axis 
2. The cumulative data destructions as shown by the left y axis 
3. One trend line for withdrawals/consented participants (regardless of verification status). This can be per 1000 for the scale on the right y axis.
4. One trend line for data destructions/consented participants (regardless of verification status). This can be per 1000 for the scale on the right y axis.
5. Then this would prompt title changes for the three cumulative plots to say "by Number of Consented Participants" instead of "by Number of Verified Participants"

We also have some feedback just to clean these up a bit.
  
6. In both the weekly and cumulative plots, on the left y axis "And" can be lowercase and changed to "and"
7. In both the weekly and cumulative plots, in the legend, instead of "Data Destruction Only" can these labels read "Data Destructions"? We realized this would be more accurate.
8. In both the weekly and cumulative plots, could you change the yellow color that is being used for "withdrawals only" to something darker, maybe blue? The yellow may not come across well on presentations.
9. For the cumulative plots, can the colors used for withdrawals and data destructions carry over from the weekly plots? If we make the "withdrawals only" in the weekly plots blue (from  comment 8 above), can this also be blue in the cumulative plots? and then if the "data destructions" are red in the weekly plots, can these be red in the cumulative plots? And then two other dark colors should be fine for the remaining two trend lines in the cumulative plots.
10. In the cumulative plots, in the legend, can you remove the "#" from the labels for both trend lines, so they now read "Withdrawals per 1K Consented Participants" and "Data Destructions per 1K Consented Participants"
11. In the cumulative plots, can you also remove the "#" from the right y axis, so this now reads "Withdrawals/Data Destructions per 1K Consented"

**Comment by jeannewu** [comment]
@kmazzilli Got it. Clear. Thanks. and also thanks for your helps, too @KELSEYDOWLING7

**Comment by jeannewu** [comment]
@kmazzilli I have updated the plots with your comments and uploaded the report with new plots in Box [ ](https://nih.app.box.com/file/1317334727135) temporarily for you to check (Page 41-53, between Table 33 and Table 34). Please let me know if anything is needed. Thanks

**Comment by jeannewu** [comment]
Here is the link to the updated file in box[ ](https://nih.app.box.com/file/1317334727135)

**Comment by KELSEYDOWLING7** [comment]
@jeannewu  It looks like there's a slight typo in the title, it should be Consented instead of Conseneted. It also looks like the word "and" is missing from the left y axis between "withdrawals" and "data destruction requests". 


@kmazzilli  For the cumulative plots you mention wanting to remove the # from the y axes. Do you want the same for the weekly plots or is that ok as is? And is the orange/yellow ok in the cumulative plots, or should that change?

**Comment by jeannewu** [comment]
@KELSEYDOWLING7 Thank you very much for your careful check. I will correct this typo and add the "and" for the labels in y axes. 
@kmazzilli @KELSEYDOWLING7 please let me know if the colors of the curves are ok: (red, blue) for the # of withdrawals and data destructions, dark red/dark orange for the ratios.

**Comment by kmazzilli** [comment]
Hi @KELSEYDOWLING7 and @jeannewu 
Thank you both! 

The colors look okay, the blue definitely shows up better than the yellow.

I actually only wanted to remove the "#" from the right y-axis of the cumulative plots (number 11 in my last comment). The "#" can stay for the left y-axis of the cumulative and weekly plots, and these can look the same for consistency's sake.

So a couple things we would like to request:
1. The "#" that can remain in the left y-axis of all three cumulative plots
2. The typo ("Consented" in the title) in the 2 grouped site cumulative plots and missing word ("and") in the left y axis of all 3 cumulative plots that Kelsey mentioned. So the left y axis of the cumulative plots should read "# of Withdrawals and Data Destruction Requests" to be consistent with the weekly plots.
3. For the cumulative plots - the scale of the right y axis looks good on the overall plot. For the two grouped site plots, can the right axis scale also contain one decimal point, just to be consistent with the overall plot? 
4. It also looks like there is a "2" and "5" on the right y axis scale of the HP, HFH, SF, MF plot that look out of place, and a "2" on the scale of the KP and UC plot that looks out of place, can you remove these?

Thanks so much!

**Comment by jeannewu** [comment]
@kmazzilli  and @KELSEYDOWLING7 Thank you very much for your helpful comments. All the plots have been updated with your comments. Please check it in the box:[ ](https://nih.app.box.com/file/1320129801109) Thanks

**Comment by jeannewu** [comment]
@kmazzilli may you please help me check the updated plots in[ ](https://nih.app.box.com/file/1330677335997). Please let me know if the plots are approved for the weekly report. Thanks a lot.

**Comment by jeannewu** [comment]
@kmazzilli the weekly report with the new plots is[ ](https://nih.app.box.com/file/1330677335997). In case, I couldn't see this link on my side in GitHub.

**Comment by kmazzilli** [comment]
Hi @jeannewu,

For the cumulative plots:

1. On the overall plot - the right y axis needs to include one decimal point. It looks like that was removed this round but we had wanted to keep it (number 3 in my last comment)
2. On the HP, HFH, SF, MF plot - The "5.0" on the right y axis scale still needs to be removed.

Thanks so much!

**Comment by jeannewu** [comment]
Hi, @kmazzilli,

Thank you very much for your careful check and helpful comments

I have updated the plots as you suggested; 
 a. On the overall plot -the right y axis needs to include one decimal point. 
 b On the HP, HFH, SF, MF plot - The "5.0"s on the right y axis scale are removed from the plots.

Please check them:[ ](https://nih.app.box.com/file/1330677335997).

Thanks a lot.

Jing

**Comment by kmazzilli** [comment]
Hi @jeannewu 
Thanks for making those changes. However, I see that for the 2 grouped site cumulative plots there are typos in their Figure names:

1. For the cumulative HP, HFH, SF, MF plot, the Figure name currently reads "Figures 5.11". Can you change this to say "Figure 5.11"
2. For the cumulative KP and UC plot, the Figure name also currently reads "Figures 5.11". Can you change this to say "Figure 5.12"
 
Thanks,
Kaitlyn

**Comment by jeannewu** [comment]
Hi, Kaitlyn,

Thank you very much for your careful check.
I've just updated the figure number in the report as you pointed out here and the new report is now in Box  [](https://nih.app.box.com/file/1331779626108) right now. Please check them again. Thank you very much. Jing

**Comment by kmazzilli** [comment]
@jeannewu it looks like they still say "Figures" plural. Please change these two figure names to say "Figure 5.11" and "Figure 5.12".

**Comment by jeannewu** [comment]
Hi, @kmazzilli Thank you very much for your patient check. The "s"s  have been removed from the Figure 5.11 and Figure 5.12. (seen[ ](https://nih.app.box.com/file/1331779626108)). Thank a lot

**Comment by KELSEYDOWLING7** [comment]
Good morning @kmazzilli  based on yesterdays report it looks like this last error has been resolved

**Comment by kmazzilli** [comment]
Thank you, this should be good to get posted to ALL

**Comment by kmazzilli** [comment]
Hi @KELSEYDOWLING7 We tried to use these metrics today and it looks like some of these might have data from 10/16/23. I think this is similar to issue 74 that was just open - could you double check that these (weekly and cumulative) "go through the last complete week when data are available on the Monday-Sunday schedule we defined for the Weekly Logs"? Thanks!

**Comment by jeannewu** [comment]
@kmazzilli & @KELSEYDOWLING7 all the plots in the Operational weekly report are updated with the date:[ ](https://nih.app.box.com/file/1335932078254) and [ ](https://nih.app.box.com/file/1335929762227). Also one participant( Connect_ID= 3986012152) with refusal withdrawal doesn't have the date of the refusal and withdrawal time (d_659990606) and he/she is excluded from this week's report

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  Yes, 74 has that issue that Michelle just opened. I believe it's now resolved so I will comment on that page separately. As for this issue with the Figure vs Figure 5.11 and 5.12, that has been resolved.

**Comment by kmazzilli** [comment]
@KELSEYDOWLING7 Please correct me if I am wrong, but it looks like for all of these figures (weekly and cumulative) that there are data points up through 10/16?  We would like to go up until the last complete week when data are available. Thanks!

**Comment by jeannewu** [comment]
@kmazzilli as Michelle mentioned before all the weekly and cumulative data (as the weekly log ones) are listed as a cycle of  "Monday-Sunday". So all the data on Monday would be reported in the next cycle not in this week's report.

**Comment by jeannewu** [comment]
I mean the data on Monday (e.g. Oct. 16) which the report is done would not be reported in the weekly log or as well as not in the weekly or cumulative plots.
