### ISSUE TITLE
Ad hoc metrics to prep for UC Sept 2023 Site Visit

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#68]
Hello Kelsey, we will be visiting the UChicago site next week (leaving 9/19) and would like to have some more detailed metrics prepared and compiled to review before we go. Could you please provide us with the following metrics in an ad hoc report? These will just be one-off metrics for the site visit. No need to run these on a timed interval or add to the Biospecimen Weekly Report, unless noted below (there’s 2 metrics we would like to have for the meeting report but also updated in the Biospecimen Weekly Report). 

Domonique is out this week, so Kaitlyn and I can help with any questions you have. Also – I think Michelle will be pulling you into the mouthwash survey issue which will take priority of these site visit metrics so make sure to check with her and Nicole on Priorities:

**Metrics just for the UC site visit (only need these metrics for the UChicago site, not overall or by other sites):**
- Please create a table metric for the biospecimen survey response rate that is stratified by the following demographics: income, education, age, race, sex. These demographic vars would come from Mod1 survey data.
     - Based on the distribution of the categories in each var, you could collapse/combine some of the categories by distribution (e.g. for education have college education and above vs everyone else)
     - The purpose of this metric is that we are trying to figure out if people with low income/less technology are filling out the biospec survey at same rate as others with higher income/access. 
- Please provide a table that shows a count of how many people at UC complete the baseline survey before vs. after check-in. Please also stratify this metric by the same Mod1 demographics above.
- Please provide a time trend plot that shows count of verifications of UC stratified by active and passive recruits. Two separate lines on one plot. (No need to pull in any biospec data into this one)

**Add to metrics for UC site visit + update in Biospecimen Weekly Report as well**
- Figure 1. Weekly Percent of Incomplete Blood Draws, University of Chicago Medicine:
     - Please split out this time trend of incompletes by partial vs. no collection where each would be a separate line on the same plot
- Table 14. Baseline Research Biospecimen Survey Status by Site:
     - Please update this table to start Feb 2023
     - Please add a second table after this that is the same table but only has data starting July 2023 when the COVID qx came out. 

**Requested by:** Amelia Roberts
**Approved by:** Michelle Brotzman and Stephanie Weinstein

**Comment by HopkinsDC** [comment]
I'm closing this issue; the items listed under "update in Biospecimen Weekly Report" will be entered under their own GitHub issue.
