### ISSUE TITLE
Bio Weekly - Table 7.3 Update

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#70]
Please see the list of HFH's clinical location names and corresponding Location IDs (BioClin_SiteBlLocation_v1r0) and incorporate the names into Table 7.3 (clinical blood draw completeness) for when the IDs are pushed to NCI.

1040010047 = West Bloomfield (WBH)
1050010095 = Wyandotte
1060170018 _or_ 1060010063 = Macomb
1011410008 = Royal Oak
1010180040 = Fairlane (Dearborn)
1011220006 = West Bloomfield (Bloom TWP)
1010120026 = Novi
1011660013 = Plymouth
1010360011 = Troy
1010010193 = K1 HFH Main

**Notes:**
- Some of the locations are not active yet, but please program all IDs into Table 7.3 so collections from the locations are recognized immediately once they are active.

**Requestor(s):** Biospecimen Team

**Table or Figure title:** Table 7.3 Blood Completeness among Henry Ford Baseline Clinical Collections by Clinic Location

**Metrics to be updated or created:** Update existing table

**Variables needed (include variable name and Concept ID):**
- BioClin_SiteBlLocation_v1r0 (185243482)

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Approved by:**Domonique

**Comment by HopkinsDC** [comment]
Updated Table 7.3 looks good and can be added to the next biospecimen metrics report (9/25).
![Screenshot 2023-09-20 at 2 23 06 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/e731dd00-b198-4d92-bd4b-41c9375e0770)

**Comment by HopkinsDC** [comment]
Please add the following location names/location IDs to Table 7.3 for HFH

- 1040010046 = West Bloomfield (WBH); this is the same location name as - 1040010047 (already exists), so both IDs should populate under West Bloomfield (WBH)
- 1010240013 = Livonia
- 1010320019 = Sterling Heights
- 1010010114 = K1 HFH Main; this is the same location name as 1010010193 (already exists), so both IDs should populate under K1 HFH Main

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
We current have 1010240013 as Plymouth, not Livonia

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 In the initial list of IDs above, Plymouth is 1011660013.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  My mistake! I was focused on the first two and last three numbers and thought they were the same. Do we need the placeholder column of no blood tubes collected? Or can we keep this out until we have figures to put in it?  I have to manually put 0 (0%) row# of times, but every time the number of rows changes as more sites are used, it breaks the code

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 No worries. We can keep them out until we have true values for them; since they aren't active yet, this should be fine. Thanks!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
Great thanks! Here's the updated table

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/11176de1-c5b0-442c-8ed4-f37e1262c17f)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Sorry for the delayed response to  this, but it looks good. Thanks!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hey Kelsey. Hopefully, this is the last time these locations will need to be updated! Please see the list of clinic locations and their location ID(s) and update Table 7.3 with the location names.

1. Macomb = 1060170018 _OR_ 1060010063
2. West Bloomfield = 1011220006 _OR_ 1040010046 _OR_ 1040010047
3. Wyandotte = 1050010095
4. Fairlane (Dearborn) = 1010180040
5. Plymouth = 1011660013
6. Royal Oak = 1011410008
7. Troy = 1010360011
8. K1 HFH Main = 1010010114 _OR_ 1010010193
9. Sterling Heights = 1010320019
10. Columbus = 1010120026
11. Livonia = 1010240013

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok no problem! Do you want all West Bloomfields on one line then, as opposed to the current "West Bloomfield Hospital" for 1040010046 OR 1040010047, and then 1011220006 as "West Bloomfield Hospital (Blood TWP)"? 

And Novi is now called Columbus?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, all 3 IDs can all be counted in one row under the name "West Bloomfield Hospital". 

And yes, change the name "Novi" to "Columbus"; the ID is the same.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/46152184-62a5-4310-938b-e298e9c76596)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Can you remove "Medical Pavilion" from Macomb's name and remove "Hospital" from West Bloomfield's and Wyandotte's names?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/71af0b07-2f25-4987-9f30-e4179a70167a)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you. Lastly, can you add the percentages to the Total row and column?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Do you want that updated for tables 7.1 and 7.2 as well? Those also currently only have a count for the Total column

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, please do.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/42b3c2f1-91c0-446d-ba5d-e10347fa9f65)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c58416ce-0350-4df7-9729-f3b83ab3af80)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/fc0f60d4-b5a9-4f8e-92ee-443329534d3a)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Please also add the percentages for the last row (342, 2, and 344); I'm sorry if that wasn't clear before.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  I'm not sure that would make sense, since these percentages are calculated by row not by column. For example, all blood tubes collected are 100%,100%....98.7% so 100% at the end next to 342 doesn't seem to make sense with the way the table is currently structured.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The table has row percents, so the last row should be 342 (99.4%), 2 (0.6%), and 344 (100%).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Oh, ok that makes sense. Sorry for the confusion.
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/becd54d9-d15f-4dd2-b0b4-672380048a20)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/3d8b909a-7687-40f1-9026-5a47ad3a7f32)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5ad26e31-2183-48ea-aa08-1a05be910915)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 No worries! These look great. Thanks!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This table looks good in today's report, but it looks like we have another unknown location ID. Can you find out what this ID is so I can ask HFH about it?

![Image](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/54dc702a-7661-4457-bc17-b6aa12f705e3)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  I'm sorry! That's been updated

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/8516c641-09ef-47ba-a498-3e05d868909a)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Do you want the current version in the ALL folder deleted and replaced with this fixed?

**Comment by HopkinsDC** [comment]
Table is up to date and correct in 11/27 metrics report.
