### ISSUE TITLE
Update QC Rules to include STRECK Tube

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#71]
A STRECK Tube (0060) will be added to baseline collections. Please update the relevant QC rules to include it **[after DevOps adds it to the biospecimen dashboard](https://github.com/episphere/connect/issues/620)**.

Helpful Variable Names:
- STRECKTube1_BioCol_TubeCollected_v1r0
- STRECKTube1_BioBPTL_DateRec_v1r0
- STRECKTube1_BioCol_Discard_v1r0

Note - HealthPartners will pilot the implementation of the STRECK tube; it will replace the ACD tube for collections. Blood completeness must be adjusted to consider blood draws complete if the 5 research tubes are collected, whether with an ACD tube or a STRECK tube being the 5th tube; both will not be collected simultaneously.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Can do! Please let me know once it has been added to prod and HP has had its first collection

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  The Non-KP clinical sites refer to only HF for now, and eventually Sanford correct? Or is HP in that list as well? I'm not sure if I just had a typo above or if HP was mentioned elsewhere

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 HF is the only active clinical non-KP site currently. Eventually, Sanford and HP will be included when they launch clinical collections.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Forgot to let you know these are now in prod and have been included in the rules checked on Monday's for the past few weeks

**Comment by HopkinsDC** [comment]
QC rule performing as expected; production data files reviewed to confirm. Closing this issue but will continue to monitor in weekly QC error reports.
