### ISSUE TITLE
Exclude HP from Tables 24, 25 & 26

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#72]
HealthPartners will not push data values for clinical draw order placement to NCI. Please exclude HP from Tables 24, 25, and 25 in the weekly biospecimen metrics report.

**Requestor(s):** Biospecimen Team

**Table or Figure title:** 
- Table 24. Time (in Days) from Verification to Draw Order Placement
- Table 25. Time (in Days) from Draw Order Placement to Clinical Collection by Site
- Table 26. Clinical Blood Draw Order Status Among Verified Participants

**Metrics to be updated or created:** Update existing table

**Variables needed (include variable name and Concept ID):**
- RcrtES_Site_v1r0 = 0 (HealthPartners)

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Hi Domonique, this is already the case. Table 24, 25 and 26 only include KPCO, KPGA, KPHI, KPNW and HF.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 HP hasn't started clinical collections yet, so HP isn't in the report tables currently, but when they do start clinical collections, they will not have data for these metrics tables. 

The tables should be set up to include all clinical collections, which would include HP when they start; this should remain the case. HP needs to be excluded by name, as Sanford will eventually be starting clinical collections and should be included in these tables.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC To specify, those tables are not filtered for just any clinical site data. They are filtered to ONLY look at the data of the 4 KP sites and HF.  So HP will not show regardless of clinical collections.

 Once Sanford starts clinical collections, I can add them to that select list.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Oh, I see! Thank you for clarifying this; I assumed all of the clinical metrics were coded by collection setting. These tables should be good for now, then. 

Are there any other clinical metrics tables filtered this way, or do they have a clinical collection setting denominator?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Np! 

Tables 10, 13, 15, 17, 22a and 22b are the same, KPs+ HF only. 
Tables 5b, and 9 are all clinical sites. 
Table 19a and 19b are all those that have completed a clinical BU survey, so site is not specified in the filter.

**Comment by HopkinsDC** [comment]
Tables 10, 13, 15, 17, 22a, 22b, 24, 25, and 26 should be all records with a clinical collection setting (650516960=1), like Tables 5b and 9.

Add a site filter to Tables 24, 25, and 26 to exclude HP. 

Tables 19a and 19b can remain as is.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Most of the tables were able to be adjusted and look exactly the same, as they should. Only Table 26 is causing issues when I change from Site=KP+HF to setting=clinical and Site!=HP


It goes from this:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/83c5ab89-229d-4e09-8dbf-54836c5693cd)




To this:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/7a83ad31-6f35-4264-bfc0-3d52f356f742)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Based on the production data file, it's possible for a setting to be NULL and have a draw order placed, so for Table 26, it's probably best to keep it as is and additional sites will have to be manually added.

It's good to hear the other tables are good.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thanks for clarifying! Ok the code's been updated to reflect these changes and the tables are all the same.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Great! This issue is complete.
