### ISSUE TITLE
Operations Report Remove Footnote Table 9

### ISSUE THREAD

**Issue by kmazzilli** [Analyticsphere/metricsReportsRequests#73]
Requestor(s): Kaitlyn Mazzilli and Amelia Roberts

Metrics to be updated or created: Operation Weekly Metrics

Notes: We would like to remove this footnote from Table 9 on the operations report: 'Note: KP sites not yet sending data for Manual Verification and Outreach category.' 

Approved by: Michelle Brotzman

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  Hi Kaitlyn, Jing and Jake are still working on the code automation and I didn't want to have that break. So Jing was able to update this table in her code.


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/06348b8a-287d-40c7-b760-9bb850924334)

**Comment by kmazzilli** [comment]
Great, thanks!
