### ISSUE TITLE
Bio Weekly - Update Location Name in Figure 9.1

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#78]
In the 10/23 weekly biospecimen metrics report, there is a collection location with the name "NA" in Figure 9.1. Please update this location name to "MF Pop-Up"

![Screenshot 2023-11-01 at 12 13 45 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/33128e12-15f7-4130-97f6-2680a85edc6b)

**Requestor(s):** Domonique

**Table or Figure title:** Fig 9.1 Weekly Biospecimen Collections at Marshfield Clinic Health System Locations

**Metrics to be updated or created:** Update existing figure

**Variables needed (include variable name and Concept ID):** BioSpm_Location_v1r0 (951355211) = 18 (MF Pop-Up; 319518299)

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thanks for pointing that out! Looks like there's 3 new BioSpm_Location variables (MF Pop-up, UCM Pop-up, Orland Park). Just added them. Orlando Park and UCM Pop-up just don't have data yet

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/128f8c17-6880-48ed-8432-6c5e947814be)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks good, and thank you for adding the other two locations as well. 

This can be included in the next scheduled metrics automation update.

**Comment by HopkinsDC** [comment]
Update successfully implemented in 11/6 weekly biospecimen metrics report.
