### ISSUE TITLE
Ad Hoc - UChicago Biospecimen Metrics Report by Collection Location

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#79]
Please generate a metrics report that includes biospecimen metrics for UChicago only. All tables should be by collection location (i.e., Ingalls Harvey, River East, South Loop, UC-DCAM). A mock-up of the tables is included below, with comments indicating the metrics table in the weekly biospecimen metrics report the new table is similar to.

[UCM_Collection Location Metrics.docx](https://github.com/Analyticsphere/metricsReportsRequests/files/13251716/UCM_Collection.Location.Metrics.docx)

**Requestor(s):** Domonique

**Table or Figure title:** N/A

**Metrics to be updated or created:** New ad hoc metrics report

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Just to give you an update, table 5 is giving me some trouble but other than that this is almost done!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Was able to fix it faster than I expected! Let me know how this looks


[Ad-Hoc-UC-Biospecimen-Metrics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13379619/Ad-Hoc-UC-Biospecimen-Metrics.pdf)

**Comment by StephanieWeinstein** [comment]
@KELSEYDOWLING7 , Michelle and I will look at this.

**Comment by KELSEYDOWLING7** [comment]
Hi @StephanieWeinstein is it alright to close this issue or is it still ongoing review?

**Comment by StephanieWeinstein** [comment]
Hi @KELSEYDOWLING7 , thanks for the reminder!  Could you run this against the most recent data?  That will add at least one other site (Orland Park).  Thank you!

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  Of course! Please see below

[Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14364125/Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf)

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  Of course! Please see below

[Ad-Hoc-UC-Biospecimen-Metrics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14364130/Ad-Hoc-UC-Biospecimen-Metrics.pdf)

**Comment by StephanieWeinstein** [comment]
Thank you so much Kelsey.  We will review this together as a team (there are some interesting findings here). @erincschwartz , can you put this on our to do list to talk about next week (before the next Chicago call)?  @KELSEYDOWLING7 , you can close this, but we may re-open it after we have done a thorough review if we find we need anything else.

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  Happy to help! Ok that sounds good, I'll close this for the time being then
