### ISSUE TITLE
Bio Weekly - Correct Table 4 Footnote

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#82]
Please remove the second "Note:" in Table 4's footnote.

![Screenshot 2023-11-07 at 12 51 44 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/30472466-63da-4922-8125-46133ca67e6d)

**Requestor(s):** Domonique

**Table or Figure title:** Table 4. Data System Status Among Baseline Clinical Collections by Specimen Type

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/cfb7ea49-1380-46ff-a468-0bfb89f4050e)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you!

**Comment by HopkinsDC** [comment]
Update successfully implemented in 11/20 weekly biospecimen metrics report.
