### ISSUE TITLE
Bio Weekly - Correct Table 22a/22b Footnote

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#84]
Please remove the second "Note:" in Table 22a/22b footnote.

![Screenshot 2023-11-07 at 1 04 28 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/3df11052-3b61-422f-8725-4fdcf83d6f3c)

**Requestor(s):** Domonique

**Table or Figure title:** 
- Table 22a. Time (in Days) from Verification to Baseline Clinical Collection for Participants Verified Before 02/01/2023
- Table 22b. Time (in Days) from Verification to Baseline Clinical Collection for Participants Verified on or After 02/01/2023

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9de9f477-271e-4ada-a87d-cfc65dc133ae)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you!

**Comment by HopkinsDC** [comment]
Update successfully implemented in 11/20 weekly biospecimen metrics report.
