### ISSUE TITLE
Bio Weekly - Add Footnote to Table 12b

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#85]
Please add the following footnote to Table 12b:

Note: _Short Draw_ reason applicable to blood collection tubes only.

**Requestor(s):** Domonique

**Table or Figure title:** Table 12b. Reason Not Collected for Tubes Not Collected at Research Collection Visits by Tube Type

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c4ab4863-1162-4524-8590-4691ee19a4ee)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Can you put Short Draw in quotations ("Show Draw")?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Yup!

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f76d9ea1-1d4b-42d8-b75e-13242e548c12)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This is so nit-picky of me, but can you make those double quotations for Short Draw?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Sorry, I can't actually do that because double quotes inside double quotes doesn't work in R; I already have "Note: 'Short Draw' reason applicable to blood collection tubes only." So it breaks if I add a second layer of double quotes

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, no problem. This issue is good to go then. Thanks!

**Comment by HopkinsDC** [comment]
Update successfully implemented in 11/20 weekly biospecimen metrics report.
