### ISSUE TITLE
Bio Weekly - Correct Table 23 Footnote

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#86]
Please remove the "a" superscript from Table 23's footnote.

![Screenshot 2023-11-07 at 1 22 38 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/16ba1e3a-e534-4a01-af5e-22dcd4f9f16f)

**Requestor(s):** Domonique

**Table or Figure title:** Table 23. Time (in Days) from Verification to Clinical Baseline Collection for Participants Verified After 06/01/2022, by Campaign Type

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**  Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5e171f7f-7ab8-4165-bd45-9b6e987cdc1d)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thanks!

**Comment by HopkinsDC** [comment]
Update successfully implemented in 11/20 weekly biospecimen metrics report.
