### ISSUE TITLE
Bio Weekly - Add Tables for Collections by Location

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#87]
Generate two new metrics tables: (1) research collections by collection location and (2) non-KP clinical collections by clinic location. 

All locations should be included in the code, but it is okay if all do not populate in the tables (they may not be live yet; "UCM Pop-Up" for example). 

Please create sub-rows in a table, with the site name as the main row and its locations as indented sub-rows (see mock-ups below for example). Each site's row should count all collections at all of the locations (100%), and the sub-rows of each site should add up to the count in the site row.

**Requestor(s):** Domonique

**Table or Figure title:** 
- Table 1.1  Baseline Research Biospecimen Collections by Collection Location
- Table 1.2  Baseline Clinical Biospecimen Collections by Clinic Location

**Metrics to be updated or created:** Create new metric tables

**Variables needed (include variable name and Concept ID):** 
- BioSpm_Setting_v1r0 (650516960) - Collection setting (research or clinical)
- RcrtES_Site_v1r0 (827220437) - Sites (Non-KP sites only) 
- BioRec_CollectFinal_v1r0 (410912345) - Complete Collections
- BioSpm_Location_v1r0 (951355211) - Research Locations
- BioClin_SiteBlLocation_v1r0 (185243482) - Clinic Locations 

**Specify numerator and denominator by variable name where applicable:** N/A

**Table 1.1**
- Denominator = Complete research collections (650516960 = 0; 410912345 = 1)
- Numerator = Non-KP sites research collection locations (827220437 = 0, 1, 6, 7, 8; 951355211)

HP - 951355211 = 4
Henry Ford - 951355211 = 5, 6, 7
Marshfield - 951355211 1, 2, 3, 12, 13, 14, 15, 16, 18
Sanford - 951355211 = 8, 17
University of Chicago - 951355211 = 9, 10, 11, 12, 19, 20

**Table 1.2**
- Denominator = Complete clinical collections (650516960 = 1; 410912345 = 1)
- Numerator = Non-KP sites clinic locations (827220437 = 0, 1, 6, 7, 8; 185243482)

HP - 185243482
NSC = 1
Elk River = 2
Chanhassen = 3

HFH - 185243482
Macomb = 1060170018 OR 1060010063
West Bloomfield = 1011220006 OR 1040010046 OR 1040010047
Wyandotte = 1050010095
Fairlane (Dearborn) = 1010180040
Plymouth = 1011660013
Royal Oak = 1011410008
Troy = 1010360011
K1 HFH Main = 1010010114 OR 1010010193
Sterling Heights = 1010320019
Columbus = 1010120026
Livonia = 1010240013

**Mock-up table if applicable:**

![Screenshot 2023-11-07 at 4 22 43 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/091f18bb-30d8-41e6-8722-ddae2f787cec)

![Screenshot 2023-11-07 at 4 17 39 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/6f0cb430-24e6-42d3-8fcf-c89b27004662)

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Should HFH Cancer Pavilion Research Clinic be included in 1.1?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes! Sorry, I must have mistakenly left that one out of the mock-up. Thank you for catching that!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Of course! Also I'm not seeing any participants with d_173836415_d_266600170_d_185243482= 1 or 2 or 3 for the HP sites. Does that sound right?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, that's right. I don't think HP has collected their first clinical collection yet.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Last question! For table 1.2 do you only want counts of clinical blood collection and not clinical urine collections? Since the variable 185243482 is just for blood location

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Any complete clinical collection should be counted, whether it is blood only, urine only, or both. You can use the blood location ID (185243482) or the urine location ID (452847912) to get the location; it can be assumed that they are the same if both are present. If one is not populated, the other can be used.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Great, thanks. This is where I'm at for these tables right now. The percentages are proving to be difficult so I'll have to keep looking into this for next week. I may not be able to do a full count and 100% next to each Site, but I should be able to do a per site collection count

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0074e412-925d-47aa-a225-d67e1df13967)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/32c5ab08-fd18-4754-83a5-48fae3bda8f4)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Got the percentages! Does this work or do we definitely need the grouped counts?
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/73869b7a-8d39-4cc2-a9a5-076d061d5a1b)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9fe54034-01a7-41a8-9fc9-6e018b673682)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks great! We will definitely need to total group counts for each site. If you can't add it to the same row as the site name, maybe adding a "Total" sub-row below the locations that adds them together would work better (example below)?

![Screenshot 2023-12-19 at 11 56 34 AM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/beff344c-ae3e-4e89-9a43-e3a0300382a5)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Got it!! Sorry the delay and all the back and forth 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/51675bd8-f8e0-452b-bfd8-158a70b7c996)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/32b939ba-9f48-47f5-ae84-58f7a822152a)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks perfect; thank you! One last thing: HP now has clinical collections, so Table 1.2 should include those in production.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thanks for the heads up. Here's that table updated

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/34d1ddcf-92be-4ad0-ae9b-8a4aa23d5aa5)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Looks good, thanks!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Table 1.2 is out of order in the 1/8 report. Please move it up to come before Table 2.

**Comment by HopkinsDC** [comment]
New tables implemented in 1/8 weekly biospecimen metrics report; corrections made and report was re-ran on 1/9.
