### ISSUE TITLE
Bio Weekly - Confirm Streck Tube Addition in Metrics Tables

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#89]
Please confirm the code for the following metrics tables account for the addition of the Streck tube.
- Table 8. Blood Tubes Not Collected Among Partial Blood Collections at Research Collection Visits
- Table 10. Blood Tubes Collected by Tube Type at Clinical Collections
- Table 12b. Reason Not Collected for Tubes Not Collected at Research Collection Visits by Tube Type
- Table 13. Number of Tubes Discarded by Type and by Site

**Requestor(s):** Domonique

**Table or Figure title:** Table 8, 10, 12b, and 13

**Metrics to be updated or created:** Update tables (if needed)

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Right now Streck Tubes are 0 for table 8 (making 12b not having a streck tube row and 13 not have Streck Tube column) and Streck Tubes are 0 for table 10  . Does that sound correct?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, that would be correct for 8, 12b, and 13 with complete collections with no discards; from the manifests, this seems to be the case for the 12 collections HP has so far.

I'm assuming 10 is fine as well, but I would need to confirm that the 12 collections from HP are all research collections; they likely are.

I'll consider this complete and confirm it in next week's report/prod data files. Thank you for checking these!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok thanks! So I won't change the tables for now, that way they don't break on Monday. I'll keep an eye on these tables over the next 2 weeks as more data come in and more Streck tubes are available for participants. and update these tables as they do

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 There are 4 partial blood collections from HP between 11/20 and 11/30 that didn't have a Streck tube (or an ACD tube) collected; I've included the Connect ID and Collection ID for these collections below. The Streck column/row should be showing up in Tables 8 and 12b for these collections. Can you look into why they are absent?

1. 6430902259 - CXA019198
2. 7005783030 - CXA019250
3. 5847846168 - CXA019244
4. 6383937121 - CXA019185

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Weird, these aren't showing up in the tables in the code and I double checked that they're finalized collections in BQ. Are these possibly from hybrid collections? Tables 8 and 12b only look at research settings

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 No, they are all research collections; HP still doesn't have any clinical collections yet.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Sorry for the delay
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0ca5fa96-6267-4877-9f60-647477987814)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d567de6b-76e8-4b67-8349-d885cc49cf45)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e093ac3e-d139-40ac-aa8d-b5a87fe93faf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 No worries! These tables all look correct. 

(As a note for myself for later, the biospecimen team may need to reevaluate how data in Table 8 is presented)

**Comment by HopkinsDC** [comment]
Update successfully implemented in 12/18 weekly biospecimen metrics report.
