### ISSUE TITLE
Wkly Modules - updates to metrics

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#9]
Overall changes:
1. Update all metrics to limit to only verified participants and update table titles to include 'among verified participants'
2. Add N count to all tables w/ percentages e.g. N(%) 
3. Please change time durations from hours to minutes and include unit in title

Metric specific changes:
4. For table 3: Duration from start to submission for each module, please separate out the percentiles vs duration to complete the module into separate tables. For the latter please add N(%)
5. For table 5: % Submission of surveys by verified participants, please move this to the top as table 1 and revert back to showing all possible combinations so that we can hopefully catch anyone in an impossible combination (e.g. completes mod2 and mod4 without completing mod1)

Stratification
6. To the top of page with N Verified count, please add counts for number verified before all modules were in app vs. after (once we know the date)
7. Please stratify the metrics by pts verified before all modules were in app vs after. You can display this whichever was is best. For table 2 Time in hours from verification to completion of each module, you can just stratify module 1 and then for mod2/3/4 only show  data for those who were verified _after_ all 4 modules were in app.

ON HOLD
8. Please convert report to R output tables so that you are not needing to manually insert the data into word. (Note, this is on hold until we can figure out the best path forward for this).

**Comment by robertsamm** [comment]
Hi Kelsey, Michelle and I reviewed last weeks report and it's looking great! Thanks for making all these different updates. A few updates below.

1. At the top of the page where you clarify the verified before/after can you make sure to mark that the 'after' date is 'on and after' 7/5?
2. Table 1 - please also stratify this one by before/after all modules in app. 
3.  Table 3 - Change labels for ‘Before’/’After’ to ‘Before All Modules Available’ and ‘After All Modules Available’ and carry to rest of the tables that are stratified 
4. Table 3 - looks good but still hard to conceptualize. Considering adding in a categorical measure (e.g. Completed Before Verified, etc). Michelle going to run past the Questionnaire Cmte. So no changes needed at this time just wanted to let you know.
5. Table 4 - The percents don't add up to 100 in either the columns or the rows for 'percentage completed. Can you look into this? I think this should be column percents. Please also add N to the 'percentage completed'
6. Table 5 - please add N for ‘No surveys completed’ and ‘at least 1 survey completed’
7. Table 7 - can now remove the Connect IDs for menstrual cycle survey

**Comment by KELSEYDOWLING7** [comment]
Thanks! These updates have been made and will be reflected on next week's report. 

I was also able to start some of the automation of the tables. For number 2, I was able to create a very similar table to what I had before, but adding the percentage per recruitment flag (ex: 13.1% of active participants haven't started Module 1) I am having issues with. Please compare the two and let me know if this replacement will suffice, or if that information is also crucial to have in this table. If it's hard to see them here I can upload them to the draft metrics box location instead. 


![Existing table](https://user-images.githubusercontent.com/101136647/197614855-3ef3c10f-d4aa-4ac7-bfd9-4ba9e69f9ad1.PNG)
![Possible Replacement](https://user-images.githubusercontent.com/101136647/197614925-2b987974-9497-4683-b57f-b4d470e57c63.png)

**Comment by KELSEYDOWLING7** [comment]
I was able to automate the report and uploaded it this morning. Please let me know what you think or if anything needs to be changed

**Comment by FrogGirl1123** [comment]
@robertsamm and @KELSEYDOWLING7, can this issue be closed?

**Comment by KELSEYDOWLING7** [comment]
My last report update was done the week BQ crashed so technically they haven't been able to see the output with all requested updates with live data

**Comment by robertsamm** [comment]
Yes, it would be good to see a final product before closing out. @KELSEYDOWLING7 are you able to run it on the data from before BQ1 went down? I think we weren't expecting it to be down so long which is why we were waiting but I'm happy to review using the 10/26 data if that's easiest.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Ok, I think as far as that date I could filter the data by those verified prior to 10/26 and run the report accordingly. The percentages of non-completed surveys might be a bit high if they were verified closer to that date, but it can give you a visual idea of the report at least

**Comment by KELSEYDOWLING7** [comment]
I was actually able to run it as is, as the prod data doesn't have anyone verified after that data anyways. I am also still working on methods to adjust the width of wider tables. I haven't been able to do so thus far, but Jing mentioned some package that may be able to help. I'll be discussing that with her tomorrow. 

Please see the file attached and let me know if you have any issues accessing it. 
[CCC-Weekly-Module-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10178401/CCC-Weekly-Module-Metrics-RMD.pdf)

**Comment by robertsamm** [comment]
Hi Kelsey, these tables are looking great. For my review I looked at [this metrics report](https://nih.app.box.com/file/1088836587028) but looked at the updated [smaller tables](https://nih.app.box.com/file/1088845200803) for tables 2 and 4. Feedback below. 

1. At the top of the page change labels for 'Verified participants prior to and on or after 7/5/22' to 'Participants Verified Before All Modules Available' and 'Participants Verified On or After All Modules Available'
2. Add a footnote under the above to state: Some of the metrics below are stratified into separate tables by whether the participant was verified before all modules were available in prod verses on or after. These are denoted by 'Before' and 'After'.
3. Please add 'Before' and 'After' into the table titles itself like you did in the smaller tables report. Then you can get rid of the 'before all modules available' etc that are listed above the titles.
4. Please add table numbers. For the metrics that have multiple tables under it, it would be helpful to label these as tables a, b, c, etc. For example have it say Table 1a: Verified Participants Survey Completion (Before) and Table 1b: Verified Participants Survey Completion (After)
5. For the number 2 tables 'Module 1 Completion Status of Verified Participants', can you remove the decimal places for N since this is a count of people? 
6. For the number 2 tables, can you also change these column percents? Right now they are row percents but it would be more helpful to see for active pts how the percent not started, started, etc 
7.  For the number 4 tables 'Module 1 Completion Status of Verified Participants (After)', etc please also remove the decimals on the n count and change to column percents.
8. For number 3 'time in minutes from verification to completion' these look really good presented with the min/1st quarter/median/etc. Is it possible to have these appear as tables?
9. For number 5' % submission of surveys modules by active recruits who cannot be verified' is it possible to present these as a table?
10. For number 7 ' Connect_IDs of those who completed the menstrual cycle' please change the title to 'Menstrual Cycle Survey Completion Status for Eligible Participants' since we don't need the Connect IDs anymore
11. For number 7, please present these in a table as well. Is it possible to stratify them by research sites vs clinical sites now that the clinical collections have started? Research=Henry Ford, HealthPartners, Marshfield, Sanford, UChicago. Clinical=KPCO, KPGA, KPHI, KPNW
12. For the smaller gt tables, is it possible to remove the '*' and '_' symbols on the labels and in the titles or does that need to be retained to get the table size to work properly?
13. For number 6 'Presence of survey completion time stamp' lets move this to the bottom of the report and only have it in the CCC reports. For the Connect_ALL report that is shared w/ the sites, we'll take this one out.
14. Not urgent, but when you have time can you change the references to the modules to their acronyms? We have started to change the order the modules appear on the PWA so now module 4 appears 2nd for some participants. Module 1=BOH section, Module 2=MRE section, Module 3=SAS section, Module 4=LAW section.

**Comment by jacobmpeters** [comment]
Hi Amelia. I generated these reports for Kelsey at around 10 am. 
[CCC-smaller-gt-tables.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10260331/CCC-smaller-gt-tables.pdf)
[CCC-Weekly-Module-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10260332/CCC-Weekly-Module-Metrics-RMD.pdf)

**Comment by KELSEYDOWLING7** [comment]
@robertsamm Please let me know how this adjusted report looks. 

I was able to adjust the labels on my original tables 2 and 4 in order to make them fit in the parameters of the pdf width constraints. I was also able to change tables 3, 5 and 7(now 6) into tables, however, these particular tables are automatically labeled "Table #: Summary Statistics" and so I'm not able to change that. Instead somehow the title appears only on the second row of the table.
 
[CCC-Weekly-Module-Metrics_RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10310712/CCC-Weekly-Module-Metrics_RMD.pdf)

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 Requested updates to module metrics below.

All requests for section 4. Duration in minutes from start to submission for each section:25, 50, 75 percentiles (active, passive, and total).

- For each module keep summary statistic (continuous) table for 'All module Total Participants' and 'Completion time for all verified participants' (categorical) table
  - Keep BOH: Table 44, Table 5d
  - Keep MRE: Table 56, table 7d
  - Keep SAS: Table 68, table 9d
  - Keep LAW: table 80, table 11d
- For LAW table 80: fix label, currently says 'All LAW _Active_ Participants', but I think you mean 'Total'
- For summary statistic tables above: add median
- For categorical tables 'completion time for all verified participants', re-order the categories so they go in order of time (shortest to longest)
- Drop from section 4: all other tables

**Comment by KELSEYDOWLING7** [comment]
@robertsamm Outside of some awkward spacing between tables in  numbers 3 and 4, the rest of these requests have been updated. Please let me know how it looks
[CCC-Weekly-Module-Metrics_RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11298569/CCC-Weekly-Module-Metrics_RMD.pdf)

**Comment by KELSEYDOWLING7** [comment]
The most recent table can be found here: https://nih.app.box.com/file/1198097127432  . Please let me know if you need me to move this report elsewhere

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Please see the comments in the PDF below for edits to the most recent metrics report (6/20/23)
[EDITS_Weekly-Biospecimen-Metrics-RMD_6_20_23.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11833586/EDITS_Weekly-Biospecimen-Metrics-RMD_6_20_23.pdf)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Would you be able to put the Figure 3 edit comments here? They're cut off. 

Also, can I have some more clarification in adding the "No Biospecimen Collections" row to tables? With the "No Samples Collected" columns in those tables, I'm not sure I fully understand. Are the "No Samples Collected" columns meant to only count those that had completed collections but gave no samples, and exclude those that haven't had their collection appointment yet? And would this new row just lump all participants from any site that haven't had their appointment yet?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Sure! The comment is in **bold** below.

**Figures 3-7
Good to see clinical trendline here!**

**Add sub-figures (i.e., Figure 3.1, 3.2, etc.) for each figure where the site has multiple collection locations (BioSpm_Location_v1r0 - 951355211) and graph the number of collections for each location:** 

**- UCHICAGO = 777644826,145191545, 489380324, 120264574**
**- HENRY FORD = 736183094, 886364332, 706927479**
**- MARSHFIELD = 692275326, 813701399, 698283667, 691714762, 487512085, 983848564, 261931804, 665277300**
**- SANFORD = 589224449, 467088902**
**- HEALTHPARTNERS - N/A (only one location; keep as is)**

**Keep the main figures (Figure 3-7) as is.
Sub-figures apply to non-KP sites only**


For the "No Biospecimen Collection", right now the "No Samples Collected" column is grouping together verified participants who had a collection appointment but all sample collection was unsuccessful and verified participants who have _not_ had a collection appointment (so no samples have been collected for them _yet_). Basically you'd have to stratify by collection finalization (BioRec_CollectFinal_v1r0 - 410912345); if the collection entry has not been finalized, the participant should be included in the "No Biospecimen Collection" row.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Thank you! 

Oh, ok. Hmm so my concern is that Jing had previously filtered ALL data coming in from the biospecimen table to be that BioRec_CollectFinal_v1r0=yes. If I remove that to add this row, I don't know how many other tables will be affected. I could alternatively make a footnote that says those counted in the "No Sample Collected" columns do not include those who have yet to have a collection appointment

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 So if there's already a filtered for finalized collections, why are the tables including all verified participants whether they have had an appointment or not (total of ~10,547 verified participants currently, but only about half as many collections, ~5,800)?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC    That's a good question... Jing needed more work and offered to help me solve this issue. The rest of the edits are complete

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Ok, thanks for looking into that! That edit isn't urgent, so I will close this issue and follow up when you and Jing have time to work on it.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Would the suffice instead for tables 1-4? It's significantly easier to add a third column rather then a new row with separate stratification then the rest of the table


![Biospe_matrix_Table2_updated_06232023](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/255ce4a5-50f3-49fc-8355-347cfd0c599f)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, this works well. Please make the following edits:

1. Retitle the columns to "Any Blood Collected", "No Blood Collected (Collection Visit)", and "No Blood Collected (No Collection Visit)".
2. Retitle the total **row** to be just "Total" (i.e., remove "Verified Participants")

*Apply edits to tables 1-4.
