### ISSUE TITLE
Ad Hoc - Collection-to-BPTL Receipt by Location

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#90]
Please generate four Collection-to-BPTL Receipt metrics tables: 
(1) frequency and percent distribution of days from research collection to BPTL receipt by collection location
(2) frequency and percent distribution of days from clinical collection to BPTL receipt by clinic location
(3) descriptive statistics for time (hrs) from research collection to BPTL receipt by collection location
(4) descriptive statistics for time (hrs) from clinical collection to BPTL receipt by clinic location

For (1) & (2), there should be six columns, "1 Day", "2 Days", "3 Days", "4 Days", ">4 Days", & "Total", and the tables should have row percent totals (see mock-up for reference)

For (3) & (4), assume the BPTL time received is 11:30am ET; BioBPTL_DateRec_v1r0 (926457119) only populates a date, not a timestamp. Add footnote to tables to note this assumption (see mock-up for reference)

All locations should be included in the code, but it is okay if all do not populate in the tables (they may not be live yet; "UCM Pop-Up" for example). 

**Requestor(s):** Domonique

**Table or Figure title:** 
- Table 1. Research Biospecimen Collection to Receipt at BPTL (in Days) by Collection Location
- Table 2. Clinical Biospecimen Collection to Receipt at BPTL (in Days) by Clinic Location
- Table 3. Time (in Hours) from Research Biospecimen Collection to Receipt at BPTL by Collection Location
- Table 4. Time (in Hours) from Clinical Biospecimen Collection to Receipt at BPTL by Clinic Location

**Metrics to be updated or created:** Create new metric tables

**Variables needed (include variable name and Concept ID):** 

1. BioSpm_Setting_v1r0 (650516960) - Collection setting (research or clinical)
2. RcrtES_Site_v1r0 (827220437) - Sites
3. BioBPTL_DateRec_v1r0 (926457119) - BPTL date/time received
4. BioRec_CollectFinalTime_v1r0 (556788178) - _Research_ collection time
5. BioClin_ClinBloodTmBL_v1r0 (822274939) _OR_ BioClin_ClinicalUrnTmBL_v1r0 (139245758) - _Clinical_ collection time (use whichever is earliest if both blood and urine date/time are populated)
6. BioSpm_Location_v1r0 (951355211) - Research Locations
- HealthPartners - 951355211 = 4
- Henry Ford - 951355211 = 5, 6, 7
- Marshfield - 951355211 1, 2, 3, 12, 13, 14, 15, 16, 18
- Sanford - 951355211 = 8, 17
- University of Chicago - 951355211 = 0, 9, 10, 11, 19, 20
7. BioClin_SiteBlLocation_v1r0 (185243482) _OR_ 7. BioClin_SiteUrLocatBL_v1r0 (452847912) - Clinic Locations (Any complete clinical collection should be counted, whether it is blood only, urine only, or both. Use the blood location ID or the urine location ID to get the location; it can be assumed that they are the same if both are present. If one is not populated, the other can be used.)
- HP - 185243482
        NSC = 1
        Elk River = 2
        Chanhassen = 3
- HFH - 185243482
        Macomb = 1060170018 OR 1060010063
        West Bloomfield = 1011220006 OR 1040010046 OR 1040010047
        Wyandotte = 1050010095
        Fairlane (Dearborn) = 1010180040
        Plymouth = 1011660013
        Royal Oak = 1011410008
        Troy = 1010360011
        K1 HFH Main = 1010010114 OR 1010010193
        Sterling Heights = 1010320019
        Columbus = 1010120026
        Livonia = 1010240013
- KPHI - 185243482
        Oahu Clinics = 22, 24, 28, 33, 34, 35, 38, 40, 55, 71
        Non-Oahu Clinics = 23, 26, 27, 32, 37, 49, 56, 69
 

**Specify numerator and denominator by variable name where applicable:**

**Table 1**
No. of Days = [BioBPTL_DateRec_v1r0 (926457119)] - [BioRec_CollectFinalTime_v1r0 (556788178)]
- Use populated date only to calculate the number of days; disregard timestamp

**Table 2**
No. of Days = [BioBPTL_DateRec_v1r0 (926457119)] - [BioClin_ClinBloodTmBL_v1r0 (822274939) _OR_ BioClin_ClinicalUrnTmBL_v1r0 (139245758)]
- Use populated date only to calculate the number of days; disregard timestamp

**Table 3**
Time in Hours = [BioBPTL_DateRec_v1r0 (926457119)] - [BioRec_CollectFinalTime_v1r0 (556788178)]
- Assume the BPTL received timestamp is 11:30am ET

**Table 4**
Time in Hours = [BioBPTL_DateRec_v1r0 (926457119)] - [BioClin_ClinBloodTmBL_v1r0 (822274939) _OR_ BioClin_ClinicalUrnTmBL_v1r0 (139245758)]
- Assume the BPTL received timestamp is 11:30am ET

**Mock-up table if applicable:**

[MOCK-UP_Collection-to-Received_Collection Location_Metrics.docx](https://github.com/Analyticsphere/metricsReportsRequests/files/13494222/MOCK-UP_Collection-to-Received_Collection.Location_Metrics.docx)

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
Should 'BioBPTL_DateRec_v1r0 (926457119) - BPTL date/time received'  be the earliest of blood/urine/mouthwash for research and blood/urine for clinical? And should all collections be finalized?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, please use the earliest date available for BioBPTL_DateRec_v1r0.

For research, yes, the collections should be finalized (BioRec_CollectFinal_v1r0 - 410912345); they need to be finalized to populate a value for BioRec_CollectFinalTime_v1r0 (556788178) which is the most accurate collection date/time for research.

For clinical, yes, the collections should be finalized (BioRec_CollectFinal_v1r0 - 410912345), but use BioClin_ClinBloodTmBL_v1r0 (822274939) OR BioClin_ClinicalUrnTmBL_v1r0 (139245758) for the actual time calculation.

**Comment by KELSEYDOWLING7** [comment]
Thanks! One other question. 8 and 11 are showing up as values for BioClin_SiteBlLocation_v1r0 (185243482) andBioClin_SiteUrLocatBL_v1r0 (452847912). Should those two be excluded for now?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Here's the updated report with those errors fixed. Unfortunately I still can't see my output report screen so let me know if anything still looks wonky

[Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13587292/Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks a lot better. Just a few edits:
- Remove the second "Table #." in all of the titles
![Screenshot 2023-12-06 at 3 07 41 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/87909992-db40-4b7c-bf00-60b346d0a842)

- Table 2 and 4: the KP site and "location" for KPGA, KPNW, and KPCO aren't paired properly
![Screenshot 2023-12-06 at 3 08 14 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/331c996f-e7fd-4bdb-a41e-bf89dcd560ef)

- Table 3 still has some negative values; can records with a negative time be excluded?
- Table 3 and 4: give all the values one decimal place
- Table 3 and 4: Add the following footnote - Note: BPTL receipt time is assumed to be 11:30am ET.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  I can finally see all my screens again so the location issue has been fixed! I also updated the decimals and added the footnote. But even after removing the urine and MW from the BioBPTL_DateRec_v1r0 list I'm still getting negative values for Table 3... Do you want me to remove any with hours under 0? If yes, do you want that done for table 1 also?


[Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13601996/Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Okay. Can you add the urine and MW back to Table 1 calculations (if they were removed)? I noticed a drop in some of the total counts, and it's important to have that be accurate in that table. Any changes we make to Table 3 shouldn't be applied to Table 1.

For Table 3, unfortunately, it is possible for a received date to be overridden from its original date due to some lingering data structure issues in the shipping dashboard. Can you run a check for any records when the collection date/time is after the date received?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok I added MW and urine back into the research (table 1) and urine back into clinical (table 2).  For table 3 only do you want just all those with collection date/time after date received to be removed? There are  of them 34 of them

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, please exclude those 34 records.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Ok please let me know how this looks
[Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13602939/Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks good from my first pass-through, so I'll share this version with the biospecimen team and follow up here if anything else is needed. Thank you!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The biospecimen group reviewed these metrics, and Tables 1 and 2 are good as is. 

For Tables 3 and 4, can you please add the "Perc. 90" and "Perc. 98" columns to both?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Also, can you give me a list of the Collection IDs (or Connect IDs, whichever is easiest to get) of records that are above the 98th percentile for Tables 3 and 4?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Sure thing.

Here's the report:
[Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13651702/Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf)


And here's the CIDs:
 4662629387 6197119024 9547251110 1478082542 6539997343 2006276419 3673107614 7762792603 4223926903 9798533024 3508218359 9327968941 5047063115 5257643005 6908198558 6816562353 7604224276 8505522521 4346497091
 8936135492 5311588385 9311404665 7592349295 4930209877 1763472927 8128675376 5042643326 1279450803 8147277568 7253803204 5739016273 5239304196 9361996215 9781429911 3398461901 6923226564 2040340204 5621157101
9784771819 8617378550 6177457629 1332601743 8188042154 5258009177 8437907461 8946098898 7294910309 8553020317 7453890686 9751806143 5863535586 8558357793 8357871646 8463094988 9959424752 9861043882 2656223971
1913191978 8663702757 7439908314 9499489820 4940326281 4405727615 2692995900 8816340632 3601129500 9275912994 6257284976 4919074716 8373725691 9880878735 3031741856 2115487775 6461739521 4604212560 7137889527
2250597955 3235358932 3108287381 1352810619 9700051401 1790592203 7317463198 7950930838 4286749399 1498855556 7808276385 5814003608 5805751827 3349865807 3832337868 9965718814 3511879738 4207384859 1829105125
 3161145870 9721508057 7911514486 4831747636 6105057731 5075405145 9307929352 9388229240 6037294154 5052380406 9575893990 9466751474 9406153090 5331248345 3404739450 2462550503 4201878434 8860625665 3750546125
1336801547 7222378208 7128462056 4701341007 4013519493 3458461793 3318500879 1846963947 3541132254 2553105235 5425916726 5418521183 8228509652 3841292250 7584627987 8997556388 1] 2385641695 6833557736 7872537005 4828233268 9360644642 9909359932 5823967526 3285883476 7867771112 5154616484 9721933597 4463279900 5976099562 7828835493 2800437904 6221481660 3923727459 5932876885 7050194484
2147112956 2180468063 1151660181 9583777327 1772603470 6466875724 9444957793 9050865085 5851781066 9315886976 6462669614 2837042300 5878222809 7724681761 9975543097 3527732797 4738148626 7177461614 1185457359
 6231438810 1988410850 4993410524 2020760731 7797189311 4589456771 9147906534 9579178186 9272255761 4988680944 4788086056 5540477269 8209993283 7848453863 9931718188 6131285812 9686408402 7868281545 3913755063 6380084928

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 For Tables 3 and 4, most of the values are whole numbers, so it seems like only the date is being used in the calculations; can you confirm that autogenerated time is also being factored into the descriptive stats? The time of BPTL receipt can be assumed to be 11:30am (YYYY-MM-DDT11:30:00.000Z) for all received dates.

Also, for each of the sites, can you generate a scatterplot for hours from collection to BPTL receipt? These plots do **not** need to be by location. For Henry Ford and HealthPartners only, please stratify the data points by collection setting (research and clinical). A mock-up is included below as an example.

![Mock-Up_Coll-to-BPTLRec 1](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/ec88dc88-2dc8-4a62-b141-3a7085cd06f0)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Oh ok so I had made it that the calculated difference in hours for tables 3 and 4 were rounded to whole numbers, which is likely the problem. and then summary statistics (min, q1, median, ect.) has only one decimal place. I also had the time at 11:30 instead of 11:30:00.000Z

I've removed the rounding of the hours in the calculation portion and updated the timestamp, and now these are the CIDs above the 98th percentile 
7604224276 9798533024 8147277568 4604212560 2006276419 9388229240 9406153090 6037294154 8498387707 7222378208 5805751827 3161145870 4930209877 5739016273 8936135492 8997556388 4678227798 4405727615 4223926903 2250597955 2040340204 3832337868 4701341007 8505522521 5047063115 3511879738 9547251110 1498855556 3398461901 9311404665 9575893990 3108287381 5172545511 9751806143 4013519493 7317463198 9361996215 6908198558 1478082542 2553105235 1352810619 9700051401 4207384859 4940326281 3349865807 9275912994 7808276385 5331248345 5425916726 1763472927 4662629387 3031741856 1913191978 5052380406 9959424752 5863535586 8188042154 6539997343 9307929352 9499489820 5418521183 7453890686 7950930838 9721508057 3404739450 9965718814 6461739521 3750546125 1279450803 8553020317 1336801547 8128675376 8558357793 6816562353 2115487775 4286749399 4919074716 5311588385 7294910309 8373725691 3458461793 4346497091 9466751474 5239304196 6177457629 9781429911 3508218359 8228509652 4201878434 5814003608 7584627987 9880878735 6257284976 3601129500 8946098898 7128462056 8463094988 4831747636 2692995900 5621157101 5257643005 7439908314 7762792603 6923226564 3841292250 3673107614 8617378550 3318500879 7911514486 9861043882 6197119024 5042643326 8663702757 5258009177 7137889527 8437907461 1829105125 8860625665 9784771819 1846963947 2656223971 8816340632 8357871646 6105057731 5075405145 7253803204 1790592203 3235358932 9327968941 2298675279 7592349295 3541132254 1332601743 2462550503 6380084928 2385641695 9360644642 7050194484 6833557736 3285883476 9909359932 5823967526 4828233268 7828835493 5154616484 2800437904 7872537005 7867771112 5932876885 3923727459 6221481660 4463279900 3527732797 5976099562 2147112956 7868281545 2180468063 9583777327 5851781066 1151660181 6462669614 2837042300 6131285812 6466875724 9444957793 9050865085 1772603470 7724681761 9975543097 4738148626 7177461614 1185457359 3913755063 4589456771 1988410850 5878222809 9315886976 4988680944 4993410524 2020760731 9147906534 7797189311 9272255761 9686408402 5540477269 8209993283 9721933597 9579178186 6231438810 4788086056 7848453863 9931718188


Here's the updated report with Tables 3 and 4 with that calculation update as well as these scatter plots. 
[Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13779702/Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Please see my comments below:

- Are the summary statistics being rounded as well? If yes, can you remove that too? The values in Tables 3 and 4 are the same as they were in the previous report.
- The locations in Tables 3 and 4 aren't listed under the correct site; please correct this.
- For all of the figures (which look good), please adjust the y-axis to have a max of 168 and number intervals of 24 (i.e., 24, 28, 72, etc.). It's okay if some data points are cut out; they are likely extreme cases that don't reflect an accurate collection-to-receipt time.
- Can you reduce the CID list down to the CIDs above the 99th percentile?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Yes, you'd requested that the summary statistics be rounded to one decimal place. I can remove it for this updated report, as well as rearrange the site locations to fit the correct site, and the y axis on all figures. 

It looks like 12 (Rice Lake) is listed in the original request twice. Is that a Marshfield location or a UC location? And should UC-DAM be included in UC?


Connect IDs above the 99th percentile are the following (only in the research, not clinical): 7604224276 9388229240 6037294154 8498387707 3161145870 8936135492 4223926903 2250597955 5047063115 9547251110 9575893990 5172545511 4013519493 2553105235 1352810619 3349865807 7808276385 5425916726 1913191978 5052380406 3404739450 9965718814 8553020317 1336801547 6816562353 3458461793 9781429911 4201878434 6257284976 8946098898 3841292250 3318500879 7911514486 9861043882 5258009177 8437907461 9784771819 1846963947
 7253803204 2298675279

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 You can leave the descriptive stats at one decimal place; I think it's just odd for the bio group to see that most of them have a zero value for that decimal place, but I guess it does make sense since the sites mostly ship around the same time of day and we're using the same receipt time for all of them.

Rice Lake is a Marshfield Location. Sorry about the error in the original request; I've corrected it.

Yes, UC-DCAM should be included for UC (also corrected in the original request; I always forget that "0" can have a value too smh)

Let me know if I'm missing any other locations.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  No problem! Sorry the sites' orders keep moving. This should be correct now

[Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13780932/Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf)

**Comment by StephanieWeinstein** [comment]
Hi @KELSEYDOWLING7 ,
Michelle and I reviewed this report this morning and have a few other questions/comments.  Since Domonique is out until Jan 8th, Michelle and I will work with you on this (I'm also out Jan 2-4).

1. Tables 3 and 4 - please drop the "Max" column
2. Tables 3 and 4 - we are still a bit confused about the values. Are they in hours or in days?  For example, the min is 24 hours for most sites.  I know all samples have the same assumed receipt time of 11:30 am, but they should all have different collection times.  So if a sample was collected at 10:30 am Eastern time, its value would be 25 hours.  But if it was collected at 12:30 pm, its value would be 23 hours.  A sample in Detroit that was collected in the afternoon, say 3pm, should have a value of 20.5 hours. So it is odd that all sites have a min of either 24.0 or 48.0 hours.
3. for the figures it is the same question, the values should not all be on exactly the 24 or 48 hour line.
4. once we have the above worked out, we would like you to add this to the Biospecimen Weekly Report.  Please add these after Figure 15, before the deviations lists.

Let me know if you have any questions.
Thanks,
Stephanie

**Comment by KELSEYDOWLING7** [comment]
Hi @StephanieWeinstein  Ah, ok so I found what was happening. Somehow when I was coding it to calculate the difference in hours it was rounding to the nearest day, then converting THAT to hours. This now looks accurate.

[Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13788817/Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf)

**Comment by StephanieWeinstein** [comment]
Hi @KELSEYDOWLING7 , thank you!  It looks great now!  A lot of useful information.  Please go ahead and add it the the Biospecimen weekly reports.  Much appreciated!
Stephanie

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  Can do! Do you want just the scatterplots? Or both the tables and the scatterplots?

**Comment by StephanieWeinstein** [comment]
@KELSEYDOWLING7 , everything please.  all the tables and all the scatter plots

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein   Ok can do. Is there a particular location in the report you'd like them? Or just at the end of the tables, before Figure 6?

**Comment by StephanieWeinstein** [comment]
Hi @KELSEYDOWLING7 , I am back in the office. Yes, before Figure 6 is good.

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  Perfect, that'll be reflected in Monday's report

**Comment by StephanieWeinstein** [comment]
Hi @KELSEYDOWLING7 ,
In reviewing my notes from the biospecimen team meeting, for Tables 1 and 2 it was also requested that we show a total for each site (especially the sites that have multiple locations).  If you are not able to do that easily in Tables 1 and 2, then could you create two new tables that just show the total numbers for each site?  Sorry for this late request, it is ok if it does not make it into Monday's report!
Thanks,
Stephanie

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, per Stephanie's request above, please add a "Total" sub-row under each site for Tables 1 and 2, using the format used in #87's [Table 1.2](https://github.com/Analyticsphere/metricsReportsRequests/issues/87#issuecomment-1870339261)?

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  I apologize for overlooking this! I had spoken to Domonique about having issues previously with those types of totals but forgot to reiterate that here. I was able to resolve it on Tables 1.1 and 1.2 but these are a bit different. I also think the total collections per day with a 100% would get confusing with the total with a 100% for each site location, so maybe separate tables are for the best. Please let me know how these looks. 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/217da868-cf57-4fc8-8ded-9543996cbe83)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e7d44838-6c51-4388-975c-8c1a6e368394)


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6afdfd74-e6ac-451f-9f8b-461642b7064c)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5f76412a-5d77-45bf-822f-f30b9e33d929)



Unfortunately I'm not able to get that on today's report, but I will be sure to do so on the next automation update on the 19th.

**Comment by StephanieWeinstein** [comment]
Hi Kelsey,
I am fine with separate tables.  KPNW is missing from Table 29a.
thank you!
Stephanie

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  Thank you for catching that! I apologize

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ffdd5fdb-b1f9-41ca-8221-1232b76bbf6f)

**Comment by StephanieWeinstein** [comment]
@KELSEYDOWLING7 , looks good, thanks!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, thank you for working on this. Can you also add the percentages to the "Total" rows of Tables 28a and 29a?

Also, for figures 6 through 14, can you stratify the data points by day of the week collected (Monday, Tuesday, Wednesday, etc.) and add legends to each? The day of the week should be determined by the collection date (x-axis). I know HP and HFH are already stratified by collection setting (research or clinical), so is it possible to distinguish that stratification another way other than color, like different data marker types (e.g., circles and squares, X's and O's, etc.)?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Here are 28a and 29a with the percentage totals. 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/dfe10b63-b700-4602-ae70-fcec1106acce)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/25e1d886-1b75-41fd-b864-041070d9bf3d)


I'll keep working on the Figures 6-14 updates

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  For Figure 6 I think the shapes are a bit hard to distinguish when there's lots of data points grouped together. 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/a1df1309-4d6b-47c8-8b35-89cba95a7d50)

I thinking maybe instead of shapes I could due a hue of colors? Or keep the shape distinction and also the hue of colors? So for example Figure 6 might have only the 'Blues' hues shown here, where each weekday is a different shade of blue. And then Figure 13 could have the 'Blues' hues for clinical collection weekdays and 'Reds' for research collection week days.
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1fbab85e-9049-43f4-8375-2a2415879488)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, that's what I meant in my initial request; use the colors for the days of the week and use the shapes to distinguish between research and clinical for Figures 8 and 9 since they have both collection settings. I'm sorry if I wasn't clear; I was thinking through as I was typing it out, so it's probably not the best explanation haha

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  My mistake! I definitely misread. Please let me know how these look

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/a0451f89-8e96-4ca6-a3f6-e72411ad2596)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4059638e-7afb-4793-8504-f0abc26df3a2)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/49638201-eeb3-4f9d-82ac-a957964210c4)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/10cba2aa-717a-4ccf-a325-523c01244a66)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c20858ab-1dab-4c86-b671-4b46899cb2fe)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/67354c23-7c97-46aa-a3e7-564b83f4f33b)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/70a01a71-7dd8-48b5-9b4c-ed19df1f72d6)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/18d23937-2095-4be6-bfd6-d333ec017faa)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/824c3bbc-1442-4def-a6f8-02dcedc08020)

**Comment by StephanieWeinstein** [comment]
Hi @KELSEYDOWLING7 Kelsey,
I think this will work, but the colors are t0o similar.  For example, Wed, Thurs, and Fri are all blue and Sun & Tues are both green.  can you get more variety in there?
Thanks!
Stephanie

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  Of course! Figure 6-12 have been updated as well so that the days of the week have uniform colors accross all the figures

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/25d8b411-4c92-4299-979f-10704b2c2638)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/692df4a8-e448-4f3d-aa9c-57a8b632ede0)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The updated colors look good to me. 
@StephanieWeinstein Does it look better to you?

**Comment by StephanieWeinstein** [comment]
yes, let's go with this and we can circle back if any other changes are needed.  Can you post the final figures here for now?
Thank you!

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  Sure!

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e1a50686-6b0a-4a5c-aa91-fdd1f3875ad7)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/3abe32a1-cd15-4a9e-b263-5919f737b20b)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/64323158-bb07-478d-87ff-4e346d0b011b)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1d583b3e-a5b6-4671-8a75-74e116532955)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f9fa3cd8-e4eb-4e38-9542-974ae80c3ae6)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6af499ed-84b9-4b39-bcdf-4279b4147855)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6311541e-5742-4c09-993e-975e01afd9ae)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/84a1d0fc-9479-4da2-a81e-829c16f7a106)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ec244f78-358f-4b85-a7af-efcc2aaba4f7)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, can you post the figures with the [updated color scheme](https://github.com/Analyticsphere/metricsReportsRequests/issues/90#issuecomment-1885344836)?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Oh I'm sorry! I was looking at the wrong output version. 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/a900dba1-fe63-4ea0-a444-baa73a176d33)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/73c17279-893d-47b6-9114-8c91af0cc766)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d4168ed1-d8f5-4822-bcad-251c439fa1e8)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ca272421-6fb1-4e0a-ad78-7f7aa7c7f997)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/80036742-1df0-4513-a3ee-7fbb85e37d6a)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/bc5f3bd9-42b6-4ee6-b04f-1b02cef41c55)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d205ec12-8f91-47f6-b2f9-553501661398)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/7b4dba6f-4090-43f6-bbd0-99b613aa7d45)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9ce26bb2-b12d-4aa3-9080-94ea1f193f63)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thanks!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, for the **research setting** time calculations **only**, can you please use BioCol_ColTime_v1r0 (678166505) instead of BioRec_CollectFinalTime_v1r0 (556788178) and repost the weekday stratified figures here?

Can you also apply this variable change to: 
1. #110 (the needle-to-receipt time calculation in column D **and** the variable data in column I) 
2. Tables 28a, 28b, & 30, **and** Figures 6, 7, 8, 13, & 14 in the weekly biospecimen report's automation code. (The figures in the report can remain as is (_not_ stratified by weekday); just update the variable in the research time calculation)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ff862662-ecc8-4137-a664-9b8160fef828)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/837b16a7-4f58-487f-b03a-8b0de7dade18)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ca7766f1-b50b-4e76-9b69-2dc44f5b1d6a)


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/52180244-2899-474f-9e9e-c4fc796f68c2)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9fc0eebd-aca9-427c-a8f2-4506679639a5)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/3c61ec7e-00f6-480e-a005-2378a35b4fd5)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/bf41389d-d685-45da-925b-0ad3eb033767)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/aa8fb482-00fc-4311-8be4-fd2c6e6d5775)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/eb0788b2-88c2-4a9e-878b-47f6fcf1e872)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4533800f-e445-40a6-927d-ac53521d7985)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/5e82daf8-6328-4c66-a299-7238ec7b4b4b)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/ab1b5474-6da9-4fb9-a749-dd587f47959f)

**Comment by StephanieWeinstein** [comment]
Hi Kelsey,
The figures look nice.  Once you have finalized everything with Domonique could you post the figures in a PDF somewhere so I can share them with the biospecimen team? We will probably incorporate them into the automated report but I'll confirm after we receive feedback.
Thanks,
Stephanie

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Per Stephanie's comment above, you can re-run the _Ad-Hoc---Collection-to-BPTL-Receipt-by-Location_ PDF document and post it here so everything is in one place. Please use the figures that are stratified by weekday. Thank you!

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  @HopkinsDC  Good morning, please see below

[Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13920708/Ad-Hoc---Collection-to-BPTL-Receipt-by-Location.pdf)

**Comment by KELSEYDOWLING7** [comment]
@StephanieWeinstein  @HopkinsDC  The automation for the Biospecimen Report will be updated tomorrow. Would we like the figures to be updated as shown above? Or left as is?

**Comment by StephanieWeinstein** [comment]
Thanks @KELSEYDOWLING7 , yes, the figures can be updated to the color coded versions with day of the week.

**Comment by HopkinsDC** [comment]
Tables and figures successfully updated in 1/22 biospecimen metrics report.
