### ISSUE TITLE
Bio Weekly - Remove Figure 5 from Weekly Report

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#91]
Please remove Figure 5 from the weekly biospecimen report; the biospecimen team no longer monitors this metric now that the KP sites have caught up on their draw order backlog.

There is a new figure mocked-up for the home collections (#88 - "Weekly Shipped and Received Home Mouthwash Collection Kits") that will take the "Figure 5" spot, but since it's not operational yet, remove the current Figure 5 and leave the other figure numbers that follow it as is for now.

**Requestor(s):** Domonique

**Table or Figure title:** Fig 5. Clinical Blood Draw Order Status of Verified Participants by Site

**Metrics to be updated or created:** N/A

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 I'll assume the code has been updated for this since you can't send a screenshot of something that doesn't exist anymore haha

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Yes that's fair lol it was removed on yesterday report in the ALL folder as well so it's all set in the automation

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Oh ok, that's great, thanks!

**Comment by HopkinsDC** [comment]
Update successfully implemented in 12/04 weekly biospecimen metrics report.
