### ISSUE TITLE
Bio Weekly - Add Figure for Weekly HFH Clinical Collections by Clinic Location

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#92]
Add a new figure for weekly number of clinical collections at HFH by clinic location.

Title this new figure: **Figure 7.2 Weekly Clinical Biospecimen Collections at Henry Ford by Clinic Location**

**Requestor(s):** Michelle

**Table or Figure title:** Figure 7.2 Weekly Clinical Biospecimen Collections at Henry Ford by Clinic Location

**Variables needed (include variable name and Concept ID):**
- RcrtES_Site_v1r0 (214456996)

- BioSpm_Setting_v1r0 (650516960)

- BioClin_SiteBlLocation_v1r0 (185243482) OR 7. BioClin_SiteUrLocatBL_v1r0 (452847912) - Clinic Locations (Any complete clinical collection should be counted, whether it is blood only, urine only, or both. Use the blood location ID or the urine location ID to get the location; it can be assumed that they are the same if both are present. If one is not populated, the other can be used.)

- BioRec_CollectFinal_v1r0 (410912345)

**Specify numerator and denominator by variable name where applicable:**
- Denominator = All finalized clinical collections at HFH - RcrtES_Site_v1r0 (214456996) = 1; BioSpm_Setting_v1r0 (650516960) = 1; BioRec_CollectFinal_v1r0 (410912345) = 1
- Numerator = HFH clinic locations (BioClin_SiteBlLocation_v1r0 (185243482) OR 7. BioClin_SiteUrLocatBL_v1r0 (452847912))
HFH Clinic Locations:
Macomb = 1060170018 OR 1060010063
West Bloomfield = 1011220006 OR 1040010046 OR 1040010047
Wyandotte = 1050010095
Fairlane (Dearborn) = 1010180040
Plymouth = 1011660013
Royal Oak = 1011410008
Troy = 1010360011
K1 HFH Main = 1010010114 OR 1010010193
Sterling Heights = 1010320019
Columbus = 1010120026
Livonia = 1010240013

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e6231de2-6fa4-43b9-8511-e8b62efc7cc6)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks good. Can you adjust the x-axis to start from 5/22/23?

Also, is it possible to move the key to be either between the title and figure (preferred) or below the figure? (asking for all figures in the weekly report)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Of course. If it's alright I'd prefer to put the key below the figure. The code is less complex and that also lines up with the plot structure in the Operations Table for consistency purposes



![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/62f71288-1301-461e-b839-bcdf336aa540)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Okay, that's fine. This figure looks great!

Can you apply the key location change to all of the figures in the report? (I'll make a new issue for it, just for tracking purposes, and link it to this one.) - #98

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Awesome! Yes, I updated all figures to have the legend on the bottom instead of the right. I also changed the titles from Fig to Figure for consistency. I'll upload the new report on the new issue

**Comment by HopkinsDC** [comment]
Update successfully implemented in 12/11 weekly biospecimen metrics report.
