### ISSUE TITLE
Bio Weekly - Update Figure 7.1 Title

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#93]
Update Figure 7.1 to the following: **Figure 7.1 Weekly Research Biospecimen Collections at Henry Ford by Collection Location**

**Requestor(s):** Domonique

**Table or Figure title:** N/A

**Metrics to be updated or created:** Update existing figure

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@h 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/b02e021f-f114-4a2b-9198-87cb2105e208)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Looks good, Thanks!

**Comment by HopkinsDC** [comment]
Update successfully implemented in 12/11 weekly biospecimen metrics report.
