### ISSUE TITLE
Bio Weekly - Add Figure for Weekly HealthPartners Clinical Collections by Clinic Location

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#94]
Add a new figure for the weekly number of clinical collections at HealthPartners by clinic location.

Title this new figure: **Figure 11.1 Weekly Clinical Biospecimen Collections at HealthPartners by Clinic Location**

**Requestor(s):** Michelle

**Table or Figure title:** Figure 11.1 Weekly Clinical Biospecimen Collections at HealthPartners by Clinic Location

**Variables needed (include variable name and Concept ID):**
- RcrtES_Site_v1r0 (214456996)

- BioSpm_Setting_v1r0 (650516960)

- BioClin_SiteBlLocation_v1r0 (185243482) OR 7. BioClin_SiteUrLocatBL_v1r0 (452847912) - Clinic Locations (Any complete clinical collection should be counted, whether it is blood only, urine only, or both. Use the blood location ID or the urine location ID to get the location; it can be assumed that they are the same if both are present. If one is not populated, the other can be used.)

- BioRec_CollectFinal_v1r0 (410912345)

**Specify numerator and denominator by variable name where applicable:**
- Denominator = All finalized clinical collections at HFH - RcrtES_Site_v1r0 (214456996) = 0; BioSpm_Setting_v1r0 (650516960) = 1; BioRec_CollectFinal_v1r0 (410912345) = 1

- Numerator = HP clinic locations (BioClin_SiteBlLocation_v1r0 (185243482) OR 7. BioClin_SiteUrLocatBL_v1r0 (452847912))
HP Clinic Locations:
NSC = 1
Elk River = 2
Chanhassen = 3

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC 
To clarify, for the HP locations would it be:
 d_173836415_d_266600170_d_185243482=1 OR d_173836415_d_266600170_d_452847912=1  means NSC
 d_173836415_d_266600170_d_185243482=2 OR d_173836415_d_266600170_d_452847912=2  means Elk River
 d_173836415_d_266600170_d_185243482=3 OR d_173836415_d_266600170_d_452847912=3  means Chanhassen?

**Comment by HopkinsDC** [comment]
> @HopkinsDC To clarify, for the HP locations would it be: d_173836415_d_266600170_d_185243482=1 OR d_173836415_d_266600170_d_452847912=1 means NSC d_173836415_d_266600170_d_185243482=2 OR d_173836415_d_266600170_d_452847912=2 means Elk River d_173836415_d_266600170_d_185243482=3 OR d_173836415_d_266600170_d_452847912=3 means Chanhassen?

Yes, that's correct.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Great, I see those values in Stage so once they're in prod I'll run the table. The code is ready

**Comment by HopkinsDC** [comment]
Update successfully implemented in 12/18 weekly biospecimen metrics report.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 My apologies! I mistook this issue for the update made to Figure 11 (Weekly Biospecimen Collections
at HealthPartners). This is a separate, new figure and it's not in the 12/18 report yet because I think we were waiting on prod data to populate.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  That's ok! We do have a few data points for it now 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/be3359be-1bb2-4e5a-bcb9-b7f4d2e0634e)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 It's good to see HP's clinical collections are showing properly. Just a couple of additional edits:
- Can you adjust the x-axis to start on 11/20/23? 
- Assuming the y-axis scale will auto-adjust as the weekly collections increase, can you adjust it to be a whole-number scale (no "#.5" half counts)?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Sure thing

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/adaf5a52-16b2-4864-af21-38043287bab4)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you!

**Comment by HopkinsDC** [comment]
Update successfully implemented in 12/26 weekly biospecimen metrics report.
