### ISSUE TITLE
Adding death data to refusal and withdrawal report

### ISSUE THREAD

**Issue by kmazzilli** [Analyticsphere/metricsReportsRequests#95]
Requestor(s): Kaitlyn Mazzilli and Amelia Roberts

Metrics to be updated or created: Refusal and Withdrawal reports

Notes: We would like to add 3 columns to the overall report and site specific reports. 

1. "Deceased" to show whether the individual has been marked as deceased.
2. "Date deceased" for the date of death.
3. "Source" to show whether the death was reported from EMR/the site vs the CSC.

Approved by: Michelle Brotzman

**Comment by KELSEYDOWLING7** [comment]
Hi @kmazzilli  I, thanks.  didn't realize these would be added to the the refusal and withdrawal report. Jing still owns that report so I will let her know about these additional columns to be added and I can communicate the updates here on Github.

Could you confirm the Connect IDs/Variable Names for these variables? Would it be:
1. 'Deceased' : HdWd_EMRPartDec_v1r0
2. 'Date Deceased': HdWd_EMRPartDecTm_v1r0
3. 'Source': (not seeing anything in the DD other than HdWd_SourceofReport_v1r0 but that's only the "who" told us, not EMR or site). Would this just be if  HdWd_EMRPartDec_v1r0=yes the source is EMR and if HdWd_Deceased_v1r0=yes the source is the Site?

**Comment by kmazzilli** [comment]
@KELSEYDOWLING7 sounds good, thanks. Can you confirm those concept IDs with @mnataraj92 ?

For number 3: 
The source is imputed from the other variables - the sites are going to send data to a separate variable. If the death is Reported by Site then the source is the site, and if not, then it'll get counted as reported to CSC. So, we think it may need to be a calculation for the 'reported by CSC' count: reported by CSC=Reported Deceased - Reported by Site/EMR. 
Madhuri should be able to give you more insight here.

**Comment by mnataraj92** [comment]
Hi @KELSEYDOWLING7,

The concept ID for HdWd_EMRPartDec_v1r0 is 857217152
The concept ID for HdWd_EMRPartDecTm_v1r0 is 772354119

To calculate the "reported by CSC" it would be 
Reported by CSC = Participant Deceased (987563196) - EMR participant deceased (857217152)

**Comment by KELSEYDOWLING7** [comment]
@mnataraj92  Thank you!!

@kmazzilli  It doesn't look like these are in BQ just yet; Madhuri confirmed they should be in the participants table. Do we know when these variables should get to prod?

**Comment by kmazzilli** [comment]
@KELSEYDOWLING7 They will be available in the December release which is set to go out on Dec 20 into prod. We welcome sites to send them after that. Probably one or two sites will be ready to start sending then, if they have any deaths. The others over the next couple of months.

**Comment by kmazzilli** [comment]
Also @KELSEYDOWLING7 they are only supposed to send deaths for verified participants. Could you add that to the QC checks?

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli Would that be the CSC should only send deaths for verified participants,  the EMR/Sites should only send deaths for verified participants, or both should only be sending deaths for verified participants? Just need he specifics before I can add this rule(s) to the death data list

**Comment by kmazzilli** [comment]
@KELSEYDOWLING7 We don't have a rule for who can report deaths to the CSC, we think it would be unlikely that someone would report to the CSC that a Connect ppt had died for a Connect ppt that was not verified

**Comment by KELSEYDOWLING7** [comment]
> Also @KELSEYDOWLING7 they are only supposed to send deaths for verified participants. Could you add that to the QC checks?

@kmazzilli  So this request means the EMR/Sites should only send deaths for verified participants? I need to have specifics for QC rules to be coded properly

**Comment by kmazzilli** [comment]
Yes that is correct, thanks!

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  Hi Kaitlyn, happy new year. Now that we have death data, I can add these columns to the refusal and withdrawal csv report. Madhuri has given me the CIDs for (1) Deceased and (2) Date Deceased for pre-existing death variables  and the new EMR death variables, but what I need to know from you is which you want. 

We have participant deceased HdWd_Deceased_v1r0 or EMR participant deceased HdWd_EMRPartDec_v1r0. Then  Date Participant Deceased HdWd_DeceasedDt_v1r0 or EMR Date Participant Deceased HdWd_EMRPartDecTm_v1r0. Please let me know specifically which to add to the report.

**Comment by KELSEYDOWLING7** [comment]
Actually it looks like there are already columns for the pre-existing variables Deceased (HdWd_Deceased_v1r0) and Date Deceased (HdWd_DeceasedDt_v1r0).  Sorry for the confusion.

I can add the new EMR Deceased and Date Deceased variables, but maybe I should keep their column name as the Variable Name (like the rest of the variables currently) to avoid confusion. And then add the Source variable. 

Do you want these new variables next to the current deceased variables?

**Comment by kmazzilli** [comment]
@KELSEYDOWLING7 yes adding these in next to the current deceased variables works, thanks

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli This has been updates for the All sites report and by site reports. Here's the all sites report as reference

[RefusalWithdrawl_cases_2024-01-04_boxfolder_141543243283.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13832385/RefusalWithdrawl_cases_2024-01-04_boxfolder_141543243283.csv)

**Comment by kmazzilli** [comment]
Kelsey and I spoke on the phone today and with Michelle's help decided the best approach would be:

For CSC: HdWd_DeceasedDtEntry_v1r0 (date and time field for CSC system) is autoset by our system, so it is required and should never be blank.
 
So, code could look something like: If HdWd_Deceased_v1r0 (overall death flag) is yes AND HdWd_DeceasedDtEntry_v1r0 (date and time field for CSC system) has a value, then source=CSC
 
For EMR: HdWd_EMRPartDecTm_v1r0 (date and time field for EMR) is not required so might be blank. So instead you can use the EMR death flag: HdWd_EMRPartDec_v1r. Code could look something like: If HdWd_Deceased_v1r0 (overall death flag) is yes AND HdWd_EMRPartDec_v1r0 has a value then source=EMR
 
For both: If HdWd_Deceased_v1r0  is yes AND HdWd_DeceasedDtEntry_v1r0 has a value AND HdWd_EMRPartDec_v1r0 has a value then source=EMR and CSC

We also agreed to move all the deceased related variables to the very end of the file.

**Comment by KELSEYDOWLING7** [comment]
Yes, this resolve the issue of the Data Source categories. The new csv file (All Sites example) looks like this now:
[RefusalWithdrawl_cases_2024-01-05_boxfolder_141543243283.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13846522/RefusalWithdrawl_cases_2024-01-05_boxfolder_141543243283.csv)

**Comment by kmazzilli** [comment]
@brotzmanmj this looks good to me and can be accepted if you agree!

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  @kmazzilli   Updated on the 1/8 Operations report

**Comment by kmazzilli** [comment]
looks good, thanks @KELSEYDOWLING7
