### ISSUE TITLE
Operations report - death data table

### ISSUE THREAD

**Issue by kmazzilli** [Analyticsphere/metricsReportsRequests#96]
Requestor(s): Kaitlyn Mazzilli and Amelia Roberts

Table or Figure title: "Table 36. Cumulative Consented Participants Reported Deceased"

Metrics to be updated or created: Weekly Operations Report

Mock-up table if applicable: (attached)
[Mock up death data table.xlsx](https://github.com/Analyticsphere/metricsReportsRequests/files/13590017/Mock.up.death.data.table.xlsx)

Notes:
1. This should be placed after Table 35 (making this Table 36)
2. We would like four columns: "Site" (to include all sites with a total # of deceased row at the bottom), "Deaths Reported" (for the cumulative number of deaths reported), "Reported by Site" and "Reported to CSC" (with the N and % breakdown for the source of report)
3.  This should be out of consented participants only

Approved by: Michelle Brotzman

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli Hi Kaitlyn, the table is juts about done for stage data. Once we finalize the details here, I'll have it ready for once we have prod data. Should the percentages be row percentages or column percentages?

**Comment by kmazzilli** [comment]
@KELSEYDOWLING7 great thank you! We would like row percentages please.

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli Thanks! So here's what that looks like. I'm not sure if the percentages are very intuitive, so let me know if you'd like an a footnote added. The 'Deaths Reported' column counts all deaths, whether they're reported from the Site or reported from the CSC. It seems as though the CSC deaths notification might be a bit slower for us to receive, and again this is stage data, but something to keep in mind. If there was no lag, all three columns would have the same values and the percentages would both be 100%. So if HeathPartners had both deaths reported by both the Site and by the CSC we'd see 2, 2(100%), 2(100%)


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6abcd5a5-8906-4cfc-9acf-6ff8b0efaeeb)

**Comment by kmazzilli** [comment]
@KELSEYDOWLING7 thanks for the update. So these two categories "reported by site" and "reported to CSC" should be mutually exclusive, and look the same as discussed in issue 95. If the death is Reported by Site then the source is the site, and if not, then it'll get counted as reported to CSC. So the calculation for that should look like: reported by CSC=Reported Deceased - Reported by Site/EMR.

Madhuri had said: "To calculate the "reported by CSC" it would be
Reported by CSC = Participant Deceased (987563196) - EMR participant deceased (857217152)"

I think once this change is made, the row percents should make more sense.

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  Ah ok so the overall deaths reported is 987563196, the reported by site is the same as reported by EMR (857217152) and the reported by CSC is the equation above?

If the variable labels/names could be included in all initial requests for clarification moving forward that would be MUCH appreciated. Thank you

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  Is it ok if the columns aren't in the exact order as the mock up? In this case, the Deaths Reported is the equivalent of a total, which is at the far right of every other table in the report; and how R automatically places totals in this type of table

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/451af640-d441-4443-a1fa-edd7585664db)

**Comment by kmazzilli** [comment]
@KELSEYDOWLING7 That sounds correct, thanks! And yes the columns look fine in that order instead.

**Comment by brotzmanmj** [comment]
Hi, I just wanted to comment that the same death can be reported to both the CSC and by EMR from the site, or may be reported to just one or the other. The way we have it working, the EMR death variable captures deaths reported via the sites' EMR. The overall 'deceased variable' will be 'yes' if reported to the CSC or the EMR. Having said that, I think the metric is still correct the way you have it. We should just recognize that a death can be reported to both.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  I'm not quite sure how I would go about coding that without more specific conditionality. Right now I have it as the overall deaths reported is (HdWd_Deceased_v1r0=yes), then either they're counted as deceased by EMR/Site when HdWd_EMRPartDec_v1r0=yes, or they're counted as deceased by CSC  whenHdWd_EMRPartDec_v1r0 != yes.


If what you're saying is the case, we'd need a different when to know when the CSC is reporting the death.

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7  I think the way you have constructed it is fine. The death was reported by EMR/Site if HdWd_EMRPartDec_v1r0=yes, and or they are counted as deceased by CSC when HdWd_Deceased_v1r0=yes = yes and HdWd_EMRPartDec_v1r0 is not equal to yes. That should work accurately.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  @kmazzilli  Are we ready to add this to the Operations report as is? Me and Jake are meeting this Friday to update all automated reports for Monday

**Comment by kmazzilli** [comment]
I think this is good to go as long as @brotzmanmj doesn't have any other feedback. Thanks @KELSEYDOWLING7 !

**Comment by brotzmanmj** [comment]
Agreed

**Comment by KELSEYDOWLING7** [comment]
Great! As long as there's data to use by Friday I'll update the report for Monday

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj @kmazzilli Data for all variables is not in prod and the table runs smoothly. This will be on Monday's report

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  @kmazzilli   Updated on the 1/8 Operations report

**Comment by kmazzilli** [comment]
looks good, thanks @KELSEYDOWLING7
