### ISSUE TITLE
Bio Weekly - Update Figure 11

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#97]
Update Figure 11 to include a second trend line showing HealthPartner's weekly number of clinical collections.

The updated Figure 11 should look like/have the same format as Figure 7 (Weekly Biospecimen Collections at Henry Ford).

**Requestor(s):** Domonique

**Table or Figure title:** Figure 11. Weekly Biospecimen Collections at HealthPartners

**Variables needed (include variable name and Concept ID):**
- RcrtES_Site_v1r0 (827220437)
- BioSpm_Setting_v1r0 (650516960)
- BioRec_CollectFinal_v1r0 (410912345)

**Specify numerator and denominator by variable name where applicable:**
- Denominator = All finalized collections at HP - RcrtES_Site_v1r0 (827220437) = 0; BioRec_CollectFinal_v1r0 (410912345) = 1
- Numerator = Clinical and research collection settings at HP - BioSpm_Setting_v1r0 (650516960) = 0 [Research] & 1 [Clinical]

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Do we have any HP clinical collections yet? The plot is only showing research

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0897c1d8-d378-48d4-ba4f-f9a2f34c1d6a)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 HP's first clinical collections were scheduled for this week (today actually), so they should show up in the next report.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Oh ok perfect. Well the code is set up and I'll check on Monday to see if its reflected here. I won't add it to the automation just yet, I'll just check manually and then upload a screenshot here

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  The clinical collection showed up on today's report. Is this ok to include in the ALL folder report?

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/e7b81eaf-07fa-4cf6-87c2-bc0642230191)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Yes, that would be great. Thank you!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Great! That's been uploaded. Because I had to manually run the report this week, the following issues should be reflected on the report now:
#92 
#93 
#98

**Comment by HopkinsDC** [comment]
Update successfully implemented in 12/11 weekly biospecimen metrics report.
