### ISSUE TITLE
Bio Weekly - Relocate All Figure Keys

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#98]
**Issue initially requested in #92.** 
Move the key to be either between the title and the figure or below the figure and apply location change to all of the figures in the weekly report

**Requestor(s):** Domonique/Mia

**Table or Figure title:** Update all figures in weekly report

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Please see below. Also, all Figure titles have been changed from Fig to Figure and all legends have proper titles now.
[Weekly_Biospecimen_Metrics.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/13602785/Weekly_Biospecimen_Metrics.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The changes you made to the keys and titles look good. 

Figures 7 and 7.1 look like there's something wrong. The y-axis scales are different, and the data points on the graphs are not the same. Also, in the new Figure 7.1, there's a trend line for HP Research Clinical. I've added screenshots below so you can see them side-by-side.

**FIGURE 7**
![Screenshot 2023-12-07 at 12 07 40 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/ec6cc3da-02e6-435c-bf97-c92c49daf3a7)

![Screenshot 2023-12-07 at 12 08 00 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/d731aad7-521b-4dce-af25-73c2bd8b2f5b)


**FIGURE 7.1**
![Screenshot 2023-12-07 at 12 08 33 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/20fd053d-f79e-437f-9630-2e820fc7e91b)

![Screenshot 2023-12-07 at 12 07 51 PM](https://github.com/Analyticsphere/metricsReportsRequests/assets/85250133/a42eae90-1bbb-48ae-a12d-393256240516)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Oh! Thank you for pointing that out. I made a code change for Figure 11 that affected these. They should be fixed now:

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/1ec84e24-3b99-4959-a404-0a8551d2b3af)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/b57dad19-13a2-4544-bfe6-bb3d2e92fd50)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/538b4784-7f3d-43e5-94df-308f5fb02e04)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thank you for the fix!

**Comment by HopkinsDC** [comment]
Updates successfully implemented in 12/11 weekly biospecimen metrics report.
