### ISSUE TITLE
Bio Weekly - Update Tables 3 & 3.1 for Home Collection

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#99]
Updated tables 3 and 3.1 to reflect home collection counts. It is okay that the "Home" row will no longer show in the table until there is actual data in production.
 

**Requestor(s):** Domonique

**Table or Figure title:** 
- Table 3. Baseline Biospecimen Collection by Collection Setting
- Table 3.1 Baseline Biospecimen Collection by Collection Setting at Henry Ford Health

**Metrics to be updated or created:** Update existing table

**Variables needed (include variable name and Concept ID):**
- BioSpm_Setting_v1r0 (650516960) – Collection setting
- BioFin_BaseMouthCol_v1r0 (684635302) – Baseline mouthwash collection
- BioSpm_MWSettingBL_v1r0 (915179629) – Mouthwash collection setting

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Approved by:**

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  The code is all set, here's what it looks like in stage. Once we have home collections in prod I'll apply the updates. 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/15084808-c7f6-4250-8391-9ba1c3096e58)

(HF doesn't have Home Collections data so can't run 3.1)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 This looks great, thank you! Can you update the footnote to the following: 

Note: Blood and urine specimens are not collected in the Home setting, and mouthwash specimens are not collected in the Clinical setting.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Sure thing

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/981cc42a-0b25-47a6-94bc-77d50d9b62cf)

**Comment by HopkinsDC** [comment]
**Footnote** update successfully implemented in 12/18 weekly biospecimen metrics report.

This issue will remain in "Accepted - Pending Automation" column until there is data in production to apply updated code.

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Able to fix this issue!
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/80104686-80eb-4fa1-9c89-2e23b769fe81)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/3bc7ea9b-5930-4979-abbf-6e4e73ca0391)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/87667dae-fe0a-4405-a4db-e32062716aa7)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 these tables look good. Please confirm, as you have previously explained for other metrics, the % of mouthwash collected is still 0% because it is such a small decimal, correct?

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Correct, because the percentage are rounded to the nearest 10th of a percent. Table 1.5 would be about 0.04% and Table 1.6 about 0.2%. I'll play around with 1.6 so the 0.2% shows

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6b8df516-d42c-4e45-a8eb-3cca05de1c03)

**Comment by erincschwartz** [comment]
@KELSEYDOWLING7 Thank you for confirming, and updating 1.6. These look ready for automation.
